### ISSUE TITLE
can't find amfrt32.dll

### ISSUE THREAD

**Issue by tcll321** [GPUOpen-LibrariesAndSDKs/AMF#10]
![image](https://cloud.githubusercontent.com/assets/21168168/17848252/f94e4160-6884-11e6-97a8-9157d59d6302.png)

**Comment by Tukan40** [comment]
Please update the driver to the latest. The DLL is part of driver package.

**Comment by tcll321** [comment]
thank you very much!
I have another question, how to render more efficient? How can I use the surface data directly?

**Comment by Tukan40** [comment]
It depends what use case do you have in mind. In general, AMF provides direct access to internal objects that are used to allocate surfaces: D3D9 surfaces, D3D11 textures, system (host) memory etc.. Check for GetNative() method in AMFPlane. interface. The return depends on surface memory type. Also, check samples and documentation. If you need help just post a question.

**Comment by tcll321** [comment]
I want to save sufaces to jpg or bmp file, but returns a failure.
![image](https://cloud.githubusercontent.com/assets/21168168/17992247/52d833ee-6b78-11e6-8c69-fb6767259468.png)

**Comment by MikhailAMD** [comment]
What is the surface format? I believe that this function can deal with RGB only.

**Comment by tcll321** [comment]
I'm not quite sure the surface is what format, is amf initialize yourself. From the examples given only obtain Y and UV data method, I want to do rendering directly after decoding, no need to switch to the system memory, the system memory will be converted to the loss of performance, I do not know whether it can be to deal with?

**Comment by MikhailAMD** [comment]
From your post I can deduce that surface format is NV12. The decoder by default returns NV12.. You can call surface->GetFormat() to check. D3DXSaveSurfaceToFile() probably works with RGB surfaces only. So you will need to do color space conversion. There are many ways to do it but one is to program AMF Decoder to output RGB by calling Init(width, height, AMF_FORMAT_BGRA). Another way to do it is to use AMF Video Converter directly. Check SimpleConverter sample.  
For presenting after decoder check PlaybackHW sample. To present you also need to do the conversion.

**Comment by MikhailAMD** [comment]
Closing as not a n issue
