### ISSUE TITLE
GPU Driver Crash when used in mixed multi-GPU System (NVIDIA+AMD)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#100]
When AMF is used for decoding, encoding or transcoding in a mixed multi-GPU System (NVIDIA+AMD for example), the AMD GPU Driver (amdkmdap) will stop responding and Windows will forcefully restart it. This also applies to systems where the Intel GPU is the primary one. (Edit: with "Intel GPU as primary" I mean that the display is connected to the Intel GPU)

System: [DxDiag.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/1151857/DxDiag.txt)
ETL: http://cdn.xaymar.com/private/2017/07/17/10/Issue100ETL.7z

**Comment by MikhailAMD** [comment]
We tried but cannot reproduce the issue. All AMF samples use default DX9 AMD device. If the device is not found the samples just fail - InitDX9(NULL) returns error. We assume that all monitors are connected to NVidia card. In this case application doesn't see any AMD DX9 device. Could you please test which function causes the drive crash. Is it InitDX9(NULL)?
Could you please also try to uninstall all graphic drivers and reinstall them? For AMD use a utility from amd.com. http://support.amd.com/en-us/kb-articles/Pages/AMD-Clean-Uninstall-Utility.aspx

**Comment by Xaymar** [comment]
GPU/Monitor:
- GTX 1080 Ti: All Monitors, PCI-E3x16 Slot 1, Driver 384.76
- R9 285: No Monitors, PCI-E3x8 Slot 2, Driver 17.7.1 Clean Install (AMD Clean Uninstall Utility and Display Driver Uninstaller were used)

Sample settings:

```
VCEEncoderD3D.exe -WIDTH 256 -HEIGHT 256 -OUTPUT file -QualityPreset Speed -RENDER DX11 -FRAMES 300 -CODEC AVC -Usage TRANSCODING -Profile High -ProfileLevel 52 -FullRangeColor false -Framerate 60,1 -RateControlMethod CBR -RateControlPreAnalysisEnable DISABLED -RateControlSkipFrameEnable false -MinQP 18 -MaxQP 51 -TargetBitrate 6000000 -PeakBitrate 6000000 -QP_I 22 -QP_P 22 -QP_B 22 -DeBlockingFilter true -FillerDataEnable false -EnableVBAQ false -EnforceHRD false -VBVBufferSize 6000000 -InitialVBVBufferFullness 64 -HalfPixel true -QuarterPixel true -MaxNumRefFrames 4 -BPicturesPattern 0
```

As you can see it happens with DirectX 11, DirectX 9 has no ability to select a GPU that does not have a monitor attached. If I attach a monitor to the AMD gpu it no longer happens until i detach the monitor again.

**Comment by MikhailAMD** [comment]
The original report says that all samples fail. Most of samples run on DX9. Can you confirm: 
- which sample fail with DX9 (is monitor attached or not?)
- VCEEncoderD3D.exe fails on DX11 (is monitor attached or not?)

**Comment by Xaymar** [comment]
By "all samples" i meant SimpleDecoder, SimpleEncoder, TranscodeHW and SimpleConverter, which all can use InitDX11 (DirectX 11). The same behaviour is experienced in the OBS Studio plugin.

---- 

>which sample fail with DX9 (is monitor attached or not?) 

None. All fail with DirectX 11, since DirectX11 is the only one capable of selecting the GPU without monitors.

> VCEEncoderD3D.exe fails on DX11

Monitor is not attached to AMD GPU. All Monitors are always attached to other vendor GPUs (Intel, Nvidia)

**Comment by Xaymar** [comment]
One thing to note is that if the AMD GPU had a monitor attached during boot or later, any further VCE/UVD use actually starts working. AMD Radeon Settings will then not complain about having no GPU and only say that it is currently not available.

**Comment by Xaymar** [comment]
It seems that this issue is specific to the R9 285, I can't get it to happen on the RX 480.

**Comment by Xaymar** [comment]
My steps are as follows:
1. Uninstall all Drivers (DDU and/or Clean Uninstall Utility)
2. Shut down computer, remove all AMD GPUs, install NVIDIA+AMD (Nvidia primary) or Intel+AMD (Intel primary, no power saving sharing)
3. Start, install drivers for both GPUs.
4. Restart
5. Attempt to use VCE.
On the R9 285 it crashes. On the RX 480 it doesn't.

I have repeated this test 10 times and got it to happen every time. I don't know why or what causes it - maybe the GPU is faulty, but that wouldn't explain why it starts working after a display is attached to it.

**Comment by Xaymar** [comment]
Closing this as a potential HW failure.
