### ISSUE TITLE
A year later, where is the 2-pass encoding?

### ISSUE THREAD

**Issue by meredith2u** [GPUOpen-LibrariesAndSDKs/AMF#101]
Is there a plan to achieve 2-pass encoding on Polaris GPU? I have been waiting for a long time.

**Comment by Benman2785** [comment]
https://community.amd.com/message/2813596

here a link to AMD ;)

**Comment by meredith2u** [comment]
As I know the Pre-Pass is not 2-pass encoding, or is it?

**Comment by Xaymar** [comment]
It is the same.

**Comment by meredith2u** [comment]
Looks like the 17.7.2 driver has been implemented Pre-Pass, so close this post.
