### ISSUE TITLE
H265: Crash when calling ->Flush() on the encoder

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#102]
Accidentally discovered while testing 17.7.2 with a 100% repro rate. Calling Flush() on a HEVC encoder will promptly cause it to crash inside atiumdva.dll (uncatchable exception).

This is a regression bug, it didn't happen in earlier drivers.

Mini Dump: http://cdn.xaymar.com/private/2017/07/28/15/AMFHevcDrainCrash.dmp
Dump: http://cdn.xaymar.com/private/2017/07/28/15/AMFHevcDrainCrashBig.7z

**Comment by Xaymar** [comment]
Additionally, if Flush() can't be called the code then crashes on the Terminate() call in the exact same location.

**Comment by MikhailAMD** [comment]
Ticket submitted.

**Comment by MikhailAMD** [comment]
Fixed: tested with driver 17.8.2
