### ISSUE TITLE
FFMpeg Switch

### ISSUE THREAD

**Issue by Gabee8** [GPUOpen-LibrariesAndSDKs/AMF#104]
Hello!
How to use AMD video acceleration in ffmpeg switch with encoding?
Please help.

**Comment by Benman2785** [comment]
https://github.com/Xaymar/ffmpeg-amf

**Comment by Gabee8** [comment]
Hello!
Show cmd this error out:
Unknown encoder 'h264_amf'

**Comment by MikhailAMD** [comment]
- Did you build ffmpeg according to instructions (Build.txt)?
- Did you switch ffmpeg to "amf-integration" branch before building? 
- Which AMD card do you have?
- Do you have the latest drivers?
-

**Comment by Gabee8** [comment]
Hello.
I try Thirdparty\ffmpeg\ffmpeg-3.3.1\win32\release\bin folder ffmpeg.exe
My videocard is ATI HD7770 and latest drivers.

**Comment by MikhailAMD** [comment]
Did you switch ffmpeg to "amf-integration" branch before building?

**Comment by Xaymar** [comment]
I'm pretty sure the user tried to encode using h264_amf in the ffmpeg version that the SDK currently bundles, which would not be correct. @Gabee8 You currently have to build ffmpeg support from scratch, the link for the repository is what @Benman2785 linked you to.

**Comment by MikhailAMD** [comment]
AMF was integrated in FFmpeg.
