### ISSUE TITLE
Capability report fails for HEVC encoder

### ISSUE THREAD

**Issue by Masa-tam** [GPUOpen-LibrariesAndSDKs/AMF#105]
Affected Drivers: 17.7.2 / 17.8.1 / 17.8.2
Hardware: RX 550

With the driver version 17.7.2 or later, CapabilityManager sample program returns that RX 550 does not support HEVC encoder.
Information can be get correctly by installing 17.7.1.

**Comment by MikhailAMD** [comment]
working on this.

**Comment by Roph** [comment]
I can't get the HEVC encoder to work at all, either via MFT (A's convertor) or AMF (xaymar's OBS plugin) on newer drivers, 17.7.2 and beyond. It just doesn't do anything. A's doesn't progress, OBS appears to record but just records nothing.

I'm using known-good presets that on older drivers have output HEVC just fine.

**Comment by MikhailAMD** [comment]
Capability manager issue was fixed in 17.9.2 driver released today.
