### ISSUE TITLE
AMF_VIDEO_ENCODER_HEVC_CAP_MAX_BITRATE returns Illegal value.

### ISSUE THREAD

**Issue by Masa-tam** [GPUOpen-LibrariesAndSDKs/AMF#107]
Affected Drivers: 17.10.1
Hardware: RX Vega 56

AMF_VIDEO_ENCODER_HEVC_CAP_MAX_BITRATE returns 2147483647(=0x7fffffff).
However, when the bitrate is set above 100Mbps, the encoder returns AMF OUT_OF_RANGE.

**Comment by MikhailAMD** [comment]
We tried to set HEVC bitrates to more then 100Mbit but didn't get the error you describe. Could you please modify SimpleEncoder sample, reproduce the issue and attach the CPP? 
Thanks

**Comment by Masa-tam** [comment]
I must sincerely apologize. It was not a problem of the bit rate upper limit, it was a problem that occurred because the wrapper library I created had set VBV based on the bit rate.
Just AMF_VIDEO_ENCODER_HEVC_VBV_BUFFER_SIZE has no cap in the document, but it was unable to exceed 100 Mbits.
Therefore, when the bit rate exceeds 100 Mbps, my wrapper sets a value exceeding 100 Mbits to the VBV Buffer Size, resulting in an error as a result.
