### ISSUE TITLE
AMF API: amfrt*.dll not available when no monitor is connected to the GPU/APU

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#11]
Reported [here](https://github.com/Xaymar/OBS-AMD-Media-Framework/issues/42) by one of my plugin users, it seems that when the GPU/APU has no monitors attached that the DLL is nowhere to be found. Perhaps install the DLL files into a common folder in the next driver release no matter if there is a Monitor attached or not?

**Comment by MikhailAMD** [comment]
If driver was installed the DLL would be there. Is it possible that the customer is on clean machine and uses 32 bit version of OBS? We have an issue that does not install VS2013 runtime DLLs for 32 bit. Working on the fix.
Another possible quirk: if monitor is not attached the application cannot create D3D9 device and AMF may need it. Thanks to MSFT. Not much I can do here. AMF inside checks the OS and on Win10 initializes AMF to DX11 if nothing was initialized. But the plug-in forces one of DX.

**Comment by Xaymar** [comment]
```
13:52:17.519: [AMF Encoder] Version 1.3.0pre1-1.3.0.5
13:52:17.519: [AMF Encoder] <Plugin::AMD::AMF::AMF> Initializing...
13:52:17.520: [AMF Encoder] <Plugin::AMD::AMF::AMF> Loading of 'L"amfrt64.dll"' failed with error code 126.
```

As far as I understood the log file, LoadLibraryW just failed to find the amfrt64.dll, which means that the user was using 64-bit OBS. Normally, amfrt64.dll should be in %WINDIR%\System32 and amfrt32.dll in %WINDIR%\SysWOW64 so I'm not sure what happened here. I'll update this if another user reports this happening again.

**Comment by MikhailAMD** [comment]
He may installed minimum version of the driver and don't have VS2013 runtime. For now he may need to install it manually. Later we will change linking to static runtime.

**Comment by Xaymar** [comment]
I have so far not been able to reproduce this at all. Closing it for now.
