### ISSUE TITLE
Raven Ridge decode/encode features

### ISSUE THREAD

**Issue by NikosDi** [GPUOpen-LibrariesAndSDKs/AMF#110]
I have read to a few places over the Internet that Raven Ridge APUs using VEGA graphics leverage a new video decoder/ encoder called VCN 1.0 (Video Core Next)

Do you mind sharing the decoding/ encoding capabilities of that video engine ?

Does it support decoding in fixed-function hardware of VP9 8bit/10bit video format ?

Thanks in advance.

**Comment by MikhailAMD** [comment]
No comments on unreleased HW. Sorry.

**Comment by NikosDi** [comment]
But I thought you have already released two products (SKUs) based on Raven Ridge:
**Ryzen 7 2700U** and **Ryzen 5 2500U**.

They are members of Ryzen Mobile released on 26/10/2017.

Right ?

**Comment by MikhailAMD** [comment]
Technically yes, though first machines yet to appear on the market. Anyway, I am not providing white papers with features and performance numbers similar to the one which was released for Vega. I will pass the request, though.

**Comment by wakywarez** [comment]
yes use VCEEnc and VCN 1.0

**Comment by NikosDi** [comment]
Yes, it seems that VCN 1.0 inside Raven Ridge APU support VP9 8bit/10bit in hardware, but it's very slow.

The pure decoding (renderless) performance of VP9 8bit/10bit in not bad, but even using very light renderer like EVR it drops to half.

I have seen some numbers using Ryzen 5 2500U and rather slow single channel DDR4-2133MHz RAM de, but even using desktop version of Raven Ridge APU like Ryzen 5 2400G with dual channel faster memory, things are not looking good.

The situation is far more worse using heavier renderers like EVR-CP.

Probably a Polaris refresh using VCN 1.x or new Vega discrete cards with VCN 1.x could do it better than APUs

**Comment by MikhailAMD** [comment]
Closed as stale issue
