### ISSUE TITLE
SubmitInput fails with AMF_INPUT_FULL after update to 17.11.1

### ISSUE THREAD

**Issue by FBirth** [GPUOpen-LibrariesAndSDKs/AMF#111]
After recent driver updates our capture software cannot encode anymore with AMD encoder.

We get these error messages after the session was started.

    [AMFDeviceDX11Impl]   Error: ..\..\..\..\..\runtime\src\core\DeviceDX11KernelImpl.cpp(267):COM failed, HR = 80070057:CreateShaderResourceView() failed
    [BltRGBto420Compute]   Error: ..\..\..\..\..\runtime\src\components\VideoConverter\Kernels\BltRGBto420Compute.cpp(60):AMF_ERROR 18 : AMF_DIRECTX_FAILED: m_pKernelRGB_NV12->SetArgPlane(index++, pSrcSurface->GetPlane(AMF_PLANE_PACKED), AMF_ARGUMENT_ACCESS_READ)
    [Blt]   Error: ..\..\..\..\..\runtime\src\components\VideoConverter\Kernels\Blt.cpp(97):AMF_ERROR 18 :     AMF_DIRECTX_FAILED: converter.Convert(pSrcSurface, pDstSurface, profile, fill, color, linearRGB, true)
    [AMFVideoConverterImpl]   Error: ..\..\..\..\..\runtime\src\components\VideoConverter\VideoConverterImpl.cpp(655):AMF_ERROR 18 : AMF_DIRECTX_FAILED: m_pKernel->Process(m_pSurfaceIn, pSurfaceOutKernelMem, colorProfile, scale, fill, color, linearRGB)
    [AMFEncoderVCE]   Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(2222):AMF_ERROR 18 : AMF_DIRECTX_FAILED: m_pConverter->QueryOutput Failed
    [AMFEncoderVCE]   Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(2219):AMF_ERROR 25 : AMF_INPUT_FULL: m_pConverter->SubmitInput Failed

    [AMFEncoderVCE]   Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(2219):AMF_ERROR 25 : AMF_INPUT_FULL: m_pConverter->SubmitInput Failed

We had no such problems with driver 17.10.1.

Looks a bit like this issue that was reported for the AMD encoder plugin in OBS Studio here:
https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/288

**Comment by MikhailAMD** [comment]
The latest driver switched default color conversion for D3D11 case from internal submission to DirectCompute. And it has several limitations. The main one is that DirectCompute does not accept DXGI_FORMAT_XXXXX_TYPELESS input.
We are working on improvements but meanwhile you can do one of following:
1.  Submit fully typed D3D11 textures.
2. Use AMF color converter as a separate component. See SimpleConverter sample. There is a property where you can force old behavior by setting AMF_VIDEO_CONVERTER_COMPUTE_DEVICE = AMF_MEMORY_COMPUTE_FOR_DX11. Note that this works with current GPUs but will not with future GPUs.
3. We will push a driver fix with conversion from TYPELESS to a fully qualified format ASAP  
Thanks

**Comment by FBirth** [comment]
Thanks a lot for the explanation. I'll try if I can apply one of the workarounds.

**Comment by FBirth** [comment]
I can confirm that encoding works fine if I pass DXGI_FORMAT_NV12 textures.

**Comment by MikhailAMD** [comment]
Yes, NV12 doesn't require color conversion.

**Comment by MikhailAMD** [comment]
This should be reolved in the latest driver.

**Comment by FBirth** [comment]
@MikhailAMD, the latest driver I see is 17.12.2. Should the conversion work again with that drivers? Do I have to change code? Because for my application 17.12.2 still doesn't work.

**Comment by MikhailAMD** [comment]
This driver doesn't have the fix. Should appear in the next big release. The SW version for 17.12.2 is 17.50.xxxx. Watch for 18.xxxxx.

**Comment by FBirth** [comment]
Thanks for the information.

**Comment by MikhailAMD** [comment]
Closed as stale issue
