### ISSUE TITLE
Possible memory leaks in FileMuxerFFMPEGImpl.cpp

### ISSUE THREAD

**Issue by velorom** [GPUOpen-LibrariesAndSDKs/AMF#113]
Hello, I developing my custom muxer, using ffmpeg and external encoded data. But in some moment I realized, that I have memory leaks in `av_interleaved_write_frame`. I start searched how to fix it and found your project. I looked in your code and found, that your code is exactly the same. So I suppose, that you have memory leaks too.
I think that the reason is in AVPacket initialization. Typically we get packets from encoder functions (`avcodec_encode_video2` or `avcodec_encode_audio2`). So I suppose that they have some additional initializations in this functions.
I fixed my memory leaks by using `av_packet_from_data` function.

**Comment by MikhailAMD** [comment]
I went through FFmpeg implementation and don't see the reason for the leak (in AMF case). The data pointer stored in AVPacket is owned by AMFBuffer object and will be deleted there. There seem no other allocations in question.

**Comment by velorom** [comment]
This is was my code before fix (listing don't breaks, I just highlighted a code, that changed):

```
AVPacket enc_pkt = {};
```
```
av_init_packet(&enc_pkt);
enc_pkt.data = (uint8_t *)av_malloc(output.dwOutputSize);
enc_pkt.size = output.dwOutputSize;
memcpy_s(enc_pkt.data, output.dwOutputSize, output.lpOutputData, output.dwOutputSize);
```
```
enc_pkt.stream_index = stream_index;
if ((output.dwFlags & ENCODER_OUTPUT_FLAG_KEYFRAME) == ENCODER_OUTPUT_FLAG_KEYFRAME)
  enc_pkt.flags |= AV_PKT_FLAG_KEY;
else
  enc_pkt.flags = 0;
enc_pkt.pts = output.qwTimestampPts;
enc_pkt.dts = output.qwTimestampDts;
enc_pkt.duration = 1;

av_packet_rescale_ts(&enc_pkt, {1, framerate}, ofmt_ctx->streams[stream_index]->time_base);

ret = av_interleaved_write_frame(ofmt_ctx, &enc_pkt);
if (ret < 0) {
  write_to_log("ERROR: WritePacket2: av_interleaved_write_frame(%p, %p) returns %d", ofmt_ctx, &enc_pkt, ret);
  return ret;
}
```

But when i changed code to:

```
AVPacket enc_pkt = {};
```
```
uint8_t *data = (uint8_t *)av_malloc(output.dwOutputSize);
memcpy_s(data, output.dwOutputSize, output.lpOutputData, output.dwOutputSize);
av_packet_from_data(&enc_pkt, data, output.dwOutputSize);
```
```
enc_pkt.stream_index = stream_index;
if ((output.dwFlags & ENCODER_OUTPUT_FLAG_KEYFRAME) == ENCODER_OUTPUT_FLAG_KEYFRAME)
  enc_pkt.flags |= AV_PKT_FLAG_KEY;
else
  enc_pkt.flags = 0;
enc_pkt.pts = output.qwTimestampPts;
enc_pkt.dts = output.qwTimestampDts;
enc_pkt.duration = 1;

av_packet_rescale_ts(&enc_pkt, {1, framerate}, ofmt_ctx->streams[stream_index]->time_base);

ret = av_interleaved_write_frame(ofmt_ctx, &enc_pkt);
if (ret < 0) {
  write_to_log("ERROR: WritePacket2: av_interleaved_write_frame(%p, %p) returns %d", ofmt_ctx, &enc_pkt, ret);
  return ret;
}
```
memory leaks disappeared. I doesn't change anything else. 
But anyway, I just saying. If someone will report you about memory leaks, you will know where to search :)

**Comment by MikhailAMD** [comment]
The difference between your original code and AMF sample code is in this allocation:
enc_pkt.data = (uint8_t *)av_malloc(output.dwOutputSize);
AMF doesn't do it, it just assigns pointer so it doesn't leak:
 pkt.data = static_cast<uint8_t*>(pInBuffer->GetNative());

**Comment by velorom** [comment]
I also tried allocate memory with malloc, and even free it immediatly after av_interleaved_write_frame call (with free and av_freep accordingly), but no luck. And I think, that av_malloc is more appropriate, because in this way ffmpeg cares about freeing memory.

**Comment by MikhailAMD** [comment]
Seems AMF implementation doesn't have this issue.

**Comment by lyzirving** [comment]
any way, velorom's comment helps me solve my problem, thx a lot!
