### ISSUE TITLE
R9 Fury crashes with AMD Driver 17.12.2

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#114]
Reported here: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/291

Seems to be a crash inside the Direct3D 11 runtime caused (directly or indirectly) by amfrt64.dll, possibly due to Intel hardware co-existing. Crashes during encoder initialization, so there is not much logging by the plugin itself.

**Comment by MikhailAMD** [comment]
We cannot reproduce this issue so far. Could you please ask for DXDIAG log?. Also tester used v 2.2.4  - the released plug-in version, can you please ask to try it?

**Comment by smeep0** [comment]
[DxDiag.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/1600278/DxDiag.txt)

**Comment by Xaymar** [comment]
@MikhailAMD 2.2.4 and 2.3.x are functionally identical, 2.3.x only blacklists older drivers and renames "Target Bitrate" internally to "bitrate" so that the other OBS code (networking, replay buffer) doesn't break.

**Comment by Xaymar** [comment]
This is an issue with Duet Display, as confirmed by the original user experiencing the issue.
