### ISSUE TITLE
Driver 18.2.1: H264 Encoder occasionally becomes completely unusable

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#116]
A really odd bug that was introduced with the 18.x versions, and as such is a regression from earlier driver versions. The symptoms seem random and can range from [short freezes](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/296) to full on hardware crashes, resulting in a forced reboot by the Mainboard.

This is a random bug, sometimes things work great, other times things don't. It would be best to run some kind of runtime checking side by side to see if the Runtime is not doing something it shouldn't do.

### Files:
- [OBS Log Files.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/1692219/OBS.Log.Files.zip)
- Unfortunately no dump file as it is quite literally impossible to get one, since the system reboots shortly afterwards - not with a bluescreen either.

### System Information
- MB: Gigabyte GA-H97-D3H
- CPU: Intel i5-4690
- GPU: AMD RX 480 8GB, XFX RX 480 8GB (CrossFire)
- RAM: 16GB DDR3, 1333 Mhz, 4 DIMMS
- HDD: 1x1TB

**Comment by Benman2785** [comment]
yeah - noticed that short freezes too
could also be the reason for some of my crashes

i got a win10-bluescreen once, and a "real" blue screen - needed to reset manually

**Comment by MikhailAMD** [comment]
It would help if you could produce a small GPUVIEW log when stuttering happens + dxdiag log.

**Comment by Benman2785** [comment]
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-26_13-01-22.7z
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-26_13-01-22.flv
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-26_13-01-22.txt
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-26_13-01-22_DxDiag.txt

freezes ~0:47 & ~0:55 & 1:02 & 1:07
ps game had noticeable stutter around 0:51& 0:55 & 1:44

**Comment by Benman2785** [comment]
you got lucky - i got one of the crashes on gpuview (while i hunted those freezes)

ps this isnt AMF related - so pls hand them over to AMD Driver team ;)
http://benmanshafen.de/downloads/amd/Merged.7z

**Comment by MikhailAMD** [comment]
I will but please use another forum for AMF-unrelated problems.

**Comment by Xaymar** [comment]
Closing as I no longer have the original HW configuration, or the ability to properly test this anyway.
