### ISSUE TITLE
H264: Init() returns AMF_FAIL with no Display attached (during boot)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#117]
Accidentally discovered during plugin testing, it seems that AMF's Init() for H264 returns AMF_FAIL if there was no display connected during the boot process. There is no reason for H264 encoding to fail if there was no Display attached, especially since it is initialized on a Direct3D11.1 context.

### Reproduction Steps
1. Boot computer without Display, start a remote session that uses a virtual desktop (Windows 10).
2. Start OBS Studio H264 encoding or ffmpeg h264_amf.
    - The same steps work for H265.

**Comment by MikhailAMD** [comment]
1. Quote: "Boot computer **without GPU**"? Maybe without monitor connected?
2. This may happen if DX9 is used. You should try SimpleEncoder sample in DX11 mode.

**Comment by Xaymar** [comment]
1. Yes, I meant Display/Monitor.
2. Encoding was done with Direct3D 11.1, as stated in the message above.

**Comment by MikhailAMD** [comment]
PLs test sample, I don't have my dev machine for a day or two to try.

**Comment by MikhailAMD** [comment]
I've tested SimpleEncoder and VCEEncoderD3D AMF samples in DX11 mode on machine with disconnected monitors, rebooted and connected via remote display. Samples work. Please debug your application or reproduce the issue with samples.

**Comment by Xaymar** [comment]
Closing as I can't reproduce this anymore.
