### ISSUE TITLE
Ryzen G: Encoding not working out of the box

### ISSUE THREAD

**Issue by FBirth** [GPUOpen-LibrariesAndSDKs/AMF#118]
We found that AMD encoding  with the new AMD Vega APUs is not working out of the box in our software. We have tow variants of capture software: One is crashing, the other just not recording.

We haven't started debugging yet, but you might give us some hints. E.g.
* Are there any limitations for Vega APUs (max. bitrate etc.)? 
* Do the Vega APUs require different handling?

**Comment by MikhailAMD** [comment]
It should be no difference between Vega APU and  Vega discrete. To save time please provide:
- dxdiag log
- try Simple encoder sample
- enable full AMF logging and provide failing log and the successful log for your older GPU or API
- for crash please provide crash dump
Full logging:
trace->EnableWriter(AMF_TRACE_WRITER_DEBUG_OUTPUT, true);
trace->SetWriterLevel(AMF_TRACE_WRITER_DEBUG_OUTPUT, AMF_TRACE_DEBUG);
or you can redirect it to file:
trace->(const wchar_t* path);
trace->EnableWriter(AMF_TRACE_WRITER_DEBUG_FILE, true);
trace->SetWriterLevel(AMF_TRACE_WRITER_DEBUG_FILE, AMF_TRACE_DEBUG);

**Comment by MikhailAMD** [comment]
Closed as stale issue
