### ISSUE TITLE
REQUEST 24fps-mode!

### ISSUE THREAD

**Issue by Benman2785** [GPUOpen-LibrariesAndSDKs/AMF#119]
@Xaymar told me that AMF kind of needs multiples of 30 for best results
(i guess) because it has fixed GOP and/or encoder - and not using variables of FPS to encode

due to given quality-output of AMF i think 720p48@4872kbps (+576kb Buffer) is optimum for speed and quality when streaming to twitch.tv (720p60@5mbit isnt watchable // 720p30 isnt "quick-smooth")
BUT i noticed that when i run in 30FPS or 60FPS the output is "smoother" and AMF has less impact than 24FPS or 48FPS on the Game

so i request an addition that AMF can also handle multiples of 24 - that would vastly increase quality while it still maintains a smooth output // best would be if its automatically choosen (or can be set manually // or 3 fixed modes: 24; 25; 30)

if you want i can provide testvideos and speak about personal noticed impact on the game

**Comment by MikhailAMD** [comment]
AMF is using frame rate for rate control and writes it to VUI header. Simply speaking how many frames is in second and home many bits can be spent per frame.
All smoothness or lack of it comes from interaction of a capture app with game. In that sense frame rate may matter.

**Comment by Benman2785** [comment]
ok
i use latest OBS Studio
i dont have that Problem using x264 720p48

**Comment by Benman2785** [comment]
noticed "VBAQ" is directly connected to "stuttery output" - if disabled 48FPS is super smooth

**Comment by MikhailAMD** [comment]
Can you please share a short clip showcasing stuttering?

**Comment by Benman2785** [comment]
actually wanted to post them too for Xaymar ;)

![720p48_h264 4872kbps_aac 128kbps_nohrd_cabac_vbaq_tra_b2_que3](https://user-images.githubusercontent.com/21282980/37625050-b243b6b4-2bca-11e8-968d-ceb84217a81d.jpg)
http://benmanshafen.de/obs/xaymar/2.3.3/720p48_h264+4872kbps_aac+128kbps_noHRD_CABAC_VBAQ_tra_b2_que3.flv

![720p48_h264 4872kbps_aac 128kbps_nohrd_cabac_tra_b2_que3](https://user-images.githubusercontent.com/21282980/37625057-b86f7c44-2bca-11e8-8490-928a2b57053b.jpg)
http://benmanshafen.de/obs/xaymar/2.3.3/720p48_h264+4872kbps_aac+128kbps_noHRD_CABAC_tra_b2_que3.flv

you see that the first one stutters - i use OpenCL Transfer
![720p48_h264 4872kbps_aac 128kbps](https://user-images.githubusercontent.com/21282980/37625098-dc9d6496-2bca-11e8-9e64-ef64799035f6.jpg)

**Comment by Benman2785** [comment]
its noticeable when using a 144hz 1ms screen - on my 75Hz IPS it just happens a few times when playing the same video

**Comment by MikhailAMD** [comment]
Is this still an issue?
