### ISSUE TITLE
Video Encode API: Driver Crash inside SubmitInput

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#12]
Graphics Driver crashes for no apparent reason, rendering SubmitInput to do exactly nothing and QueryOutput to return AMF_REPEAT. Might be related to #22.

Happens with any Memory Type, including with and without OpenCL. Occasionally a BSOD is going to happen with the message THREAD_STUCK_IN_DEVICE_DRIVER.

My System Specs:

- MB: ASRock 970 Pro3
- CPU: AMD FX-6100 (Stable 4.0 Ghz, tested with Prime95 over 8 hours)
- GPU: AMD R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
- HDD: 2x Seagate 2TB 7200rpm
- Windows 10 64 Bit (Auto-updated, Anniversary Update is installed)

Dump Files:

* http://cdn.xaymar.com/private/2016/09/DriverCrash_16-9-2_obs64.7z

Developer Community: https://community.amd.com/message/2751281

**Comment by Xaymar** [comment]
Additionally, when using these settings amfrt64.dll crashes at Terminate() with the following exception:
`Exception thrown at 0x00007FFA0AF8B670 (amfrt64.dll) in obs64.exe: 0xC0000005: Access violation executing location 0x00007FFA0AF8B670.`

**Comment by MikhailAMD** [comment]
Can you produce and share dumps for crashes? 
Crash In Terminate() 
1. Who is calling terminate?
2. Did you implement Drain() of Flush()
3. Is it easy to reproduce?

**Comment by Xaymar** [comment]
1. Terminate() is called by the plugin when it is supposed to stop encoding.
2. No, right now I did not, I was not aware that this was necessary for a proper Terminate() call.
3. It happens every time with these settings, at least with my system. As for the driver crash, that ones a little harder to reproduce as it requires a specific action to be done at the same time (loading stuff into VRAM).

My System:
- AMD FX-6100
- AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
- ASRock 970 Pro 3
- Windows 10 64-Bit (automatically updated to latest version, non-insider)

**Comment by Xaymar** [comment]
Another user has managed to crash the driver, also with a R9 285. I'm not sure if this is a 3rd Generation GCN issue or a VCE issue.
See here: https://obsproject.com/forum/threads/amd-advanced-media-framework-encoder-plugin-for-obs-studio.52305/page-10#post-238327

**Comment by Xaymar** [comment]
Also I'm not sure how to create a dump for amfrt*.dll, do I just dump the full process in case it happens to me?

**Comment by MikhailAMD** [comment]
Yes, just dump for whole process.
Thanks,
Mikhail

**Comment by MikhailAMD** [comment]
Hey,

Few small things from the latest code:

1. There is no need to call surface->Acquire(); surface->Release(); You use smart pointers in the queue and they will do all work.

2. if you got AMF_INPUT_FULL on SubmItInput() you probably should not exit loop because next attempt to submit will be only when the next frame will be put in the queue. something like res = AMF_OK;  will do the job.


Thanks,

Mikhail

________________________________

**Comment by Xaymar** [comment]
1. Alright. I'll change it back.
2. The queue so far has always been up to speed with the code so far, nothing really increased past the limit except when encoding literally gets stuck as reported in #19. I changed it to try for 5 milliseconds, waiting a single msec between SubmitInput calls and if it still didn't work to just wait for the next signal. I had issues with it forever getting stuck in a AMF_INPUT_FULL loop before.

**Comment by MikhailAMD** [comment]
Did you try InitOpenCL()?
SubmitInput has no places to stuck except to wait for CSC and therefore for HW 3D queue.

Mikhail

**Comment by Xaymar** [comment]
> Did you try InitOpenCL()?
> SubmitInput has no places to stuck except to wait for CSC and therefore for HW 3D queue.
> 
> Mikhail

Testing with InitOpenCL resulted in the overloaded/stuck issue happening immediately and upon 2nd run it caused the following error:
```

20:51:36.034: [AMF Encoder] <Plugin::AMD::VCEEncoder::SendInput> Input Queue is full, dropping frame...
20:51:36.035: [AMFTrace::AMFEncoderVCE]    Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(1986):Assertion failed:SubmitInput() - Invalid param
20:51:36.035: [AMF Encoder] <Plugin::AMD::VCEEncoder::InputThreadLogic> SubmitInput failed with error A (code 4).
```

**Comment by MikhailAMD** [comment]
OK, there are two issues:

1.      OpenCL is slow to start up

2.      Before calling SubmitINput() call surface->Convert(AMF_MEMORY_OPENCL);

Mikhail

**Comment by Xaymar** [comment]
Got the same BSOD as the other user now, THREAD_STUCK_IN_DEVICE_DRIVER. No dump generated from Windows, was stuck at 0% for ~5 minutes before I hit the reset button.

**Comment by Xaymar** [comment]
Can't reproduce anymore, seems to have been fixed in 16.9.1 or a Windows Update. Closing.

**Comment by Xaymar** [comment]
Re-encountered just now, here is the dump file:

* http://cdn.xaymar.com/private/2016/09/DriverCrash_16-9-2_obs64.7z

Additionally I have deleted any on my comments here so it's clean issue again.

**Comment by MikhailAMD** [comment]
OK, the driver crash (TDR) was reproduced and internal ticket logged.

**Comment by Xaymar** [comment]
Seems to have been fixed by 16.10.1 by what I can tell. I have not managed to crash the driver with my usual test setup.

**Comment by MikhailAMD** [comment]
I am not aware of this particular fix (the ticket was not closed) but late we couldn't repro it. There are many other changes that could be responsible. Let's wait for some stats.

Mikhail
On Wed, Oct 05, 2016 at 3:56pm, Michael Fabian Dirks <notifications@github.com<mailto:notifications@github.com>> wrote:


Seems to have been fixed by 16.10.1 by what I can tell. I have not managed to crash the driver with my usual test setup.

-

**Comment by dvv47** [comment]
Hello, i am also got crash after SubmitInput on Windows 7 x64

I use DirectX11 surface B8G8R8A for input, submit it to converter for resize, and then push Data to encoder.
Driver 16.10.1
GPU r9 380
Preset ultra_low_latency

And this code works fine with windows 10 x64

With this crash stack trace
 	dxva2.dll!000007fef5014fda()	Unknown
 	dxva2.dll!000007fef5014f84()	Unknown
 	dxva2.dll!000007fef5014d26()	Unknown
 	dxva2.dll!000007fef501694d()	Unknown
 	dxva2.dll!000007fef50168a4()	Unknown
 	dxva2.dll!000007fef5014d26()	Unknown
 	amdave64.dll!0000000073f4538f()	Unknown
 	amdave64.dll!0000000073f44f34()	Unknown
 	amdave64.dll!0000000073f43f3c()	Unknown
 	amdave64.dll!0000000073f4111f()	Unknown
 	amfrt64.dll!000007fee44eb4a1()	Unknown
 	amfrt64.dll!000007fee44eac27()	Unknown
 	amfrt64.dll!000007fee44e9897()	Unknown
 	amfrt64.dll!000007fee44f323b()	Unknown
 	amfrt64.dll!000007fee44af730()	Unknown

**Comment by Xaymar** [comment]
@dvv47 You do not have the same crash, your crash is related to using DirectX11 on Windows 7 which is not supported. See #25 for an answer.

**Comment by MikhailAMD** [comment]
Hi,
Win 7 has limited support for DX11. In particular, encoder works only using DX9. It is possible to use DX11 surfaces in converter but AMF needs to be programmed certain way:

1.      InitDX9()

2.      InitDX11()

3.      InitOpenCL()

4.      Force converter to work via OpenCL and return DX9 NV12 surface:

-        AMF_VIDEO_CONVERTER_MEMORY_TYPE = DX9

-        AMF_VIDEO_CONVERTER_COMPUTE_DEVICE = OPENCL
So the logic would be:

1.      Application submit DX11 texture (should be allocated by AMF or allocated by application with shared handle for performance reasons)

2.      AMF interops input texture into OpenCL

3.      AMF allocated DX9 output surface

4.      AMF interops it into OpenCL

5.      AMF runs converter GPU kernels using OpenCL

6.       AMF un-interops output surface back to DX9 and returns it

7.      Application submits DX9 NV12 surface to the encoder
I will add more error checking for the next release.
Thanks,
Mikhail

**Comment by Xaymar** [comment]
OpenCL works like a charm now and I'm no longer able to reproduce this. So this was most likely fixed.
