### ISSUE TITLE
FrameRateTargetControl + AMF = noticeable stutter ingame + usually crashes within 30min

### ISSUE THREAD

**Issue by Benman2785** [GPUOpen-LibrariesAndSDKs/AMF#120]
when i use FRTC + AMF it impacts the game (stutter) and randomly crashes

also crashes for games with built in framerate-cap (like the Division)

http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-26_00-16-48_game_crash.flv
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-26_00-16-48_game_crash.txt

http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-25_23-40-53_FRTC.flv
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-25_23-40-53_FRTC.txt

cant provide dumps - thedivision.exe was killed
when using driver-FRTC driver crashes - i try to get a dump

**Comment by MikhailAMD** [comment]
I acknowledge the problem but since the game process crashed and not OBS process where AMF is used the problem should be brought to general AMD support. Although, I will send a note to responsible team,  it doesn't look like AMF issue. And  the log is clean.

**Comment by Benman2785** [comment]
thank you

and yes, i think its more a general driver problem than AMF related

i will try to reproduce a crash of OBS (that randomly happens) - but those crashes could be related to #116

**Comment by MikhailAMD** [comment]
Is this still an issue?
