### ISSUE TITLE
Tool to detect AMF capabilities

### ISSUE THREAD

**Issue by rboy1** [GPUOpen-LibrariesAndSDKs/AMF#121]
I'm working on a project to which involves doing video encoding. I would like to use the AMF hardware encoding capabilities, but to use it I need to first figure out if the system supports AMF and if the driver installed supports AMF hardware encoding of h.264 and hevc

Is there some sort of a CLI tool available that I can run to figure out the capabilities of the installed drivers and if it supports AMF and what capabilities it supports?

NVIDIA has a simple tool which provides the CUDA version of the capabilities of the driver/hardware. Hopfefully I can find something similar for AMF.

Is there a similar CLI tool which can print the AMF capabilities or some way to detect the presence of AMF encoders?

**Comment by rboy1** [comment]
If I'm reading your code correct basically you're just initializing the encoder and it will detect if the capabilities are present or throw an error is not? I didn't understand your comment about "actually work".

**Comment by Xaymar** [comment]
Yes, that is exactly what that process does. It is spawned by the plugin itself to check for unexpected behavior ("actually work"), such as crashing, memory corruption or even device crashes. While these are "rare" (around 7% of all crashes I've had reported are that), this provides an additional bit of safety which is really useful for video encoding.

**Comment by rboy1** [comment]
To save myself the effort of building the entire ecosystem from scratch, would have a link to a built executable (win32) that I can use to test stuff out?

Is there any difference from a capability point of view between the win32 and win64 versions of AMF?

**Comment by rboy1** [comment]
I think this sample/tool is SO useful, it should be a part of the AMF framework itself

**Comment by MikhailAMD** [comment]
AMF sample "CapabilityManager" is a good starting point. If AMFCapabilityManger interface reports that a feature is supported but it does not actually work please report it as a bug. 
Please note that for correct checking you should supply DX9 or DX11 device allocated on desired DXGI adapter to AMF before asking for capabilities. See DeviceDX11.cpp and DeviceDX9.cpp in samples.
Please note that all encoder properties have min/max or enum values and can be queried on actual instance of the encoder. See AMFPropertyStorageEx Interface.

**Comment by rboy1** [comment]
I understand that, I'm requesting that a tool be available for the non expert that they can download to run to check if the system "supports" encoding/decoding and which codecs. One shouldn't be forced to learn coding and how to compile just to know my systems' capabilities.
Just a suggestion, it helps a lot of projects and custom scripts which use prebuilt 3rd party tools (e.g. ffmpeg/handbrake) but need to identify how to invoke these tools based on system capabilities.

**Comment by rboy1** [comment]
> Did you run the sample? It is a command line utility.

Where can I download it from? I don't see any links, just code that I would need to setup an environment and built from scratch.

**Comment by MikhailAMD** [comment]
You would have to build it. Everything is provided as a source code since this is SDK for developers.

**Comment by rboy1** [comment]
Would be nice to have a prebuilt version of the "tool" kept the repo so as to encourage folks to use it, something like what @Xaymar has created

**Comment by rboy1** [comment]
@MikhailAMD  when I try to build CapabilityManager, it seems to be missing some header files (using VS2017).

> Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'vulkan/vulkan.h': No such file or directory	CapabilityManager	c:\amf-master\amf\public\include\core\vulkanamf.h	43	
Error	C1083	Cannot open include file: 'atlbase.h': No such file or directory	CapabilityManager	c:\amf-master\amf\public\samples\cppsamples\common\devicedx11.h	36	
Error	C1083	Cannot open include file: 'atlbase.h': No such file or directory	CapabilityManager	c:\amf-master\amf\public\samples\cppsamples\common\devicedx9.h	34	
Error	C1083	Cannot open include file: 'vulkan/vulkan.h': No such file or directory	CapabilityManager	c:\amf-master\amf\public\include\core\vulkanamf.h	43	
Error	C1083	Cannot open include file: 'atlbase.h': No such file or directory	CapabilityManager	c:\amf-master\amf\public\samples\cppsamples\common\devicedx9.h	34

**Comment by MikhailAMD** [comment]
Did you install Vulkan SDK? Did you install Windows 10 SDK (Version 10586)?
They are the requirements: https://github.com/GPUOpen-LibrariesAndSDKs/AMF

**Comment by roman380** [comment]
atlbase.h is coming from VS2017 (not Windows 10 SDK), one needs to review the components installed with VS2017 and check boxes related to ATL/MFC support.

**Comment by roman380** [comment]
FWIW, as this topic mentions a pre-built capability detection application, I have a limited amount of capabilities (H.264 encoding related) in this application MediaFoundationDxgiCapabilities ([Win32](http://www.alax.info/svn/public/trunk/Toolbox/MediaFoundationDxgiCapabilities-Win32.exe), [x64](http://www.alax.info/svn/public/trunk/Toolbox/MediaFoundationDxgiCapabilities-x64.exe))

```
##### AMD AMF SDK Specific

 * AMF SDK Version: 1.4.9.0 // https://gpuopen.com/gaming-product/advanced-media-framework/
 * AMF Runtime Version: 1.4.12.0

###### AMFVideoEncoderVCE_AVC

 * Acceleration Type: AMF_ACCEL_HARDWARE
 * AMF_VIDEO_ENCODER_CAP_MAX_BITRATE: 100,000,000
 * AMF_VIDEO_ENCODER_CAP_NUM_OF_STREAMS: 16
 * AMF_VIDEO_ENCODER_CAP_MAX_PROFILE: AMF_VIDEO_ENCODER_PROFILE_HIGH
 * AMF_VIDEO_ENCODER_CAP_MAX_LEVEL: 52
 * AMF_VIDEO_ENCODER_CAP_BFRAMES: 0
 * AMF_VIDEO_ENCODER_CAP_MIN_REFERENCE_FRAMES: 1
 * AMF_VIDEO_ENCODER_CAP_MAX_REFERENCE_FRAMES: 16
 * AMF_VIDEO_ENCODER_CAP_MAX_TEMPORAL_LAYERS: 1
 * AMF_VIDEO_ENCODER_CAP_FIXED_SLICE_MODE: 0
 * AMF_VIDEO_ENCODER_CAP_NUM_OF_HW_INSTANCES: 1

####### Input

 * Width Range: 64 - 4,096
 * Height Range: 64 - 2,160
 * Vertical Alignment: 32
 * Format Count: 6
 * Format: AMF_SURFACE_NV12 Native
 * Format: AMF_SURFACE_YUV420P 
 * Format: AMF_SURFACE_YV12 
 * Format: AMF_SURFACE_BGRA 
 * Format: AMF_SURFACE_RGBA 
 * Format: AMF_SURFACE_ARGB 
 * Memory Type Count: 4
 * Memory Type: AMF_MEMORY_DX11 Native
 * Memory Type: AMF_MEMORY_OPENCL 
 * Memory Type: AMF_MEMORY_OPENGL 
 * Memory Type: AMF_MEMORY_HOST 
 * Interlace Support: 0

####### Output

 * Width Range: 64 - 4,096
 * Height Range: 64 - 2,160
 * Vertical Alignment: 32
 * Format Count: 1
  * Format: AMF_SURFACE_NV12 Native
 * Memory Type Count: 4
  * Memory Type: AMF_MEMORY_DX11 Native
  * Memory Type: AMF_MEMORY_OPENCL 
  * Memory Type: AMF_MEMORY_OPENGL 
  * Memory Type: AMF_MEMORY_HOST 
 * Interlace Support: 0
```

An easy way to verify at least that AMF runtime is in good standing, its version and that it reports valid caps for given DX11 device.

**Comment by rboy1** [comment]
Thank you all, I was finally able to build CapabilityManager

To avoid the hassle for other folks who JUST need a quick look at the capabilities of their AMD cards using a simple CLI tool without having to become a coder/compiling expert in VS, attached is a zip file that contains the release builds of x86 and x64 version of CapabilityManager for everyone to use.

I really wish they were included in the SDK but anyways here they are.

[CapabilityManager.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/3263485/CapabilityManager.zip)

**Comment by hackertron** [comment]
what should be the expected output from the CLI that you have provided !!

thanks

**Comment by MikhailAMD** [comment]
This is a sample app. It traces all AMF capabilities it discovered to SDDOUT.
