### ISSUE TITLE
When to stop using AMD GPU for decode

### ISSUE THREAD

**Issue by richT1977** [GPUOpen-LibrariesAndSDKs/AMF#122]
Hello,

I've created a decode library that uses AMF for AMD acceleration, when do I know when the resources are max'd so that I can stop suing AMD and degrade gracefully to CPU cycles?

My test Kaveri processor reports AMF_NOT_FOUND when I call:

sts = m_pAMDDecoder->GetProperty(AMF_VIDEO_DECODER_CAP_NUM_OF_STREAMS, &supported);

Does any one know of a method that will work?
Could the error be related to the fact that the driver is running on Windows 7?

Cheers for any pointers.

Rich.

**Comment by MikhailAMD** [comment]
This property is exposed by AMFCaps, not by decoder component. Use: m_pAMDDecoder->GetCaps(&caps);
caps->GetProperty(AMF_VIDEO_DECODER_CAP_NUM_OF_STREAMS, &supported);
Pls note that the returned value is for selected GPU for whole PC, not AMF limit. For example, if WMP opens a video to play it will consume one of decode sessions and your app will have less. One way to handle  this is to continue create decode sessions till Init() returns failure and then switch to SW.

**Comment by richT1977** [comment]
Thank you for your reply, this makes sense. I'll test and report my findings.

**Comment by MikhailAMD** [comment]
Closed as stale issue
