### ISSUE TITLE
Using AMF with an exisiting GL context (GLFW)

### ISSUE THREAD

**Issue by Findus79** [GPUOpen-LibrariesAndSDKs/AMF#124]
Hi,

I am trying to integrate AMF to decode videos, and use them as a texture for my application. I have basic integration running, but everytime I call AMFContext::InitOpenGL with my current context (retrieved from glfw) I get the following runtime errors:
```

[AMFDeviceOpenGLImpl]   Error: ..\..\..\..\..\runtime\src\core\DeviceOpenGLImpl.cpp(740):Assertion failed:AMFOpenGLContextImpl::Lock() wglMakeCurrent failed 170
[DeviceComputeImplOpenGL]   Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImplOpenGL.cpp(150):OpenCL failed, error = -60:AMFDeviceComputeImpl::InteropSurface() - clCreateFromGLTexture() failed
[AMFSurfaceImpl]   Error: ..\..\..\..\..\runtime\src\core\SurfaceImpl.cpp(225):Assertion failed:Convert() - InteropSurface failed
```

Are there any specific settings I have to set for my glfw Initialization?

Also, are there any samples on how to directly render onto a GL texture? I derived my implementation from the PlaybackHW sample, although I am currently not using my own GL context, but rather copying the decoded video data to a persistent-mapped PixelBuffer through using AMF_MEMORY_HOST, which is rather slow and certainly not the way to go.

Any help is appreciated,

best regards
findus

**Comment by MikhailAMD** [comment]
yes, you want to use multiple GPU APIs. It requires some preparations: 
- Decoder works via DX9 or DX11
- Color converter works via OpenCL
- Output surface/texture in OpenGL
The key here is an interop built-in into OpenCL. To make it working you have to initialize AMF and these APIs in a certain order.
1. Initialize OpenGL. If you do it manually see DeviceOpenGL.cpp in AMF samples.
2, Initialize DX11 (DX9 if you are on Win7). See DeviceDX11.cpp or DeviceDX9.cpp
3. Initialize OpenCL providing information about DX and OGL devices. See DeviceOpenCL.cpp
4. Pass device information to AMF:
- InitOpenGL()
- InitDX11()
- InitOpenCL().
You can use shortcuts and pass some of devices as NULL to AMF but it should be done in this order.
Note, that if user has more then one GPU, device selection and initialization of all APIs on the same adapter is responsibility of application. Sample code Device<>.cpp shows adapter enumeration for these APIs.
After that when you initialize AMF color converter component you should tell him to use OpenCL as engine and OpenGL as output. Set properties before Init() call:
AMF_VIDEO_CONVERTER_MEMORY_TYPE = AMF_MEMORY_OPENGL
AMF_VIDEO_CONVERTER_COMPUTE_DEVICE = AMF_MEMORY_OPENCL
This should work.

**Comment by Findus79** [comment]
Hi,

sticking to your advice, my application now works as intendend :+1: 

thanks a lot for the heads up
