### ISSUE TITLE
AMF Decode: control framerate

### ISSUE THREAD

**Issue by Findus79** [GPUOpen-LibrariesAndSDKs/AMF#126]
Hi,

my application always decodes and displays videos as fast as possible. How do I limit the decoder to the framerate of the video?

I tried
`BitStreamParser::SetFrameRate`
as well as 
`AMFDecoder Property AMF_VIDEO_DECODER_FRAME_RATE`.

If I play my test video using the PlaybackHW Sample, the video shows the correct speed. I just could not find anything framerate related in the sources of the PlaybackHW sample.

regards
Findus

**Comment by MikhailAMD** [comment]
The decoder doesn't do any timing. If your app needs to keep frame pace check PlaybackHW sample and video and audio presenter code. It is done based on timestamps from container, though they can be generated if missing. Note possible need for AV  synchronization

**Comment by Findus79** [comment]
Thanks, after looking at the PlaybackHW sample again, I found it :) Works now, thank you
