### ISSUE TITLE
Sample encode/decode single Image BMP 

### ISSUE THREAD

**Issue by Armin234** [GPUOpen-LibrariesAndSDKs/AMF#129]
Hi,
does anyone have a sample to encode a single Image in RGB Bitmap format with the AMF ?

**Comment by MikhailAMD** [comment]
do you want to encode RGB to H264 or H265 or convert from NV12 to RGB?

**Comment by Armin234** [comment]
I want to encode RGB to H265, save it one disc, decode it back to RGB, and then run some OpenCL Kernel on the lossy Image

**Comment by MikhailAMD** [comment]
OK, the sequence should be very similar to SimpleEncoder AMF sample. Few differences:
- You would need to allocate RGB AMF surface as AMF_MEMORY_HOST
- Call surface->GetPlaneAt(0)->GetNative()
- Fill pixels taking care of horizontal alignment (see AMFPlane interface)
- Configure encoder to accept RGBs: call encoder->Init(AMF_SURFACE_RGBA, width, height).
- Dump encoder output to a file - it  will be an elementary stream in Annex B format
- For decoding use SimpleDecoder sample  - call decoder Init(AMF_SURFACE_RGBA, width, height) if you want RGB output
- If you want to use OpenCL right after decoder, you would have to initialize OpenCL with DX11 interop and pass DX11 device and OpenCL context to AMF. Then you can call "surface->Convert(AMF_MEMORY_OPENCL)" and get native OCL handle as surface->GetPlaneAt(0)->GetNative().
- For correct DX11 and OpenCL initialization see DeviceDX11.cpp and DeviceOpenCL.cpp in AMF samples.

**Comment by Armin234** [comment]
I encode single Images with this Pseudo Code:

Encoder->SetProperty(AMF_VIDEO_ENCODER_PROFILE, AMF_VIDEO_ENCODER_PROFILE_HIGH);
Encoder->SetProperty(AMF_VIDEO_ENCODER_PROFILE_LEVEL, 51);
Encoder]->SetProperty(AMF_VIDEO_ENCODER_B_PIC_PATTERN, 0);


- Encoder-Init
- for x=0 to 100
  Read BMP   Nr.  x
  Surface->SetProperty(AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE, AMF_VIDEO_ENCODER_PICTURE_TYPE_I);
  encoder-submitinput(Surface)
  endfor

- for x=0 to 100 
  Encoder-Queryoutput()
  Write H264  Nr. x
  endfor
- Encoder-Terminate

  When use the analog sequence for decoding all images it works, but it didn't work when
I try to deocde only one Image, for example

- Decoder-Init
-  Read H264  Nr.  50
- Decoder-submitinput
 - Write BMP  Nr. 50
- Decoder-Terminate
What must I do to get this working without reinit or terminate the Encoder in the loop

**Comment by Armin234** [comment]
I encode single Images with this Pseudo Code:
Encoder->SetProperty(AMF_VIDEO_ENCODER_PROFILE, AMF_VIDEO_ENCODER_PROFILE_HIGH);
Encoder->SetProperty(AMF_VIDEO_ENCODER_PROFILE_LEVEL, 51);
Encoder]->SetProperty(AMF_VIDEO_ENCODER_B_PIC_PATTERN, 0);

Encoder-Init
for x=0 to 100
  Read BMP Nr. x
  Surface->SetProperty(AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE,     AMF_VIDEO_ENCODER_PICTURE_TYPE_I);
  encoder-submitinput(Surface)
endfor

for x=0 to 100
  Encoder-Queryoutput()
  Write H264 Nr. x
endfor
Encoder-Terminate

When use the analog sequence for decoding all images it works, but it didn't work when
I try to deocde only one Image, for example

Decoder-Init
Read H264 Nr. 50
Decoder-submitinput
Decoder-Queryoutput()
Write BMP Nr. 50
Decoder-Terminate

What must I do to get this working without reinit or terminate the Encoder in the loops ?

**Comment by Armin234** [comment]
That means, I must use the followig sequence doe encoding

Encoder-Init
for x=0 to 100
Read BMP Nr. x
Surface->SetProperty(AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE, AMF_VIDEO_ENCODER_PICTURE_TYPE_I);
encoder-submitinput(Surface)
Encoder-Queryoutput()
Write H264 Nr. x
Encoder-flush
endfor

I think that will slow down everything, because i can't fill the input Queue while the Encoding Prozess ?

**Comment by MikhailAMD** [comment]
I suggested to do flush once after the loop.

**Comment by Armin234** [comment]
Is there a mistake ? I need to encode 100 BMP images, one file for every image, and i must be able to decode every file without the other 99 files.

**Comment by MikhailAMD** [comment]
Ok, you should force IDR frame instead of I frame, you don't need Flush, you should get extradata buffer from encoder after Init and pass it to decoder before Init once.
After that you can decode every compressed frame as soon as you get it out of encoder.

**Comment by Armin234** [comment]
Changing to IDR Frame isn't a problem, but the program for decoding didn't have an encoder

**Comment by MikhailAMD** [comment]
I am lost. What is the problem are you trying to solve?

**Comment by Armin234** [comment]
One Program should encode many single Images as fast as possible, and save the encoded images on disc (one file for one image), The other program should be able to load one file and decode it. 
All Images have the same size.

**Comment by Armin234** [comment]
Now I am lost, Mikhail suggest to call flush on the encoder and AlexKordic suggest to call flush on the decoder !

The Decoder ist running as suggested by Mikhail with AMF_VIDEO_DECODER_MODE_LOW_LATENCY ...

**Comment by Armin234** [comment]
When i encode my 100 Images like this:


Thread 1:
Encoder-Init
for x=0 to 100
Read BMP Nr. x
Surface->SetProperty(AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE, AMF_VIDEO_ENCODER_PICTURE_TYPE_IDR);
encoder-submitinput(Surface)
endfor

Thread 2:
for x=0 to 100
Encoder-Queryoutput()
Write H264 Nr. x
endfor
Encoder-Terminate

I get 100 single h264 files, but with the PlaybackHW I can't open this files. It look's like there are missing some data in the files. (the ExtraData?)

**Comment by MikhailAMD** [comment]
You need extradata buffer passed from encoder to decoder:
AMFVariant var;
encoder->GetProperty(AMF_VIDEO_ENCODER_EXTRADATA, &var);
AMFBufferPtr  buffer(var.pInterface);

 or force SPS/PPS to be included in on each frame: 
surface->SetProperty(AMF_VIDEO_ENCODER_INSERT_SPS, true); 
surface->SetProperty(AMF_VIDEO_ENCODER_INSERT_PPS, true); 
enocoder->SubmitInout(surface);

**Comment by Armin234** [comment]
With forcing SPS/PPS to be included in on each Frame it works fine.

thanks
