### ISSUE TITLE
Get AMF_EOF when try to encode again after queried data

### ISSUE THREAD

**Issue by maxest** [GPUOpen-LibrariesAndSDKs/AMF#131]
I encode data with SubmitInput, then I QueryOutput on the encoder, then I try to SubmitInput another data but I get AMF_EOF. There is no problem if before second SubmitInput I recreate the encoder but that is not something I want to do each time I want to SubmitInput.

**Comment by MikhailAMD** [comment]
Did you try SimpleEncoder sample? It does the same as you do. Compare with your code.

**Comment by maxest** [comment]
I actually modify those samples (SimpleEncoder/Decoder). And it's actually the Drain function that when called causes this problem. But when I don't call Drain the app crashes.

**Comment by MikhailAMD** [comment]
QueryOutput is designed for polling, it may return no data and caller should be prepared for it.
Drain tells a component to return all delayed outputs if available and then return EOF signalling that drain is complete. After that app can continue use a component and submit new inputs.

**Comment by maxest** [comment]
Thanks for that explanation. That doesn't help my problem though. My list of calls, more or less, looks like this:

SubmitInput
Drain
QueryOutput <- this happens in a while loop which I break once I read AMD_EOF
SubmitInput <- here function returns AMD_EOF; why?

**Comment by MikhailAMD** [comment]
Once drain process is complete if you want to continue use the component you should call Flush to reset EOF state. If it doesn't work you would have to call ReInit. This is encoder - specific but I don't have driver code right now to confirm.

**Comment by MikhailAMD** [comment]
Closed as stale issue
