### ISSUE TITLE
InitOpenCL slows down

### ISSUE THREAD

**Issue by Armin234** [GPUOpen-LibrariesAndSDKs/AMF#133]
Hi, 

when I insert the InitOpenCL in my program, the entire execution takes near twice as long ?

	for (int uu = 0; uu < ANZGPU; uu++)
	{
		res = g_AMFFactory.GetFactory()->CreateContext(&context[uu]);

		DeviceDX11  deviceDX11;
		DeviceOpenCL  deviceOpenCL;

		bool deviceDX11Init = false;
		bool deviceOpenCLInit = false;
		if (deviceDX11.Init(uu) == AMF_OK)
		{
			deviceDX11Init = (context[uu]->InitDX11(deviceDX11.GetDevice()) == AMF_OK);
			if (deviceOpenCL.Init(NULL, deviceDX11.GetDevice(), NULL, NULL) == AMF_OK)
			{
				deviceOpenCLInit = (context[uu]->InitOpenCL(deviceOpenCL.GetCommandQueue()) == AMF_OK);
			}

		
		}

**Comment by MikhailAMD** [comment]
You submit RGB surfaces to encoder. But HW encoder works with NV12 surfaces only. So internally the encoder creates AMF color converter component for color conversion. If you initialized AMF with only DX11 the converter will use DirectCompute. When you added OpenCL initialization you told color space converter to use OpenCL. Now, you submit frames in system memory. Encoder need it input in DX11. So color converter transfer inputs from CPU to OpenCL, allocates output surfaces in DX11, interops them into OpenCL for conversion, run conversion shader(kernel) and un-interop output back to DX11. Interop is not a cheap operation. AMF has optimizations for reuse of surfaces but you will see the results after several frames are processed. 
Note, that if you would use color converter outside of the encoder you would be able to choose the GPU API the converter uses.  The performance will be exactly the same.

**Comment by Armin234** [comment]
Thanks for the detailed Information. 

The only thing i need to do, is working on decoded Image of Type AMF_MEMORY_DX11, RGBA with me OpenCL algorithmn. Is there a simple possibility to have read access on surface->GetPlaneat(0)->GetNative() from OpenCL ?

**Comment by MikhailAMD** [comment]
Sure: 
surface->Convert(AMF_MEMORY_OPENCL); 
cl_mem image2D= (cl_mem)surface->GetPlaneAt(0)->GetNative();

**Comment by Armin234** [comment]
okay, but surface->Convert(AMF_MEMORY_OPENCL) doesn't work without InitOpenCL

**Comment by MikhailAMD** [comment]
Of course.

**Comment by Armin234** [comment]
This means I either have to accept the slowdown of InitOpenCl, or convert the Surface to AMF_MEMORY_HOST and then load it back into the GPU for OpenCL, which also slows down everything unacceptably.

I can not understand why I can not easily access the Surface (AMF_MEMORY_DX11 RGBA) with OpenCL (without the negative effects of InitOpenCL), which is on the same GPU? 
Is that a limitation of the AMF?

**Comment by Armin234** [comment]
My full GPU pipeline is:

HOST(IMAGERGBA) -> AMF encoder(DX11) -> AMF Decoder(DX11) -> OpenCL

**Comment by MikhailAMD** [comment]
But you want decoder output as RGBA? so you have second color converter running inside decoder and it will be your bridge to OpenCL. Ideally you should create color converter components and set them up to exactly GPU APIs you want. But you can probably use one cheat:
1. Create devices DX11 and OCL for all GPUs
2. call AMFContext::InitDX11(device) for all GPUs
3. Fully Initialize encoders including AMFComponent::Init()
4. Call AMFContext::InitOpenCL() for all GPUs and contexts
5. Initialize decoders includingAMFComponent::Init()

So your pipeline would look like:
surface(HOST RGB)->**surface(DX11 RGB)->color converter shader (DX11)->surface(DX11 NV12)->AMF encoder(DX11)**->buffer(HOST)->**decoder(DX11)->surface(DX11 NV12)->surface(interop from DX11 to OCL NV12)->color converter shader (OCL)->surface(OCL interop from DX11 RGB)->surface(DX11 interop back from OCL RGB)**->surface(OCL interop from DX11 RGB)->your custom shader (OCL)->surface(OCL)
Evrything in bold will be part of AMF.

**Comment by MikhailAMD** [comment]
Surface (DX11 RGB) internally is ID3D11Texture2D. It cannot be converted to ID3D11Buffer. Though you can get pointer to D3D11 texture via GetNative() and do whatever.

**Comment by MikhailAMD** [comment]
But you can convert surface (OCL RGB) to buffer(OCL) via AMFCompute::ConvertPlaneToBuffer(). 
Possible problems:
- you have to use horizontal alignment from the original surface when you access such buffer  in your shader
- if MSFT allocates texture as "tiled" your pixels in buffer will be shuffled.
