### ISSUE TITLE
Can Re:live record HDR video with a vega56 card 

### ISSUE THREAD

**Issue by wingback18** [GPUOpen-LibrariesAndSDKs/AMF#136]
hi 
i have a  vega 56 card with a samsung HG70 monitor. it works great , but when i record HDR content. the videos have washed out colors and when the screen is on SDR while HDR is enable the colors are over saturated and distorted .

i even have this video 
https://www.youtube.com/watch?v=jtfV0T5Cu5w 

 is there something i need to . 
logs in need to provided ?
the cpu is a r5 1600x 
16 gb of ddr4 ram 
x370 mobo 
latest amd driver (this is been happening for a while )
monitor connected using a DP 1.4

**Comment by MikhailAMD** [comment]
Question is not releated to AMF SDK
