### ISSUE TITLE
CopySurfaceRegion 

### ISSUE THREAD

**Issue by Armin234** [GPUOpen-LibrariesAndSDKs/AMF#137]
Hi,

I'm sharing a surface with OpenCL, so that mD11SurfaceOut and mCLSurfaceOut are the same memory on the GPU.

When I copy the SurfaceRegion from the Queryouput to my shared memory, I must insert a the amf_sleep. Without this Sleep it seems, that the Kernel is running before the CopySurfaceRegion finished.

How i can block until  CopySurfaceRegion is finished ?

amf::AMFDataPtr lDataLossy;

decoder->QueryOutput(&lDataLossy)				
((amf::AMFSurfacePtr)lDataLossy)->CopySurfaceRegion(mD11SurfaceOut, 0, 0, 0, 0, IMAGE_W, IMAGE_H);

amf_sleep(100);
				
(*m_pclEnqueueAcquireD3D11ObjectsKHR)(gGPUCmdQueue, 1, &mCLSurfaceOut,0,NULL, NULL);
…… 
clEnqueueNDRangeKernel	
…….			
(*m_pclEnqueueReleaseD3D11ObjectsKHR[lGPU])(gGPUCmdQueue, 1, &mCLSurfaceOut, 0, NULL, NULL)

**Comment by MikhailAMD** [comment]
CopySurfaceRegion is just a wrapper around clEnqueueCopyImage(). It is designed for batch processing. To submit job to the queue you should call AMFCompute::FlushQueue(). If you want to wait on CPU for completion you should call AMFCompute::FinishQueue();

**Comment by Armin234** [comment]
Where I can get the AMFCompute, I only have a context ?

res = g_AMFFactory.GetFactory()->CreateContext(&context);
DeviceDX11  deviceDX11;
bool deviceDX11Init = false;
if (deviceDX11.Init(0) == AMF_OK)
{
	deviceDX11Init = (context->InitDX11(deviceDX11.GetDevice()) == AMF_OK);
}

**Comment by MikhailAMD** [comment]
For OpenCL surface: context->GetCompute(AMF_MEMORY_OPENCL, &compute);
For D3D11 surface: context->GetCompute(AMF_MEMORY_DX11, &compute);

**Comment by Armin234** [comment]
thanks, that was the solution
