### ISSUE TITLE
VCE multi-instance mode - is it documented anywhere?

### ISSUE THREAD

**Issue by roman380** [GPUOpen-LibrariesAndSDKs/AMF#138]
[Header excerpt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/0c609511c74198d942ef197e39e1e1cc53f5628e/amf/public/include/components/VideoEncoderVCE.h#L209) suggests it is for cloud gaming:

```
// Properties for multi-instance cloud gaming
#define AMF_VIDEO_ENCODER_MAX_INSTANCES                         L"EncoderMaxInstances"      //  amf_uint32; default = 1; max number of encoder instances
#define AMF_VIDEO_ENCODER_MULTI_INSTANCE_MODE                   L"MultiInstanceMode"        //  bool; default = false;
#define AMF_VIDEO_ENCODER_CURRENT_QUEUE                         L"MultiInstanceCurrentQueue"//  amf_uin32; default = 0; 
```

I don't see anything else but declarations. I am curious if there is any material explaining the capability.

**Comment by MikhailAMD** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/tree/master/amf/doc
AMF_Video_Encode_API.pdf

**Comment by roman380** [comment]
Practical information from this document and bottom of page 13 is that (a) multi-instance mode can be enabled (b) there are some two work queues in this mode. I wondered if there was some better description than a dozen of words.

**Comment by roman380** [comment]
Apart form multi-instancing an assessment of the SDK revealed more gray areas: use of encoder call back, details on how usage property blocks change of other properties like rate control, small documentation typos.

**Comment by MikhailAMD** [comment]
Please reopen if you have a particular issue. HW encoder supports multiple instances in general, but only once process can create low latency session.
