### ISSUE TITLE
Sometimes the level setting is rewritten unintentionally.

### ISSUE THREAD

**Issue by Masa-tam** [GPUOpen-LibrariesAndSDKs/AMF#139]
Affected Drivers: 18.10.1
Hardware: R7 360

I set up L1 with H.264 encoder, but depending on the resolution or fps it will be output as not L1 stream.

|Width|Height|FPS|Output Level|
| ---- | ---- | ---- | ---- |
|192|64|15|1|
|192|112|15|1.1|
|192|64|30000/1001|1|
|192|64|30|3.2|

The above set bit rates are all 50 kbps CBR.

**Comment by MikhailAMD** [comment]
This works as designed. AMF encoder corrects level if some parameters are set outside of the spec: https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC. In addition max number of reference frames is checked.
The last line in the table looks dubious, should be 1

**Comment by Masa-tam** [comment]
I saw the spec and issued this question.
First calculate the number of macroblocks per frame.

192/16 = 12
112/16 = 7
12 × 7 = 84 Macroblocks / frame

Next, calculate the number of macroblocks per second.

84 x 15 = 1260 Macroblocks / second

Since both are less than the limit of Level 1(99MB/f, 1485MB/s).

**Comment by Masa-tam** [comment]
There was a description missing, max number of reference frames is same value in 4.

**Comment by MikhailAMD** [comment]
This should be fixed in the drvier.

**Comment by MikhailAMD** [comment]
Should be fixed.
