### ISSUE TITLE
AMF API: 32-bit and 64-bit return different versions in Driver 16.8.2

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#14]
32-Bit:

```
10:32:11.675: [AMF Encoder] <Plugin::AMD::AMF::AMF> Loaded 'amfrt32.dll'.
10:32:11.676: [AMF Encoder] <Plugin::AMD::AMF::AMF> Runtime is on Version 1.0.3.0
```

64-Bit

```
10:33:03.606: [AMF Encoder] <Plugin::AMD::AMF::AMF> Loaded 'amfrt64.dll'.
10:33:03.607: [AMF Encoder] <Plugin::AMD::AMF::AMF> Runtime is on Version 1.3.0.4
```

SDK Version is 1.3.0.5 so there is something weird here.

**Comment by Xaymar** [comment]
Turns out the 32-Bit Runtime is actually on that version and it's incredibly broken. Might be worth it to push a hotfix driver out for that?

**Comment by MikhailAMD** [comment]
I built the plug-in and reproduced the problem. The returned version is the correct one. Check the full value in hex. You may want cast uint64_t to uint_t **for all parameters** before passing it to print or similar function with variable number of arguments.

**Comment by Xaymar** [comment]
You are right, printf indeed converted it from the wrong format. With proper casting it works. Closing this now.
