### ISSUE TITLE
Unable to Build VC++ 2017

### ISSUE THREAD

**Issue by DineshGuptaa** [GPUOpen-LibrariesAndSDKs/AMF#142]
Hello,

I am quite new in Cpp programming. I want to build FFmpeg library on windows 10 with Visual Studio 2017(Windows SDK Version 10.0.17763.0).
I have taken FFmpeg project from https://github.com/ShiftMediaProject/FFmpeg/ and its have dependency of AMF lib.
So that I have taken source 1.4.7 and tried to compile but its failed

	9>d:\cygwin64\home\dineshgupta\shiftmediaproject\amf\amf\public\common\amfstl.cpp(608): error C3861: 'vscprintf': identifier not found
	9>    0 Warning(s)
	9>    1 Error(s)
	9>
	9>Time Elapsed 00:01:17.88
	13>    The command exited with code 2.
	13>  Done executing task "CL" -- FAILED.
	13>Done building target "ClCompile" in project "Stitch_VS2017.vcxproj" -- FAILED.
	13>
	13>Done building project "Stitch_VS2017.vcxproj" -- FAILED.
	13>
	13>
	13>Build FAILED.
	13>
	13>d:\cygwin64\home\dineshgupta\shiftmediaproject\amf\amf\public\common\amfstl.cpp(608): error C3861: 'vscprintf': identifier not found
	13>    0 Warning(s)
	13>    1 Error(s)
	13>
	13>Time Elapsed 00:00:59.58
	========== Build: 1 succeeded, 12 failed, 0 up-to-date, 0 skipped ==========

Please help me to resolve this issue.

Thanks in advance :-)

**Comment by MikhailAMD** [comment]
Get the latest AMD: v 1.4.9. It was fixed.

**Comment by DineshGuptaa** [comment]
Yes, it's working but For this I have to install another sdk which is quite big. :-(

Thanks

**Comment by MikhailAMD** [comment]
You can get just header and cpp from the new SDK or just compare and find the fix. Though, it is better to be on the latest and greatest version.
