### ISSUE TITLE
[REQUEST] aq_strenght & ratetol

### ISSUE THREAD

**Issue by Benman2785** [GPUOpen-LibrariesAndSDKs/AMF#148]
hi,

to improve quality i would ask for:

aq_strength - could sharpen the image more - this would help alot (maybe needs chooseable aq_mode 0-2)

&

ratetol - can maintain better quality over time because it limits the max and minimun size difference of any single frame to a percentage of average bitrate - in combination with custom buffer it would maintain a "less spiky & overall good quality stream"

those two would help to maintain a better stream quality

**Comment by MikhailAMD** [comment]
aq_strength - codec team would like to know more about your target usage for better design considerations
ratetol - We have MAX_AU_SIZE to control single frame size, playing together with VBV_BUFFER_SIZE & INITIAL_VBV_BUFFER_FULLNESS parameters, it could serve the purpose of output “less spiky & overall good quality stream”

**Comment by Benman2785** [comment]
for aq_strength
as far as i know amf supports aq_mode 1 and 2; with aq_strength of 0.2-1,5 i could force a much more "clean-looking" image quality

like:
x264 AQ=0
http://i32.tinypic.com/2s85r3m.png
x264 AQ=0.5
http://i27.tinypic.com/30ue25j.png
x264 AQ=1.0
http://i26.tinypic.com/23sw4sy.png
x264 AQ=1.5
http://i32.tinypic.com/2w4mx6s.png

(links from: http://forum.doom9.org/archive/index.php/t-163852.html)
