### ISSUE TITLE
Does the current version support encoding and decoding of the 10bit format

### ISSUE THREAD

**Issue by woodyexcellent** [GPUOpen-LibrariesAndSDKs/AMF#150]
hi
  I have one question about the encode and decode projects.How to use the format AMF_SURFACE_P010.When I set formatOut = amf::AMF_SURFACE_P010,the decoder->Init will return AMF_INVALID_FORMAT。
thanks

**Comment by MikhailAMD** [comment]
It is driven by HW capabilities. Currently 10-bit decoding is supported for HEVC codec on Vega and Polaris GPUs.

**Comment by woodyexcellent** [comment]
> 
> 
> It is driven by HW capabilities. Currently 10-bit decoding is supported for HEVC codec on Vega and Polaris GPUs.

thanks，I get it.

**Comment by woodyexcellent** [comment]
sorry,just now I realized that my GPU is WX8200 which belongs to Vega series GPUs. But when I decode a h265 file(10bit HDR) and set formatOut = amf::AMF_SURFACE_P010,the return of decoder->Init is AMF_INVALID_FORMAT.that's why?

**Comment by MikhailAMD** [comment]
Without looking into your initialization code and the particular video clip you use I can only guess but I would first ensure that the clip is 10-bit, and that you set "EXTRADATA" parameter before Init() call. You may also share AMF log (configured to write a file or copy debug output) to have more info.

**Comment by woodyexcellent** [comment]
I am sure that my clip is 10-bit, and there is already set "EXTRADATA" parameter before Init()  in this code. I've changed almost nothing except let formatOut = amf::AMF_SURFACE_P010. I will provide my clip below.and I wonder how to let it work and get the YUV file at last. thank you very much.@MikhailAMD 
[testfile.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/2875079/testfile.zip)

**Comment by woodyexcellent** [comment]
by the way, I am using SimpleDecoder.

**Comment by MikhailAMD** [comment]
I tried your clip. You have to use AMFVideoDecoderHW_H265_MAIN10 as a codec ID for CreateComponent(). After that SimpleDecoder worked for me.

**Comment by woodyexcellent** [comment]
After I used AMFVideoDecoderHW_H265_MAIN10 as a codec ID for CreateComponent()，the Init() returned AMF_CODEC_NOT_SUPPORTED.The same things happened in PlaybackHW too.I don't know Why is that. Is there anything else I should do?  Or is there any other SDK I should install before I use SimpleDecoder or PlaybackHW?
My work environment is Radeon-Pro-Software-18.Q4.1(I had opened the 10bit Setting), windows7 and vs2017.  My GPU is WX8200.And my display screen is not support 10bit. Does it matter?

**Comment by MikhailAMD** [comment]
Ok, the decoder uses dx9 on win7 and dx9 or dx11 on win10. Dx9 doesn't have p010 format and 10 bit decoding via dx9 is not supported.

**Comment by woodyexcellent** [comment]
That sounds terrible，howerer thanks for your reply.

**Comment by superbin** [comment]
Why GetAccelerationType returns **AMF_ACCEL_NOT_SUPPORTED** for AMFVideoDecoderHW_H265_MAIN10 decoder? But PlaybackHW can playback some HEVC 10-bit files?
My card is RX 580.

**Comment by superbin** [comment]
> Why GetAccelerationType returns **AMF_ACCEL_NOT_SUPPORTED** for AMFVideoDecoderHW_H265_MAIN10 decoder? But PlaybackHW can playback some HEVC 10-bit files?
> My card is RX 580.

I have found the cause. I just used vulkan context.
