### ISSUE TITLE
Crashed when calling decoder->Init()

### ISSUE THREAD

**Issue by superbin** [GPUOpen-LibrariesAndSDKs/AMF#153]
Test using the SimpleDecoder project, and using hevc 10bit elementary stream file. Memory type is amf::AMF_MEMORY_DX11; Surface format is amf::AMF_SURFACE_P010.
 [The test source file](https://1drv.ms/u/s!AuOUOJzgRhF8ihC9g6473k6ko22D)
[Crash screen snip](https://1drv.ms/u/s!AuOUOJzgRhF8ihGNaUttT6epjILz)
[SimpleDecoder.dmp](https://1drv.ms/u/s!AuOUOJzgRhF8ihJwaHQ08VVUJRQT)

**Comment by superbin** [comment]
Graphics Card: Radeon RX 580 Series
Driver Version: 25.20.15003.5010/Win10 64

**Comment by MikhailAMD** [comment]
OK, thanks. I found an issue in VUI HDR header parser. The fix should appear in the one of hot fix drivers and in sample HEVC parser on GitHub. Please note that Vega Analyzer complains about errors in your clip in frames 1,2,3,8 and shows corruption on decoding. It is not related to VUI header.

**Comment by MikhailAMD** [comment]
The fix is in the released drvier
