### ISSUE TITLE
Is there a functionality to capture screen directly and encode at GPU buffer memory??

### ISSUE THREAD

**Issue by js21c** [GPUOpen-LibrariesAndSDKs/AMF#156]
I'm trying to develop game screen capture and transfer mode. 
To achieve low latency, I want to capture frames and encode directly at GPU buffer memory level without copying screen buffer to system memory.
I know that DEC mode is vanished. 
Are there any similar modes at SDK?

**Comment by MikhailAMD** [comment]
Yes, it is possible. There is MSFT's Desktop Duplication API to capture screen. It works reasonably well and one can wrap the captured D3D11 texture into AMF surface, make a GPU copy and continue with AMF color converter and encoder. We plan to publish am AMF sample with simple implementation.

**Comment by tobi-tobsen** [comment]
That sample would be much appreciated, looking forward to it!

**Comment by roman380** [comment]
amf\public\src\components\DisplayCapture already has code which is basically wrapping DD API into AMF component. If my memory serves me right DVR sample shows how to use it (source code definitely [has traces](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/2d3061a423c6ccb3cb0410fdaac01aa8d885ccd2/amf/public/samples/CPPSamples/common/DisplayDvrPipeline.h#L62) that it was/is working).

**Comment by MikhailAMD** [comment]
Yes, thanks.

**Comment by MikhailAMD** [comment]
Closed as answered

**Comment by npip99** [comment]
@MikhailAMD Is there a similar API for Linux?

**Comment by tobi-tobsen** [comment]
I just scrolled through the header and CPP file @MikhailAMD linked and saw that it is not using windows Dxgi screenduplikation but AMFCreateComponentDisplayCapture. 

If something like  that was working on Linux too, this would give AMD an edge over competitors imo (currently this is not possible under Linux afaik and you would have to use systemmemory to grab the screen and the reupload to the GPU for encoding).

**Comment by MikhailAMD** [comment]
I hear you :)

**Comment by gitautas** [comment]
Has anything changed since? Is there a way to do this on Linux?
