### ISSUE TITLE
Decoder - QueryOutput always AMF_OK and Data != NULL ???

### ISSUE THREAD

**Issue by Armin234** [GPUOpen-LibrariesAndSDKs/AMF#157]
Hi,

when I call 

res= gAMFdecoder->pVtbl->QueryOutput(gAMFdecoder, &lDataLossy);

the result is Always AMF_OK and lDataLossy != NULL			
even i didn't submit data to the Decoder.

Is there a example using the decoder in C ?

Regards 
Armin

**Comment by MikhailAMD** [comment]
AMF_OK without input is normal. There is no "C" sample for the decoder but all components behave the same so SimpleEncoderC sample should be sufficient to demonstrate how to call AMF objects from "C". SimpleDecoder should show the decoder details.

**Comment by Armin234** [comment]
There was a mistake, lDataLossy  is only not equal Null after one SubmitInput to the decoder.
I looked at the samples suggested and I'm assuming the problem is the missing release of the data,
but when I release the Data, the program is crashing

res = gAMFdecoder->pVtbl->QueryOutput(gAMFdecoder, &lDataLossy);
if( res==AMF_OK &&  lDataLossy != NULL)
{
   lDataLossy->pVtbl->Release(lDataLossy);
}

Any other suggest ?

**Comment by MikhailAMD** [comment]
That should work. One thing: if there is no output it is recommended to add some small sleep in the polling loop or your app will burn a lot of CPU on constant polling. Note amf_sleep() and amf_increase_timer_precision(). The increase of precision is important for the accurate sleep. The functions are provided with source code so you can port them to "C"

**Comment by Armin234** [comment]
Thanks, for the information.

When I set lDataLossy=NULL bevor calling QueryOutput it seems working :-)
