### ISSUE TITLE
Description of defaults implied by ULTRA_LOW_LATENCY

### ISSUE THREAD

**Issue by vlovich** [GPUOpen-LibrariesAndSDKs/AMF#158]
I'm wondering if there's any documentation about all the setting values implied by H264 AMF_VIDEO_ENCODER_USAGE? The reference document doesn't seem to describe this option in any kind of meaningful detail.

For example, it looks like it overrides whatever value of FULL_RANGE_COLOR may be set before (at least a value of ULTRA_LOW_LATENCY does). Additionally, it looks like if this mode is set to ULTRA_LOW_LATENCY then setting CBR as the rate control method is rejected with AMF_ACCESS_DENIED.

Those are just 2 examples I've found of how it affects encoder setup in non-obvious ways so hoping to get some clarification on the settings impacted by this setting & especially which options are disallowed from being set afterward. Additionally, are there any settings internal to the driver that are controlled by AMF_VIDEO_ENCODER_USAGE that aren't otherwise configurable through the publicly available set of encoder params.

**Comment by MikhailAMD** [comment]
One should treat USAGE parameter as an easy preset. It sets most of parameters to a certain value and disables some. In doc folder there is AMF_Video_Encode_API.pdf where in table A-3 usage values are documented. Normally an app sets USAGE first and then tweaks some parameters. For full flexibility one should use TRANSCODING usage which gives full access to paramters and allows manually set any combination including replicate any usage preset.

**Comment by vlovich** [comment]
Got it. Thanks for the pointer.
