### ISSUE TITLE
h264 - Assertion failed:Failed to execute SendConfig()

### ISSUE THREAD

**Issue by Vouk** [GPUOpen-LibrariesAndSDKs/AMF#159]
I have problems with using h264 in ffmpeg master. hevc works fine. "libav-users" couldn't help me any further.

```
AVCodec *codec = avcodec_find_encoder_by_name("h264_amf");  
if (codec) {  
  AVCodecContext *codecContext = avcodec_alloc_context3(codec);  
  if (codecContext) {  
    codecContext->width = 1920;  
    codecContext->height = 1080;  
    codecContext->time_base = { 25 , 1 };  
    codecContext->pix_fmt = codec->pix_fmts[0];  

    if (avcodec_open2(codecContext, codec, NULL) == 0) {
      printf("yes");
    } else {
      printf("no");
    }
    avcodec_free_context(&codecContext);  
  }
} 
```

AMFEncoderVCE: 2019-05-20 23:23:03.069 40D8 [AMFEncoderVCE] Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(2081):Assertion failed:Failed to execute SendConfig(). AVE error = 0x80000000  
AMFEncoderVCE: 2019-05-20 23:23:03.069 40D8 [AMFEncoderVCE] Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(870):AMF_ERROR 1 : AMF_FAIL: Init() - Failed to set the new encode config  
VCEEncoderTrace: 2019-05-20 23:23:03.078 40D8 [VCEEncoderTrace] Info: &&&DestroyEncoder(-1):active encoder instance=0, codecID=0x5 ok!  
AMFEncoderVCE: 2019-05-20 23:23:03.078 40D8 [AMFEncoderVCE] Info: Submitted 0, Queried 0  

What am I doing wrong here? As I said hevc_amf is working fine.

**Comment by MikhailAMD** [comment]
Not sure but one thing I see:: you fill time_base as a frame rate. It should be the opposite: codecContext->time_base = { 1 , 25 }; or you can set frame rate directly: codecContext->framerate = { 25 , 1 };  
Just recently I discussed very similar code here: https://trac.ffmpeg.org/ticket/7922 . You can ignore rate controls parameters. It always worth to check the driver.

**Comment by Vouk** [comment]
I can't believe it was as simple as that. I spent weeks on this. Thanks!!
