### ISSUE TITLE
Detect support for VBR_LAT apart from hitting AMF_NOT_SUPPORTED

### ISSUE THREAD

**Issue by roman380** [GPUOpen-LibrariesAndSDKs/AMF#160]
I am seeing a report from user system with AMF_NOT_SUPPORTED as a result of attempt to use AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD and AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_LATENCY_CONSTRAINED_VBR. Unfortunately the documentation has no mention of limitations related to this mode. What is the suggested way to identify availability of VBR_LAT, do I really need to handle the configuration failure by providing alternate fallback code path, or it is possible to identify capabilities of the GPU/SDK beforehand?

**Comment by MikhailAMD** [comment]
Which GPU do you use and what is the version of the graphics driver?

**Comment by roman380** [comment]
It's some (no data) Ryzen CPU with integrated AMD Radeon(TM) Vega 8 Graphics. No data on driver version, but I know that AMF runtime is 1.4.12.0.

**Comment by MikhailAMD** [comment]
check Radeon Settings ->System->Software->Driver Packaging Version

**Comment by roman380** [comment]
It's a report from end user who has issues with software and our log files report AMF_NOT_SUPPORTED in AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD call. There is no information from Radeon Settings.

**Comment by MikhailAMD** [comment]
OK, I probably know what it is: we recently fixed a bug specific to Ryzen with integrated GPU and group of rate controls properties. I don't have the hot fix driver release time yet but it is coming.

**Comment by MikhailAMD** [comment]
Please check the latest public driver.
