### ISSUE TITLE
Corrupted H264 encode

### ISSUE THREAD

**Issue by Armin234** [GPUOpen-LibrariesAndSDKs/AMF#161]
Hi,

for testing my Plugin for another software I encode and decode 40 Images in a neverending loop.
For 32767 encode/decode steps it works well, but at the 32768 encode step the 
gAMFencoder->pVtbl->QueryOutput(..) give me a AMFData that submitting to the decoder cause a crash of the entire program.

I attached the Trace-file which shows at the line 330269:
2019-06-02 20:14:05.303     5380 [H264Parser]   Error: ..\..\..\..\..\runtime\src\components\VideoStreamParser\parsers\h264\H264Parser.cpp(2066):read_next_nalu() Invalid startcode emulation prevention found. 602

I attachted the output of the encoder, which crashs not only my program but also the PlaybackHW-Example. With all other 32767 outputs of the encoder there are no problems.

What can i do prevent the crash ?

Armin

[h264 32767.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/3245068/h264.32767.zip)
[amf.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/3245070/amf.zip)

**Comment by Armin234** [comment]
Hi, does anyone have a solution / suggestion ?

**Comment by MikhailAMD** [comment]
The clip has a single corrupted frame so the decoder fails to parse. Is it possible to get the app which reproduces the issue? I could write a similar one but there is no guarantee that I will reproduce the problem. Could be a private drop. Email: mikhail<dot>mironov<att>amd<dot>com

**Comment by MikhailAMD** [comment]
Any update?

**Comment by Armin234** [comment]
No, I'm still waiting for the new driver that will fix the problem

**Comment by MikhailAMD** [comment]
The problem (uniqueness ofthe case) was in submittion of IDR-frames only. The fix should be in the public driver by now. Could you please try the latest driver?
