### ISSUE TITLE
Do we need to define manually picture type? 

### ISSUE THREAD

**Issue by grancia** [GPUOpen-LibrariesAndSDKs/AMF#162]
What's the proper way to set up picture type?
Given following function call, I expected to get IDR picture every 30 frames but it wasn't.
// tried both, but any of them not worked
surface_->SetProperty(AMF_VIDEO_ENCODER_IDR_PERIOD, 30);
component_->SetProperty(AMF_VIDEO_ENCODER_IDR_PERIOD, 30);

So now I'm manually injecting picture type like below assuming gop is 30. Is this only way to set up picture type? No way to use just gop thing?
if(sumbitCount_ % 30 == 0) {
   surface_->SetProperty(AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE, AMF_VIDEO_ENCODER_PICTURE_TYPE_IDR);
    sumbitCount_ = 0;
  } else {
    surface_->SetProperty(AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE, AMF_VIDEO_ENCODER_PICTURE_TYPE_P);
  }

**Comment by MikhailAMD** [comment]
if you want IDR every 30th frame you should set the property on the encoder component during initialization as you did: component_->SetProperty(AMF_VIDEO_ENCODER_IDR_PERIOD, 30);
If it doesn't work please provide full initialization code. Note that USAGE property overwrites many other properties. 
If  you want manually control IDR insertion you should set picture type on the input surface before the submission every time exactly as you did.
Please ensure that you use the latest driver.

**Comment by grancia** [comment]
Followings are what I'm doing for setting components. 
```
    // Create encoder component
    hr = g_AMFFactory.GetFactory()->CreateComponent(amfContext_, codec_.c_str(), &amfComponent_);
    
    hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_USAGE, AMF_VIDEO_ENCODER_USAGE_TRANSCONDING);
    
   hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_IDR_PERIOD, 30);
   
   hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_B_PIC_PATTERN, 0);

    hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_QUALITY_PRESET, AMF_VIDEO_ENCODER_QUALITY_PRESET_SPEED);

    hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_TARGET_BITRATE, (amf_int64)bitrate);

    hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_FRAMESIZE, ::AMFConstructSize(width_, height_));

    hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_FRAMERATE, ::AMFConstructRate((amf_int32)fps, 1));

    hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_PROFILE, AMF_VIDEO_ENCODER_PROFILE_HIGH);

    // This numbering is recommended by AMF manual in case we want to consider upto 4k
    hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_PROFILE_LEVEL, 51);   

    hr = amfComponent_->SetProperty(AMF_VIDEO_ENCODER_B_PIC_PATTERN, 0);
```

**Comment by MikhailAMD** [comment]
Looks OK to me. 
- What is in codec_?
- What is the GPU?
- What is the OS?
- What is the driver version?
- Which GPU API do you use: DX9, DX11, Vulkan?
- Where is Init() call?
- How do you test for IDR frame presence?

**Comment by grancia** [comment]
What is in codec_?
What is the GPU?
 - RX Vega
What is the OS?
 - Windows 10 64bit
What is the driver version?
 - 19.6.1
Which GPU API do you use: DX9, DX11, Vulkan?
 - DX11
Where is Init() call?
 - amfComponent_->Init is called right after property settings
How do you test for IDR frame presence?
 - In polling thread.
  amfComponent_->QueryOutput(&data);
  data->GetProperty(AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE, &pictureType);

**Comment by MikhailAMD** [comment]
The output frame type property is wrong. Should be : data->GetProperty(AMF_VIDEO_ENCODER_OUTPUT_DATA_TYPE, &pictureType); It returns: AMF_VIDEO_ENCODER_OUTPUT_DATA_TYPE_ENUM

**Comment by grancia** [comment]
I have checked with AMF_VIDEO_ENCODER_OUTPUT_DATA_TYPE. 
Interesting is I can only get IDR frames. Given following settings, I would expect to get IDR every 30 frames?
amfComponent_->SetProperty(AMF_VIDEO_ENCODER_IDR_PERIOD, 30);

**Comment by MikhailAMD** [comment]
Yes, you should get IDR every 30th frame and the rest would be P-frames.

**Comment by grancia** [comment]
Do you have any idea why it always return only IDR frames?

**Comment by MikhailAMD** [comment]
I hope you don't force the IDR every frame. Show the modified polling code. Or you can modify SimpleEncoder sample, repro the issue and share whole CPP.

**Comment by grancia** [comment]
No I don't force the IDR every frame for sure. This is polling code. 

while (true) {
    amf::AMFDataPtr data;
	res = amfComponent_->QueryOutput(&data);
	if (res == AMF_EOF) {
	  break; // Drain complete
 	}

    if (data != nullptr) {
	  amf_pts pollTime = amf_high_precision_clock();
	  amf_pts startTime = 0;
	  uint64_t pictureType;
      data->GetProperty(AMF_VIDEO_ENCODER_OUTPUT_DATA_TYPE, &pictureType);
      ...
    } else {
	  amf_sleep(1);
	}
  }

**Comment by MikhailAMD** [comment]
Looking good to me. How do you check the returned value?

**Comment by grancia** [comment]
`bool isKeyFrame = pictureType == AMF_VIDEO_ENCODER_PICTURE_TYPE_IDR || pictureType == AMF_VIDEO_ENCODER_PICTURE_TYPE_I;`

**Comment by MikhailAMD** [comment]
1. KeyFrames are IDR only, at least for seek, not every player seeks to I-frame
2. The code is wrong: you are using wrong enum. Should be:
 bool isKeyFrame = pictureType ==  AMF_VIDEO_ENCODER_OUTPUT_DATA_TYPE_IDR || pictureType ==  AMF_VIDEO_ENCODER_OUTPUT_DATA_TYPE_I;

**Comment by grancia** [comment]
you got it! thanks a lot!!

**Comment by MikhailAMD** [comment]
Closed as resolved.
