### ISSUE TITLE
RDNA (Navi) media engine support

### ISSUE THREAD

**Issue by EwoutH** [GPUOpen-LibrariesAndSDKs/AMF#163]
Add and document RDNA (Navi) media engine support.

- VP9 decode
- H.264 encode & decode
- H.265 encode & decode

![061571_amd-tech-day-2019-mike-mantor_07](https://user-images.githubusercontent.com/15776622/59273604-e0522000-8c58-11e9-9ef6-c474e7d70938.jpg)

**Comment by EwoutH** [comment]
Linux kernel support for VCN2 (Video Coding Next 2) on Navi10 is added [here](https://lists.freedesktop.org/archives/amd-gfx/2019-June/035170.html).

**Comment by MikhailAMD** [comment]
What's the question?
