### ISSUE TITLE
AMD Radeon R7 decoder hevc report AMF_CODEC_NOT_SUPPORTED

### ISSUE THREAD

**Issue by breezeewu** [GPUOpen-LibrariesAndSDKs/AMF#164]
I use simpledecoder to decoder hevc , when decoder init, it return AMF_CODEC_NOT_SUPPORT, can you tell me if readeon R7 support hevc decoder, or there are some problem in code?

**Comment by MikhailAMD** [comment]
Radeon R7 doesn't support HEVC.

**Comment by breezeewu** [comment]
But I had use HIKVISION VSplayer play mp4 file with hevc codec, it seems to be use hardwave accelerate with a low  CPU usage(about 2%-4%) in Radeon R7. Other player play the same mp4 about 12% CPU usage. can you tell me is there any other  hardwave accelerate  solution for amd Radeon R7?

**Comment by MikhailAMD** [comment]
You can check if HW decoder is active in Task Manager->Performance Tab->GPU->Video Decode.
R7 supports H.264 encoding and decoding, for decoding some older codecs like DIVX, MPEG2, VC1.
