### ISSUE TITLE
Does AMF 1.4.9 on linux only support vulkan?

### ISSUE THREAD

**Issue by tianhanghai** [GPUOpen-LibrariesAndSDKs/AMF#165]
I'm using AMF 1.4.9 for video encoder. 
Its readme.md says "Version 1.4.9 or later requires Vulkan SDK for some samples: https://vulkan.lunarg.com/ and AMD Radeon Software Adrenalin Edition 18.8.1 (18.30.01.01) or newer. This version supports Linux (see amd.com for driver support)". 
The card I used for testing is Radeon Pro WX5100.
I run SimpleEncoder ,it works fine. In that sample, it uses amf::AMF_MEMORY_VULKAN as the memory type.   
```
...
static const wchar_t *pCodec = AMFVideoEncoderVCE_AVC;
...
static amf::AMF_MEMORY_TYPE memoryTypeIn  = amf::AMF_MEMORY_VULKAN;
...
AMF_RESULT res = AMF_OK; // error checking can be added later
res = g_AMFFactory.Init();
...
res = g_AMFFactory.GetFactory()->CreateContext(&context);
...
res = amf::AMFContext1Ptr(context)->InitVulkan(NULL);
...
res = g_AMFFactory.GetFactory()->CreateComponent(context, pCodec, &encoder);
...
```
I try to use `amf::AMF_MEMORY_HOST`,`g_AMFFactory.GetFactory()->CreateComponent(context, pCodec, &encoder);` returns `AMF_NOT_INITIALIZED`,while the code works fine in windows.
```
...
static const wchar_t *pCodec = AMFVideoEncoderVCE_AVC;
...
static amf::AMF_MEMORY_TYPE memoryTypeIn  = amf::AMF_MEMORY_HOST;
...
AMF_RESULT res = AMF_OK; // error checking can be added later
res = g_AMFFactory.Init();
...
res = g_AMFFactory.GetFactory()->CreateContext(&context);
...
res = g_AMFFactory.GetFactory()->CreateComponent(context, pCodec, &encoder);
...
```
I also try to use `amf::AMF_MEMORY_OPENCL`,`amf::AMFContext1Ptr(context)->InitOpenCL(NULL)` returns `AMF_OK`. When I call `g_AMFFactory.GetFactory()->CreateComponent(context, pCodec, &encoder)`,it returns `AMF_NOT_INITIALIZED`.
```
...
static const wchar_t *pCodec = AMFVideoEncoderVCE_AVC;
...
static amf::AMF_MEMORY_TYPE memoryTypeIn  = amf::AMF_MEMORY_OPENCL;
...
AMF_RESULT res = AMF_OK; // error checking can be added later
res = g_AMFFactory.Init();
...
res = g_AMFFactory.GetFactory()->CreateContext(&context);
...
//res = amf::AMFContext1Ptr(context)->InitOpenCL(NULL);
...
res = g_AMFFactory.GetFactory()->CreateComponent(context, pCodec, &encoder);
...
```
Finally, I try to use  `amf::AMF_MEMORY_OPENGL`,it crashed when I call `amf::AMFContext1Ptr(context)->InitOpenGL(NULL,NULL,NULL)`.  
As mentioned above,I'm wondering that does AMF 1.4.9 on linux only support vulkan or the way I used for other memory type is wrong. If the way I'm using is wrong ,could you offer me with the right way.   
Thanks.

**Comment by MikhailAMD** [comment]
AMF on Linux supports HOST, OCL, OGL memory types but the encoder runs via Vulkan only. So to use the encoder an application must call InitVulkan() before creating an encoder component. The encoder will accept other memory types: HOST at any time. For OpenCL input surfaces an application would need to call InitOpenCL() in addition to InitVulkan(). Similar to OpenGL. Please note that there is no interop between OCL and Vulkan so the submission of OCL surfaces to the encoder will  be sub-optimal.

**Comment by tianhanghai** [comment]
That helps a lot.
Thanks.

**Comment by tianhanghai** [comment]
I tested its performance both on Windows and Linux. 
On Windows, encoding H264 of 1080p NV12  using DX11 as the  memory type,it can encode almost 120 frames per second and encoding 4K video can reach 30 frames per second and the gpu usage is 100%.
While on Linux, using HOST or just like SimpleEncoder, it can only encode 60 fps of 1080p NV12 and 20 fps of 4K and gpu usage is just 4-8% monitored by radeontop.
So is there any way I can use to improve the performance on linux?

**Comment by MikhailAMD** [comment]
The problem is in memory transfer from HOST to GPU. In DX11 there is no transfer and in your Linux experiment there is. Ideally the application should submit Vulkan images. But on Linux many applications still use OpenGL. There is spec for interop from OpenGL to Vulkan which would help avoid transfers to and from HOST. We are exploring possibility to incorporate the interop in AMF.

**Comment by tianhanghai** [comment]
OK, I got it.
Thanks for your help.
