### ISSUE TITLE
Modified SimpleDecoder sample to decode h264 data from buffer and display timely, but the image is blurry

### ISSUE THREAD

**Issue by bessiep** [GPUOpen-LibrariesAndSDKs/AMF#166]
These are my codes

BOOL Init(BitStreamType StreamType, DecFrameCallBackFunc pDecFrameCB, void* pUserData)
{
	AMF_RESULT res = AMF_OK;
	wchar_t szDecID[MAX_PATH] = L"";
	
	res = m_AMFFactory.Init();
	if (res != AMF_OK)
	{
		LOG(L"### m_AMFFactory Init fail");
		return FALSE;
	}

	res = amf::AMFDataStream::OpenDataStream(L"memory://", amf::AMFSO_READ, amf::AMFFS_SHARE_READ, &m_AMFDataStream);
	if (res != AMF_OK)
	{
		LOG(L"### OpenDataStream fail");
		return FALSE;
	}

	res = m_AMFFactory.GetFactory()->CreateContext(&m_AMFContext);
	if (res != AMF_OK)
	{
		LOG(L"### CreateContext fail");
		return FALSE;
	}

	switch (g_MemoryType)
	{
	case amf::AMF_MEMORY_DX9:
		res = m_AMFContext->InitDX9(NULL);
		break;

	case amf::AMF_MEMORY_DX11:
		res = m_AMFContext->InitDX11(NULL);
		break;
	}
	if (res != AMF_OK)
	{
		LOG(L"### init dx fail");
		return FALSE;
	}

	m_BitStreamParser = BitStreamParser::Create(m_AMFDataStream, StreamType, m_AMFContext);
	switch (StreamType)
	{
	case BitStreamH264AnnexB:
		memcpy(szDecID, AMFVideoDecoderUVD_H264_AVC, sizeof(AMFVideoDecoderUVD_H264_AVC));
		break;

	case BitStream265AnnexB:
		memcpy(szDecID, AMFVideoDecoderHW_H265_HEVC, sizeof(AMFVideoDecoderHW_H265_HEVC));
		break;
	}

	res = m_AMFFactory.GetFactory()->CreateComponent(m_AMFContext, szDecID, &m_AMFDecoder);
	if (res != AMF_OK)
	{
		LOG(L"### CreateComponent fail");
		return FALSE;
	}

	m_pDataCB = pDecFrameCB;
	m_pUserData = pUserData;
	return TRUE;
}

int Decode(char* pSrc, int iSrcSize)
{
	amf::AMFDataPtr dstdata;
	amf::AMFDataPtr srcdata;
	AMF_RESULT res = AMF_OK;

	if (!m_bGetStreamInfo)
	{
		// 将待解码数据放入指定内存中
		m_AMFDataStream->Write(pSrc, iSrcSize, NULL);

		if (!m_BitStreamParser->GetStreamInfo())   // 必须等到SPS和PPS信息都获取到才能开始解码
		{
			LOG(L"### GetStreamInfo fail");
			return 0;
		}

		amf::AMFBufferPtr buffer;
		if (m_BitStreamParser->GetExtraDataSize())
		{
			m_AMFContext->AllocBuffer(amf::AMF_MEMORY_HOST, m_BitStreamParser->GetExtraDataSize(), &buffer);
			memcpy(buffer->GetNative(), m_BitStreamParser->GetExtraData(), m_BitStreamParser->GetExtraDataSize());
			m_AMFDecoder->SetProperty(AMF_VIDEO_DECODER_EXTRADATA, amf::AMFVariant(buffer));
		}

		res = m_AMFDecoder->Init(amf::AMF_SURFACE_NV12, m_BitStreamParser->GetPictureWidth(), m_BitStreamParser->GetPictureHeight());
		if (res != AMF_OK)
		{
			LOG(L"### m_AMFDecoder init fail");
			return 0;
		}

		m_bGetStreamInfo = true;
	}

	amf::AMFBufferPtr		m_pictureBuffer;
	res = m_AMFContext->AllocBuffer(amf::AMF_MEMORY_HOST, iSrcSize, &m_pictureBuffer);
	memcpy(m_pictureBuffer->GetNative(), pSrc, iSrcSize);
	m_pictureBuffer->SetDuration(300000);
	srcdata = m_pictureBuffer.Detach();

	res = m_AMFDecoder->SubmitInput(srcdata);
	if (res != AMF_OK)
	{
		LOG("### m_AMFDecoder SubmitInput fail [%d]", res);
		return 0;
	}
	
	res = m_AMFDecoder->QueryOutput(&dstdata);
	if (dstdata == NULL || res != AMF_OK)
	{
		LOG("### m_AMFDecoder QueryOutput fail");
		return 0;
	}

	res = dstdata->Convert(amf::AMF_MEMORY_HOST); // convert to system memory
	amf::AMFSurfacePtr surfaceNV12(dstdata); // query for surface interface		
	WritePlane(amf::AMF_PLANE_Y, surfaceNV12->GetPlane(amf::AMF_PLANE_Y)); // get y-plane pixels
	WritePlane(amf::AMF_PLANE_UV, surfaceNV12->GetPlane(amf::AMF_PLANE_UV)); // get uv-plane pixels
	m_DecFrameDataParams.pszData = m_pNV12Data;
	m_pDataCB(m_DecFrameDataParams, m_pUserData);

	return 1;
}

m_pDataCB is a callback function, used to display the image data.

These codes run well when decoding source h264 data from the video with slow picture change, but output image will blur when decoding data from the video with fast picture change.

Waiting for help

**Comment by MikhailAMD** [comment]
The decoder doesn't do any conversion or touch pixels. You may want to dump your elementary H264 stream to a file and play it with PlaybackHW sample. It uses the same decoder. You may want to capture screenshots to show the problem and share the H264 stream.

**Comment by bessiep** [comment]
> The decoder doesn't do any conversion or touch pixels. You may want to dump your elementary H264 stream to a file and play it with PlaybackHW sample. It uses the same decoder. You may want to capture screenshots to show the problem and share the H264 stream.

Thank you for your reply :)

The H264 streams are from an encoding equipments and transmitted via RTSP protocol, I have used VLC to open the network streaming and the display is normal, VLC uses DXVA to decode the H264 data.
Is there something wrong with my codes?

**Comment by MikhailAMD** [comment]
I don't see any obvious problem in the code you copied so it would make sense to check the actual data your code submits: width, height, extradata, input buffers. For example, for RTSP DESCRIBE request the response is in SDP format and should include  SPS/PPS NAL units in "sprop-parameter-sets" in form of "extradata" (FFmpeg term).
You have to be sur that you submit the correct extradata.
AMF can work without extradata but it will produce garbage till IDR frame with SPS/PPS nal units is submitted. If you plan to use this mode you should call AMFComponent::Init(NV12,0,0); Again this is not needed if SDP has all necessary information. 
You may want to check AMFDump interface implemented on all AMF components and acquired via QueryInterface(). With this interface you can configure dump file so I could check what you are submitting to the decoder . Or you can dump the input yourself.

**Comment by bessiep** [comment]
> I don't see any obvious problem in the code you copied so it would make sense to check the actual data your code submits: width, height, extradata, input buffers. For example, for RTSP DESCRIBE request the response is in SDP format and should include SPS/PPS NAL units in "sprop-parameter-sets" in form of "extradata" (FFmpeg term).
> You have to be sur that you submit the correct extradata.
> AMF can work without extradata but it will produce garbage till IDR frame with SPS/PPS nal units is submitted. If you plan to use this mode you should call AMFComponent::Init(NV12,0,0); Again this is not needed if SDP has all necessary information.
> You may want to check AMFDump interface implemented on all AMF components and acquired via QueryInterface(). With this interface you can configure dump file so I could check what you are submitting to the decoder . Or you can dump the input yourself.

Thank you very much!
I have solved the problem.
