### ISSUE TITLE
Get "AMF_CODEC_NOT_SUPPORTED" return, When call decoder_->Init()

### ISSUE THREAD

**Issue by mkl13031** [GPUOpen-LibrariesAndSDKs/AMF#169]
Hi all,

I get a error return "AMF_CODEC_NOT_SUPPORTED", When I call decoder_->Init();
and output message:
"Error: ..\..\..\..\..\runtime\src\components\DecoderUVD\DecodeEngines\DirectX\DirectX9\DecodeEngineDXVA2.cpp(429):COM failed, HR = 80004005:InitDecoder() - Could not create video decoder; profile: UVD H265 Unencrypted Config Profile"

My computer spec:
CPU: AMD Ryzen 7 2700X Eight-Core Processor
GPU: AMD Radeon VII

Test video:
Res: 5760
Bit rate:120mbps
codec: HEVC

Thanks!

**Comment by MikhailAMD** [comment]
Is 5760 the resolution width? If so HEVC codec is limited to 4Kx4K. Please check CapabilityManager sample.

**Comment by mkl13031** [comment]
Thanks! I think its the problem.
