### ISSUE TITLE
Video Encode API: Proper Presentation Timestamp?

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#17]
Right now ->GetPts returns the Decode Timestamp, which in turn means that I have no idea what the presentation timestamp is supposed to be. If I send in let's say 60 frames with keyframes every 60 frames and the current frame index set as a custom property will I get the proper presentation timestamp by retrieving that property?

Example:
```
Frame:   0 1 2 3 4 5 6 7 8 9 ...
Output:  I P B B B P B B B P ...
Decode:  I P B B B P B B B P ...
Decode:  0 1 2 3 4 5 6 7 8 9 ...
Present: I B B B P B B B P B ...
Present: 0 2 3 4 1 6 7 8 5 - ...
```

**Comment by MikhailAMD** [comment]
Yes, custom property will do this. Any unknown property is copied from input frame to the corresponding output buffer in submission order. the encoder reorders times set by SetPTS. The are two reasons for this: 
1. This is required behaviour for MFT encoders
2. H264 elementary stream has enough information for frame reordering in the decoder - so there is no real need in presentation timestamps.

**Comment by Xaymar** [comment]
Alright, thank you for the information!
