### ISSUE TITLE
Does NAVI gpu support 10bits encode?

### ISSUE THREAD

**Issue by molcolm** [GPUOpen-LibrariesAndSDKs/AMF#173]
I found some introduction of the Navi have a feature about hdr/wcg encode.
The HDR should been encode in 10bits, so is it means the Navi gpu support 10bits HEVC encode?

**Comment by MikhailAMD** [comment]
Yes it does. One can set 10 bit property and submit P010 surfaces or program color conversion

**Comment by molcolm** [comment]
@MikhailAMD 
The CapabilityManager result of the CapabilityManager sample is here. 
[caps_RX5700.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/3491463/caps_RX5700.txt)
There is no P010 in the support list. 
Is there something wrong?

**Comment by MikhailAMD** [comment]
This is an oversight in CAPs interface, we will fix it. P010 is supported for submission. Thanks for letting know.

**Comment by molcolm** [comment]
@MikhailAMD 
I found there are some descriptions of the parameters about the color like AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH written in AMF_Video_Encode_API.pdf and AMF_Video_Encode_HEVC_API.pdf in previous version. 
But no found at last commit. 
Is there some problem?

**Comment by molcolm** [comment]
@MikhailAMD 
I found you update the doc for AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH 
but there are some other parameters shown on 1.4.14 gone on this version. 
ex : AMF_VIDEO_ENCODER_HEVC_INPUT_COLOR_PROFILE, MF_VIDEO_ENCODER_HEVC_OUTPUT_COLOR_PROFILE, 
AMF_VIDEO_ENCODER_HEVC_INPUT_TRANSFER_CHARACTERISTIC,
AMF_VIDEO_ENCODER_HEVC_OUTPUT_TRANSFER_CHARACTERISTIC,
AMF_VIDEO_ENCODER_ HEVC_INPUT_HDR_METADATA,
AMF_VIDEO_ENCODER_ HEVC_OUTPUT_HDR_METADATA ... etc

And I had test the AMF_VIDEO_ENCODER_ HEVC_INPUT_HDR_METADATA, it seems workable.

**Comment by molcolm** [comment]
I found the CAPs interface had fixed the P010 support issue. 
And also i can encode to 10 bits on HEVC. 
So I think the issue can close.
