### ISSUE TITLE
ID3D11Device::CreateShaderResourceView Return DXGI_ERROR_DEVICE_REMOVED

### ISSUE THREAD

**Issue by sols000** [GPUOpen-LibrariesAndSDKs/AMF#175]
- Using AMD 5700,  Driver is the latest.

- In the first 3-5 min,  All Runs OK.

The D3D11 API return S_OK with Rx580.
Then Get The Reson with ID3D11Device::GetDeviceRemovedReason,
Return DXGI_ERROR_DEVICE_HUNG.

Anyone can help me?

**Comment by MikhailAMD** [comment]
Do you use AMF? What is the app is doing? The device removed could mean several things: driver crashed, out of memory, shader hangs, etc.
