### ISSUE TITLE
How to select a specified AMD Graphic Adapter to encode when running with multi AMD Graphic Adapter?

### ISSUE THREAD

**Issue by tianhanghai** [GPUOpen-LibrariesAndSDKs/AMF#177]
Can I select a specified AMD Graphic Adapter to encode when there are several AMD adapters on machine?   For example: there are two AMD adapters on the machine,can I select one adapter to encode two streams and let the other adapter free or each adapter encode one stream?

I looked for such interfaces in AMF and I did't find any interface related.

**Comment by MikhailAMD** [comment]
AMF components like encoder or decoder operate via D3D11, D3D9 or Vulkan. Usually an application creates the device objects with these APIs and passes them to AMF. Therefore the application selects adapters. So there is no need for AMF to provide a special interface. Check DeviceDX11.cpp, DeviceDX9.cpp and DeviceVulkan.cpp in samples for the adapter selection.

**Comment by tianhanghai** [comment]
That helps a lot. Thanks.
