### ISSUE TITLE
Plans & ETA for H.265 encoder support with Vulkan?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/AMF#179]
Hi,
just compiled ffmpeg from git to test new Linux AMF support via Vulkan:
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/f8ad2ddd7a51df5d6e768ba2a6f65ee64b94e29b
https://www.phoronix.com/scan.php?page=news_item&px=FFmpeg-AMD-AMF-Vulkan
but supports only H264..
was about to ask to ffmpeg devs about H265 but just found AMF 1.4.9 notes mention:
"Vulkan (encoder supports H.264 only)"
So question is if H.265 is supported now on AMF Vulkan on current 1.4.14 and if not if there is some plans to implement it.. and better some ETA?

thanks..

**Comment by MikhailAMD** [comment]
Currently HEVC is not supported via Vulkan. We are working on this but no ETA.

**Comment by oscarbg** [comment]
ok thanks.. will leaven open if you don't mind..

**Comment by barolo** [comment]
can we get an update, a year later? @MikhailAMD

**Comment by MikhailAMD** [comment]
still not ready. :(

**Comment by MikhailAMD** [comment]
Supported in 21.50 driver (22.3.1) for Navi10 and later now (RX 5xxx , RX 6xxx)

**Comment by MagicAndre1981** [comment]
@MikhailAMD what about Polaris (12 Pro) GPUs?

**Comment by MikhailAMD** [comment]
No concrete plans at this time. Sorry.

**Comment by rhutsAMD** [comment]
Closing as this is implemented 😊
