### ISSUE TITLE
Strange problems with encode

### ISSUE THREAD

**Issue by tianhanghai** [GPUOpen-LibrariesAndSDKs/AMF#180]
Finally I finished my work of AMD encoding on Windows. Thanks a lot for your help.
And during testing,I have met up with two strange problems.

Environment: 
 Graphic Adapter: Radeon™ RX 480
 Processor: Intel(R) Xeon(R) CPU E-5-2630 v3 @ 1.60GHz
 Driver:Adrenalin 2019 Edition 19.5.2

Problem 1:
I test H265 encoding with 1 stream in format of NV12 720x480.
The encode fps is around 190 while the gpu is 50%. 
On other computer( cpu : i5,i7), the record of that test is 410 fps and the gpu is 100%.  
When I open Radeon Overlay, just show the UI but without any operation,the boundary is broken and the fps will reach 410 fps from time to time. When I close Radeon Overlay,just hide the UI, all things go back. The fps would always be aound 190. I also tried to adjust Radeon Overlay, it did't work.

Problem 2:
I test H265 encoding with 6 streams in format of NV12 720x480.
The reasonable result should be 70 fps per stream (total fps 410 - 420) and 100% for gpu usage. 
I tested it for a lot of times. In most tests, the result was just like the reasonable result mentioned above. But in some tests, the result was 50 fps per stream (total fps 280 - 300) and 100% gpu usage. The gpu usage makes me confused. If I don't do any other operation,the fps and gpu usage will go on. When I start a another H265 encoding with 1 stream in format NV12 3840x2160 and then I stop the NV12 3840x2160 H265 encoding, things seem to be right. 
The fps of that 6 streams became 70 (total fps 410 - 420 )and the usage of gpu was still 100%.

The first problem only happens in the machine of the environment mention above (Intel(R) Xeon(R) CPU E-5-2630 v3 @ 1.60GHz). So I guess the cpu leads to this problem.

The second problem happens not only in in the machine of the environment mention above (Intel(R) Xeon(R) CPU E-5-2630 v3 @ 1.60GHz) but also happens in other machines with other cpu (i5,i7).

Those are the two problems I met up with, so is there any solutions to solve them or can you show me the causes of these two problems.

**Comment by MikhailAMD** [comment]
Few notes:
1. Please update the driver to the latest. You are running the old one from May (19.5.1).
2. If you have Windows fully updated you will see the "Video Encoder" graph in the Task Manager. Overall GPU load is meaningless in this context.
3. For your problem #1: your app is probably bound by CPU or CPU to GPU transfer, not by HW encoder, so you see different results with different CPUs. GPUVIEW log will show the encoder load and possible gaps between encoder jobs. The same for Radeon Overlay, the UI consumes some GPU but not the encoder and may interfere with your app. Again GPUVIEW will show all.
4. For problem #2: the same: record GPUVIEW and check interference between applications and correlation between CPU and GPU. 
5. One note: don't record more then 5-10 seconds of GPUVIEW logs.

**Comment by tianhanghai** [comment]
After getting your notes, I test it again.  
Note 1: I update the driver to Adrenalin 2019 Edition 19.9.1 Optional.
Note 2:I can see the "Video Encoder" graph in the Task Manager. And I monitor the Encode details.
![taskmanager](https://user-images.githubusercontent.com/16220207/64316958-e56d0400-cfe8-11e9-8baa-df9c0697e759.PNG)
Note 3 - 5: I download Win10 SDK and try to run GPUView.

And I have made a mistake , my test format is NV12 1280x720 not 720x480.  

For problem 1, I find that `AMF_RESULT  AMF_STD_CALL SubmitInput(AMFData* pData)` takes more time than expected. 
When the usage for encode is 50%,my record is just as following.
```
alloc:0 fill:1 submit:12 try:2
alloc:0 fill:0 submit:1 try:1
alloc:0 fill:0 submit:0 try:1
alloc:0 fill:0 submit:13 try:2
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:12 try:2
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:0 submit:13 try:2
alloc:0 fill:0 submit:0 try:1
alloc:0 fill:0 submit:0 try:1
alloc:0 fill:1 submit:13 try:2
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:12 try:2
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:0 submit:13 try:2
alloc:0 fill:0 submit:0 try:1
alloc:0 fill:1 submit:0 try:1
```
The time duration is measured in milliseconds. So the average time for submit is 4-5 ms. So the average fps is around 200fps.
And when I open the UI of Radeon Overlay,just move the cursor on it but without any click,the fps could keep around 410 and the time record of `AMF_RESULT  AMF_STD_CALL SubmitInput(AMFData* pData)` is different.
```
alloc:0 fill:0 submit:2 try:2
alloc:0 fill:1 submit:3 try:3
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:4 try:3
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:2 try:2
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:3 try:3
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:0 submit:1 try:1
alloc:0 fill:0 submit:2 try:2
alloc:0 fill:1 submit:2 try:2
alloc:0 fill:1 submit:3 try:3
alloc:0 fill:1 submit:2 try:2
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:2 try:2
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:2 try:2
alloc:0 fill:0 submit:1 try:1
alloc:0 fill:1 submit:0 try:1
alloc:0 fill:1 submit:4 try:3
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:1 try:2
alloc:0 fill:1 submit:2 try:2
```
The average time for submit is 2-3 ms,so it can reach around 410 fps.

I also use GPUVIEW to record logs, they show different ,but I can't get more information from these records. May you analysis it for me? And how can I send these files to you?

With using GPUVIEW, I found a stranger problem. It's just like problem 2,but GPUVIEW led to that problem.

With RX480, I start my test program with 1  encode stream in format 1280x720 NV12. And the encode fps is around 410 and then I run GPUVIEW log in cmd, the fps will reduce to around 280 fps.
The fps will not go back to 410 unless I start a encode stream in format 3840x2160 and then stop the 3840x2160 stream.
I reproduce this in two different computers. So I think you may reproduce that problem easily.
I alse try to reproduce this problem with WX5100, and its performance is quite different from RX480.
GPUVIEW log can't  make 410 fps to 280 fps, but it can let 280 fps to 410 fps.
I try a lot of times to get the encoder with 280 fps in format NV12 1280x720 , then I want to record its GPUVIEW log , so I run GPU log in cmd and then the encoder's encode fps increase to 410 fps.

**Comment by MikhailAMD** [comment]
few notes and questions:
1. Which memory type do you use to submit input frame?
2. How do you measure time? check amf_high_precision_clock()
3. try: - what does it mean? Do you get return code "INPUT_FULL"?
4. You may hit GPU power management if you submit in system memory and forces AMF to transfer frames to video memory. GPUVIEW will show this.
5. GPUVIEW does affect GPU behaviour but is is the best tool avaliable.
6. Use dropbox.com or similar service and send me a link via private email: mikhail[dot]mironov[att]amd[dot]com

**Comment by tianhanghai** [comment]
Question 1: I use `AMF_MEMORY_DX11` as the memory type.
Question 2: I just use `clock()` to get the time. I will test it with `amf_high_precision_clock()`  again.
QUestion 3:   
                 `alloc` means `AllocSurface(AMF_MEMORY_TYPE type, AMF_SURFACE_FORMAT format, amf_int32 width, amf_int32 height, AMFSurface** ppSurface)`   
                 `fill` means `UpdateSubresource`   
                 `submit` means `AMF_RESULT AMF_STD_CALL SubmitInput(AMFData* pData)`  
                 `try` means times of `SubmitInput`, when I get `AMF_INPUT_FULL ` ,I will `amf_sleep(1)` and just try again.   

The total code my program calls is just like following:  
```
    ...
    // 1. create encoder h265
    // 1.1 init factory
    AMF_RESULT t_res = AMF_OK;
	amf::AMFFactory* t_p_factory = NULL;
	t_p_factory = g_amf_factory.get_factory();
	if (t_p_factory == NULL) {
		t_stat = MW_VENC_STATUS_FAIL;	// create context failed
		m_b_create_encoder = false;
		return t_stat;
	}

	t_res = t_p_factory->CreateContext(&m_p_context);
	if (t_res != AMF_OK || m_p_context == NULL) {
		t_stat = MW_VENC_STATUS_FAIL;	// create context failed
		m_b_create_encoder = false;
		return t_stat;
	} 
    ...
    // 1.2 init dx11 device
    if (m_mem_type_in == amf::AMF_MEMORY_DX11||
		m_mem_type_in == amf::AMF_MEMORY_HOST) {
		void* t_p_dx11_device = NULL;
		if (t_u32_adapter_id >= 0) {
			// create dx11 device from given adapter id
			t_p_dx11_device = get_dx11_device(t_u32_adapter_id);
		}
		m_p_d3d11_device = t_p_dx11_device;
		t_res = m_p_context->InitDX11(t_p_dx11_device);
		if (t_res != AMF_OK&&t_res != AMF_ALREADY_INITIALIZED)
			m_mem_type_in = amf::AMF_MEMORY_HOST;
	}
    ...
    // 1.3 create h265 encode component  
    t_res = t_p_factory->CreateComponent(m_p_context, AMFVideoEncoder_HEVC, &m_p_encoder);
    if (t_res != AMF_OK || m_p_encoder == NULL) {
		t_stat = MW_VENC_STATUS_FAIL;	// create component failed
		m_b_create_encoder = false;
		return t_stat;
	}
    ....
    // 1.4 set all params
    t_res = m_p_encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_USAGE, AMF_VIDEO_ENCODER_HEVC_USAGE_TRANSCONDING);
    ...
    t_res = m_p_encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_QUALITY_PRESET, t_quality);
    ...
    t_res = m_p_encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_RATE_CONTROL_METHOD, t_rete_control);
    ...
    t_res = m_p_encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_FRAMESIZE, ::AMFConstructSize(p_param->width, p_param->height));
    ...
    t_res = m_p_encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_FRAMERATE, ::AMFConstructRate(p_param->fps.num, p_param->fps.den));
    ...
    t_res = m_p_encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_SLICES_PER_FRAME, p_param->slice_num);
    ...
    t_res = m_p_encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_GOP_SIZE, p_param->gop_pic_size);
    ...
    t_res = m_p_encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_PROFILE, t_profile);
    ...
    t_res = m_p_encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_PROFILE_LEVEL, t_profile_lvl);
    ...
    m_p_encoder->Init(t_surface_fmt, p_param->width, p_param->height);
    ...
    // 1.5 start querry output thread
    m_p_thread = new CPollingThread(m_p_context, m_p_encoder,MW_VENC_CODE_TYPE_H265);
	m_p_thread->set_callback_output(frame_callback, user_ptr);
	m_p_thread->Start();
    ...

    // 2. put frame
    // 2.1 alloc surface
    if (m_surface_in == NULL&&p_frame != NULL) {
		m_surface_in = NULL;
		amf::AMF_MEMORY_TYPE t_mem_type = m_mem_type_in == amf::AMF_MEMORY_VULKAN?amf::AMF_MEMORY_HOST:m_mem_type_in;
		//t_alloc_begin = clock();
		t_res = m_p_context->AllocSurface(
			t_mem_type,
			t_amf_fmt,
			t_u32_width,
			t_u32_height,
			&m_surface_in);
		//t_alloc_end = clock();
		if (t_res != AMF_OK||m_surface_in==NULL) {
			t_stat = MW_VENC_STATUS_FAIL;
			return t_stat;
		}
	}
    // 2.2 fill surface dx 11
    ...
    ID3D11Device *deviceDX11 = (ID3D11Device *)context->GetDX11Device();
    ...
    if (t_fmt == amf::AMF_SURFACE_NV12) {
			ID3D11Texture2D* surfaceDX11_1 = NULL;
			surfaceDX11_1 = (ID3D11Texture2D*)surface->GetPlaneAt(0)->GetNative(); // no reference counting - do not Release()
			deviceContextDX11->UpdateSubresource(surfaceDX11_1, 0, NULL, t_p_data, t_u32_stride, 0);
	}
    ...
    // 2.3 submit surface
    t_res = AMF_INPUT_FULL;
		uint8_t t_u8_sub_try = 0;
		//t_submit_begin = clock();
		while (t_res != AMF_OK) {
			t_res = m_p_encoder->SubmitInput(m_surface_in);
			t_u8_sub_try++;
			if (t_res == AMF_INPUT_FULL)
				amf_sleep(1);
			else {
				if (t_res != AMF_OK) {
					t_stat = MW_VENC_STATUS_FAIL;
					return t_stat;
				}

				m_surface_in = NULL;
			}

			if (t_u8_sub_try > 1000) {
				t_stat = MW_VENC_STATUS_FAIL;
				return t_stat;
			}		
		}
		//t_submit_end = clock();
		//printf("alloc:%ld fill:%ld submit:%ld try:%d\r", t_alloc_end - t_alloc_begin, t_fill_end - t_fill_begin, t_submit_end - t_submit_begin, t_u8_sub_try);
```  
Here is my code called in test program.  

After changing `clock()` to `amf_high_precision_clock()`, the log is as following.
50%
```
alloc:124 fill:6309 submit:948 try:1
alloc:140 fill:5745 submit:92168 try:2
alloc:123 fill:5926 submit:1070 try:1
alloc:107 fill:5987 submit:994 try:1
alloc:108 fill:5719 submit:126074 try:2
alloc:116 fill:5962 submit:1066 try:1
alloc:106 fill:5963 submit:996 try:1
alloc:100 fill:5571 submit:127009 try:2
alloc:123 fill:5656 submit:1060 try:1
alloc:105 fill:5852 submit:972 try:1
alloc:107 fill:5588 submit:129652 try:2
alloc:121 fill:5617 submit:1085 try:1
alloc:105 fill:5875 submit:971 try:1
alloc:101 fill:5549 submit:130654 try:2
alloc:129 fill:5899 submit:1234 try:1
alloc:104 fill:5882 submit:992 try:1
alloc:103 fill:5706 submit:129233 try:2
alloc:120 fill:5844 submit:1074 try:1
alloc:120 fill:6151 submit:962 try:1
alloc:112 fill:5794 submit:126467 try:2
alloc:122 fill:5631 submit:1085 try:1
alloc:105 fill:5933 submit:992 try:1
alloc:106 fill:5283 submit:126716 try:2
alloc:130 fill:5647 submit:1055 try:1
alloc:106 fill:5901 submit:973 try:1
alloc:103 fill:5563 submit:127377 try:2
alloc:123 fill:5627 submit:1072 try:1
alloc:116 fill:5872 submit:976 try:1
alloc:102 fill:5599 submit:130932 try:2
```
100%
```
alloc:123 fill:6370 submit:12355 try:2
alloc:117 fill:5678 submit:33614 try:3
alloc:137 fill:6035 submit:12315 try:2
alloc:127 fill:6948 submit:11811 try:2
alloc:118 fill:5800 submit:13071 try:2
alloc:130 fill:6024 submit:12689 try:2
alloc:152 fill:6403 submit:32000 try:3
alloc:108 fill:5910 submit:12907 try:2
alloc:109 fill:5998 submit:12705 try:2
alloc:131 fill:6750 submit:12179 try:2
alloc:136 fill:5925 submit:12360 try:2
alloc:124 fill:5906 submit:32874 try:3
alloc:121 fill:6367 submit:12313 try:2
alloc:126 fill:5679 submit:13118 try:2
alloc:120 fill:6313 submit:11866 try:2
alloc:118 fill:6144 submit:12756 try:2
alloc:130 fill:5693 submit:33188 try:3
alloc:125 fill:5883 submit:13091 try:2
alloc:125 fill:7044 submit:2768 try:1
alloc:128 fill:5948 submit:20263 try:2
alloc:115 fill:6044 submit:32842 try:3
alloc:142 fill:6232 submit:12688 try:2
alloc:133 fill:6034 submit:11706 try:2
alloc:135 fill:6442 submit:12367 try:2
alloc:123 fill:6297 submit:12503 try:2
alloc:135 fill:6135 submit:32817 try:3
```  

I have extracted the related code from my project and writen a test example 
with that code. You can get it from my Github page, the link is https://github.com/tianhanghai/test_amf_encode .
And more details I will upload to dropbox and send an email to you.  

Thanks a lot for your help.

**Comment by MikhailAMD** [comment]
Few things:
1. UpdateSubresource() function is asynchronous and will be executed when the texture is actually used. This happens inside SubmitInput(). Because of that, timing of UpdateSubresource() is situated inside SubmitInput() and this explains your time measurements. BTW: clock() should be precise enough.
2. I've checked your GPUVIEW logs. In both cases you encode at 190 fps. See the attached screenshots with explanations. there are three  encode jobs in the selected area of 15 ms in both logs. The difference is the job duration.  Radeon Overlay raises GPU clocks and jobs become shorter: 4.9 ms vs 2.4 ms. But this shouldn't worry you. it looks like you submit at certain frequency. It could be intentional or accidental. If the app would submit faster, the clocks will raise automatically and jobs will become shorter. The AMF encoder internally doesn't do any timing or pacing. It tries to encode as fast as it can.
3. If you care about latency you can set AMF_VIDEO_ENCODER_HEVC_LOWLATENCY_MODE = true property.
4. The difference in frame rate I can explain only by a error in measurements. Check GPUVIEW with 480 fps. The submitted jobs are stacked in two layers meaning that they are submitted at one time then wait till previous job is complete before it starts to execute.
