### ISSUE TITLE
There is no 8*8 transform blocks in the stream？

### ISSUE THREAD

**Issue by yangyan0202** [GPUOpen-LibrariesAndSDKs/AMF#181]
Hi,
   I used the Radeon 550 Series to encode a video and found that no matter how the parameters are set, the H.264 stream does not have 8x8 macro blocks, which results in a low PSNR. Also,  when I use HEVC codec, the PU does not have 8x8  , 16*16, or  32*32 blocks, TU does not have 4*4. I don't know why and how to solve it?

**Comment by MikhailAMD** [comment]
This is a limitation of HW encoder.

**Comment by yangyan0202** [comment]
So there's no solution?
