### ISSUE TITLE
Using AMF in Win7 with DX11, all format of AllocSurface returns AMF_NOT_SUPPORTED

### ISSUE THREAD

**Issue by tianhanghai** [GPUOpen-LibrariesAndSDKs/AMF#182]
I test my code in Win7.
`AllocSurface ` always returns `AMF_NOT_SUPPORTED`.

Environment:
System : Win7 SP1
Adapter: Radeon Pro WX5100 
Driver: Radeon™ Pro Software for Enterprise 19.Q.3  

I also check the caps.  
Code as follows:  
```
amf::AMFCaps *t_p_caps = NULL;
	t_res = m_p_encoder->GetCaps(&t_p_caps);
	if (t_res == AMF_OK) {
		amf::AMFIOCaps* t_p_iocaps = NULL;
		t_res = t_p_caps->GetInputCaps(&t_p_iocaps);
		if (t_res == AMF_OK) {
			int t_n_num_mem = t_p_iocaps->GetNumOfMemoryTypes();
			for (int i = 0;i < t_n_num_mem;i++) {
				amf::AMF_MEMORY_TYPE t_mem_type = amf::AMF_MEMORY_TYPE::AMF_MEMORY_UNKNOWN;
				bool t_b_native = false;
				t_res = t_p_iocaps->GetMemoryTypeAt(i, &t_mem_type, &t_b_native);
				if (t_res == AMF_OK) {
					printf("index:%d mem:%d native:%d\n",i,t_mem_type,t_b_native);
				}
			}

			int t_n_num_foramt = t_p_iocaps->GetNumOfFormats();
			for (int i = 0;i < t_n_num_foramt;i++) {
				amf::AMF_SURFACE_FORMAT t_surface_fmt = amf::AMF_SURFACE_FORMAT::AMF_SURFACE_UNKNOWN;
				bool t_b_native = false;
				t_res = t_p_iocaps->GetFormatAt(i, &t_amf_fmt, &t_b_native);
				if (t_res == AMF_OK) {
					printf("index:%d format:%d native:%d\n", i, t_amf_fmt, t_b_native);
				}
			}
		}
	}
```
And its result is : 
![1](https://user-images.githubusercontent.com/16220207/64606781-a3cdc600-d3f9-11e9-8dd2-45931a8f7764.PNG)

**Comment by MikhailAMD** [comment]
In general, DX11 support on Win7 is limited. The encoder will work via DX9 only. Some DX11 textures are not supported also in DX11. So if you really need DX11 input you should use AMF color converter as a bridge. Configure it for DX11 input, DX9 NV12 output and OpenCL as a compute engine. And if the input is allocated by your app ensure that textures are allocated with shared handle.
