### ISSUE TITLE
how to write RGBA data correctly?

### ISSUE THREAD

**Issue by yangyan0202** [GPUOpen-LibrariesAndSDKs/AMF#183]
I try to write RGBA data to file, but find that the image is reversed。
The code for writing RGB surface is as follows：

amf::AMFPlane *plane = surface->GetPlane(amf::AMF_PLANE_PACKED);
	amf_uint8 *data = reinterpret_cast<amf_uint8*>(plane->GetNative());
	amf_int32 offsetX = plane->GetOffsetX();
	amf_int32 offsetY = plane->GetOffsetY();
	amf_int32 pixelSize = plane->GetPixelSizeInBytes();
	amf_int32 height = plane->GetHeight();
	amf_int32 width = plane->GetWidth();
	amf_int32 pitchH = plane->GetHPitch();
	for (amf_int32 y = 0; y < height; y++)
	{
		amf_uint8 *line = data + (y + offsetY) * pitchH;		
		m_pFile.write(reinterpret_cast<char*>(line) + offsetX * pixelSize, pixelSize * width);
	}

And the output of NV12 surface & RGBA surface as follows: 
![微信截图_20190917142628](https://user-images.githubusercontent.com/26272318/65016891-f5c19f00-d957-11e9-8e36-edf85952169e.png)
How do I write RGB surface correctly？

**Comment by MikhailAMD** [comment]
There are two  questions: 
- Who filled the surface? AMF really don't care about line order. AMD decoder and color converter write lines (rows) from top to bottom order as you seem expect.
- What does your viewer expect? For example BMP file format stores lines from bottom to top - opposite to what you expect.

**Comment by yangyan0202** [comment]
> There are two questions:
> 
> * Who filled the surface? AMF really don't care about line order. AMD decoder and color converter write lines (rows) from top to bottom order as you seem expect.
> * What does your viewer expect? For example BMP file format stores lines from bottom to top - opposite to what you expect.

The surface was queried from decoder. I used "Elecard YUV Viewer" to open the file but I actually don't know  in what order the viewer are displayed, maybe that's the problem. I solved this problem by writing lines from bottom to top.  thanks!
