### ISSUE TITLE
how to use the encoder when i CreateComponent, it return AMF_NOT_SUPPORTED

### ISSUE THREAD

**Issue by jamaik7** [GPUOpen-LibrariesAndSDKs/AMF#184]
i test the code in Win10

Environment:
Windows10 1809
Adapter: Radeon Pro S7150v AMD MxGPU
Driver: Adrenalin-Edition-17.12.2 (17.50.07)
i use the AMF-1.4.6

`
int _tmain(int argc, _TCHAR* argv[])
{
    AMF_RESULT res = AMF_OK; // error checking can be added later
    res = g_AMFFactory.Init();
    if(res != AMF_OK)
    {
        wprintf(L"AMF Failed to initialize");
        return 1;
    }

    ::amf_increase_timer_precision();

    amf::AMFTraceEnableWriter(AMF_TRACE_WRITER_CONSOLE, true);
    amf::AMFTraceEnableWriter(AMF_TRACE_WRITER_DEBUG_OUTPUT, true);
    

    // initialize AMF
    amf::AMFContextPtr context;
    amf::AMFComponentPtr encoder;
    amf::AMFSurfacePtr surfaceIn;

    // context
    res = g_AMFFactory.GetFactory()->CreateContext(&context);
    AMF_RETURN_IF_FAILED(res, L"CreateContext() failed");

    if(memoryTypeIn == amf::AMF_MEMORY_DX9)
    {
        res = context->InitDX9(NULL); // can be DX9 or DX9Ex device
        AMF_RETURN_IF_FAILED(res, L"InitDX9(NULL) failed");
    }
    if(memoryTypeIn == amf::AMF_MEMORY_DX11)
    {
        res = context->InitDX11(NULL); // can be DX11 device
        AMF_RETURN_IF_FAILED(res, L"InitDX11(NULL) failed");
        PrepareFillDX11(context);

    }
    // component: encoder
    res = g_AMFFactory.GetFactory()->CreateComponent(context, pCodec, &encoder);`
it return AMF_NOT_SUPPORTED and AMFComponentPtr encoder is NULL ptr
how can i run this simple

**Comment by MikhailAMD** [comment]
- Which codec do you try to create?
- What do you see in the debug output?
You have almost two years old driver and GPU released recently. Try the latest hotfix from amd.com.

**Comment by jamaik7** [comment]
@MikhailAMD 
1.AMFVideoEncoderVCE_AVC
2.SimpleEncoder.cpp:AMF_RETURN_IF_FAILED(res, L"CreateContext() failed");fail AMF_NOT_SUPPORTED
3.Because i use it in the Virtualization [https://www.amd.com/zh-hans/support/professional-graphics/firepro/firepro-s-series/firepro-s7150-x2](url) the page support my driver only the 17.12.2 so i have not try other version driver.

**Comment by MikhailAMD** [comment]
Driver for virtualized GPU doesn't support encoder. You would have to put the GPU in passthrough mode.

**Comment by jamaik7** [comment]
@MikhailAMD the whole GPU is S7150 the virutalized GPU is S7150v ,all of them can passthrough into VM and you means  S7150v doesn't support encoder and S7150 support encoder?

**Comment by MikhailAMD** [comment]
Not sure I understand the question. Do you need to capture screen and have problems? If so, there are two APIs: DesktopDuplication API from Microsoft https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api. I would start with it. AMF has a sample how to use it. Check VideoCapture component. Also there is AMD DOPP API connected to OpenGL. Works only with Pro GPUs and drivers. https://github.com/GPUOpen-LibrariesAndSDKs/DOPP

**Comment by jamaik7** [comment]
such as game play in full screen mode ,dxgi only capture the black image

**Comment by MikhailAMD** [comment]
Did you try on regular, not VM setup? You can use OBS studio and enable DD mode.

**Comment by jamaik7** [comment]
I will try it ，thanks for your help

**Comment by MikhailAMD** [comment]
BTW: for AMD the solution is DOPP

**Comment by jamaik7** [comment]
ok thanks

**Comment by AlanDaniels101** [comment]
> 
> 
> Driver for virtualized GPU doesn't support encoder. You would have to put the GPU in passthrough mode.

When will it be supported?

**Comment by MikhailAMD** [comment]
Realy sorry but I cannot comment on non-released features.

**Comment by AlanDaniels101** [comment]
Thanks Mikhail. This is critical for our use case. Seems like cloud gaming and Citrix-type products would use this too. Hopefully it comes through soon.

**Comment by MikhailAMD** [comment]
If you like you can send me a private info about your project. I will show it to the people involved. Email:
mikhail'dot'mironov'att'amd'dot'com
