### ISSUE TITLE
Is there a method to obtain effective QP from H.264 encoded frame?

### ISSUE THREAD

**Issue by roman380** [GPUOpen-LibrariesAndSDKs/AMF#185]
I would expect that amf::AMFBufferPtr holding encoder output has a proprety with QP value and it does not look like it exists. 

If there is something else meaningful to attach, it could be present there as well.

**Comment by MikhailAMD** [comment]
This is not available at this point. What is the use case for such property to be exposed?

**Comment by roman380** [comment]
We have live video encoded incrementally as incoming data appears (and only when input has changes/updates in it), but in the same time encoder is set for bitrate targeting. With QP knowledge it is possible to better track situations when encoder output quality is not good because of tight bitrate budget immediately, and repeated input frames could clarify output.

**Comment by roman380** [comment]
Also both Intel and Nvidia expose this, so I thought you'd want to align the feature set.
