### ISSUE TITLE
VP9 HW decoding of Navi 10 and Capability Manager of AMF SDK v1.4.14

### ISSUE THREAD

**Issue by NikosDi** [GPUOpen-LibrariesAndSDKs/AMF#186]
Hello.

It's been almost three months since Navi 10 released (5700/5700 XT) and I still read complaints regarding VP9 HW decoding of those cards.

1) Is VP9 HW acceleration working inside Web browsers playing VP9 Youtube content for all resolutions (1080p/4K/8K) ?

2) Does it work offline leveraging DXVA2/D3D11 hardware decoding of Media Players for 4K/8K VP9 content ?

3) Is it possible to compile/ provide Capability Manager of AMF SDK v1.4.14 ?

4) Does Capability Manager report VP9 HW decoding capabilities of Navi 10 cards ?

Thank you!

**Comment by MikhailAMD** [comment]
1. DXVA2/D3D11VA acceleration is working.
2. For WMP it should be an MFT built on top of DXVA2/D3D11VA. So far there is no MFT.
3. AMF doesn't support VP9 yet. Work in progress.
4. Once AMF provides the support Capability Manager sample will be updated.

**Comment by NikosDi** [comment]
1. I'm afraid that all 8K VP9 clips of YouTube don't get any VP9 HW acceleration and fall back in software decoding.
I'm not sure for 4K.

2. The same is true for offline VP9 8K content using MPC-HC or other DXVA2/D3D11VA capable media players.
I'm not sure for 4K, also.

3. OK

4. Do you offer an executable or just the code to compile Capability Manager ?
I would like to have the binary file.

Thank you!

**Comment by MikhailAMD** [comment]
All this is question of integrating DXVA/D3D11VA in thse apps.
Capability Manager is a sample, not a utilty. Maintaining binaries complicates things.

**Comment by NikosDi** [comment]
Not sure I fully understand you.

You mean browsers like Chrome, Edge, Mozilla haven't implemented properly VP9 HW acceleration for Navi only ?

Because for all other HW decoders, these browsers work like a charm regarding VP9 8K YouTube content HW acceleration (Pascal/Turing for nVidia and Intel's iGPU)

Also for offline content, LAV filters have one of the best DXVA2/D3D11VA implementations out there, working for AMD, nVidia and Intel GPUs.

Thanks!

**Comment by MikhailAMD** [comment]
What I am trying to say is that these applications have own decoder implementations to call DXVA2/D3D11VA interfaces. For example Edge, is probably based on Media Foundation. I don't know how they detect HW capabilites. But in any case they don't use AMF. So if for Navi VP9 HW decoding doesn't work the application owner should contact AMD.

**Comment by NikosDi** [comment]
They certainly don't use AMF just for HW decoding, but on the other hand, before Navi every AMD had standard DXVA2/D3D11VA acceleration enabled via drivers (decoder devices)

Running for example DXVA Checker on Navi 10 cards, they expose the common Decoder Devices for DXVA2/D3D11VA.

Are you trying to say that Navi 10 cards don't follow standard DXVA2/D3D11VA acceleration out of the box and they use a proprietary mode for HW acceleration especially for VP9 ?

Because all the other codecs (H.264/H.265 etc) work out of the box using DXVA2/D3D11VA without contacting AMD.

Thanks!

**Comment by NikosDi** [comment]
With the release of new drivers and new AMF SDK version, I think all of the above issues have been resolved/ replied in theory at least because I don't have a Navi 10 card.

If I'm not mistaken, we can close this issue.
