### ISSUE TITLE
Driver requirements for LOWLATENCY_MODE

### ISSUE THREAD

**Issue by kyleqian** [GPUOpen-LibrariesAndSDKs/AMF#187]
Referencing #170, are there any additional driver requirements for using LOWLATENCY_MODE beyond what you'd need for TRANSCODING usage? Thanks!

**Comment by MikhailAMD** [comment]
Not really. What is your concern?

**Comment by kyleqian** [comment]
Currently working on Oculus Link and want to make sure that drivers for LOWLATENCY_MODE don't require a significantly newer driver version than what we'd already require for TRANSCODING.

**Comment by MikhailAMD** [comment]
This feature/property exists for a while: 2-3 years. Just recently decision was made to make it public and support.
