### ISSUE TITLE
Window compositing

### ISSUE THREAD

**Issue by Suhail** [GPUOpen-LibrariesAndSDKs/AMF#188]
Hi there,

Can these libraries do window compositing on GPU?

Here's what I am looking for:

- I'd like to run Ubuntu 18.04, X, and an application like Google Chrome
- Capture the window of just google chrome (overlapping windows would not show up)
- H.264 encode the captured frame

NVIDIA has libraries that can do this that we've used.

Secondly, are there any licensing or pricing restrictions? Specifically around limiting the resolution you can capture, the type of hardware you can use?

Thirdly, is there any benchmarks I can look at in terms of capture + encode latency?

Currently we're seeing < 5ms with a T4 NVIDIA GPU.

**Comment by MikhailAMD** [comment]
For compositing please check Video Converter component. It can do scaling, cropping and compositing with alpha channel. Check SimpleConverter sample to start with. For latency, chef SimpleEncoder sample.
AMF doesn't have a capture component.
Also composition and an encoder works via Vulkan.
There is no pricing or restrictions but codec fee is your responsibility.

**Comment by nathankidd** [comment]
@Suhail see #156

**Comment by MikhailAMD** [comment]
In addition to DD API from MSFT There is also DOPP SDK for Pro GPUs but it is also for Windows. https://gpuopen.com/gaming-product/firepro-dopp/

**Comment by Suhail** [comment]
We're looking for something for Linux (ideally Ubuntu but not required)

**Comment by MikhailAMD** [comment]
I understand and will pass the request.
