### ISSUE TITLE
Passthrough vs. shared

### ISSUE THREAD

**Issue by Suhail** [GPUOpen-LibrariesAndSDKs/AMF#189]
How might you use AMD GPUs with AMF to virtualize GPU resources?

For example, NVIDIA + Citrix enable you to do this with vGPU where they partition the VRAM onboard the GPU per VM.

Is there an equivalent?

Our goal is to provide a VM per user that cause utilize a portion of the GPU memory + compute.

If there isn't a way? Is there a multi-seat solution by shimming Linux by user account?

**Comment by GennadiyAMD** [comment]
@Suhail - AMF doesn't deal with GPU virtualization specifically. We have a dedicated GPU virtualization area on GPUOpen/Github, which can be found here: [https://github.com/GPUOpen-LibrariesAndSDKs/MxGPU-Virtualization](https://github.com/GPUOpen-LibrariesAndSDKs/MxGPU-Virtualization). You can also find additional resources at the AMD site here: [https://www.amd.com/en/graphics/workstation-virtual-graphics](https://www.amd.com/en/graphics/workstation-virtual-graphics).
