### ISSUE TITLE
Is there any way I can use to pass through a self-defined structure with frames encoded?

### ISSUE THREAD

**Issue by tianhanghai** [GPUOpen-LibrariesAndSDKs/AMF#192]
I need to bind a self-defined data with the frame, so I can get that specified data from the output encoded data.  
I need to bind the specified data with the raw video frame ,then encode that frame to the H264/H265 data, finallly I want to get the specified from the encoded data.  
I have three ways needed to be confirmed:  
1.  using the timestamp to match the input frame and output frame
```C++
#define START_TIME_PROPERTY L"StartTimeProperty"
...
t_p_data->GetProperty(START_TIME_PROPERTY, &t_pts_start_time);
```

2. using the property `LTR_INDEX` to match the input frame and output frame
```C++
AMF_VIDEO_ENCODER_MARK_CURRENT_WITH_LTR_INDEX
AMF_VIDEO_ENCODER_OUTPUT_MARKED_LTR_INDEX
```
But I don't know the meaning of `LTR_INDEX`

3.using the property `AMF_VIDEO_ENCODER_EXTRADATA`
its comment says :
```C++
#define AMF_VIDEO_ENCODER_EXTRADATA                             L"ExtraData"                // AMFInterface* - > AMFBuffer*; SPS/PPS buffer in Annex B format - read-only
```
Can I directly use `AMF_VIDEO_ENCODER_EXTRADATA` to pass through the specified data?

Which way should I use and is there any other solutions?

Looking foward  to your help.
Thanks a lot.

**Comment by MikhailAMD** [comment]
If you need to attach some data to the input frame and get them back from the output buffer the first variant is the correct one.
The second variant: don't try to repurpose existing properties some new way. Please read documentation for their meaning
The third variant: extradata is a way to retrieve SPS/PPS which is needed to initiate many muxers ( file containers). This property is a component property and unrelated to input/output properties.

**Comment by tianhanghai** [comment]
Thanks a lot.
