### ISSUE TITLE
AMFVideoEncoder_HEVC returns AMF_FAIL for attempt to read PerformanceCounter property

### ISSUE THREAD

**Issue by roman380** [GPUOpen-LibrariesAndSDKs/AMF#197]
An attempt to read exposed and enumerated property "PerformanceCounter" with, for example, `amf::AMFPropertyStorage::GetPropertyAt` call returns `AMF_FAIL` in the case of H.265/HEVC encoder (`AMFVideoEncoder_HEVC`).

That is an iteration over properties to read and log them is giving the unexpected error.

**Comment by MikhailAMD** [comment]
This is an internal property and behaviour is expected. Your code should ignore the error and continue.
