### ISSUE TITLE
Video Encode API: Unable to set Two Pass Encoding

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#2]
There currently seems to be no way to tell AMF/VCE which encoding type should be used. It is either missing from the include files or not properly documented. I may have missed it though.

**Comment by Xaymar** [comment]
I have been stepping through the amfrt32 and amfrt64 library for a bit now and only discovered strings related to HEVC, not Two Pass or SinglePass encoding. I will continue looking until there is an official update.

**Comment by Roph** [comment]
An update on this would be nice. I assume the 2-pass is also for H264, not just H265?

**Comment by Xaymar** [comment]
Two Pass encoding is really needed to provide better quality than what you currently get in dark scenes. I don't know why but AMF uses a bitrate way too low for dark areas - similar to x264 superfast behaviour.

**Comment by Roph** [comment]
Any word on this? HEVC and 2-pass support were big reasons I went with a polaris GPU instead of going Nvidia. It's disappointing that these advertised features are still not supported. Developers out there are sat twiddling their thumbs waiting for SDK support to implement it in their apps :(

**Comment by Xaymar** [comment]
16.10.3 seems to be the first driver that has new parameters available, including one that referse to a Preanalysis. Is it really going to happen, Pre-Pass/"Two"-Pass encoding before christmas?

**Comment by locodicegr** [comment]
@Xaymar Maybe they will add it in the ''annual'' driver this year...a.k.a Omega / Crimson / Whats next?

**Comment by Roph** [comment]
...Should I be saving for a Geforce 1050? The advertised features are supported before the card was even released. :/

**Comment by Xaymar** [comment]
It will most likely be in the next non-hotfix driver. Also you can already use it, my plugin already offers a way to enable the flag for it.

**Comment by Xaymar** [comment]
Implemented by commits:
- 1ee0166a35d2bb48d7c219ff491ea43f683c5d32
- dde744f39cf9162afd3779e932c0104cb65ea8c0
- 3852afaaf4b05925ee505dcc26a894ebe9dc15ce
