### ISSUE TITLE
AMF API: Documentation or API define error

### ISSUE THREAD

**Issue by mfleisz** [GPUOpen-LibrariesAndSDKs/AMF#20]
On Page 11 of the AMF_Video_Encode_API.pdf the RateControlMethod is described to have the following options:
- CQP – Constrained QP,
- CBR - Constant Bitrate,
- VBR - Peak Constrained VBR,
- VBR_LAT - Latency Constrained VBR

However in the API headers the following constants are defined in the AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_ENUM:

```
    AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_CONSTANT_QP = 0,
    AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_CBR,
    AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_PEAK_CONSTRAINED_VBR,
    AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_LATENCY_CONSTRAINED_VBR
```

So is the first option called Constant or Constrained QP?
For my project I need to dynamically control the QP of the encoder. Is the first control method the right one to choose for this job (according to the docs QPI, QPP and QPB are only applied if this mode is choosen)?

**Comment by MikhailAMD** [comment]
Yes, CQP is "constrained" - based on QP, we will correct the naming in the next release

**Comment by Xaymar** [comment]
Wait, so it's actually Constrained QP or Constant QP now? Since it seems to act like Constant QP while Latency Constrained VBR acts like Constrained QP.

**Comment by MikhailAMD** [comment]
My fault: just checked with dev - it is constant QP. We will update documentation.

**Comment by mfleisz** [comment]
So that means QPI, QPP and QPB parameters are only available with VBR_LAT control method?

**Comment by Xaymar** [comment]
QPI, QPP and QPB are available for CQP method. VBR_LAT uses a combination of Target Bitrate, Min QP and Max QP - not entirely sure which actually affects it and which is just coincidence.

**Comment by mfleisz** [comment]
@Xaymar Ah I see - so "constant" in this case means constant QP with respect to the QPI, QPP and QPB settings - thanks for the clarification!

**Comment by MikhailAMD** [comment]
Documentation was updated
