### ISSUE TITLE
hevc_amf does not adhere to define bitrates

### ISSUE THREAD

**Issue by EposVox** [GPUOpen-LibrariesAndSDKs/AMF#201]
Hi all,
I'm doing a lot of testing with AMF's encoders and have found a weird issue where encoding 4 source files with HEVC set to CBR, only one of the source files' results actually adhered to the bitrate I told it to. The rest averaged between 14 and 16mbps. I can't figure out why. This was consistent across two machines with 3 generations of AMD GPUs (5700xt, Radeon VII, RX580), all w/ the latest Adrenaline drivers.

Encode line:
`ffmpeg -y -i "%%A" -map 0:0 -map 0:1 -c:v hevc_amf -preset slow -rc cbr -b:v 2.5M -maxrate 2.5M -bufsize 2.5M*2 -pix_fmt yuv420p -profile:v main "%%~dnpA-VCEH265-2-5m.mp4"`

_(I did multiple tests at 1, 2.5, 3.5, 6, 8, 10mbps.)_
Encodes from a source file consisting of camera footage edited together adhered exactly to my specified bitrates, whereas that of gameplay just set its own bitrates ignoring the command entirely.
I've since tried removing the map parameters, the preset, changing bufsize to match the bitrate exactly, removing the -rc cbr parameter, etc. There is nothing I can do to get it to adhere to the bitrate I set out. It always produces the higher bitrate file.

What am I missing? Please identify what is incorrect here and why it worked on one of the files, but not the other three. Thanks!

(It may also be worth noting that I also encountered this exact issue in Handbrake, but assumed it was a poor implementation in Handbrake, but is present in both uses of the encoder. Is this just a known bug? I also found [this unanswered thread](https://community.amd.com/thread/228508) of someone having the same issue.)
I've had a few other users attempt the same kind of encode on their systems and got similar results - not adhering to the defined bitrates.

I had also made a [post on the FFMPEG subreddit](https://www.reddit.com/r/ffmpeg/comments/euaaw6/hevc_amf_cbr_not_adhering_to_set_bitrates/), but received no response.

**Comment by MikhailAMD** [comment]
What is your driver exact version? Check in Software section.

**Comment by EposVox** [comment]
The RX580 and 5700XT were running on 19.12.3. I believe the Radeon VII was running on a newer version that had just released, but I do not have access to that PC at this time.

**Comment by EposVox** [comment]
Just updated to 20.1.4 and confirmed I'm still getting the same behavior.

**Comment by MikhailAMD** [comment]
OK, I will check tomorrow when I have access to PC. To save time it would help if you could share one source and output clips.

**Comment by EposVox** [comment]
Here's one of the source files I used (it's 20GB, be warned, as I'm specifically needing to test based on lossless source footage) - [https://drive.google.com/file/d/1ITgYw2h84S9j_xTC6akbgmhc6K3tytuv/view?usp=sharing](https://drive.google.com/file/d/1ITgYw2h84S9j_xTC6akbgmhc6K3tytuv/view?usp=sharing)
Here's a sample encode with the kind of FFMPEG command I listed [https://drive.google.com/open?id=197E0bUpfltSvVaxK90k1kX304gQtE_IP](https://drive.google.com/open?id=197E0bUpfltSvVaxK90k1kX304gQtE_IP)

**Comment by MikhailAMD** [comment]
Thanks for the files. They've really helped. Here is what happens: with default ffmpeg QP setting there is not enough room to respect bitrate. Whatever reason in ffmpeg the default value for qmax is 31. You can change it to 51 or use AMF parameters directly (AMF respect both). I tried to add: "-max_qp_i 51 -max_qp_p 51". With this change and your source file the result bitrate matches the requested.

**Comment by EposVox** [comment]
Testing now, it seems to be working! Thanks so much!!
