### ISSUE TITLE
AMFData::Duplicate from OPENGL to HOST is slow

### ISSUE THREAD

**Issue by lingdhox** [GPUOpen-LibrariesAndSDKs/AMF#204]
I try to use AMFData::Duplicate to copy OpenGL texture data into system memory, but it's slow than glReadPixels. 
For example, for a 3840x1920 rgba opengl texture, glReadPixels takes 20ms and AMFData::Duplicate takes 30ms.
I also test DX11 to HOST, it faster than OPENGL, takes 10ms.
My graphics card is "AMD Radeon RX 5700 XT".
Is there a faster way to copy OpenGL textures?

**Comment by MikhailAMD** [comment]
Our goal is to avoid transfer to CPU. It is slow. What is your full application model, why do you need this?

**Comment by lingdhox** [comment]
> Our goal is to avoid transfer to CPU. It is slow. What is your full application model, why do you need this?

Thanks for reply.
Our program is a panoramic video editor. In the process of video processing, some CPU level Image algorithms depend on the rendering results of OpenGL. So we have to read the rendering results of OpenGL.

**Comment by MikhailAMD** [comment]
As an experiment you can try to initialize in AMF OpenCL after initializing OpenGL, use Convert(AMF_MEMORY_OPENCL) doing interop from OGL to OCL and then Duplicate(AMF_MEMORY_HOST). It may be faster.

**Comment by lingdhox** [comment]
> As an experiment you can try to initialize in AMF OpenCL after initializing OpenGL, use Convert(AMF_MEMORY_OPENCL) doing interop from OGL to OCL and then Duplicate(AMF_MEMORY_HOST). It may be faster.

According to the test results, OpenCL took 21ms, much slower than Dx11, although faster than OpenGL

**Comment by MikhailAMD** [comment]
That what I would expect. AMF just wraps OGL standard method glGetTexImage. But AMF also has to copy in CPU and this adds some time. If you dont case about CPU memory alignment you may choose to use OGL directly by acquiring OGL texture handle via GetNative().
