### ISSUE TITLE
The average consume time of capture-convert-encode is 22ms on 1080p, is it normal?

### ISSUE THREAD

**Issue by yanrk** [GPUOpen-LibrariesAndSDKs/AMF#206]
Is there any encode performance data?

My test environment: 

> AMD Radeon RX 570 Series, 
>
> latest driver, 
>
> 1920*1080 resolution

The data flow: 

​    *capture-dx11-surface --> convert-bgra-to-nv12 --> encode-with-ultra-low-latency-mode*

```c++
bool AmdEncoderImpl::init_amd_encoder(ID3D11Device * device, uint32_t src_width, uint32_t src_height, uint32_t dst_width, uint32_t dst_height, uint32_t frame_rate)
{
    do
    {
        // extern ::AMFFactoryHelper g_AMFFactory;
        if (AMF_OK != g_AMFFactory.Init())
        {
            break;
        }
        
        // amf::AMFContextPtr m_context;
        if (AMF_OK != g_AMFFactory.GetFactory()->CreateContext(&m_context))
        {
            break;
        }
        
        if (AMF_OK != m_context->InitDX11(device))
        {
            break;
        }
        
        // amf::AMFComponentPtr m_converter;
        if (AMF_OK != g_AMFFactory.GetFactory()->CreateComponent(m_context, AMFVideoConverter, &m_converter))
        {
            break;
        }
        
        if (AMF_OK != m_converter->SetProperty(AMF_VIDEO_CONVERTER_MEMORY_TYPE, amf::AMF_MEMORY_DX11))
        {
            break;
        }
        
        if (AMF_OK != m_converter->SetProperty(AMF_VIDEO_CONVERTER_OUTPUT_FORMAT, amf::AMF_SURFACE_NV12))
        {
            break;
        }
        
        if (AMF_OK != m_converter->SetProperty(AMF_VIDEO_CONVERTER_OUTPUT_SIZE, AMFConstructSize(dst_width, dst_height)))
        {
            break;
        }
        
        if (AMF_OK != m_converter->Init(amf::AMF_SURFACE_BGRA, src_width, src_height))
        {
            break;
        }
        
        // amf::AMFComponentPtr m_encoder;
        if (AMF_OK != g_AMFFactory.GetFactory()->CreateComponent(m_context, AMFVideoEncoderVCE_AVC, &m_encoder))
        {
            break;
        }
        
        if (AMF_OK != m_encoder->SetProperty(AMF_VIDEO_ENCODER_USAGE, AMF_VIDEO_ENCODER_USAGE_ULTRA_LOW_LATENCY))
        {
            break;
        }
        
        if (AMF_OK != m_encoder->SetProperty(AMF_VIDEO_ENCODER_FRAMERATE, AMFRate{ frame_rate, 1 }))
        {
            break;
        }
        
        if (AMF_OK != m_encoder->Init(amf::AMF_SURFACE_NV12, dst_width, dst_height))
        {
            break;
        }
        
        return true;
    } while (false);
    
    return false;
}
```

the test encoding average consume 22.36ms, detail information as below

| capture avg consume | convert avg consume | encode avg consume | total avg consume |
| :-----------------: | :-----------------: | :----------------: | :---------------: |
|    0.143866667ms    |    5.819233333ms    |   16.40326667ms    |   22.36636667ms   |

Is there something wrong with the way I'm handling it, or is the RX570 performance something like that.

**Comment by MikhailAMD** [comment]
1. You may add property AMF_VIDEO_ENCODER_QUALITY_PRESET = AMF_VIDEO_ENCODER_QUALITY_PRESET_SPEED to decrease latency.
2. Convert numbers look dubious: DX11 converter submits job to GFX queue and returns output right away. The synchronization with following encoder happens implicitly in the driver and transparent for app. So 5.8 ms looks like app time, not converter time.
3. For precise performance review I would use GPUVIEW logs and viewer
4. Because you are using various sleeps don't forget to increase seep precision by amf_increase_timer_precision() 
5. Your encoder time probably include color converter time. for 1080p with speed settings you should get around 10ms.

**Comment by yanrk** [comment]
@MikhailAMD It is ok now, use amf_increase_timer_precision() make consume time to 11ms, Thanks
