### ISSUE TITLE
h264 bit stream without sei infomation

### ISSUE THREAD

**Issue by foroot** [GPUOpen-LibrariesAndSDKs/AMF#207]
cannot find any sei infomation in h264 bit stream, and also no bit rate info in sps? how can I set encoder's property to get thoese infomation, certainly I set AMF_VIDEO_ENCODER_TARGET_BITRATE and  variable bitrate control, it's very important for me,any help will be highly appreciated

**Comment by MikhailAMD** [comment]
SEI messages are mostly used for timing. AMF encoder doesn't do any timing or pacing. It encodes as fast as HW is capable of. The provided frame rate is used for rate control only. So, the encoder cannot generate any meaningful SEI. Also SEI are used for application - defined messages, the app can just add them to output buffers.
I went through h.264 spec and didn't find any bitrate field.  And this is kind of logical. An encoder application can dynamically change bitrate at any time and no special information in h.264 stream required to indicate the change.

**Comment by foroot** [comment]
> SEI messages are mostly used for timing. AMF encoder doesn't do any timing or pacing. It encodes as fast as HW is capable of. The provided frame rate is used for rate control only. So, the encoder cannot generate any meaningful SEI. Also SEI are used for application - defined messages, the app can just add them to output buffers.
> I went through h.264 spec and didn't find any bitrate field. And this is kind of logical. An encoder application can dynamically change bitrate at any time and no special information in h.264 stream required to indicate the change.

bit rate info is in sps vui_parameter->hrd_parameters or vcl_parameters, but, h264 bit stream from amd encoder has no nal_hrd_parameters_presentt_flag or vcl_hrd_parameters_present_flag

**Comment by foroot** [comment]
![{CDB3C7FA-851B-4532-A589-BEAA1EC1F589}_20200323113247](https://user-images.githubusercontent.com/33152153/77278462-60360c00-6cfa-11ea-88af-411bafc080df.jpg)

**Comment by tobi-tobsen** [comment]
@foroot interesting, which tool are you using to analyse the bitstream and create the output above?

**Comment by foroot** [comment]
> @foroot interesting, which tool are you using to analyse the bitstream and create the output above?

Elecard StreamEye Tools，eseye_u.exe

**Comment by MikhailAMD** [comment]
We currently don't support HRD info in VUI. Application knows target bitrate, it may have many other ways to sync this info between server and client.
