### ISSUE TITLE
Converter::Init(for D3D -> Opengl texture) took more than 2 seconds

### ISSUE THREAD

**Issue by lingdhox** [GPUOpen-LibrariesAndSDKs/AMF#209]
Our render engine is based on OpenGL, but FFmpeg/decoder can only output dx9/dx11 texture. 
According to doc and samples, We found the dx texture can be converted to rgba opengl texture.

The code like below:
1. InitDX11
2. InitOpenGL
3. InitOpenCL
4. Init converter with:
    AMF_VIDEO_CONVERTER_MEMORY_TYPE = AMF_MEMORY_OPENGL 
    AMF_VIDEO_CONVERTER_COMPUTE_DEVICE = AMF_MEMORY_OPENCL
    AMF_VIDEO_CONVERTER_OUTPUT_FORMAT = AMF_SURFACE_RGBA
5. submit and query opengl output 
6. render opengl texture

It works well, performance is much better than copying to CPU, reach 4k 200fps with RX 5700 XT.

Because we have many different files, each file has a different Dx11 device. So we have to create many AMFContext. 
But the InitOpenCL is very slow, tooks more than 2 seconds. 

Is there any way to optimize its speed?
Or better way to use DX texture with OpenGL?

**Comment by lingdhox** [comment]
What about WGL_NV_DX_interop?  Would it be better?

**Comment by MikhailAMD** [comment]
1. Speed of AMFContext::InitOpenCL- we just use public APIs. You can do all initialization in your code. Check DeviceOpenGL.cpp, DeviceDX11.cpp, DeviceOpenCL.cpp in samples. The created devices can be passed into AMFCotext::Init<>() functions. It is the same thing. Doing the intialization in your code allows you select a GPU in multi-GPU cases.
2. WGL_NV_DX_interop is supported at AMD but I didn't try it. You should be able to use it outside of AMF.
3. If you still need to do color conversion, then use of AMF converter and OpenCL as a bridge between OGL and DX11 will work with the same speed as using WGL_NV_DX_interop. The main issue is synchronization. 
4. IntiOpenCL() speed: Can you share /reuse AMFContext instead of initializing it every time?

**Comment by lingdhox** [comment]
> 1. Speed of AMFContext::InitOpenCL- we just use public APIs. You can do all initialization in your code. Check DeviceOpenGL.cpp, DeviceDX11.cpp, DeviceOpenCL.cpp in samples. The created devices can be passed into AMFCotext::Init<>() functions. It is the same thing. Doing the intialization in your code allows you select a GPU in multi-GPU cases.
> 2. WGL_NV_DX_interop is supported at AMD but I didn't try it. You should be able to use it outside of AMF.
> 3. If you still need to do color conversion, then use of AMF converter and OpenCL as a bridge between OGL and DX11 will work with the same speed as using WGL_NV_DX_interop. The main issue is synchronization.
> 4. IntiOpenCL() speed: Can you share /reuse AMFContext instead of initializing it every time?

Thanks.
1.  I guess InitOpenCL is not the actual reason. Because when I comment out InitOpenCL, it still works, but converter::init takes more than 2s. 
2. We don't really need the color conversion, but the convert can't output nv12 opengl texture.
3. Surely, we can share device or context in decoders, but it will bring some code complexity, and  need to change the source code of ffmpeg. So we hope to find a simple way

**Comment by MikhailAMD** [comment]
If you don't call InitOpenCL it is called internally in converter.
I assume in OGL you use R8 as a substitute for NV12.
We've tried to offer AMFContext sharing between FFmpeg codecs (hwcontext concept) for similar reasons but it was rejected at ffmpeg. We plan to try again.

**Comment by miker-constructive** [comment]
Is there a simple sample anywhere in the SDK which illustrates the process of playing a video file onto an openGL texture?

**Comment by MikhailAMD** [comment]
I assumed you already doing this. But here is the full decription.
The main idea is to use AMF Video converter as color space converter and as a DX11->OGL bridge at the same time.
You can modify SimpleConverter sample to do following:
1. Submit NV12 DX11
2. Output RGBA(BGRA) OpenGL
3. Use OpenCL as an engine
4. To make it all working ensure you initialize AMF context in this order:
- InitOpenGL()
- InitDX11()
- InitOpenCL()
Or you can initialize all these graphic API yourself using AMF sample code: deviceOpneGL.cpp, DeviceDX11.cpp, DeviceOpenCL.cpp and passing devices to AMF.
Once you have it working you can use SimpleDecoder sample to configure AMF Decoder to run on DX11 and produce NV12 surfaces.

You could also modify PlaybackHW sample to use OGL presenter (VideoPresenterOpenGL.h,cpp) and do the above converter configuration but this is full player sample.

**Comment by lingdhox** [comment]
I would prefer to use WGL_NV_DX_interop2. 
1.  Use ID3D11VideoProcessor do DXGI_FORMAT_NV12 -> DXGI_FORMAT_R8G8B8A8_UNORM color conversion. It also support color range/space conversion.
2. Use WGLEW_NV_DX_interop2 do texture sync between D3D11 and OpenGL.

Because I did not find a simple and direct way to map r8 and r8g8 channels of DXGI_NV12 to OpenGL respectively, so made nv12 to RGBA conversion first. Maybe we can avoid this with some tricks.

There are several benefits to this way:
1. More general. eg. intel hd card.
2. Similar performance. 
3. Simpler interface.  eg. We have to impl custom surface allocator to support preallocated surface with converter in AMF.  
4. Less dependency and faster initialization.  Now we don't need to initialize OpenCL
