### ISSUE TITLE
Video Encode API: What does the first parameter to ->Init() actually do for VCE?

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#21]
I couldn't find it being mentioned anywhere in the AMF_Video_Encode_API.pdf, so what does it do? The first parameter seems to define the surface format - which can again be defined in the actual surface itself. Since VCE always outputs 4:2:0 Partial (even though Full would be nice to have), what's the point of this parameter? Is it even used?

I didn't check with reverse engineering yet, since I haven't yet managed to fully reverse engineer the wrapper classes.

**Comment by MikhailAMD** [comment]
app can set NV12  - just initializes VCE, app can set RGB or other formats supported by AMF video converter- will also initialize internal converter./ scaler.

**Comment by Xaymar** [comment]
Alright, thank you for the clarification.
