### ISSUE TITLE
how to determine the color space settings

### ISSUE THREAD

**Issue by yanrk** [GPUOpen-LibrariesAndSDKs/AMF#211]
Hi, sorry to bother you again, I have mentioned a problem ([about chromatism](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/210)). at present, it is necessary to set the color space at the encoder end, current judgment and solution:

> the 'color_full_range' is default to false
> and 'color_profile' is default to -1
>
> if the decode machine use graphics card to acceleration, 
> the encoder need set 'color_profile' to 'BT-709'
>
> if the decode machine not use graphics card to acceleration, 
> the encoder need set 'color_profile' to 'BT-601'
>
> the 'color_full_range' always set to false

then, a layer of network protocol is added between the encoder machine and the decoder machine to determine whether the decoder machine can use the graphics card.

but I am not sure whether the current judgment basis is reasonable, and I do not know whether there is a better way. do you have any suggestions or ideas, thanks.

**Comment by MikhailAMD** [comment]
I don't really understand why logic involves presence or absence of HW encoder (graphic card). As you saw in my previous post encoder side and decoder side should agree on the same converter options to get the consistent result. On both sides the options are available. So I would **force on both sides** 701 and maybe full range.

**Comment by yanrk** [comment]
@MikhailAMD okay, thanks for your advice!
