### ISSUE TITLE
how to use AMF_VIDEO_ENCODER_OUTPUT_COLOR_PROFILE 

### ISSUE THREAD

**Issue by yanrk** [GPUOpen-LibrariesAndSDKs/AMF#212]
Hi, I have try to convert color space with converter property parameter *AMF_VIDEO_CONVERTER_COLOR_PROFILE*

```c++
AMF_RESULT res = converter->SetProperty(AMF_VIDEO_CONVERTER_COLOR_PROFILE, AMF_VIDEO_CONVERTER_COLOR_PROFILE_709);
```

the function can execute normally

but the decoder can not get the *color_primaries / color_trc / colorspace* from *AvFrame* structure, and there is a serious color difference problem in the player something, and something it is ok.

I find a encoder property parameter *AMF_VIDEO_ENCODER_OUTPUT_COLOR_PROFILE*

```c++
AMF_RESULT res = encoder->SetProperty(AMF_VIDEO_ENCODER_OUTPUT_COLOR_PROFILE, AMF_VIDEO_CONVERTER_COLOR_PROFILE_709);
```

but it get error *AMF_INVALID_ARG*

is this property parameter no longer valid, or is there a problem with my usage? 

thanks.

**Comment by MikhailAMD** [comment]
This parameter is using a different ENUM: 
AMF_COLOR_PRIMARIES_ENUM Currently only BT709 and BT2020 are supports.
But you should understand that this parameter just sets a flag in VUI header to indicate color primary type was used.

**Comment by yanrk** [comment]
@MikhailAMD 

sorry, I find it in *VideoEncoderVCE.h*, it seems that comment is wrong

as you said, I change the code

```c++
AMF_RESULT res = AMF_OK;

res = encoder->SetProperty(AMF_VIDEO_ENCODER_OUTPUT_COLOR_PROFILE, AMF_COLOR_PRIMARIES_BT709);

res = encoder->SetProperty(AMF_VIDEO_ENCODER_OUTPUT_COLOR_PROFILE, AMF_COLOR_PRIMARIES_BT2020);
```

but, it also get error *AMF_INVALID_ARG*

**Comment by MikhailAMD** [comment]
It seems your GPU does not support it. For H264 this feature is supported on RX 5700 only.

**Comment by yanrk** [comment]
@MikhailAMD em, my graphics card is RX 580. thanks.
