### ISSUE TITLE
SetProperty HevcColorBitDepth not found

### ISSUE THREAD

**Issue by Nybon** [GPUOpen-LibrariesAndSDKs/AMF#214]
Hello there. 

I'm writing an encoder that uses HEVC to encode desktop images. I have set the properties as listed under, but HevcColorBitDepth fails every time. It says; [UVEEncoderTrace] Warning: SetProperty HevcColorBitDepth not found. I'm aware that 8 is the default, but it returns the same error when it's not in my code. 

I count myself as a C++ newbie and I may be wrong about my following statements. Wouldn't it be better to use 'enum class' over 'enum'? If it is, why is it not used in places like AMF_SURFACE_FORMAT? The documentation (AMF_Video_Encode_HEVC_API.pdf) says that 16 is also an option, but no place to find in the AMF_COLOR_BIT_DEPTH_ENUM. 
       
> res = encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_USAGE, AMF_VIDEO_ENCODER_HEVC_USAGE_LOW_LATENCY);
        res = encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_QUALITY_PRESET, AMF_VIDEO_ENCODER_HEVC_QUALITY_PRESET_SPEED);
        res = encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH, AMF_COLOR_BIT_DEPTH_8);
        res = encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_FRAMESIZE, ::AMFConstructSize(widthIn, heightIn));
        res = encoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_FRAMERATE, ::AMFConstructRate(frameRateIn, 1));

Thanks in advance!

**Comment by MikhailAMD** [comment]
Let's separate issues:
1. Failing attempt to set DEPTH property probably tells that you have an old driver without this property support. What is your driver version?
2. Surface format for DEPTH property is not used because only valid values would be NV12 and P010 out of many.
3. 16-bit encoding is currently not supported, documentation needs to be updated.

**Comment by Nybon** [comment]
I'm using AMD Ryzen™ 5 3400G with AMD Radeon(TM) RX Vega 11 Graphics. My current driver version is 19.50.29.27-200421a-354308E-RadeonSoftwareAdrenalin2020.

**Comment by MikhailAMD** [comment]
OK, I checked, this property will appear only if Encoder supports more then 8 bit (10). This is true for GPUs that support 10 bit HEVC encoding and only if you use **DX11**.

**Comment by Nybon** [comment]
I'm using DirectX 12, can this be an issue? AMD Radeon Software says that _Software & Driver_ is on the latest version, the encoder should then be able to encode with 8 bits?

**Comment by MikhailAMD** [comment]
AMF encoder can run via DX9, DX11 or Vulkan. See SimpleEncoder sample for details.

**Comment by Nybon** [comment]
I have tried them all, but the same error occurred on every attempt. Here is my full code that does the encoding. It always returns _[UVEEncoderTrace] Warning: SetProperty HevcColorBitDepth not found_ when I run it on my side. 
[Encoder.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/4583502/Encoder.txt)
[EncoderCPP.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/4583503/EncoderCPP.txt)

Thanks in advance!

**Comment by MikhailAMD** [comment]
Sorry, didn't realize that you are using APU. 10-bit encoder support starts with Navi10 (RX5700) and the property would be added for this GPU only.

**Comment by Nybon** [comment]
I'm trying to encode 8-bit and the _HevcColorBitDepth_ should by default use 8 bits. I've also tested the code using h.264, but the code still results in the same warning. APU's should have support for HEVC encoding right?

**Comment by MikhailAMD** [comment]
The warning is because this property is not exposed for your hardware. 8-bit encoding for H264 and HEVC is supported.

**Comment by Nybon** [comment]
After what I understand, the warning should not be an issue for me and will not prevent the encoder from encoding.
