### ISSUE TITLE
AMFDataStream unresolved external symbol

### ISSUE THREAD

**Issue by Nybon** [GPUOpen-LibrariesAndSDKs/AMF#215]
Hey again MikhailAMD.

I'm currently making a hardware decoder using HEVC. The SimpleDecoder sample is using something called AMFDataStream and BitStreamParser. It confuses me because the documentation says nothing about this. Anyways, I'm including every file that the SimpleDecoder does, but I still get 
![Capture](https://user-images.githubusercontent.com/64807403/82228740-d08f9100-9929-11ea-8fcc-eaf15ba159b1.PNG)

> #include "public/common/AMFFactory.h"
> #include "public/include/components/VideoDecoderUVD.h"
> #include "public/common/AMFSTL.h"
> #include "public/common/TraceAdapter.h"
> #include "public/common/DataStream.h"

I have faced the same error with AMFThreads too. 

Thanks in advance!

**Comment by MikhailAMD** [comment]
To fix link error: you would have to add to your project from this folder: public\common\ DataStreamMemory.cpp, DataStreamFile.cpp, DataStreamFactory.cpp, Thread.cpp, TraceAdapter.cpp
Please note, that HEVC parser wich uses data streams is just sample code and has little use for real applications. The parser parses elementary stream to create a buffer representing full compressed frame. In real life cases it is done by containers: file format or streaming protocol.

**Comment by Nybon** [comment]
The link error is fixed now, thank you. I'm making a low latency streaming application, is it necessary for me then to use parsing? I have an AMFBuffer that I receive from a socket. I tested some different variations without parsing, but it seems like all of them is returning; 

> [AMFDecoderUVDImpl]   Error: ..\..\..\..\..\runtime\src\components\DecoderUVD\DecoderUVDImpl.cpp(653):AMF_ERROR 23 : AMF_EOF: SubmitInput() - Parser SubmitInput Failed
>[AMFVideoStreamParserImpl]   Error: ..\..\..\..\..\runtime\src\components\VideoStreamParser\VideoStreamParserImpl.cpp(139):Assertion failed:SubmitInput() pData == NULL while !m_bRepeat

**Comment by MikhailAMD** [comment]
It depends on your protocol. AMF decoder assumes that you submit full frame buffers. Also it expects but not mandatory that you provide extradata (SPS/PPS) before initialization. Most protocols support both requrements. If your protocol transfers arbitrary chunks of video, you may need the parser - feed your data via your implementation of data stream.
