### ISSUE TITLE
CreateSurfaceFromDX11Native returning AMF_NOT_SUPPORED

### ISSUE THREAD

**Issue by Nybon** [GPUOpen-LibrariesAndSDKs/AMF#217]
Hi again MikhailAMD.

I'm trying to encode some ID3D11Texture2D textures that are coming from [Microsoft's desktop duplication API](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api). using  HEVC. I store the textures inside a structure that I use to copy my ID3D11Texture2D to a surface like shown below. 
https://i.gyazo.com/7245c21f9cddce614b288a186c587c67.png   

The desktop duplication API says this,
> The format of the desktop image is always DXGI_FORMAT_B8G8R8A8_UNORM no matter what the current display mode is.

I should then be using AMF_SURFACE_BGRA while I'm encoding frames and not using a converter? I'm making this as hardware specified as possible to prevent latency and I do not want the CPU to get involved in the image processing. I have been trying to use` CreateSurfaceFromDX11Native`
but returns error 10 (AMF_NOT_SUPPORTED). This is not an available return value from what I can see in AMF_API_Reference.pdf, can this conflict with that I'm testing on a Ryzen 5 3400G that have 
Radeon™ RX Vega 11 Graphics? 
`FRAME_DATA data {}`
`res = context->CreateSurfaceFromDX11Native(data.Frame, &surface, observer);`
 I'm then forced to use AllocSurface and I end up with a completely black image.

Thanks in advance!

**Comment by MikhailAMD** [comment]
Yes, you don't want to copy the captured texture to CPU. DXGI_FORMAT_B8G8R8A8_UNORM is supported. 
- What is your driver version?
- Did you initialize AMF with DX11 device (InitDX11( my_DX11_device))?  (This is the most probable cause  - you should share DX11 device with AMF)

Going forward you may don't need to copy the texture. You will have to produce NV12 for encoder so just submit what you captured to AMF color converter.

**Comment by Nybon** [comment]
The problem was that I did not share device with AMF. I wanted to test quality and some other things before I do it with NV12. I need to say that I'm impressed by the quality and speed so far!
