### ISSUE TITLE
Radeon RX 5700 XT AVC encoder takes input and does not produce any output

### ISSUE THREAD

**Issue by roman380** [GPUOpen-LibrariesAndSDKs/AMF#218]
Sadly there is not yet detailed information on the problem since it is taking place at user systems with limited diagnostics. We have three similar reports at the moment, all three with 5700 XT and two of them are fixed by rolling back the video driver.

So it might be something known and if so maybe there is a note on what exactly impact is.

The symptoms are this: AVC video encoder is configured to encode low latency video from DX11 ARGB32 surfaces. No errors are issued, input is accepted up to indication of "input is full", and no single output buffer is produced.

One of the users said he "reverted to WHQL driver" (this one confirmed he had 20.5.1 at the moment of the issue), another said he "reinstalled drivers" and there is no word back yet from third of the three mentioned in the beginning.

**Comment by roman380** [comment]
We have a sort of reproducer app, which implements a loop over encoding a set of frames, and one of users shared AMF trace enabled log which exhibits failure to encode with suspicious entries

> 2EAC [AMFEncoderUVE]    Info: SubmitToEncoder(): UVEH264_Encoder() returned UVEH264__STATUS_QUEUE_FULL

[AMD Radeon RX 5700 XT (bad).zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/4758201/AMD.Radeon.RX.5700.XT.bad.zip)

For comparison, log from Radeon RX 570 Series

[Radeon RX 570 Series (good).zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/4758208/Radeon.RX.570.Series.good.zip)

**Comment by roman380** [comment]
Based on the feedback we have:

1. `AMF_VIDEO_ENCODER_CAP_COLOR_CONVERSION` is not the right way to identify the impacted HW series
2. NV12 does work the problem around

We will apply the workaround and maybe you would be able to drop a line once there is an improvement from driver end. I think we don't want or need to improve or optimize our forced NV12 code path so it's more a temporary solution.

**Comment by MikhailAMD** [comment]
Certainly. I am tracking releases and will post an update here.

**Comment by roman380** [comment]
One more thing to share is that a user who previously managed to resolve the problem by rolling back Adrenalin driver reported that solution with 20.5.1 & pre-conversion to NV12 is overall visibly smoother (even though we convert using D3D11 VP and not your converter running on compute queue).

**Comment by MikhailAMD** [comment]
It depends how you configure AMF. If you configure just DX11, the result should be the same as VP. If you added OCL or DX9 - the result will be slower.

**Comment by MikhailAMD** [comment]
The issue should be fixed in 20.7.1 driver release (July 9, 2020)

**Comment by roman380** [comment]
We have a couple of confirmations that 20.7.1 is resolving this bug with AMD Radeon RX 5700 XT and similar.
