### ISSUE TITLE
ThreadWindows.cpp, amf_high_precision_clock(), bug.

### ISSUE THREAD

**Issue by dlee6210** [GPUOpen-LibrariesAndSDKs/AMF#219]
ThreadWindows.cpp, amf_high_precision_clock(),
(PerformanceCount.QuadPart - StartCount.QuadPart) * 10000000LL  may exceed LLONG_MAX, overflow occurs, the value will less than zero. 

And, I do this:
LONGLONG ms_value = (PerformanceCount.QuadPart - StartCount.QuadPart) * 1000 / Frequency.QuadPart; // ms
return static_cast<amf_pts>( ms_value * 10000LL);

**Comment by MikhailAMD** [comment]
Yes, we already modified it internally. Please use this if you need it now:
amf_pts AMF_CDECL_CALL amf_high_precision_clock()
{
    static int state = 0;
    static LARGE_INTEGER Frequency;
    static LARGE_INTEGER StartCount;
    static amf_pts offset = 0;

    if(state == 0)
    {
        if(QueryPerformanceFrequency(&Frequency))
        {
            state = 1;
            QueryPerformanceCounter(&StartCount);
        }
        else
        {
            state = 2;
        }
    }
    if(state == 1)
    {
        LARGE_INTEGER PerformanceCount;
        if(QueryPerformanceCounter(&PerformanceCount))
        {
            amf_pts elapsed = static_cast<amf_pts>((PerformanceCount.QuadPart - StartCount.QuadPart) * 10000000LL / Frequency.QuadPart);

            // periodically reset StartCount in order to avoid overflow
            if (elapsed > (3600LL * AMF_SECOND))
            {
                offset += elapsed;
                StartCount = PerformanceCount;

                return offset;
            }
            else
            {
                return offset + elapsed;
            }
        }
    }
#if defined(METRO_APP)
    return GetTickCount64() * 10;

#else
    return GetTickCount() * 10;

#endif
}

**Comment by dlee6210** [comment]
3Q.
