### ISSUE TITLE
Video Encode API: SubmitInput returns AMF_INPUT_FULL while QueryOutput returns AMF_REPEAT

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#22]
Issue #19 referred to this as problem scenario 3. Basically what happens is that SubmitInput will return AMF_INPUT_FULL every few seconds while QueryOutput will immediately return AMF_REPEAT. For some reason, this makes the entire computer stutter for about half a second or less.

Debug Data provided:
* [Commit that it was last reproduced with](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/commit/49e6d80dbbd61c34f4e9454827f8f2b20acb06e1)
* Dump+Log 1: [xaymar.com](http://cdn.xaymar.com/private/2016/09/amf19_14-09-2016_obs64_AMF_INPUT_FULL.7z) [mega.co.nz](https://mega.nz/#!uRllQRKZ!Xdqc2X6WUTgOSoOZcJL6ywg7BT2fOdGrVdPwKkzLw38)

**Comment by Xaymar** [comment]
16.9.2 now causes this issue to appear around 90% of the time. When do we get a fix for it? Media SDK had no issues like this (the only thing Media SDK had was long SubmitInput times).

**Comment by Xaymar** [comment]
Seems to be related to OpenCL, as it doesn't happen with the non-OpenCL version. The non-OpenCL version also had massively lower CPU usage.

**Comment by MikhailAMD** [comment]
Reproduced and internal ticket was opened.

**Comment by Xaymar** [comment]
No longer encountering this, was it fixed?

**Comment by Xaymar** [comment]
Can't reproduce this anymore, seems to be fixed by 16.10.*.
