### ISSUE TITLE
H.264 encoder fails with AMF_FAIL with Ryzen APUs

### ISSUE THREAD

**Issue by roman380** [GPUOpen-LibrariesAndSDKs/AMF#222]
It is a problem with old driver however it is still important because it is the driver which is installed automatically through Windows Update (on a fresh install of Windows).

We are seeing this problem in relatively small number of systems and eventually I got some more details from one of them.

AMD Ryzen 5 2400G with Radeon Vega Graphics; AMD Radeon(TM) RX Vega 11 Graphics

Windows update brings 19.20 driver with AMF 1.4.12

Even though H.265/HEVC encoder works as expected there, H.264 exhibits a AMF_FAIL failure. Possibly because of RGB input, but I have not had a chance to try NV12 there. We're encoding through D3D11 interface.

I think the same problem applies to other APUs.

It looks like the problem sometimes comes up at configuration stage when I set one of the properties; at other times the error is triggered when first input is submitted. 

We normally suggest that users download and install current 20.x.x driver from the website.

If you have any comments on this, please share.

**Comment by roman380** [comment]
Installation of Adrenaline 2020 version 20.4.2 fixes the encoding on the mentioned APU.

**Comment by MikhailAMD** [comment]
New 20.7.1 driver was released. It is up to MSFT to pickup newer driver for Windows update, hard to convince.

**Comment by roman380** [comment]
Finally landed our update which adds error trace to the failure context. Example:

AMD Radeon(TM) RX Vega 10 Graphics
Driver 19.10.26.07-190813a-345230C-Acer (received with Windows update, I suppose)
AMF 1.4.12.0

```2020-08-13 15:58:56.878     3BD4 [DriverParameterUVEH264Adapter]   Error: ..\..\..\..\..\runtime\src\components\EncoderUVE\DriverParameterUVEH264Adapter.cpp(459):AMF_ERROR 1 : AMF_FAIL: Failed to Set RateControlMode

2020-08-13 15:58:56.878     3BD4 [DriverParameterUVEH264Adapter]   Error: ..\..\..\..\..\runtime\src\components\EncoderUVE\DriverParameterUVEH264Adapter.cpp(298):AMF_ERROR 1 : AMF_FAIL: Failed to set UVEH264 param(32). err 0x80000009

2020-08-13 15:58:56.878     3BD4 [DriverParameterUVEH264Adapter]   Error: ..\..\..\..\..\runtime\src\components\EncoderUVE\DriverParameterUVEH264Adapter.cpp(459):AMF_ERROR 1 : AMF_FAIL: Failed to Set RateControlMode

2020-08-13 15:58:56.878     3BD4 [DriverParameterUVEH264Adapter]   Error: ..\..\..\..\..\runtime\src\components\EncoderUVE\DriverParameterUVEH264Adapter.cpp(298):AMF_ERROR 1 : AMF_FAIL: Failed to set UVEH264 param(32). err 0x80000009

2020-08-13 15:58:55.845     200C [DriverParameterUVEH264Adapter]   Error: ..\..\..\..\..\runtime\src\components\EncoderUVE\DriverParameterUVEH264Adapter.cpp(298):AMF_ERROR 1 : AMF_FAIL: Failed to set UVEH264 param(28). err 0x80000002

2020-08-13 15:58:55.774     200C [DriverParameterUVEH264Adapter]   Error: ..\..\..\..\..\runtime\src\components\EncoderUVE\DriverParameterUVEH264Adapter.cpp(298):AMF_ERROR 1 : AMF_FAIL: Failed to set UVEH264 param(28). err 0x80000002
```

**Comment by roman380** [comment]
Same on 

AMD Radeon(TM) RX Vega 11 Graphics
19.10.16-190514a-343170C-Channel

Didn't you have `AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_CBR` in 1.4.12? What fallback should we do if we want to cover this old version and CBR is not supported, `AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_CONSTANT_QP`?

**Comment by MikhailAMD** [comment]
Param #32 is rate control mode. Unfortunately with new GPUs this parameter became static and cannot be changed after Init(). So the error.
Param #28 corresponds to AMF_VIDEO_ENCODER_INTRA_REFRESH_NUM_MBS_PER_SLOT - the same issue - it is static now.

CBR is always available but rate control mode cannot be changes on the fly.

**Comment by roman380** [comment]
Since I still do not see full context for the error I can't tell whether this is initial setup or re-configuration, but I would assume it's just initialization. I never change `AMF_VIDEO_ENCODER_INTRA_REFRESH_NUM_MBS_PER_SLOT` in particular, just a hardcoded value. And this is expected to happen before first SubmitInput.

Can I expect that I don't get the failure if I try to set the same value which is already set? Twice or more but all calls before SubmitInput? 

It looks like I would need to make sure I am not reusing components between session and I create new one each time, so that I never hit these once-initialized parameters.

**Comment by MikhailAMD** [comment]
These properties have to be set before Init() call. Any attempt to set them after will cause this error. Though, you can ignore it.

**Comment by roman380** [comment]
Yes it looks like rate control method/mode property change triggers the error and to be honest I don't understand why it has to be this way. The error is triggered even if the same value as current is provided. The error code is not descriptive and the behavior itself is not well documented. The runtime could just do AMF_OK since such call does not have a change that runtime can't handle.

**Comment by MikhailAMD** [comment]
This is not AMF but driver behaviour. Any change in the driver takes time, And from driver perspective the behaviour is correct: the app tries to set a property when the change cannot be done. The driver and AMF must report a error and not conseal it. We should not give an impression to the app that the requested change was accepted. Or this would lead to the errors down the road.

**Comment by roman380** [comment]
I will close this one. I think I will have confirmation for implemented workaround to work in at least a few weeks, but I think I got the idea: after `AMFComponent::Init` call properties go read-only and setter for even current values trigger failure error codes, by design.
