### ISSUE TITLE
Decoding results for certain HEVC streams are corrupted.

### ISSUE THREAD

**Issue by Masa-tam** [GPUOpen-LibrariesAndSDKs/AMF#224]
[sample.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/5055584/sample.zip)

When I decode the attached file, I get corrupted video.
Other decoders can get the video normally.

I checked the corrupted video in the output_1920x1080.nv12 obtained by changing bWriteToFile = true; in SimpleDecoder.cpp.

**Comment by MikhailAMD** [comment]
I tried and cannot reproduce this.  

- Which GPU are you running?
- What is your OS?
- What is your driver?
- Any modifications in the sample?

Please provide the corruption screenshot
Please  ZIP output NV12 file and share

**Comment by Masa-tam** [comment]
I'm very sorry for the lack of information.

GPU:RX 5500 XT
OS:Windows10 x64 Pro Version 1903 OS Build 18362.959
Driver:20.7.2

I'm attaching the patch file and decoded nv12 file.
[changed.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/5060020/changed.zip)
[output_1920x1080.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/5060027/output_1920x1080.zip)

**Comment by MikhailAMD** [comment]
Could you please try the latest driver 20.8.1 ?

**Comment by Masa-tam** [comment]
I tried 20.8.1.
It still failed to decode correctly.

**Comment by MikhailAMD** [comment]
Hmmm. This looks like not decoding but a synchronization issue. Does the corruption look the same on every run or different?

**Comment by Masa-tam** [comment]
I ran it three times and got an nv12 file with identical results.
I tested it with "fc /b", it is exactly the same.

**Comment by MikhailAMD** [comment]
OK, then please share the HEVC file.

**Comment by Masa-tam** [comment]
The sample.zip at the top is one of the HEVC streams in question.
If you need more samples, I can make them.

**Comment by MikhailAMD** [comment]
Yes, thanks, I've used it for testing.

**Comment by MikhailAMD** [comment]
I see the problem on a different GPU. Will investigate. I assume you produced the clip with SimpleEncoder sample. Did you make any changes in it?

**Comment by Masa-tam** [comment]
This HEVC stream was encoded with Skylake's HW encoder using the first 90 frames of SimpleEncoderC's output.
I used it as a copyright-free, well compressed source.

**Comment by MikhailAMD** [comment]
Strictly speaking based on Vega Analyzer information the clip has errors but I don't think it is the issue. 
I can repro the problem but not on 5500. Is it possible that your system have two GPUs: one from Ryzen (Vega) and one discreet (5500) and the decode app run on Vega? You can check this in Task Manager based on Video decode activity.

**Comment by Masa-tam** [comment]
<img width="520" alt="TaskManager" src="https://user-images.githubusercontent.com/31396809/90199569-2338f600-de10-11ea-815b-7902fb6e3fb5.png">

I'm Attaching a screenshot of the task manager.
My machine has an i7-6700K CPU and I ran the HEVC hardware encoding on this Skylake.

**Comment by MikhailAMD** [comment]
As I can repro the issue on selected hardware I filed an internal ticket. I will keep you posted. Thanks for your help and patience.

**Comment by MikhailAMD** [comment]
Please try the latest driver.  This issue was fixed in September 2020.

**Comment by Masa-tam** [comment]
Thank you very much.
I have confirmed that it works with the latest drivers.
