### ISSUE TITLE
5700 encoder performance？

### ISSUE THREAD

**Issue by chllcy** [GPUOpen-LibrariesAndSDKs/AMF#225]
my gpu is AMD Radeon RX 5700  8G. and when I run simpleEncoder with 1920\*1080 60fps, the gpu encoder for 50%.
and I run with 2560\*1440 144fps, the gpu encoder for 100%. is it support 2k 144HZ encoder for 5700?

https://www.guru3d.com/articles-pages/tech-preview-radeon-rx-5700-and-5700-xt-(navi),5.html
The media engine has been updated as well, now offering support for H.264 4K150/8K30 Decodes and 4K90 Encodes (that's Ultra HD recording at 90 Hz/PS).

I find 5700 support for 4K90 Encodes.it's equal to 2k180,but why it's 100% for 2k144HZ.
when I used nvidia 1080ti for encoder 2k144hz(nvidia video codec sdk), it's used only about 25% video encode. with 1070,it's also below 40%.what's problem with amd?？

![image](https://user-images.githubusercontent.com/12612758/90206501-626a4580-de16-11ea-9af6-c1f79761f71e.png)

AMF version:1.4.16.0 (04.02.2020) version
OS version : windows 10 1903
CPU: AMD 3700X
MEMORY: 32GB

**Comment by MikhailAMD** [comment]
Few random notes:
1. Windows task Manager shows how filled is the Encoder queue. If there are no gaps between encoder jobs, it will show 100%. You can see these jobs if you record GPUVIEW log and open the log in the viewer. But it doesn't mean that the encoder run at full capacity. It may run on lower clocks for various reasons and every job will be longer than it can be. One of the reasons for such behavior is power management.
2. From performance perspective, frame rate parameter set on encoder is irrelevant. It is used only in bitrate control and is written into VUI header. The encoder doesn't try to keep any frame rate /timing / pacing. It will work with the rate of input frame submission and HW capabilities.
3. If you are interested to check maximum performance of the encoder, you can use it using SimpleEncoder sample by adding one property to the encoder setup: AMF_VIDEO_ENCODER_LOWLATENCY_MODE = true. At the end of the run the "encode  per frame =" output will give the number of average encoding time in milliseconds.
4. Encoder performance is scalable almost linearly. If you measured that it can encode 4K@90 fps (11.1 ms), you can assume that it can do 1080p@360fps or 4x1080p@90 etc.
5. I cannot provide the exact numbers for encoder performance. It depends on many factors: version of GPU, OEM tuning of the card, other GPU load, color conversion on GPU, power etc.

**Comment by chllcy** [comment]
thanks @MikhailAMD 。 
I will use GPUVIEW and setup AMF_VIDEO_ENCODER_LOWLATENCY_MODE = true tomorrow。
and I test Video Encoding Benchmark  with https://egpu.io/forums/pro-applications/easy-video-encoding-benchmark-test-your-gpu-within-seconds/
I get the result
![image](https://user-images.githubusercontent.com/12612758/90335591-87260f00-e008-11ea-946a-633c6e012f6e.png)
the result 5700 GPU with h264 encode is so poor。

**Comment by MikhailAMD** [comment]
Something is wrong with this tool. For RX 5700, H264 and H265 performance should be comparable and closer to the H265 results. 
One thing I notised, they run FFmpeg in quality mode - this is not the fastest mode. You can set almost envery AMF parameter in FFmpeg via command line. 
Another: the command line in the link assumes software decoding and therefore transfer between CPU ang GPU video memory. This adds to timing.

**Comment by roman380** [comment]
@chllcy you might want to run this https://alax.info/blog/2033 and see the numbers for different resolutions/rates. I am doing this test with lowest latency settings in mind but generally you should be able to see starting at which settings the encoder can't keep real time pace. I don't have data for 5700 but if you compare NVIDIA encoders are capable to handle might higher throughput.

RX 570, for example, can do 2560x1440@60 but can't already do 2560x1440@72. 

NVIDIA GeForce GTX 1650 in comparison can handle 2560x1440@144.

**Comment by chllcy** [comment]
thanks @MikhailAMD 
I test with AMF_VIDEO_ENCODER_LOWLATENCY_MODE. and get the result
SimpleEncoder.exe
latency           = 26.4462ms
encode  per frame = 5.6762ms
write per frame   = 0.0033ms
so it only used 5.67ms,and I had changed resolutions to 2560*1440. so it can encode 2k 144hz?  1000/5.6762 = 176fps
-------------------------------------------------------------------------------------------------------------
below is one packet in hardware queue video encode
Creation Time: 70919954 (7,091.9954ms)
Process (15776) SimpleEncoder.exe
Context: 0xFFFFDA85C4AEFDE0

Standard Dma Packet
Submission fence: 956
SubmittedToHardwareQueueTime: 70920001 (7,092.0001ms)
GpuStartProcessingTime: 70971955 (7,097.1955ms)
CompletedByISRTime: 71022640 (7,102.2640ms)
CompletedByDPCTime: 71022717 (7,102.2717ms)
Time in HW queue: 102639 (10.2639ms)
Execution time: 50685 (5.0685ms)
Packet Status: Completed
Queue Packet: Dma Size (bytes): 1392
Queue Packet: Number of allocations referenced: 0
Queue Packet: Number of patch locations: 0

Allocation References: zero entries
------------------------------------------------------------------------------------------------------------------------
below is one packet in simpleencode.exe process device context

Creation Time: 70881265 (7,088.1265ms)

Standard queue packet
Submission Sequence: 987
SubmissionTime: 70881265 (7,088.1265ms)
CompletionTime: 71022784 (7,102.2784ms)
Time in SW queue: 14 milliseconds
Dma size (bytes): 1392
Number of allocations referenced: 0
Number of patch locations: 0

---------- Associated Dma Packet(s) follows -----------
DmaPacketList size=1
Creation Time: 70919954 (7,091.9954ms)
Process (15776) SimpleEncoder.exe
Context: 0xFFFFDA85C4AEFDE0

Standard Dma Packet
Submission fence: 956
SubmittedToHardwareQueueTime: 70920001 (7,092.0001ms)
GpuStartProcessingTime: 70971955 (7,097.1955ms)
CompletedByISRTime: 71022640 (7,102.2640ms)
CompletedByDPCTime: 71022717 (7,102.2717ms)
Time in HW queue: 102639 (10.2639ms)
Execution time: 50685 (5.0685ms)
Packet Status: Completed
Queue Packet: Dma Size (bytes): 1392
Queue Packet: Number of allocations referenced: 0
Queue Packet: Number of patch locations: 0

Allocation References: zero entries

![image](https://user-images.githubusercontent.com/12612758/90366053-6fe33200-e099-11ea-9c52-816455b22b6d.png)


--------------------------------------------------------------------------------------------------------------------------------------
thanks @roman380 .I test with AmaEncode.exe.get the result
H264
1920x1080@120   11.69
1920x1080@144   5.96
2560x1440@60    14.19
2560x1440@72    14.23
2560x1440@90    184.30
2560x1440@120   FAIL
3840x2160@30    33.76
3840x2160@60    FAIL

H265
1920x1080@120   7.20
1920x1080@144   6.59
2560x1440@60    10.08
2560x1440@72    10.04
2560x1440@90    10.02
2560x1440@120   8.36
2560x1440@144   7.98
3840x2160@30    18.36
3840x2160@60    18.37
3840x2160@72    12.79
3840x2160@90    12.47
3840x2160@120   FAIL

**Comment by roman380** [comment]
```
AVC
...
2560x1440@60 14.19
2560x1440@72 14.23
2560x1440@90 184.30
2560x1440@120 FAIL
3840x2160@30 33.76
3840x2160@60 FAIL
...
HEVC
...
2560x1440@144 7.98
...
3840x2160@90 12.47
3840x2160@120 FAIL
```

That is for AMD Radeon RX 5700 the bottleneck for 2560x1440 is close under 90 fps for AVC and above 144 fps for HEVC.

So NVIDIA numbers remain apparently better, esp. for H.264.

**Comment by chllcy** [comment]
@roman380 anything wrong?
why 2560x1440@90  with Average Encoding Time: 184.19 ms ? and it's ok

**Comment by roman380** [comment]
the number is too high because it's on the edge of throughput, the GPU was a bit slower than realtime in encoding so it did not fail but the number is way too high. Note that Video Encoding Benchmark gave you 87 for this mode. So at 90 is is just a bit slower than realtime.

**Comment by chllcy** [comment]
hi @MikhailAMD 
is the latency equal (Time in HW queue) + (Execution time)??
and when I used DVR.exe(DisplayCapture -> Converter -> Encoder),the Execution time go to 10ms+,it's also with h264 encoder.
![image](https://user-images.githubusercontent.com/12612758/90395440-23aee680-e0c7-11ea-91a8-433c0833f6a3.png)

**Comment by MikhailAMD** [comment]
Several random topics:
- Repeat: RX 5700 performance for H264 and H265 is equal, probably test sets different parameters or defaults are different. 
 - @chllcy Latency: yes and no. If an application submit frames ASAP, the frames will be accumulated in two queues: SW and HW. SW queue is several frames length. This is what you see in the third device context. HW queue is 2 frame length. GPUVIEW reports for HW queue Video Encode wait plus execution. In this ASAP regime the total latency will be bigger then what you see in GPUVIEW HW queue. 
- The latency in the ASAP mode is what you can see in SimpleEncoder
- If you want to minimize the latency in scenarios like game streaming or remote desktop you would have to pace submission to avoid frame accumulation in the queues . Then the time measured on CPU will be close to GPU jobs in GPUVIEW.
- Note that in DX3D11 synchronization is done under the hood. If you have extensive rendering, the result is submitted to color conversion and then to the encoder without any waits on CPU, the encoder will wait till all related GPU jobs are done. This could lead to wrong measurements on CPU side: time will include render and / or color conversion time.

**Comment by roman380** [comment]
It's not clear how H.264/H.256 throughput can be equal, in what sense exactly. These are different physical circuitry, so how they can be strictly equal, then the configuration options are different. The runtime data clearly show a different picture. In my app I am pushing input maintaining fixed frame rate, not ASAP and the numbers are still aligned with the other app.

In my test my in input is originally RGB32 and loads the GPU with conversion to GPU, but it's equal for the two codecs.

These 5700 numbers above are also correlating well with other AMD GPUs showing slightly better performance with H.265. I assume the two ASICs are balanced to show similar performance but why this has to be equal. Also it is common sense to let H.265 be a bit more performant because it is likely to be used for higher resolution, and this is what is effectively happening.

**Comment by MikhailAMD** [comment]
I believe you test on RX 570. True, in that card H264 and H265 have diffrent performance. Of course the parameters should match to compare. If you set low latency mode to true, it doesn't matter if you use ASAP or on-in-one-out style as long as in measurements you take in account possible latency due to the queues.

**Comment by roman380** [comment]
Indeed performance varies across GPUs. However RX 5700 numbers are above and they don't show similar performance(even though they are closer). 

To mention some more examples:

This one shows more or less comparable performance.

AMD Radeon Pro 5500M 

These have H.265/HEVC somewhat more performant.

Radeon RX 560 Series
Radeon RX 570 Series

This has H.265/HEVC apparently more performant.

Radeon RX Vega M GH Graphics

**Comment by chllcy** [comment]
thanks @MikhailAMD 
I had find the key parameter is AMF_VIDEO_ENCODER_FRAMESIZE. without set it,the encode time go up to 11ms.and add it,it will go down to 5ms+.
now I used AMF_VIDEO_ENCODER_USAGE_ULTRA_LOW_LATENCY, one thread submitinput(encoder), another thread queryout.

`		printf("encode out1 %lld, %x\n", amf_high_precision_clock(), std::this_thread::get_id());
        AMF_RESULT res = AMFComponentElement::QueryOutput(ppData);
		printf("encode out2 %lld, %d, %d, %x\n", amf_high_precision_clock(), res, *ppData != NULL, std::this_thread::get_id());
		
		`
--------------------------------------
the log below
encode out1 8153527, d374
encode out2 8228862, 0, 1, d374
encode out1 8229721, d374
encode out2 8231277, 0, 1, d374

**it used 7ms to QueryOutput data**,and then another frame come out follow.
Any suggestions？the gpu do encoder and convert simultaneously In different threads

**Comment by MikhailAMD** [comment]
The FRAMESIZE parameter changes output resolution and therefore time to encode. Is it what you want?

Based on AMFComponentElement use you are not using SimpleEncoder but some other sample code. The default mode of AMFComponent::QueryOutput() from enoder is polling mode. It just checks if there is some output and returns. It should take about 0.2-0.5 ms depend on output buffer size and availability. There something wrong with the calling code. You may block DX device or have some sleep. Hard to tell without seen the full code.

**Comment by chllcy** [comment]
yes, above code from AMF DVR sample, and I modified a bit.
There is no code between the two print logs and QueryOutput。It is normal most of the time(for about 5ms to get next frame). occasionally abnormal.
you mentioned DX device，is it  DeviceDX11 m_deviceDX11 ? and I had used amf::AMF_MEMORY_DX11.

**Comment by MikhailAMD** [comment]
Access to DX11 device is protected/serialized by calls to AMFContext::LockDX11/UlockDX11 which is usually wrapped into AMFDX11Locker class. But this is only guess.

It should not be delayed for 5 ms.

Another possiblity: you have some intensive GPU rendering on PC and you are using AMF color converter, explicitly or inside the encoder. In this case during the conversion the converter has to wait for GPU tasks to complete before doing the conversion and it will internally block DX11 device inside his QueryOutput call. This in turn would block encoder's QueryOutput.
