### ISSUE TITLE
DirectX11 leaks?

### ISSUE THREAD

**Issue by smourier** [GPUOpen-LibrariesAndSDKs/AMF#228]
Hi,

I have a Radeon 5600 XT card, using the latest drivers 20.8.3.

AMF version (header) : 1.1.16.0
AMF version (runtime): 1.1.17.0

I use the SimpleEncoder sample with small changes:

a) I change DX9 to DX11

    static amf::AMF_MEMORY_TYPE memoryTypeIn  = amf::AMF_MEMORY_DX11; instead of DX9

b) I declare this in the beginning:

    ID3D11Debug* dxdebug = NULL;
    ID3D11Device* dxdevice = NULL;
    ID3D11DeviceContext* deviceContext = NULL;

c) Add this to create our own device and use it in AMF:

    DWORD flags = D3D11_CREATE_DEVICE_BGRA_SUPPORT;
        flags |= D3D11_CREATE_DEVICE_VIDEO_SUPPORT;
        flags |= D3D11_CREATE_DEVICE_DEBUG;

    D3D_FEATURE_LEVEL level;
    D3D11CreateDevice(NULL, D3D_DRIVER_TYPE_HARDWARE, NULL, flags, NULL, 0, D3D11_SDK_VERSION, &dxdevice, &level, &deviceContext);
    dxdevice->QueryInterface(&dxdebug);
    res = context->InitDX11(dxdevice); pass our device

d) Add this to the end, 

    g_AMFFactory.Terminate();
    // add this after terminate
    dxdevice->Release();
    deviceContext->Release();
    dxdebug->ReportLiveDeviceObjects(D3D11_RLDO_DETAIL);

The whole program runs fine, but then in the end, `ReportLiveDeviceObjects` outputs this:

```
D3D11 WARNING: Live ID3D11Device at 0x0000019D3016C5B0, Refcount: 2 [ STATE_CREATION WARNING #441: LIVE_DEVICE]
D3D11 WARNING: 	Live ID3D11Context at 0x0000019D3016E5E0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #2097226: LIVE_CONTEXT]
D3D11 WARNING: 	Live ID3DDeviceContextState at 0x0000019D3018EDA0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #3145742: LIVE_DEVICECONTEXTSTATE]
D3D11 WARNING: 	Live ID3D11BlendState at 0x0000019D3011D0F0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #435: LIVE_BLENDSTATE]
D3D11 WARNING: 	Live ID3D11DepthStencilState at 0x0000019D301543B0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #436: LIVE_DEPTHSTENCILSTATE]
D3D11 WARNING: 	Live ID3D11RasterizerState at 0x0000019D3019A100, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #437: LIVE_RASTERIZERSTATE]
D3D11 WARNING: 	Live ID3D11Sampler at 0x0000019D3019A300, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #434: LIVE_SAMPLER]
D3D11 WARNING: 	Live ID3D11Query at 0x0000019D301AED60, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #438: LIVE_QUERY]

```
There seems to be some DirectX leaks. Am I doing any mistake here?
Thanks

**Comment by MikhailAMD** [comment]
I did the same experiment and got the same result. Then I did this:
- Added dxdebug->Release() after ReportLiveDeviceObjects call
- put a breakpoint on dxdevice->Release() line
- once the breakpoint hit, switched the debugger to disassembler
- Entered two levels down through virtual call to the real implementation in the d3d_SDKlayers.dll
- Put a breakpoint there
- Hit Continue
- The breakpoint in disassembler stopped two more times - in both cases called from dxdebug->Release() from DXGIDebug.dll

Conclusion: two references on D3D11 device object are hold inside DXGI debug code  - not a real leak.
