### ISSUE TITLE
AMF Encoders are broken in ffmpeg 4.3.1 and newer release

### ISSUE THREAD

**Issue by jindal1979** [GPUOpen-LibrariesAndSDKs/AMF#229]
AMF encoders are not accepting DXVA2_VLD or D3D11 surface as input. I throws error:

[h264_amf @ 0000020dd0af2e00] Format dxva2_vld is not supported

It was working in earlier ffmpeg 4.2 versions.  Kindly resolve it.

**Comment by MikhailAMD** [comment]
What command line are you using? DXVA2 is **decoder** acceleration spec. https://docs.microsoft.com/en-us/windows/win32/medfound/about-dxva-2-0
Encoder supports NV12 D3D11 textures as input.

**Comment by jindal1979** [comment]
The following command works fine on ffmpeg version 4.2.0

ffmpeg.exe -y -hwaccel dxva2 -hwaccel_output_format dxva2_vld -extra_hw_frames 16 -i input.mp4 -c:a aac -b:a 192k -ac 2 -ar 44100 -c:v hevc_amf -profile:v main -level 51 -usage 0 -quality 1 -b:V 4000k  output.mp4

But with ffmpeg 4.3.1 it throws following error:
[h264_amf @ 0000020dd0af2e00] Format dxva2_vld is not supported

Let me if the dxva2_vld support is no longer valid for AMF encoders..

**Comment by MikhailAMD** [comment]
I will ask some people to check why the behavior has been changed, but if you just remove  "-hwaccel_output_format dxva2_vld" from your CMD it will work as before.

**Comment by jindal1979** [comment]
Without "-hwaccel_output_format dxva2_vld" it works however the transcoding efficiency reduces by 1/5, therefore making it unusable.

**Comment by MikhailAMD** [comment]
OK, people are looking into this. Thanks.

**Comment by OvchinnikovDmitrii** [comment]
> AMF encoders are not accepting DXVA2_VLD or D3D11 surface as input. I throws error:
> 
> [h264_amf @ 0000020dd0af2e00] Format dxva2_vld is not supported
> 
> It was working in earlier ffmpeg 4.2 versions. Kindly resolve it.

Hi!
This patch should solve the problem. I will send it to ffmpeg-dev in the next few days.

[0001-lavc-amfenc-HWConfig-for-amf-encoder.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/5332411/0001-lavc-amfenc-HWConfig-for-amf-encoder.zip)

**Comment by OvchinnikovDmitrii** [comment]
I sent the corresponding patch to ffmpeg dev. https://patchwork.ffmpeg.org/project/ffmpeg/patch/20201015001625.32832-1-ovchinnikov.dmitrii@gmail.com/

**Comment by MikhailAMD** [comment]
There is no reaction from ffmpeg so far. @jindal1979 : it may help if you open a bug in ffmpeg bug system: https://trac.ffmpeg.org/.

**Comment by jindal1979** [comment]
I have created the ticket at ffmpeg
https://trac.ffmpeg.org/ticket/8953#ticket

**Comment by nyanmisaka** [comment]
> I sent the corresponding patch to ffmpeg dev. https://patchwork.ffmpeg.org/project/ffmpeg/patch/20201015001625.32832-1-ovchinnikov.dmitrii@gmail.com/

The `scale_amf` filter in the patch series failed to convert P010 to NV12.
This CSC pipeline is missing from AMF converter component. Still needs to use software scaler such as `scale` or `zscale`.

**Comment by MikhailAMD** [comment]
Yes, this conversion is missing at this point. Working on it.

**Comment by nyanmisaka** [comment]
> Yes, this conversion is missing at this point. Working on it.

Hope it won't take too long. https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/152

HEVC Main10 and P010 output are also missing in `hevc_amf` encoder on RDNA1(VCN 2.0) and later. But are available on VAAPI encoder.

**Comment by jindal1979** [comment]
great 👍
