### ISSUE TITLE
Video Encode API: Encoder doesn't return data after a while

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#23]
Basically the Encoder will stop returning valid information for frames after a while, rendering a 2 hour 20 minute recording to be only 800 mb big - because it only contains information for 20 minutes and 48 seconds. No player can play this file back properly after a the ~20 minute mark.

This was first reported to me by ball2hi on obsproject.com and has now been reproduced by me. Perhaps some obvious error can be spotted that I didn't see. Dump will be provided once I figure out how to spot this issue actually happening before i stop encoding.

### Debug Data:
* [Project Code](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/commit/3fc72dbe4106dbf0cceefc6cb948bf586f70ddb4)
* Recording & Log: [xaymar.com](http://cdn.xaymar.com/private/2016/09/2016-09-15%2020-48-56.7z)
* Recording, Log & Dump: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/23#issuecomment-247543957

### Attempted Solutions:
* Extract & Remux using FFMPEG: **Failed.** (Only recovered 20:48 of Video.)

**Comment by Xaymar** [comment]
This could be a VCE3 exclusive issue (R9 285, R9 380, RX 4XX, Fury, and other similar cards).

Another set of Debug Data:
* Recording: http://cdn.xaymar.com/private/2016/09/2016-09-16%2008-43-22_Video.7z
* Log: http://cdn.xaymar.com/private/2016/09/2016-09-16%2008-43-22_Log.7z
* Dump: http://cdn.xaymar.com/private/2016/09/2016-09-16_08-43-22_Dumps.7z (Error "Error saving dump. Invalid pointer" appeared during saving)

**Comment by Roph** [comment]
Well definitely not always occurring on my 4xx; I streamed over 9 hours non-stop at 720p30 with no problem. 

For me it's been perfect, is there some specific stuff you want me to try to reproduce it?

**Comment by Xaymar** [comment]
This is the profile i tested with that had the issue in recordings: 
[AMF_Issue__Encoder_Stuck.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/478827/AMF_Issue__Encoder_Stuck.zip)

**Comment by Xaymar** [comment]
I'm not sure what the actual issue is here, since it seems to only affect recorded files. It might be an issue with muxing, in which case this issue is invalid. I'll have to test around.

**Comment by Xaymar** [comment]
Muxing issue, streaming works fine. Closing this as invalid.
