### ISSUE TITLE
documentation or overview which hardware supports which features

### ISSUE THREAD

**Issue by arancino1** [GPUOpen-LibrariesAndSDKs/AMF#230]
Is there any documentation giving a brief overview which hardware (Polaris, Vegas etc.) supports which AMF-related features (number encoding/decoding session, HEVC 10bit, 4:2:2, B-frames etc.)?

**Comment by cs9kc** [comment]
Something like this would be VERY useful for folks to have now that AMD Radeon cards have the potential to be in the hands of many more content creators.  I didn't mind going through the code and documents on this very github to get the information for myself, but I don't expect that the average user would be inclined to do so on their own volition.

Likewise, it would be nice to have documentation for each new iteration of the ASIC and/or VCN version, as trying to find what, if any, new features came with VCN 3.0 on RDNA2 has been a massive exercise in futility.  The documents on this github and the table on wikipedia aside, there is -no- information out there other than the promise that AV1 hardware decoding would be included with VCN 3.0.  That said, hardware AV1 decoding works nicely in Edge/Chrome with Youtube and Adrenaline 20.12.1. Thanks for that!

**Comment by Isalight** [comment]
So much time has passed, but AMD still has not created official documentation on video card hardware codecs. You have to look on third-party resources, where information is sometimes different. I don't think it takes a lot of time or work. Please, finally add this following the example of [Nvidia](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new) or [Intel](https://www.intel.com/content/www/us/en/develop/documentation/media-capabilities-of-intel-hardware/top.html).

**Comment by rhutsAMD** [comment]
We appreciate your patience. This information is now available on the Wiki page for [GPU and APU HW Features and Support](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/GPU%20and%20APU%20HW%20Features%20and%20Support).

This is the initial version which we will expand and update regularly.
