### ISSUE TITLE
Calling InitVulkan makes Convert very slow

### ISSUE THREAD

**Issue by maxest** [GPUOpen-LibrariesAndSDKs/AMF#233]
I modified simple decoder sample a little bit and noticed something weird.

I modified the sample, for simplicity, to be single-threaded and go like this:
```
CreateBufferFromHostNative

SubmitInput
QueryOutput

Output -> Convert( amf::AMF_MEMORY_HOST )
```
I measured the time of Convert. It turned out that depending on whether I call InitDX11 or InitVulkan, performance of that operation can vary greatly. There are these options:
1. Call InitDX11 (with NULL argument). This gives me Convert time of ~4 ms.
2. Not call any Init***. Thi gives me Convert time of ~6 ms.
3. Call InitVulkan. Convert time is... ~180 ms!

What could be the reason for that?

**Comment by MikhailAMD** [comment]
- ensure you run the latest driver.
- Did you just change from InitDX11 to InitVulkan or changed static variable at the top with memory type?
- is it 180 ms for every frame or for first frame only?
- What is nonmodified sample with memory type VULKAN prints on your setup at the end? 
- share your modifications and measurements.

**Comment by maxest** [comment]
1. I run an alienware laptop with natively has an NVIDIA gpu, so I connected an AMD card using alienware graphics amplifier. This configuration has already caused me some problems in the past, where some Vulkan demos did exhibit pixels flickering which did not take place on a desktop computer. But I have the latest possible drivers.
Version: 27.20.12029.1000
Date: 9/9/2020

2. I changed the static variable at the top, but as far as I can see this variable is only used on switch to call Init***.

3. It's the average. Here are timings (in ms) for the first couple of frames:
> time   114.668999
> time   126.986000
> time   112.704002
> time   115.790001
> time   126.652000
> time   187.492996
> time   186.145004
> time   197.341995
> time   182.901001
> time   220.748993
> time   225.804993
> time   210.858994
> time   186.651001
> time   187.332001
> time   202.988998
> time   185.873001
> time   189.145996

4. I have only now checked that and the DX11 way produces avg time of 2 ms, whereas VULKAN produces ~1.5 ms. BUT... WaitDecoder only copies a 2x2 grid of pixels. This one is fast. But when I measured call to Convert under the bWriteToFile if-statement the timing is pretty much what I get in my modified sample.

5.  Here are my modifications.
[decoder.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/5510502/decoder.zip)
I decode each frame directly from my pre-recorded frames dumped from our software that produced the frames, so I skipped using the parser.

**Comment by MikhailAMD** [comment]
OK, I've reproduced the issue, we are looking into this.

**Comment by maxest** [comment]
Cool. Thank you.

**Comment by MikhailAMD** [comment]
Could you please retest with the latest public driver? Should be fixed.
