### ISSUE TITLE
Full Color Range undocumented

### ISSUE THREAD

**Issue by e00E** [GPUOpen-LibrariesAndSDKs/AMF#234]
In `ColorSpace.h` in `AMF_VIDEO_CONVERTED_COLOR_PROFILE_ENUM` there are entries for `FULL_601` and `FULL_709`.

However in the pdf documentation these values are never mentioned. In fact the whole `AMF_VIDEO_ENCODER_HEVC_I(NPUT|OUTPUT)_COLOR_PROFILE` from `VideoEncoderHEVC.h` is never mentioned. This makes it unclear whether these color spaces are supported and how to properly set them.

**Comment by MikhailAMD** [comment]
Thanks for letting know. We will update the documentation. In the SDR case you can set only input profile, describing your input.

**Comment by e00E** [comment]
The documentation does not state that for SDR you can only set the input profile. So I'm not sure if the documentation is correct or your comment (but has been a year).

The PDF still does not document AMF_VIDEO_ENCODER_HEVC_NOMINAL_RANGE.

**Comment by rhutsAMD** [comment]
The doc has been updated and will be publicly visible in a future AMF release. In the meantime, the new note can be referenced as follows:

**Name:**
`AMF_VIDEO_ENCODER_HEVC_NOMINAL_RANGE`

**Values:**
`AMF_VIDEO_ENCODER_HEVC_NOMINAL_RANGE_STUDIO`, `AMF_VIDEO_ENCODER_HEVC_NOMINAL_RANGE_FULL`

**Default Value:**
`AMF_VIDEO_ENCODER_HEVC_NOMINAL_RANGE_STUDIO`

**Description:**
Sets the minimum and maximum pixel values that can be encoded. The nominal range refers to the range of pixel values that represent the full dynamic range of a video signal.
