### ISSUE TITLE
Is it possible to encode data from AMFBufferPtr?

### ISSUE THREAD

**Issue by maxest** [GPUOpen-LibrariesAndSDKs/AMF#236]
In the simple encoder sample data submitted to the encoder are in AMFSurfacePtr. I have tried submitting data stored in AMFBufferPtr (which I created with context->AllocBuffer and specifying the appropriate memory type) but it crashes.

The reason I wanted to submit a buffer is that our pipeline generates NV12-format image in form of a linear buffer (first width*height linear luma, then UV intertwined linear as well). We could generate an actual Vulkan image and write to it and call CreateSurfaceFromVulkanNative on it and use that, but I've been wondering if it was possible to submit a buffer to the encoder. That would save us some trouble.

**Comment by MikhailAMD** [comment]
HW encoder works with images only. You would have to allocate Vulkan image using AMF or wrap your image into AMF and write to it from your buffer, maybe with a simple shader.

**Comment by maxest** [comment]
Got it. We're already, in a shader, writing to VkBuffer. So I'll just add variant that writes to VkImage then.
Thank you for the answer.
