### ISSUE TITLE
SimpleEncoder: A fresh empty project does not work

### ISSUE THREAD

**Issue by maxest** [GPUOpen-LibrariesAndSDKs/AMF#237]
I created an empty C++ project in Visual Studio and copied SimpleEncoder's source code so it's 1-1 match.
When the code calls InitDX11 it spits, to the Output window, the following:
> Exception thrown at 0x00007FFF234B3B29 in ConsoleApplication1.exe: Microsoft C++ exception: _com_error at memory location 0x000000E86ACFB140.

It does not crash the app thought. However, on call to SubmitInput I see this in the Output:
> 2020-11-10 20:13:26.517     4B48 [AMFEncoderUVE]   Error: ..\..\..\..\..\runtime\src\components\EncoderUVE\EncoderUVEH264Impl.cpp(2197):Assertion failed:Encoder did not get initialized
and SubmitInput returns AMF_NOT_INITIALIZED.

When I call InitDX9 instead of InitDX11 I do not get the former exception, but I still get info about encoder not being initialized.

**Comment by MikhailAMD** [comment]
- What is the full HW setup? - please share log from DXDIAG.exe
- What is your OS?
- Do you by chance run OS in VM?
- What does CapabilityManager sample output to console?

**Comment by maxest** [comment]
Just to reassert this. The base SimpleEncoder works just fine. It's the fresh project that I copied the whole SimpleEncoder's source code to, that does not work.

1. [DxDiag.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/5519753/DxDiag.txt)

2. Windows.

3. No.

4. Can't compile it cause I get:

> fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory (compiling source file ..\common\DeviceDX9.cpp)
> fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory (compiling source file ..\common\DeviceDX11.cpp)
> fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory (compiling source file CapabilityManager.cpp)

**Comment by MikhailAMD** [comment]
1. Could you please clarify your HW: you have m17 laptop which is sold only with RX 5500X . How can you get RX 5700 XT?
2. How do you get inactive NV RTX 2080 device?
3 . For compile issue (atlbase.h): looks like VS cannot find Windows SDK referenced in the sample project. You should install the used version or update the project to a newer version.

**Comment by maxest** [comment]
1. I have M17 with native GeForce 2080 RTX. I have RX 5700 XT connected to the laptop using alienware graphics amplifier.
2. I disabled the NV gpu and Intel one as well in the device manager, so the only gpu that is for instance listed by Vulkan API is 5700 XT.
3. The Windows SDK version I find in the samples is 10.0.17763.0. I don't have that one, I have a newer one - 10.0.18362.0. Do you suggest I need to install 10.0.17763.0 specifically?

**Comment by MikhailAMD** [comment]
You can just change AMF project settings in VS to your SDK - it is newer.

**Comment by maxest** [comment]
Of course, I did change that version but I still get the errors.

**Comment by MikhailAMD** [comment]
I checked on my system: atlbase.h should come from VS installation. Here is my path: 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include

**Comment by MikhailAMD** [comment]
Is it possible that you did selective VS install?

**Comment by maxest** [comment]
I changed include of:
<atlbase.h> to:
#include "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/atlbase.h" (the only atlbase I have)
and now I get
fatal error C1083: Cannot open include file: 'atldef.h': No such file or directory (compiling source file ..\common\DeviceDX9.cpp)
in atlbase.h

But is this really relevant? SimpleEncoder sample works. A fresh project with the same source does not. It must be a problem with some project settings, not related to caps of the device cause the device does support the features as SimpleEncoder works.

**Comment by MikhailAMD** [comment]
I missed the part that SimpleEncoder sample does work. There are no special settings in the project. 
AMF runtime works even with other compilers like GCC in ffmpeg.
So it is really something bad with general project settings. Or Windows disabled access to D3D to your new app.

**Comment by maxest** [comment]
Ok. So... two things.

1. I created another fresh project. Played with some project settings and other shenanigans. Ultimately I had two fresh projects where this error would show up in only one of them. I don't know where it's coming from but I remember I had something similar in one of my D3D11 projects. It's "probably" harmless.

2. This error actually does not impact the assertion that occurs on SubmitInput. This one is on me is I had forgotten to call Init on the encoder component...
