### ISSUE TITLE
Target bit rate cannot exceed 100Mbps for HEVC encoding

### ISSUE THREAD

**Issue by Masa-tam** [GPUOpen-LibrariesAndSDKs/AMF#240]
GPU:RX 5500 XT
OS:Windows10 x64 Pro Version 20H2 OS Build 19042.685
Driver:20.11.2

When I modified SimpleEncoderC a little and tried to encode at HEVC L5.1 High Tier 3840x2160 60fps 101Mbps, it aborted with the following error.

SimpleEncoderC.c(189):AMF_ERROR 5 : AMF_OUT_OF_RANGE: SetProperty(AMF_VIDEO_ENCODER_HEVC_TARGET_BITRATE, 101000000) failed

The build is Visual Studio 2019 Version 16.8.3, and it occurs in Release x64 build.

The patch file for the changes is attached.

[SampleEncoderC.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/5713426/SampleEncoderC.zip)

**Comment by MikhailAMD** [comment]
With more tracing enabled you would see that encoder fails to set AMF_VIDEO_ENCODER_HEVC_VBV_BUFFER_SIZE. To get around this, you should set AMF_VIDEO_ENCODER_HEVC_VBV_BUFFER_SIZE to some value before setting bitrate. Note, that the maximum is 100Mbits. If it is not default, then when you set bitrate, encoder will not try to guess VBV buffer size. 
We should add something to avoid this in the future.
Thanks,

**Comment by MikhailAMD** [comment]
Does it help you?

**Comment by Masa-tam** [comment]
Sorry, I was on winter vacation.

Thank you very much for your advice.
I was able to avoid the error by setting the VBV buffer first.
