### ISSUE TITLE
How do I import an NV12 file and encode it

### ISSUE THREAD

**Issue by liuzhongwen-smq** [GPUOpen-LibrariesAndSDKs/AMF#242]
I want to decode the nV12 file from the decode sample, how can I pass the file in? I don't see where the file is put into the hardware. I am a novice programmer.

**Comment by liuzhongwen-smq** [comment]
I see that there is inputfile in the decode sample but there is no inputfile in the encode sample. How can I import the QueryOutput of the decode sample into the encode sample SubmitInput.

**Comment by liuzhongwen-smq** [comment]
`res = context->AllocSurface(memoryTypeIn, formatIn, widthIn, heightIn, &surfaceIn);
			
			FillSurfaceDX11(context, surfaceIn);`
What should I do to pass the content I want to code to Surfacein

**Comment by liuzhongwen-smq** [comment]
`res = context->AllocSurface(memoryTypeIn, formatIn, widthIn, heightIn, &surfaceIn);`
`FillSurfaceDX11(context, surfaceIn);`
What should I do to pass the content I want to code to Surfacein

**Comment by MikhailAMD** [comment]
If your memory with NV12 is in one blob, check CreateSurfaceFromHostNative().  If not, use AllocSurface(AMF_MEMORY_HOST...), then surface->GetPlaneAt(0 or 1)->GetNative() - fill returned pointers for plane 0 and plane 1 line by line. Don't forget about line alignment: GetHPitch(). and UV plane is half with of Y plane.

**Comment by liuzhongwen-smq** [comment]
https://user-images.githubusercontent.com/75414106/102839469-98aa7800-443b-11eb-8a66-904b64041ffb.mp4

sorry, Sir.I need't to fill color in what I'm coding, I just want to code my content, however, I only get the MP4 file from our sample encode. Why don't I see fileNameIn in the sample encode as in the sample decode , I want to convert an NV12 file to an H264 file. What should I do?

**Comment by liuzhongwen-smq** [comment]
https://user-images.githubusercontent.com/75414106/102840468-e88a3e80-443d-11eb-8517-88134bfbffe5.mp4

sorry, Sir.I need't to fill color in what I'm coding, I just want to code my content, however, I only get the MP4 file from our sample encode. Why don't I see fileNameIn in the sample encode as in the sample decode , I want to convert an NV12 file to an H264 file. What should I do?

**Comment by liuzhongwen-smq** [comment]
I convert an H264 file into an nv12 file by  the sample decode, then, I want to convert the nv12 file into an H264 file, but without the fileNameIn in the sample encode, I was a little confused.

**Comment by liuzhongwen-smq** [comment]
this is my test code 
`int main(int argc, char* argv[])
{
	system("pause");
	AMF_RESULT              res = AMF_OK; 

	res = g_AMFFactory.Init();              
	if (res != AMF_OK){
		wprintf(L"AMF Failed to initialize");
		return 1;
	}
	
	g_AMFFactory.GetTrace()->SetWriterLevel(AMF_TRACE_WRITER_DEBUG_OUTPUT, AMF_TRACE_TRACE);

	::amf_increase_timer_precision();       

	amf::AMFContextPtr      context;
	amf::AMFComponentPtr    decoder;
	amf::AMFDataStreamPtr   datastream;
	BitStreamParserPtr      parser;	

	res = amf::AMFDataStream::OpenDataStream(fileNameIn, amf::AMFSO_READ, amf::AMFFS_SHARE_READ, &datastream);
	if (datastream == NULL){
		wprintf(L"file %s is missing", fileNameIn);
		return 1;
	}

	res = g_AMFFactory.GetFactory()->CreateContext(&context);
    res = context->InitDX11(NULL);

	BitStreamType bsType = BitStreamH264AnnexB;
	parser = BitStreamParser::Create(datastream, bsType, context);

	wchar_t fileNameOutWidthSize[2000];
	swprintf(fileNameOutWidthSize, amf_countof(fileNameOutWidthSize), fileNameOut, parser->GetPictureWidth(), parser->GetPictureHeight());

	res = g_AMFFactory.GetFactory()->CreateComponent(context, AMFVideoDecoderUVD_H264_AVC, &decoder);

	res = decoder->SetProperty(AMF_TIMESTAMP_MODE, amf_int64(AMF_TS_DECODE)); 

	amf::AMFBufferPtr buffer;
	context->AllocBuffer(amf::AMF_MEMORY_HOST, parser->GetExtraDataSize(), &buffer);
	memcpy(buffer->GetNative(), parser->GetExtraData(), parser->GetExtraDataSize());

	decoder->SetProperty(AMF_VIDEO_DECODER_EXTRADATA, amf::AMFVariant(buffer));

	res = decoder->Init(formatOut, parser->GetPictureWidth(), parser->GetPictureHeight());

	PollingThread1 thread1(context, decoder, fileNameOutWidthSize);
	thread1.Start();

	amf::AMFDataPtr data;
	bool bNeedNewInput = true;

	while (submitted < frameCount || frameCount < 0)
	{
		if (bNeedNewInput){
			data = NULL;
			res = parser->QueryOutput(&data);
			if (res == AMF_EOF || data == NULL){
				break;
			}
		}
		amf_pts start_time = amf_high_precision_clock();
		data->SetProperty(START_TIME_PROPERTY, start_time);

		res = decoder->SubmitInput(data);  
		if (res == AMF_NEED_MORE_INPUT){
			
		}
		else if (res == AMF_INPUT_FULL || res == AMF_DECODER_NO_FREE_SURFACES){ 
			bNeedNewInput = false;       
			amf_sleep(1);
		}
		else{ 
			submitted++;
			bNeedNewInput = true;
		}
	}

	res = decoder->Drain();  
	thread1.WaitForStop();

	//---------------------------------------------------------------------------------------------
	amf::AMFTraceEnableWriter(AMF_TRACE_WRITER_CONSOLE, true);         
	amf::AMFTraceEnableWriter(AMF_TRACE_WRITER_FILE, true);

	amf::AMFComponentPtr encoder;
	amf::AMFSurfacePtr surfaceIn;  
 
	PrepareFillFromHost(context);

	res = g_AMFFactory.GetFactory()->CreateComponent(context, pCodec, &encoder); 

	res = encoder->SetProperty(AMF_VIDEO_ENCODER_USAGE, AMF_VIDEO_ENCODER_USAGE_TRANSCONDING);
	if (bMaximumSpeed){
		res = encoder->SetProperty(AMF_VIDEO_ENCODER_B_PIC_PATTERN, 0); 
		res = encoder->SetProperty(AMF_VIDEO_ENCODER_QUALITY_PRESET, AMF_VIDEO_ENCODER_QUALITY_PRESET_SPEED);
	}
	res = encoder->SetProperty(AMF_VIDEO_ENCODER_TARGET_BITRATE, bitRateIn);  
	res = encoder->SetProperty(AMF_VIDEO_ENCODER_FRAMESIZE, ::AMFConstructSize(widthIn, heightIn)); 	
	res = encoder->SetProperty(AMF_VIDEO_ENCODER_FRAMERATE, ::AMFConstructRate(frameRateIn, 1)); 

	res = encoder->Init(formatIn, widthIn, heightIn);  

	PollingThread2 thread2(context, encoder,fileNameOut_h264 );
	thread2.Start();

	submitted = 0; 
	while (submitted < frameCount)
	{
		if (surfaceIn == NULL)
		{
			surfaceIn = NULL;

			res = context->AllocSurface(memoryTypeIn, formatIn, widthIn, heightIn, &surfaceIn);
			
			FillSurfaceDX11(context, surfaceIn);  
		}

		amf_pts start_time = amf_high_precision_clock();
		surfaceIn->SetProperty(START_TIME_PROPERTY, start_time);

		res = encoder->SubmitInput(surfaceIn);  
		if (res == AMF_INPUT_FULL) // handle full queue
		{
			amf_sleep(1); // input queue is full: wait, poll and submit again
		}
		else
		{
			surfaceIn = NULL;
			submitted++;  
		}
	}
	while (true)
	{
		res = encoder->Drain();
		if (res != AMF_INPUT_FULL) // handle full queue
		{
			break;
		}
		amf_sleep(1); // input queue is full: wait and try again
	}
	thread2.WaitForStop();
	//---------------------------------------------------------------------------------------------
	// cleanup in this order
	data = NULL;
	decoder->Terminate();
	decoder = NULL;
	parser = NULL;
	datastream = NULL;
	
	pColor1 = NULL;
	pColor2 = NULL;
	surfaceIn = NULL;       
	encoder->Terminate();
	encoder = NULL;         

	context->Terminate();
	context = NULL; // context is the last

	g_AMFFactory.Terminate();
	system("pause");
	return 0;
}`

**Comment by liuzhongwen-smq** [comment]
Can I understand the method in the sample as YUV pictures pasted into Dx11? I want to ask if there is a way to enter data directly

**Comment by liuzhongwen-smq** [comment]
i had use CreateSurfaceFromHostNative(),but can't encoder->SubmitInput(surfaceIn) ,what should i do?
`if (surfaceIn == NULL)
		{
			surfaceIn = NULL;

			//res = context->AllocSurface(memoryTypeIn, formatIn, widthIn, heightIn, &surfaceIn);			
			res = context->CreateSurfaceFromHostNative(formatIn, widthIn, heightIn, 0, 0, buffer, &surfaceIn, NULL);
			FillSurfaceDX11(context, surfaceIn);  //对输入的数据进行渲染处理
		}
		amf_pts start_time = amf_high_precision_clock();
		surfaceIn->SetProperty(START_TIME_PROPERTY, start_time);
		res = encoder->SubmitInput(surfaceIn);`

**Comment by MikhailAMD** [comment]
In general, it should work. The encoder internally will call surface->Convert(AMF_MEMORY_DX11) , which will transfer memory form HOST to DX11 texture. You can call it yourself before submission.  
If you see a failure please check debug output for errors.

**Comment by liuzhongwen-smq** [comment]
Thank you very much, Mikhail. I have solved the problems related to encoding and decoding. Now I want to build a new project. What problems should I pay attention to? Such as libraries, header files, etc，can you give me some information?

**Comment by MikhailAMD** [comment]
Too broad question. Check AMF samples, we tried to cover many use cases. And this site is always open for questions.
