### ISSUE TITLE
CaptureVideo simple

### ISSUE THREAD

**Issue by liuzhongwen-smq** [GPUOpen-LibrariesAndSDKs/AMF#246]
How can I debug the CaptureVideo sample correctly? I can't  break in, Does the sample have requirements for the hardware configuration of the graphics card result to i couldn't get into the program？

**Comment by MikhailAMD** [comment]
I am not sure I understand. As any C/C++ program this sample is built in Visual Studio with PDBs and can be debugged. If you cannot set breakpoints, your PDBs don't match the binaries and code. 
If you capture a full screen game you may choose to put Visual Studio window into a secondary monitor so it would less interfere with the game.

**Comment by liuzhongwen-smq** [comment]
thanks
