### ISSUE TITLE
Does new driver for RX5700 AMD vce encoder support HDR metadata property

### ISSUE THREAD

**Issue by vetsad** [GPUOpen-LibrariesAndSDKs/AMF#247]
I want to use VCE to record HDR video by RX5700.

After I install Adrenalin 2020 Edition 20.12.1 Optional (WHQL)  to update my driver, I use AMF_VIDEO_ENCODER_HEVC_INPUT_HDR_METADATA property to set metadata in my software, but I find the output video without metadata. 

It was worked before when I installed Adrenalin 2020 Edition 20.9.1 Recommended (WHQL).

And I also notice the newest SDK document remove AMF_VIDEO_ENCODER_HEVC_INPUT_HDR_METADATA  property.

Does it not support anymore?
How do I record HDR with metadata information?

**Comment by MikhailAMD** [comment]
This feature has was changed. You should assume following logic: all color related parameters with "INPUT" in the property name describe input surface for internal color converter (normally some variant of RGBA). All parameters with "OUTPUT" describe output surface of the internal converter and the same time applied to the stream. So please use AMF_VIDEO_ENCODER_HEVC_OUTPUT_HDR_METADATA. Sorry for inconvenience.

**Comment by vetsad** [comment]
Hi MikhailAMD,
Thanks for your reply. But I tried to set AMF_VIDEO_ENCODER_HEVC_OUTPUT_HDR_METADATA, it also did not worked.

**Comment by MikhailAMD** [comment]
Looked a little bit more. Will try to push the fix into the driver ASAP. Please continue use  **AMF_VIDEO_ENCODER_HEVC_INPUT_HDR_METADATA**.

**Comment by vetsad** [comment]
I see. Thank you.

**Comment by MikhailAMD** [comment]
This should be fixed with the latest driver release (21.6.1)

**Comment by rhutsAMD** [comment]
Closing as fixed starting in driver release 21.6.1
