### ISSUE TITLE
AMF Failed to initialize 1

### ISSUE THREAD

**Issue by henrypark77** [GPUOpen-LibrariesAndSDKs/AMF#248]
GPU : Radeon Pro W5700
OS : CentOS 7.6
Driver : amdgpu-pro-19.50-1011208-rhel-7.7

if i run sample encoder then error occur at initialize.

how can i fix it?

**Comment by MikhailAMD** [comment]
What is in the tracing? Did you install Vulkan Pro and disable Vulkan Mesa?

**Comment by henrypark77** [comment]
vulkan installed 1.1.97.

----
vulkan-filesystem-1.1.97.0-1.el7.noarch
vulkan-1.1.97.0-1.el7.x86_64
vulkan-devel-1.1.97.0-1.el7.x86_64
----

how can disable Vulkan Mesa? 
Sorry, i'm a beginner. can you explain in detail?

**Comment by MikhailAMD** [comment]
Driver installation Pro variant: https://amdgpu-install.readthedocs.io/en/latest/install-installing.html#installing-the-pro-variant

Selecting the driver: in general drivers are provides in radeon_icd.x86_64.json file and you may want to exclude mesa version. Here is the link with discussion: https://wiki.archlinux.org/index.php/Vulkan

**Comment by henrypark77** [comment]
i can't find radeon_icd.x86_64.json file. 
/usr/share/vulkan/icd.d/ directory empty.

**Comment by MikhailAMD** [comment]
1. Can you check if any Vulkan driver is installed?
2. What does AMF sample trace?

**Comment by henrypark77** [comment]
I think this is so file issue.
I can not find the libamdrt64.so file when i check in my system. 
where can i get that file?
or how can is install that file?

**Comment by nyanmisaka** [comment]
amf-amdgpu-pro is not installed by default iirc.
You have to install it manually such as `sudo apt install amf-amdgpu-pro` on ubuntu.

**Comment by MikhailAMD** [comment]
Yep

**Comment by henrypark77** [comment]
I'd like to install the driver on centos, centos Is not support currently?

**Comment by MikhailAMD** [comment]
It is supported. Select your GPU and find driver for your OS: https://www.amd.com/en/support

**Comment by henrypark77** [comment]
What I want is to do Encoding in Centos. By the way, it seems that libamfrt64.so file is not installed when driver is installed in centos. I want to know how to install libamfrt64.so in centos.

**Comment by MikhailAMD** [comment]
Did you install the latest Pro driver and then optional amf-amdgpu-pro package?
What is your Centos version?
https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-45

**Comment by henrypark77** [comment]
OS : CentOS 7.6
I installed driver amdgpu-pro-20.10-1101037-rhel-7.8, amdgpu-pro-19.50-1011208-rhel-7.7, amdgpu-pro-20.45-1188099-rhel-7.9.

**Comment by MikhailAMD** [comment]
The last driver is what you need.  Did you run:
 "sudo apt install amf-amdgpu-pro"
Any errors reported?
After that you should have AMF SO on the system.

**Comment by henrypark77** [comment]
I misunderstood amf-amdgpu-pro as a driver. After installing amf-amdgpu-pro, I checked that the libamfrt64.so file was installed. Thank you.
