### ISSUE TITLE
Request main10 profile support for HEVC encoder

### ISSUE THREAD

**Issue by nyanmisaka** [GPUOpen-LibrariesAndSDKs/AMF#249]
Since HEVC encoder has already support 10bit output on Navi cards, can we have the missing main10 profile in the future?

`AMF_VIDEO_ENCODER_HEVC_PROFILE_MAIN` is the only option for now.

AFAIK main10 profile is supported through VAAPI on Mesa. Would be great if AMF can get the same one.

Thanks in advance!

**Comment by MikhailAMD** [comment]
It is supported. Just set 10 bit encoding via property.

**Comment by nyanmisaka** [comment]
Indeed so! I was misled by the tier from player.
Set to AMF_SURFACE_P010 means main10 regardless of this profile option.

**Comment by fourwhey** [comment]
> It is supported. Just set 10 bit encoding via property.

How would one go about setting this in ffmpeg?

**Comment by MikhailAMD** [comment]
We are working on changes for ffmpeg.
