### ISSUE TITLE
Crash when initializing DirectX11 - Open Broadcaster Software Crash

### ISSUE THREAD

**Issue by Xbye** [GPUOpen-LibrariesAndSDKs/AMF#25]
I posted [this issue](https://obsproject.com/forum/threads/amd-advanced-media-framework-encoder-plugin-for-obs-studio.52305/page-13#post-240165) on the OBS forums and was directed here by Xaymar.

Previous versions of his plugin work, but upon using the most up to date version **RC 4** my OBS crashes. Right before crashing, OBS states _"Encoding overloaded! Consider turning down video settings or using a faster encoding preset."_ Here are some logs:

**OBS Log**: https://gist.github.com/f358c76d6279a2527f2ee2d7a2438245
**Crash Log**: http://pastebin.com/cUnGwHpJ

**Normal OBS Log on RC3**: https://gist.github.com/1a3cd1488d11499432df712b8c9da87e

I have done the following:
- Entered Safemod followed by using DisplayDriverUninstaller to remove AMD files, then reinstalling **16.9.1** on my RX 480.
- Installed some Windows7 updates.
- Reinstalled plugin.

**Comment by Xaymar** [comment]
The crash happens here:

```
08:12:40.642: [AMFTrace] 2016-09-19 08:12:40.603     1CD4 [AMFDeviceDX11Impl]   Error: ..\..\..\..\..\runtime\src\core\DeviceDX11Impl.cpp(162):COM failed, HR = 80070057:CreateNativeSurface - CreateTexture2D failed
08:12:40.642: [AMFTrace] 2016-09-19 08:12:40.603     1CD4 [AMFDeviceDX11Impl]   Error: ..\..\..\..\..\runtime\src\core\DeviceDX11Impl.cpp(200):AMF_ERROR 18 : AMF_DIRECTX_FAILED: CreateNativeSurface(format, width, height, true, (void**)&pSurface)
08:12:40.642: [AMFTrace] 2016-09-19 08:12:40.603     1CD4 [AMFSurfaceImpl]   Error: ..\..\..\..\..\runtime\src\core\SurfaceImpl.cpp(484):AMF_ERROR 18 : AMF_DIRECTX_FAILED: AllocPlanes()- CreateSurface
08:12:40.642: [AMFTrace] 2016-09-19 08:12:40.603     1CD4 [AMFContextImpl]   Error: ..\..\..\..\..\runtime\src\core\ContextImpl.cpp(779):AMF_ERROR 18 : AMF_DIRECTX_FAILED: pSurface->Alloc(type, format, width, height)
```

Which is something that I don't even expect to fail, at least not according to the information given to me.

**Comment by MikhailAMD** [comment]
DX11 on Win 7 has limited capabilities, For example one cannot decode or encode using DX11. So the plug-in must use encoder on DX9. 
I checked plug-in code: Xaymar, please block DX11 for Win 7. Currently it is done in Auto mode only.

**Comment by Xaymar** [comment]
I did that now, so this issue can be closed.

**Comment by MikhailAMD** [comment]
XBye, can we close this issue or there is more to it? Thanks,

**Comment by Xbye** [comment]
@MikhailAMD @Xaymar 

I recently upgraded to Win10 and have no foreseeable interest in going back, so I'll be unable to really test this. I do believe Xaymar fixed the issue by limiting the DX version on Win7 back when I mentioned it though.

**Comment by M4RK22** [comment]
@Xbye Yes, you can close the ticket :smile:
