### ISSUE TITLE
add features: manual matrix + AMF load indicator

### ISSUE THREAD

**Issue by Benman2785** [GPUOpen-LibrariesAndSDKs/AMF#253]
hey, for streaming with OBS it would be nice to manually set custom matrix

also - especially for OBS it would be nice to have an indicator how much load is on AMF: simple would be "traffic light" with green = medium load; yellow = high load; red = risk of encoder overload // or simply give % - with a red warning indicator at over 95%

**Comment by MikhailAMD** [comment]
Load indicator is a question for the plug-in and UI in OBS. The plug-in can monitor encoding time to figure encoder load. BTW: a pull request with new plug-in code has been submitted to OBS. This plug-in was implemented as one-in-one-out. So the input queue is controlled outside of the plug-in or AMF - unlike the older plug-in.
