### ISSUE TITLE
10bit HEVC encoding, Pre-Analysis, Pre-Processing components not supported by VCEEncoder

### ISSUE THREAD

**Issue by NikosDi** [GPUOpen-LibrariesAndSDKs/AMF#254]
Hello.

It seems that all these three AMF features supported by RDNA (Navi) onwards :

a) 10bit HEVC encoding, 

b) Pre-Analysis component, 

c) Pre-Processing component

are not supported by VCEEncoder provided by AMD.

Are you going to add it ?

Especially for 10 bit encoding I think is necessary in order to help developers for an easier use.

**Comment by MikhailAMD** [comment]
All these features, some more, some less, are related to hardware capabilities. VCE is legacy hardware replaced by VCN. VCE doesn't have means to support these features.
The exception is pre-processing. It just a filter, can be used as a separate component with any encoder.

**Comment by NikosDi** [comment]
The word VCEEncoder that I used was probably wrong, because I meant software encoder support by AMD not hardware encoder support.

I got a feedback from a developer that AMD's encoder, probably software sample encoder (?), doesn't support these features.
