### ISSUE TITLE
AMD Radeon Pro V520 H264 encoding issues

### ISSUE THREAD

**Issue by visuall** [GPUOpen-LibrariesAndSDKs/AMF#255]
We are using Amazon AWS g4ad instance which has this card in it. We are building a simple encoding app with AMF and its H264. However we see some issues:

1. B-frames: Although the SDK is not reporting any error when we enable b-frames and the value we set is accepted with AMF_OK the output has no b-frames. At the same time capability manager reports b-frames are not supported. Is it really such high end card not supporting b-frames or there is some other issue?

2. Reference frames: The SDK and the capability manager reports that reference frames are supported. Supported values are between 1 and 16. However no matter what we set the output refs are always set to 1 ( confirmed with Media Info ). The same code works on other low end Radeon card. 

The above results has been confirmed with third party source code base using AMF like ffmpeg.

**Comment by MikhailAMD** [comment]
1. B-frames are not supported in the latest GPUs. Setting non-zero parameter should return error.
2.  There seems a problem in SPS generation in newer GPUs that keeps 1 as number of reference frames. While it doesn't affect actual frames it will be corrected.
Thanks

**Comment by visuall** [comment]
Thanks Mikhail! 

I am really surprised that b-frames are not supported on latest GPUs given that it is trivial feature of other hardware encoders. Are there any plans this to be corrected via a new driver or something? For sure on the AMD Radeon Pro V520 when setting it is not giving an error. The issue is confirmed on AWS instance with this card on it and the AWS provided driver. 

Ok for Refs. Good to hear that it is in fact using the configured value and it is just a header issue.

**Comment by MikhailAMD** [comment]
Sorry, cannot comment on future hardware (and software).

**Comment by dcominottim** [comment]
> 1. B-frames are not supported in the latest GPUs. Setting non-zero parameter should return error.
> 
> 2.  There seems a problem in SPS generation in newer GPUs that keeps 1 as number of reference frames. While it doesn't affect actual frames it will be corrected.
> 
> Thanks

Do you mean even RDNA2 does not support B-frames? Not even for HEVC?

**Comment by MikhailAMD** [comment]
Currently doesn't.

**Comment by macchky** [comment]
@MikhailAMD 

> Currently doesn't.

Does it means RDNA2 has capable of b-frame but currently not support ?

**Comment by MikhailAMD** [comment]
I cannot comment on features that are not exposed by AMF SDK. Sorry.
