### ISSUE TITLE
dxgi with only one frame,no encoder frame output

### ISSUE THREAD

**Issue by chllcy** [GPUOpen-LibrariesAndSDKs/AMF#258]
hi, I'm test with DisplayCapture(dxgi) -> Converter -> Encoder .

sometimes AcquireNextFrame only return one frame in several seconds,such as crtl + alt + del.
then the encoder will not output the frame, before the next frame comes.
how can AMF encoder output the frame one by one,no need to wait for the next frame with dxgi?

add log
```
class DisplayPipeline::PipelineElementEncoder : public AMFComponentElement
{
	AMF_RESULT SubmitInput(amf::AMFData* pData)
	{
            ......
            pintf("SubmitInput encoder");
	    res = m_pComponent->SubmitInput(pData);
            ......
	    return res;
       }
    virtual AMF_RESULT QueryOutput(amf::AMFData** ppData)
    {
        AMF_RESULT res = AMFComponentElement::QueryOutput(ppData);
        if(res == AMF_OK && *ppData != nullptr)
        {
            amf_pts capturePts = (*ppData)->GetPts();
            amf_pts encodedPts = m_pDisplayPipeline->m_pCurrentTime->Get();
            printf("QueryOutput encoder");
            // AMFTraceInfo(L"Latency", L"latency = %5.2f", (encodedPts - capturePts) / 10000. );
        }
        else
        {
            int a = 1;
        }
        return res;
    }
};
```

with only one frame, I see the data had SubmitInput,but no data QueryOutput

**Comment by chllcy** [comment]
I Connect Pipeline with CT_Direct, change to CT_ThreadQueue is ok.

**Comment by MikhailAMD** [comment]
You are dealing with Desktop Duplication API behavior. it will capture new frame only when DWM or full screen app executes Present(). If you want to maintain constant frame rate you would have to encode previous frame. Check DDAPISource.cpp. There is an option to duplicate output frame. you would have to duplicate all the time, store pointer to texture and return it again in case DXGI_ERROR_WAIT_TIMEOUT comes from AcquireNewFrame.
