### ISSUE TITLE
No 10-bit HEVC encode support in FFmpeg?

### ISSUE THREAD

**Issue by Chipcraft** [GPUOpen-LibrariesAndSDKs/AMF#259]
Since basically no documentation exist on the subject, I thought you might be able to give an answer.
Is it really the case that it is not possible to encode 10-bit HEVC using FFmpeg? 8-bit HEVC works fine however, p010 pixel format is being refused and apparently, only yuv420p and nv12 are available? Also, there doesn't seem to be any way to otherwise select the output depth.

This is on Navi 21.

Thanks!

**Comment by MikhailAMD** [comment]
10bit HEVC encode is not yet integrated into ffmpeg AMF codec.

**Comment by Chipcraft** [comment]
Thats quite unfortunate, but thanks for the lightning fast reply Mikhail!

**Comment by cs9kc** [comment]
Apologies for grave digging, but regarding ffmpeg, it does appear that the version of AMF in ffmpeg is quite old, still.  It would be awesome to see an update to ffmpeg's AMF implementation, with features like 10-bit encoding and the new Quality VBR for H264 included, among others.  We're all out here cheering yall on!  Thanks!

**Comment by rhutsAMD** [comment]
10-bit HEVC support patches were submitted to FFmpeg and are under review. Closing this issue.

https://patchwork.ffmpeg.org/project/ffmpeg/patch/20231023134753.17106-3-lucenticus@gmail.com/
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20231023134753.17106-5-lucenticus@gmail.com/
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20231023134753.17106-7-lucenticus@gmail.com/

**Comment by SuperMitic** [comment]
Is there a way to compile FFMPEG with 10Bit HEVC AMF encoder? I have only found ffmpeg build without 10bit AMF support

**Comment by MikhailAMD** [comment]
> Is there a way to compile FFMPEG with 10Bit HEVC AMF encoder? I have only found ffmpeg build without 10bit AMF support

We submitted the patches and are waiting for acceptance. Once they are merged into FFmpeg tree you can get the build from regular sources. You can make a custom FFmpeg build by applying the patches.

**Comment by markg85** [comment]
I was just playing with desktop streaming. I want 10 bit there as 8 bit gives a bit too much banding. So i wanted to enable.... and it's not there :(

Are you guys still trying to get this merged?

**Comment by MikhailAMD** [comment]
The last attempt to submit the patch was in May 30, 2024:
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240530130826.374-3-ovchinnikov.dmitrii@gmail.com/
We will send update soon.

**Comment by agatakotecka** [comment]
> The last attempt to submit the patch was in May 30, 2024: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240530130826.374-3-ovchinnikov.dmitrii@gmail.com/ We will send update soon.

What is an update on this?
