### ISSUE TITLE
Video Encode API: AMF_MEMORY_COMPUTE_FOR_DX9 and AMF_MEMORY_COMPUTE_FOR_DX11 usage?

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#26]
Trying to get more alternative backends into my plugin and I stumbled upon these memory types. How would I use them?

Right now I have an optional OpenCL backed version, would this no longer be needed with that?

**Comment by Xaymar** [comment]
All my tests so far have resulted in a Driver Crash after a few seconds. What are those memory types for if not for a different type of Compute usage?

**Comment by MikhailAMD** [comment]
These memory types are used in AMFCompute interface for various OpenCL - like shaders. They are needed for fast interops. Typical scenario:
- allocate surface as DX9 or DX11
- render to it using DX9 or DX11
- convert to COMPUTE_FOR_DX9 or COMPUTE_FOR_DX11
- execute a shader using AMFCpmpute 
- convert surface back to DX9 or to DX11
- present surface or submit to encoder component

**Comment by Xaymar** [comment]
Alright, thank you for the information.
