### ISSUE TITLE
Will RX 6000 Series new feature be coming soon?

### ISSUE THREAD

**Issue by macchky** [GPUOpen-LibrariesAndSDKs/AMF#260]
Like H264 b-frame support?

**Comment by MikhailAMD** [comment]
We do not comment on unreleased features.

**Comment by macchky** [comment]
![HNV3ItNnrd](https://user-images.githubusercontent.com/814209/123528254-17e97300-d721-11eb-8d58-dcc04636c892.png)
Is this wrong??

**Comment by MikhailAMD** [comment]
It is not enabled yet.

**Comment by macchky** [comment]
Roger. I'm looking forward to it for long time.

**Comment by cs9kc** [comment]
Likewise, many of us eagerly look forward to additional encoder features!

Keep up the good work!  <3

**Comment by HaraldKal** [comment]
So does it support B-frames now?
I just find it very odd that you can mess around with B-frame settings in OBS but it's very unclear if it actually works or not?

**Comment by macchky** [comment]
@HaraldKal not yet
OBS b-frame setting is for older GPU.

**Comment by nyanmisaka** [comment]
> Support for consecutive B-frames and adaptive miniGOP for AVC Encoder

listed in [AMF Release 1.4.24](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v1.4.24)

Hi @MikhailAMD Does this mean the H264 b-frames is enabled in RDNA cards?

**Comment by MikhailAMD** [comment]
Yes.

**Comment by macchky** [comment]
Finally!!!!   B-frame comming!!!!!!!!!!!!!!!!!!

**Comment by macchky** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v1.4.24

**Comment by HaraldKal** [comment]
Nice! Now I Just need to figure out a way how to make B-frame setting work in OBS Studio for RDNA2

**Comment by macchky** [comment]
@cs9kc OBS amf encoder not using ffmpeg.
https://github.com/obsproject/obs-amd-encoder
but this project is nearly dead

ffmpeg encoder is used by Xaymar's plugins
https://github.com/Xaymar/obs-StreamFX/

**Comment by cs9kc** [comment]
> @cs9kc OBS default amf encoder not using ffmpeg. https://github.com/obsproject/obs-amd-encoder but this project is nearly dead
> 
> ffmpeg encoder is used by Xaymar's plugins https://github.com/Xaymar/obs-StreamFX/

If I recall, Xaymar is who wrote the OBS Studio built-in AMF encoder.  He has not worked with OBS Studio for over a year now.

**Comment by cs9kc** [comment]
> StreamFX uses FFMPEG for AMF encode. So until FFMPEG (or obs-amd-encoder) implements latest AMF lib, you cannot use b-frame on OBS.

Correct, this is what I was getting at in my first comment above.
