### ISSUE TITLE
Linux support is not mentioned in Readme or on GPU open website

### ISSUE THREAD

**Issue by Civil-Code** [GPUOpen-LibrariesAndSDKs/AMF#265]
Though the [Linux support issue](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/4) has been closed, this support is not mentioned in the AMF Readme or on the GPU open website. 

> **AMF Readme**
> Prerequisites:   Windows® 7 (SP1 with the Platform Update), Windows® 8.1, or Windows® 10

> **Website** https://gpuopen.com/advanced-media-framework/
> Requirements:   Microsoft® Windows® 7, Microsoft® Windows® 8.1 or Microsoft® Windows® 10.

**Comment by rhutsAMD** [comment]
Thanks for catching that! A mention of Linux support has been added to the Readme and the GPUOpen website will be updated to match.

Feel free to check out the new Wiki pages including the one for [Linux](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/Linux)
