### ISSUE TITLE
Is new QVBR rate control mode working with 21.7.1 drivers ?

### ISSUE THREAD

**Issue by NikosDi** [GPUOpen-LibrariesAndSDKs/AMF#266]
Hello.
I tried VCEEnc v6.13 which implements new AMF v1.4.21 rate control mode (--qvbr) but it doesn't seem to work.

My platform is:
Win 10 21H1 (19043.1110) build with 21.7.1 drivers and RX 470.

Is QVBR enabled with 21.7.1 drivers ?

**Comment by rhutsAMD** [comment]
Yes, QVBR is enabled with 21.7.1 drivers.
 
However, QVBR is not supported on RX 4xx or RX 5xx GPUs. It requires a more recent GPU such as the RX 5xxx or RX 6xxx series. If you will use an APU then it requires the Ryzen Mobile 4xxx or 5xxx series.

Additionally, the application can query a list of supported modes via AMFPropertyStorageEx::GetPropertyInfo and use AMFPropertyInfo::pEnumDescription to check what is supported.

**Comment by NikosDi** [comment]
After more than a month and the developer hasn't fixed this issue even for RDNA cards.

So, I close this ticket because he is obviously not interested enough to fix it and I'm not a developer.

Thank you.
