### ISSUE TITLE
Video Encode API: Multithreading causes GetProperty to return values out of order or invalid values.

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#27]
This is one of the more stranger things that I found that I fixed by moving all GetProperty calls into a synchronized/single-threaded approach. For some reason GetProperty would not work when multiple threads used it.

Example:
- Thread A calls SetPropery on a Surface, "Frame" is being set to 29392 (8m 09s 52frames).
- Thread B calls GetProperty "Frame" that happens to overlap the SetProperty call, expected returned value is 29388 (4 frame encoding delay).
- Thread A successfully sets the property "Frame".
- Thread B returns from GetPropery with an invalid value or a value further in the future (29392 for example).

I'm still working on a test case in which it happens more often, but basically it can be fixed by forcing SetPropery and GetProperty to never overlap.

**Comment by MikhailAMD** [comment]
Please check documentation: surface and buffers are not thread-safe.

**Comment by Xaymar** [comment]
So even if I have a Surface and a Buffer I can't call SetProperty on the Surface and GetProperty on the Buffer? What kind of madman designed that?

**Comment by MikhailAMD** [comment]
Please watch your tongue, this is public forum. I designed it. One can access any property but from one thread at the time. These objects should be "owned" by thread (compare to components that are thread-safe.) If objects are in the queue to be processed by a thread there is no need to access them from another thread.  There are reasons why it is done such way. As an example that not everything is thread-safe you could read about D3D11 thread model.

**Comment by Xaymar** [comment]
Sorry, but quoting DirectX 11 as an example is just silly. Vulkan and DirectX 12 are better examples here, since they take the asynchronous approach that GCN has to the end developer.

Still it does not make sense for SetPropery and GetProperty on two entirely different objects to affect each other. A Surface that is allocated on one thread and SetProperty is being called on should not affect the behavior of a GetProperty on another thread on a buffer that QueryOutput returned. I don't think there is a single design out there that actually wants this behaviour.

Media SDK had the same issue, but in Media SDK even the Components would not act nicely with threading. Anyway, if this is not going to be fixed, then it can be closed. I am working on my own implementation anyway using reverse engineered information.

**Comment by MikhailAMD** [comment]
OK:
1. I am AMD architect for AMF and Media SDK
2. Threading model is identical for Media SDK and AMF
3. D3D11 is just an example I could give you many more. Currently AMF does not support DX12 and Vulkan so it has a particular threading model selected some time ago as a compromise from performance perspective.
4. In general, different objects are completely independent on properties. But all properties except special ones are copied from the input object to the output object by component after processing is complete so application could attach any property it likes to input and they will be propagated to output.  
5. While objects are submitted app should not make any assumption that these objects can be used from another thread.

**Comment by Xaymar** [comment]
Let me explain the issue in better detail:

Thread A creates a Surface using AllocSurface, copies data onto the ->GetNative() buffers and then uses ->SetProperty(L"Frame", frameIndexA) to give it a unique frame index for the Presentation Timestamp (turns out the NAL does not have enough information for proper decoding).

Thread B happens to have received a amf::AMFDataPtr from QueryOutput just at about the same time, copies the data from it into a static buffer to hand over to the muxer and retrieves the Frame property using ->GetProperty(L"Frame", &frameIndexB).

Thread B would now possibly get a corrupted value written into frameIndexB instead of the proper value. When this happens varies, but usually it starts immediately and becomes a bigger and bigger problem over time until the muxer just drops the packets because an incorrect presentation timestamp is given.

I hope you understand what the issue is now and why I reported it.

**Comment by MikhailAMD** [comment]
The scenario is completely valid but did you put in consideration that frames will be reordered if B-frames are enabled? Please state what kind of input and output do you expect and what do you get. 
Anyway, this is not a threading issue.

**Comment by Xaymar** [comment]
I did and it happens without B-Frames enabled too. But for testing purposes I have B-Frames enabled, since it makes it easier to spot.

```
Input:
Frame   1  2  3  4  5  6  7  8  9
Ex.Type	I  B  B  B  P  B  B  B  P
Ex.DTS  1  3  4  5  2  7  8  9  6 

Output:
Type    I  P  B  B  B  P  B  B  B
RetDTS  1  2  3  4  5  6  7  8  9
Ex.PTS  1  5  2  3  4  9  6  7  8
Ac.PTS  1  5  2  3  4  1  7 99 -1
```

Like said before, after a varying amount of time (when calling SetProperty and GetProperty in different threads), the "Frame" property that is used to calculate the PTS timestamp will store invalid information to the given variable. The only solution I found so far was to make all GetProperty and SetProperty calls happen in the same thread.

**Comment by MikhailAMD** [comment]
You should know that AMF doesn't have any threads in encoder. all operations on properties happen in SubmitInput() and QueryOutput()
I checked but not debugged your code. It looks like you again has a bug by printing 64-bit integers in the log as regular integers. %d is for 32 bit integers.

**Comment by Xaymar** [comment]
This has nothing to do with logging, it happens in the actual output - I retrieved the values in the above listing by using breakpoints that were enabled when something like that happened. The "#ifdef DEBUG" parts haven't seen the light in a long time as they have been replaced by AMF log output now.

I first reported this as #23, but now I have figured out the actual cause of it. @Xbye was the first one to reproduce the issue and report it to me and I reproduced it a long time after that.

**Comment by MikhailAMD** [comment]
You could fix printouts and send me a log.

**Comment by Xaymar** [comment]
This could take a while, as the issue starts clearly surfacing at about 20-40 minutes into recording. I have started now.

**Comment by Xaymar** [comment]
# Related Files
* Log: http://cdn.xaymar.com/private/2016/09/2016-09-27%2022-27-16.txt
* Video File: http://cdn.xaymar.com/private/2016/09/2016-09-27%2022-27-16.7z
* Dump: http://cdn.xaymar.com/private/2016/09/2016-09-27%2022-27-16_obs64.7z

I had to revert to 1.3.0rc4hf1 for this, since I didn't want to spend a ton of time undoing an earlier change.

**Comment by MikhailAMD** [comment]
Could you please point to time where you see the error? The log is 40MB. I do see reorder but it is expected. Not sure for the reason to print with %4ld.
Print spec for VS runtime: 
%ld  is for "long int" which is 4 bytes parameter while you are passing 8 byte values (int64_t):.
https://msdn.microsoft.com/en-us/library/tcxf1dw6.aspx
https://msdn.microsoft.com/en-ca/library/s3f49ktz.aspx
AMF_LOG_INFO("Packet: Type(%ld), PTS(%4ld,%12ld), DTS(%4ld,%12ld), Size(%8ld)", pkt.type, pkt.pts, pkt.pts_usec, pkt.dts, pkt.dts_usec, pkt.data.size());
MSFT spec requires "%I64d". it is non compatible with Linux but not much you can do.
.

**Comment by Xaymar** [comment]
Check the video file, it does not contain enough data for the time recorded. At about 15:36 it happens for example.

**Comment by MikhailAMD** [comment]
I would like to see it in the log - wrong data. I would avoid debugging code outside of your plug-in

**Comment by MikhailAMD** [comment]
%lld will work with VS compiler but C/C++ does not standardize size of long or long long . I am avoiding it when I can.

**Comment by Xaymar** [comment]
> %lld will work with VS compiler but C/C++ does not standardize size of long or long long . I am avoiding it when I can.

Pretty much all documentation I have seen about printf and sprintf define d for int, ld for long and lld for long long. Long Long is defined as an Integer with at least 64 bits. [Doc 1](http://en.cppreference.com/w/cpp/io/c/fprintf) [Doc 2](http://www.cplusplus.com/reference/cstdio/printf/) [Fundamental Types (MSDN)](https://msdn.microsoft.com/en-us/library/cc953fe1.aspx) [Fundamental Types](http://en.cppreference.com/w/cpp/language/types)

> I would like to see it in the log - wrong data. I would avoid debugging code outside of your plug-in

Turns out it didn't happen that time, it's rarer than I thought. If @xbye could provide a log file + video in which it happened that would be great.

**Comment by MikhailAMD** [comment]
OK, will wait for the log.
The problem with long is with wording "at least". if it is changed printf will be incorrect. I saw this on other platforms. For example: 
https://software.intel.com/en-us/articles/size-of-long-integer-type-on-different-architecture-and-os
So printf will expect different size of parameter on the stack depend on platform but int64_t is the same size on all platforms.

**Comment by Xaymar** [comment]
I'm closing this for now (Tracking purposes) until I have additional data. I'm not entirely sure how to reproduce it even, since it doesn't happen with 16.9.1 and 16.9.2 to me - for all I know it could be due to a broken driver installation (mix&match).

**Comment by Xaymar** [comment]
After careful investigation of the bug, dumps and log files I have produced while trying to reproduce this again, I have discovered that this only happens when the output queue gets too large. Which means that the bug is actually in OBS Studio and not here.

Sorry for wasting your time @MikhailAMD.

**Comment by MikhailAMD** [comment]
Hey,
I am here to help. Bugs are usually happen on both sides. I do appreciate your efforts on AMF VCE integration and several real bugs that I am pushing to be fixed ASAP.
Cheers,
Mikhail
