### ISSUE TITLE
SampleEncoder not working in AMD Radeon Vega 8 card

### ISSUE THREAD

**Issue by vinodspillai** [GPUOpen-LibrariesAndSDKs/AMF#272]
I tried running the sample Encoder app on a Radeon Vega 8 graphics card, it generates output.h264 file. I tried playing this file in VLC player, but It is not playing. I enabled logging in VLC and this the error
-- logger module started --
main: one instance mode ENABLED
main: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
h26x warning: h264 module discarded (no startcode)
ps warning: this does not look like an MPEG PS stream, continuing anyway
ps warning: garbage at input from 509, trying to resync...
-- logger module stopped --

Am I missing something here?

**Comment by rhutsAMD** [comment]
I reproduced the issue and it looks to be an issue with VLC media player. Wrapping the output stream in an MP4 container allows VLC playback to work. The bitstream looks OK from a stream analyzer as well as another playback application. Perhaps VLC requires some additional optional parameters for H264 streams.

**Comment by vinodspillai** [comment]
Thank you for the reply.  I found an another behavior. When I turned on color conversion inside encoder ( AMF_SURFACE_RGBA) the file size is around 61 kb, and when it is turned off ( AMF_SURFACE_NV12 ) the file size is 223 kb. Is this behavior expected?  My assumption was since the input size is same, the encoded size should also kind of match.

**Comment by rhutsAMD** [comment]
The reason you are seeing encoded sizes that are different is because the inputs are different. NV12 input is purple + green and RGBA input is blue + red. This leads to different encoding.
