### ISSUE TITLE
AMFComponent::SubmitInput error documentation does not match SimpleEncoder example

### ISSUE THREAD

**Issue by e00E** [GPUOpen-LibrariesAndSDKs/AMF#274]
In [SimpleEncoder](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/5359f7dba51107da19b7650e5d8a40a0f04ea6d9/amf/public/samples/CPPSamples/SimpleEncoder/SimpleEncoder.cpp#L275) for AMFComponent::SubmitInput the checked error codes are

- NEED_MORE_INPUT
- INPUT_FULL
- DECODER_NO_FREE_SURFACES

On the other hand in the PDF documentation for the function the possible error return values are
- NO_DEVICE
- INVALID_ARG
- INPUT_FULL

So either the example is checking for error codes that cannot occur or the documentation is not documenting some error codes that can occur.

**Comment by e00E** [comment]
In addition to not being documented in the PDF, NEED_MORE_INPUT also has a confusing comment in Result.h because the sentence seems to cut off before completing.

**Comment by rhutsAMD** [comment]
The documentation has been updated and will be visible in the next AMF release.

In the meantime, these are the return values you can expect from AMFComponent::SubmitInput

`AMF_NEED_MORE_INPUT` when B-frames are used then the encoder may need several inputs before it can produce first output
`AMF_INPUT_FULL` when the output is not properly drained
The rest of the possible returns are various errors.

**Comment by e00E** [comment]
Thank you, and once again feel free to close whenever.
