### ISSUE TITLE
AMF_VIDEO_ENCODER_RATE_CONTROL_QUALITY_VBR not documented

### ISSUE THREAD

**Issue by e00E** [GPUOpen-LibrariesAndSDKs/AMF#279]
missing in PDF

**Comment by visuall** [comment]
Yes, some guide how we use MF_VIDEO_ENCODER_RATE_CONTROL_QUALITY_VBR and on what it depends, is there enum we should set for target quality etc will be really useful. Currently no idea how this mode works.

**Comment by rhutsAMD** [comment]
The documentation has been updated and will be visible in a future AMF release. The enum value used to enable the Quality-Defined Variable Bitrate rate control method for the H264 Encoder is `AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_QUALITY_VBR = 4`. Also the property `AMF_VIDEO_ENCODER_QVBR_QUALITY_LEVEL` can be used to set the quality level for this feature within the range [1, 51] inclusive (where higher means more quality). This feature is only supported when PreAnalysis is enabled.

**Comment by rhutsAMD** [comment]
The documentation update can now be found within https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v1.4.24 .
