### ISSUE TITLE
Video Encode API: Dark Areas have too low bitrate

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#28]
It seems that bitrate detection is not done properly for dark frames, making these basically a block-hell. Possibly needs #2 to be done, but x264 can do it with single-pass encoding, so it is more likely a bitrate detection issue.

**Comment by MikhailAMD** [comment]
We need more concrete information on this. We compared x264 and VCE encoders on the same video stream. We did not find any significant differences in dark areas. Below are the screenshots and Json files. Please provide similar information for this issue.  
[BlackAreas.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/503176/BlackAreas.zip)

**Comment by Xaymar** [comment]
You are allowed to call me dumb for forgetting that I had downgraded to 16.9.1 to test something. 16.9.2 runtime works as expected.

**Comment by Xaymar** [comment]
I did not mean to reopen and delete a comment. Anyway, the issue is fixed in 16.9.2, which I didn't have installed due to testing reasons.
