### ISSUE TITLE
Document lifetime requirements of data passed to CreateSurfaceFrom

### ISSUE THREAD

**Issue by e00E** [GPUOpen-LibrariesAndSDKs/AMF#280]
It is unclear how long for example the input texture for CreateSurfaceFromDX11Native has to live. When can it be destroyed?
The following behaviors seems reasonable to me but I do not know which one is correct:
1. The texture can be destroyed immediately because AMF created a copy of it during thet CreateSurfaceFrom call.
2. The texture has can be destroyed after the surface has been used in AMFComponent::SubmitInput because there a copy of the texture is created.
3. The texture can be destroyed after the AMFComponent has used the surface. In this case I am not sure how to know when this is the case.

**Comment by rhutsAMD** [comment]
The CreateSurfaceFromDX11Native function call provides an option to setup a callback which would be called once AMF is no longer using the surface/texture internally. AMF will not copy the surface during the CreateSurfaceFromDX11Native call. This would mean option #3 should be used.

**Comment by e00E** [comment]
Thank you. That makes sense.
