### ISSUE TITLE
There is no AMF_VIDEO_ENCODER_HEVC_PROFILE_MAIN10 defined in AMF SDK

### ISSUE THREAD

**Issue by onealexanderivanov** [GPUOpen-LibrariesAndSDKs/AMF#281]
AMF_VIDEO_ENCODER_HEVC_PROFILE_ENUM defines only AMF_VIDEO_ENCODER_HEVC_PROFILE_MAIN

BTW, when I am asking capabilities like this:
	const amf::AMFPropertyInfo* var;
	AMF_RESULT  res = enc->GetPropertyInfo(AMF_VIDEO_ENCODER_HEVC_PROFILE, &var);
        const amf::AMFEnumDescriptionEntry* enm = var->pEnumDescription; 

I see tat there are 2 values returned:
and for the first item its |enm->name| states "Main" while for the second - "Main10" 

It looks like the proper declaration of AMF_VIDEO_ENCODER_HEVC_PROFILE_ENUM should be:
enum AMF_VIDEO_ENCODER_HEVC_PROFILE_ENUM
{
    AMF_VIDEO_ENCODER_HEVC_PROFILE_MAIN = 1,
    AMF_VIDEO_ENCODER_HEVC_PROFILE_MAIN10 = 2,
};

**Comment by nyanmisaka** [comment]
The Main10 profile have been added in AMF 1.4.23.
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/55e4d844b77885cc3f7832bdb3cf41a1f16950ef/amf/public/include/components/VideoEncoderHEVC.h#L51
