### ISSUE TITLE
Setting high quality usage on Polaris and Vega fails the encoding

### ISSUE THREAD

**Issue by nyanmisaka** [GPUOpen-LibrariesAndSDKs/AMF#282]
High quality usage works well on RX 5000/6000 series card and related APUs.

There should be a graceful fallback to usage `transcoding` for old VCE cards.

```
VCEEncoderTrace: 2021-12-04 23:33:53.167     4B9C [VCEEncoderTrace]   Debug: SetProperty(-1) Usage:4
EncoderPropertySet: 2021-12-04 23:33:53.167     4B9C [EncoderPropertySet]   Error: ..\..\..\..\..\runtime\src\common\EncoderPropertySet.cpp(64):Assertion failed:EncoderProperty::GetUsage - Failed to find entry for usage 4
```

**Comment by MikhailAMD** [comment]
The app should ignore the  error returned by SetProperty in this case.

**Comment by nyanmisaka** [comment]
> The app should ignore the error returned by SetProperty in this case.

Does the macro `AMF_ASSIGN_PROPERTY_INT64(ret, encoder, AMF_VIDEO_ENCODER_USAGE, usage)` have a implicit check?

**Comment by MikhailAMD** [comment]
This macro doesn't check for errors, it returns "res". See PropertyStorage.h for implementation.

**Comment by nyanmisaka** [comment]
The two usages I was trying to add to is ffmpeg, the log level was set to debug.

It seems that ffmpeg didn't write any log instead of crashing when that AMF runtime error appears.

There should be some related logs If the check was return by `AMF_RETURN_IF_FALSE`.

https://github.com/FFmpeg/FFmpeg/blob/3a9861e22c636d843c10e23f5585196d1f3400dd/libavcodec/amfenc_h264.c#L151

**Comment by MikhailAMD** [comment]
I see what is happening. Some validation checking needs to be added for enum properties. As a way-around you can verify presence or absence of a particular enum value by calling GetPropertyInfo and enumerating pEnumDescription till name is nullptr.

**Comment by MikhailAMD** [comment]
The fix will be available in one of driver updates.
