### ISSUE TITLE
Does setting ENCODER_USAGE affect more than default parameters?

### ISSUE THREAD

**Issue by e00E** [GPUOpen-LibrariesAndSDKs/AMF#283]
It is clear that that setting the usage affects the default parameters. What is not clear is whether the usage has any other side effect. For example, consider a situation where we are manually setting all documented parameters. In this case where all parameters are going to be set anyway, does setting the usage have any other side effect?
It would be nice to clarify this in the documentation.

**Comment by MikhailAMD** [comment]
You should treat USAGE as preset of parameters. Any individual parameter can be changed after setting usage. There are no hidden things.
