### ISSUE TITLE
No DX12 encoding support in Vega?

### ISSUE THREAD

**Issue by nyanmisaka** [GPUOpen-LibrariesAndSDKs/AMF#285]
As per the announcement from Microsoft devblogs, DX12 encoding on AMD is only supported on RX 5000 and Ryzen 2000 or newer GPU. And no support for Vega (56/64 and Radeon VII) which was launched in 2017 and 2019?

I don't think this is a good idea especially when the newer cards are not affordable due to mining. Not to mention the NVIDIA GTX10 series from 2016 still support it.

https://devblogs.microsoft.com/directx/announcing-new-directx-12-feature-video-encoding/

**Comment by MikhailAMD** [comment]
@nyanmisaka I understand your concern but this repo is dedicated to AMF integration and I cannot comment on native DX12 encoder implementation, especially not yet released.

**Comment by nyanmisaka** [comment]
Yeah. I just hope that AMD can extend its support for old GPUs as much as possible in such a hard period.

But how about the DX12 support in AMF? I saw DX12 pipeline has been supported in the last release.
I thought it is a future-proof API after reading the docs from Microsoft.

**Comment by MikhailAMD** [comment]
No comments on new AMF features but DX12 is our priority.
