### ISSUE TITLE
Link error in for compilation of  AMF\amf\public\proj\vs2019\AmfMediaCommon.sln

### ISSUE THREAD

**Issue by donutsbacchus** [GPUOpen-LibrariesAndSDKs/AMF#291]
ComponentsFFMPEG.vcxproj does not link anymore in the version 1.4.23

1. The compilator is: `Microsoft Visual Studio Community 2019 Version 16.11.8`
2.  The compilation command is: `AMF\amf\public\proj\vs2019\AmfMediaCommon.sln /p:WindowsTargetPlatformVersion=10.0;WindowsTargetPlatformMinVersion=10.0;PlatformToolset=v142;Configuration=Debug;Platform=x64 `
3. The compilations log is: `AMF\amf\public\proj\vs2019\ComponentsFFMPEG\..\..\..\..\..\Thirdparty\ffmpeg\ffmpeg-4.3.2\x64\release\lib\avformat.lib : fatal error LNK1107: invalid or corrupt file: cannot read at location 0x82 [AMF\amf\public\proj\vs2019\ComponentsFFMPEG\ComponentsFFMPEG.vcxproj]`

**Comment by rhutsAMD** [comment]
Thanks for reporting this issue. The Git LFS pointers for the FFmpeg binaries were previously uploaded and are now replaced with the actual binaries as this repo does not use LFS.

**Comment by donutsbacchus** [comment]
Thank you, it seems great! Is it possible to have a new git tag on it please?
