### ISSUE TITLE
how to set color description such as color space, color trc when encode h264 & hevc

### ISSUE THREAD

**Issue by foroot** [GPUOpen-LibrariesAndSDKs/AMF#295]
Please avoid asking about future products or anything that is unreleased.
I am just using ffmpeg 4.4 and I cannot find any ideas to set color description while encoding, does amf sdk support that or not, any response will be highly appreciated, thanks alot

**Comment by foroot** [comment]
> 
Is convenient to provide some sample code? thanks alot

**Comment by foroot** [comment]
>

**Comment by nyanmisaka** [comment]
See this patch: https://patchwork.ffmpeg.org/project/ffmpeg/patch/d6a48f863ffe0ae2968aa487b571a1a68412522d.1642029358.git.info@xaymar.com/

**Comment by ByteYIFFF** [comment]
@nyanmisaka @MikhailAMD I used this patch to ffmpeg, the vui tag of the encoded hdr video is empty. Is this patch valid?

**Comment by ByteYIFFF** [comment]
@nyanmisaka @MikhailAMD The problem maybe  that my driver version is 20 （AMD 5300M）

**Comment by nyanmisaka** [comment]
That patch series doesn't add support for passing P010 format to hevc encoder.

Update to the latest driver first and can you try this ffmpeg and see if it works? https://github.com/jellyfin/jellyfin-ffmpeg

**Comment by ByteYIFFF** [comment]
@nyanmisaka @MikhailAMD My graphics card is rx5500 xt, ffmpeg fails in the init encoder, but I see that the driver already supports this series on the official website. Does my graphics card support this? it is very important to me！

**Comment by MikhailAMD** [comment]
Full list of GPUs: https://www.amd.com/en/graphics/amd-radeon-rx-laptops
Your GPU: https://www.amd.com/en/products/graphics/amd-radeon-rx-5500m
Looks like encode supported. 
What is failing: which command line? What is the input? Did you try AMF samples?

**Comment by ByteYIFFF** [comment]
> Full list of GPUs: https://www.amd.com/en/graphics/amd-radeon-rx-laptops Your GPU: https://www.amd.com/en/products/graphics/amd-radeon-rx-5500m Looks like encode supported. What is failing: which command line? What is the input? Did you try AMF samples?

@MikhailAMD  Thanks. So, in the case of encoding hevc 10bit, is amf already supported on my graphics card?

**Comment by MikhailAMD** [comment]
In the failure what is in format?
Your card is Navi10. 10-bit HEVC encoding is supported from Navi21 (RX 6xxxx). 10-bit HEVC is supported in AMF API but not yet in ffmpeg integration.

**Comment by ByteYIFFF** [comment]
> In the failure what is in format? Your card is Navi10. 10-bit HEVC encoding is supported from Navi21 (RX 6xxxx). 10-bit HEVC is supported in AMF API but not yet in ffmpeg integration.

format is AMF_SURFACE_P010. and  i add this  patch(https://patchwork.ffmpeg.org/project/ffmpeg/patch/d6a48f863ffe0ae2968aa487b571a1a68412522d.1642029358.git.info@xaymar.com/)  to ffmpeg.  so , my ffmpeg is supoort about format p010le

**Comment by MikhailAMD** [comment]
I cannot comment on the patch but:
1. P010 assumes HEVC 10-bit - the caller should set AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH = AMF_COLOR_BIT_DEPTH_10
2. Your GPU doesn't support 10-bit HEVC encoding.

**Comment by ByteYIFFF** [comment]
> I cannot comment on the patch but:
> 
> 1. P010 assumes HEVC 10-bit - the caller should set AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH = AMF_COLOR_BIT_DEPTH_10
> 2. Your GPU doesn't support 10-bit HEVC encoding.

thanks. So my GPU doesn't support 10-bit HEVC encoding. Can you further provide a website about which gpu supports 10-bit hevc encoding, so that I can test my code. @MikhailAMD

**Comment by nyanmisaka** [comment]
> @nyanmisaka My graphics card is rx5500 xt, ffmpeg fails in the init encoder, but I see that the driver already supports this series on the official website. Does my graphics card support this? it is very important to me！

The latest radeon driver for Windows is 22.3.2. Grab the latest patched jellyfin-ffmpeg and retry with the following command. 10bit hevc encoding works fine on 4000/5000 series APU.

But on Linux you should use VAAPI instead.
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/gallium/drivers/radeonsi/si_get.c#L562
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/amd/common/amd_family.h#L105

`ffmpeg.exe -init_hw_device d3d11va=dx11:,vendor=0x1002 -hwaccel_device dx11 -hwaccel d3d11va -hwaccel_output_format d3d11 -i "src_yuv420p10.mp4" -an -sn -c:v hevc_amf -quality speed -profile:v main10 -level 5.1 -b:v 8M -y "dst_p010.mp4"`

**Comment by ByteYIFFF** [comment]
> I cannot comment on the patch but:
> 
> 1. P010 assumes HEVC 10-bit - the caller should set AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH = AMF_COLOR_BIT_DEPTH_10
> 2. Your GPU doesn't support 10-bit HEVC encoding.

After I set AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH = AMF_COLOR_BIT_DEPTH_10, the video has hdr effect only for the first few seconds in rx6600m graphics card. this is my video.
[hdr.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/8367904/hdr.zip)

**Comment by ByteYIFFF** [comment]
> > @nyanmisaka My graphics card is rx5500 xt, ffmpeg fails in the init encoder, but I see that the driver already supports this series on the official website. Does my graphics card support this? it is very important to me！
> 
> The latest radeon driver for Windows is 22.3.2. Grab the latest patched jellyfin-ffmpeg and retry with the following command. 10bit hevc encoding works fine on 4000/5000 series APU and newer with VCN 2.0+ support.
> 
> But on Linux you should use VAAPI instead. https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/gallium/drivers/radeonsi/si_get.c#L562 https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/amd/common/amd_family.h#L105
> 
> `ffmpeg.exe -init_hw_device d3d11va=dx11:,vendor=0x1002 -hwaccel_device dx11 -hwaccel d3d11va -hwaccel_output_format d3d11 -i "src_yuv420p10.mp4" -an -sn -c:v hevc_amf -quality speed -profile:v main10 -level 5.1 -b:v 8M -y "dst_p010.mp4"`

@nyanmisaka i use this patch（that you give me）(https://patchwork.ffmpeg.org/project/ffmpeg/patch/d6a48f863ffe0ae2968aa487b571a1a68412522d.1642029358.git.info@xaymar.com/) to ffmpeg and update amf to version 1.4.23. Is it enough to run encoding hevc 10bit in windows？sorry, i don’t have enough time to read your ffmpeg code.

**Comment by ByteYIFFF** [comment]
> ffmpeg.exe -init_hw_device d3d11va=dx11:,vendor=0x1002 -hwaccel_device dx11 -hwaccel d3d11va -hwaccel_output_format d3d11 -i "src_yuv420p10.mp4" -an -sn -c:v hevc_amf -quality speed -profile:v main10 -level 5.1 -b:v 8M -y "dst_p010.mp4"

@nyanmisaka hi，I just added your ffmpeg patch（0004-add-amf-refactor-and-hevc-10-bit-encoding.patch） to my code, and the video exported using the ffmpeg command line still only has the hdr effect for the first few seconds. Is it convenient for you to encode my video to hevc 10bit. it is important to me ,thanks~

**Comment by nyanmisaka** [comment]
> > ffmpeg.exe -init_hw_device d3d11va=dx11:,vendor=0x1002 -hwaccel_device dx11 -hwaccel d3d11va -hwaccel_output_format d3d11 -i "src_yuv420p10.mp4" -an -sn -c:v hevc_amf -quality speed -profile:v main10 -level 5.1 -b:v 8M -y "dst_p010.mp4"
> 
> @nyanmisaka hi，I just added your ffmpeg patch（0004-add-amf-refactor-and-hevc-10-bit-encoding.patch） to my code, and the video exported using the ffmpeg command line still only has the hdr effect for the first few seconds. Is it convenient for you to encode my video to hevc 10bit. it is important to me ,thanks~

I meet the same issue in "movies and tv" on windows but it plays fine on other players and iOS. Something went wrong in the latest AMF runtime.

If I remember correctly, this issue didn't exist in last year's Radeon drivers. Can you revert to the 21.10.2 WHQL driver or older one and try again?

**Comment by MikhailAMD** [comment]
I've checked the file from @ByteYIFFF using analyzer. Nothing wrong with it but the first IDR frame has SPS/PPS and VUI header inside SPS with color info (video_signal_type_present_flag) and following IDR-frames don't have SPS/PPS. This is done by design.  An app can request SPS/PPS/IDR for a particular frame by setting a property on input surface. I assume that Films&TV player is confused by the lack of SPS/PPS in the second IDR-frame. I will bring this to codec team.

**Comment by MikhailAMD** [comment]
Spoke to codec folks. They confirmed that current behavior is intentional. If an app wants to have SPS/PPS in IDR it can:
HEVC: set AMF_VIDEO_ENCODER_HEVC_HEADER_INSERTION_MODE = AMF_VIDEO_ENCODER_HEVC_HEADER_INSERTION_MODE_IDR_ALIGNED
H264: set AMF_VIDEO_ENCODER_HEADER_INSERTION_SPACING to  the same value as AMF_VIDEO_ENCODER_IDR_PERIOD
Try it in the patch.

**Comment by nyanmisaka** [comment]
@ByteYIFFF I can confirm HDR works flawlessly in Films&TV player with `-header_insertion_mode idr` added in the patched ffmpeg.

**Comment by MikhailAMD** [comment]
Can you share encoded stream?

**Comment by nyanmisaka** [comment]
> Can you share encoded stream?

Sure. [encoded_hdr.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/8373720/encoded_hdr.zip)
And the source HDR video can be downloaded from https://4kmedia.org/sony-camping-in-nature-4k-demo/

**Comment by MikhailAMD** [comment]
Reproduced in SimpleEncoder  - opened a ticket.

**Comment by ByteYIFFF** [comment]
> header_insertion_mode
Sorry for the inconvenience, I set AMF_VIDEO_ENCODER_HEVC_HEADER_INSERTION_MODE_IDR_ALIGNED, and the video playback is normal in movie and TV. However, I cannot read the vui color information in sps using the elecard hevc analyzer tool. I can't understand this question. this is my video.https://drive.google.com/file/d/1NtArHbMwQMsZ30jH5rrxl2B7qGPyD0TF/view?usp=sharing

**Comment by MikhailAMD** [comment]
The video has more then one SPS. You seems looking into wrong one.

**Comment by ByteYIFFF** [comment]
> @ByteYIFFF I can confirm HDR works flawlessly in Films&TV player with `-header_insertion_mode idr` added in the patched ffmpeg.

@nyanmisaka I failed that my video has more then one SPS.  Would  you please send me the encoded 10bit hevc video?🙇‍ I want to see the vui of your video. thanks

**Comment by nyanmisaka** [comment]
> > @ByteYIFFF I can confirm HDR works flawlessly in Films&TV player with `-header_insertion_mode idr` added in the patched ffmpeg.
> 
> @nyanmisaka I failed that my video has more then one SPS. Would you please send me the encoded 10bit hevc video?🙇‍ I want to see the vui of your video. thanks

https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/295#issuecomment-1082168687

**Comment by ByteYIFFF** [comment]
> You seems looking into wrong one.

HI, @MikhailAMD  this is my code . I just set  `ctx->header_insertion_mode = AMF_VIDEO_ENCODER_HEVC_HEADER_INSERTION_MODE_IDR_ALIGNED;`  Do you know how to make vui store color information .

    // Color Metadata
    /// Color Range (Support for older Drivers)
    if (avctx->color_range == AVCOL_RANGE_JPEG) {
        AMF_ASSIGN_PROPERTY_BOOL(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_NOMINAL_RANGE, 1);
    } else {
        AMF_ASSIGN_PROPERTY_BOOL(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_NOMINAL_RANGE, 0);
    }

    /// Color Space & Depth
    color_depth = AMF_COLOR_BIT_DEPTH_8;
    color_profile = AMF_VIDEO_CONVERTER_COLOR_PROFILE_UNKNOWN;
    switch (avctx->colorspace) {
    case AVCOL_SPC_SMPTE170M:
        if (avctx->color_range == AVCOL_RANGE_JPEG) {
            color_profile = AMF_VIDEO_CONVERTER_COLOR_PROFILE_FULL_601;
        } else {
            color_profile = AMF_VIDEO_CONVERTER_COLOR_PROFILE_601;
        }
        break;
    case AVCOL_SPC_BT709:
        if (avctx->color_range == AVCOL_RANGE_JPEG) {
            color_profile = AMF_VIDEO_CONVERTER_COLOR_PROFILE_FULL_709;
        } else {
            color_profile = AMF_VIDEO_CONVERTER_COLOR_PROFILE_709;
        }
        break;
    case AVCOL_SPC_BT2020_NCL:
    case AVCOL_SPC_BT2020_CL:
        if (avctx->color_range == AVCOL_RANGE_JPEG) {
            color_profile = AMF_VIDEO_CONVERTER_COLOR_PROFILE_FULL_2020;
            color_depth = AMF_COLOR_BIT_DEPTH_10;
        } else {
            color_profile = AMF_VIDEO_CONVERTER_COLOR_PROFILE_2020;
            color_depth = AMF_COLOR_BIT_DEPTH_10;
        }
        ctx->header_insertion_mode = AMF_VIDEO_ENCODER_HEVC_HEADER_INSERTION_MODE_IDR_ALIGNED;
        break;
    }

    AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH, color_depth);
    //AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_INPUT_COLOR_PROFILE, color_profile);
    AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_OUTPUT_COLOR_PROFILE, color_profile);
    /// Color Transfer Characteristics (AMF matches ISO/IEC)
    //AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_INPUT_TRANSFER_CHARACTERISTIC, (amf_int64)avctx->color_trc);
    AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_OUTPUT_TRANSFER_CHARACTERISTIC, (amf_int64)avctx->color_trc);
    /// Color Primaries (AMF matches ISO/IEC)
    //AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_INPUT_COLOR_PRIMARIES, (amf_int64)avctx->color_primaries);
    AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_OUTPUT_COLOR_PRIMARIES, (amf_int64)avctx->color_primaries);

    // Picture control properties
    AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_NUM_GOPS_PER_IDR, ctx->gops_per_idr);
    AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_GOP_SIZE, avctx->gop_size);
    if (avctx->slices > 1) {
        AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_SLICES_PER_FRAME, avctx->slices);
    }
    AMF_ASSIGN_PROPERTY_BOOL(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_DE_BLOCKING_FILTER_DISABLE, deblocking_filter);
    AMF_ASSIGN_PROPERTY_INT64(res, ctx->encoder, AMF_VIDEO_ENCODER_HEVC_HEADER_INSERTION_MODE, ctx->header_insertion_mode);
`

**Comment by MikhailAMD** [comment]
what I meant is that your video has two SPS NAL units in the first IDR-frame:  
![image](https://user-images.githubusercontent.com/15144639/160921777-8991d19f-7f9b-4994-982e-79435c8fa9d2.png)
The first one doesn't have VUI. The second one does:
![image](https://user-images.githubusercontent.com/15144639/160922017-dae869fb-521e-4113-83ef-40fde48bba54.png)
Following IDR-frames have single SPS with similar VUI

**Comment by ByteYIFFF** [comment]
> what I meant is that your video has two SPS NAL units in the first IDR-frame: ![image](https://user-images.githubusercontent.com/15144639/160921777-8991d19f-7f9b-4994-982e-79435c8fa9d2.png) The first one doesn't have VUI. The second one does: ![image](https://user-images.githubusercontent.com/15144639/160922017-dae869fb-521e-4113-83ef-40fde48bba54.png) Following IDR-frames have single SPS with similar VUI



> AMF_VIDEO_ENCODER_HEVC_HEADER_INSERTION_MODE_IDR_ALIGNED

@MikhailAMD  I understand the problem. however, is this an interface design problem? When I didn't set AMF_VIDEO_ENCODER_HEVC_HEADER_INSERTION_MODE_IDR_ALIGNED, the first IDR had VUI (with color information). Now that the parameters are set, the IDR has two sps.

**Comment by ByteYIFFF** [comment]
@MikhailAMD Sorry to bother you, how can I set the parameters so that the video encoded by hevc_amf contains b frames.

**Comment by MikhailAMD** [comment]
b-frames has been enabled for H264 (AVC) only, check doc/Readme.txt.

**Comment by ByteYIFFF** [comment]
> 
First of all thanks for your quick reply. Secondly, I found that readme.txt doesn't mention that hevc supports bframe. You mean if I follow the h264 code, hevc_amf still can't support b frame. @MikhailAMD
