### ISSUE TITLE
[Request]: Add MJPEG decoder sample

### ISSUE THREAD

**Issue by toruishihara** [GPUOpen-LibrariesAndSDKs/AMF#296]
I saw SimpleDecoder.cpp as h.264 stream decoding sample.
Do you have same kind for sample for MJPEG decoder?

MJPEG is commonly used for USB camera. I need HW decoder of MJPEG on AMD PC.

**Comment by rhutsAMD** [comment]
Yes, the TranscodeHW sample can perform HW decoding of the MJPEG format. You may use command line options similar to this: 

`TranscodeHW.exe -input "input.mjpeg" -output "output.mp4" -width 1280 -height 720 -usage transcoding -qualitypreset speed -RateControlMethod cqp -targetBitrate 5000000 -FRAMES 10 -engine DX11 -threadcount 1 -Codec h264`

If you prefer to use the SimpleDecoder sample, you may modify it to use the FFmpeg File Demuxer and change the decoder ID to ` AMFVideoDecoderUVD_MJPEG`. There is no parser for the MJPEG format but the remaining code sample is the same.

**Comment by toruishihara** [comment]
I tested some *.mjpeg files downloaded from internet. It failed with AMF_SURFACE_UNKNOWN.
RawStreamReader.cpp GetFormatFromString() does not handle "mjpeg".

I like to know what kind of JPEG byte data and extra data passing to decoder.
And timestamp is mandatory or not.

**Comment by rhutsAMD** [comment]
1.	Which sample app are you using? If you are using TranscodeHW then it is unexpected for the app to try to use the RawStreamReader for a *.mpeg file instead of the FFmpeg File Demuxer.
2.	Which modifications have you made to the sample app, if any?
3.	What command line arguments are you using?
4.	Could you please share the details of the MJPEG file you are using or the location you have downloaded it from?

**Comment by toruishihara** [comment]
I use mjpeg file from this site: https://filesamples.com/formats/mjpeg
file : sample_1280x720_surfing_with_audio.mjpeg
This sample is top of Google search result with "mjpeg sample"

Run TranscodeHW.exe without modification with this command line.
 
`TranscodeHW.exe -input "sample_1280x720_surfing_with_audio.mjpeg" -output "output.mp4" -width 1280 -height 720 -usage transcoding -qualitypreset speed -RateControlMethod cqp -targetBitrate 5000000 -FRAMES 10 -engine DX11 -threadcount 1 -Codec h264`

Result :
```
DX11: List of adapters:
          0: Device ID: 15D8 [AMD Radeon(TM) Graphics]
DX11 : Chosen Device 0: Device ID: 15D8 [AMD Radeon(TM) Graphics]
InitDX11() created HW DX11.1 device
InitDX11() created HW DX11 device
AMFCreateComponent(DemuxerFFMPEG) failed Error:AMF_FAIL
No threads were successfuly run
TranscodeHW.exe (process 36588) exited with code -101.
```

I got same result with other mjpeg files.
If you have mjpeg file which successfully run with TranscodeHW.exe, please let me know.

**Comment by rhutsAMD** [comment]
Please make sure you are building the project “ComponentsFFMPEG” as the TranscodeHW sample depends on it when using the SW decoder. We have noticed this project build dependency is missing in the CPPSamples solutions. This will be fixed in a future AMF release.

**Comment by toruishihara** [comment]
I made a sample.
https://github.com/toruishihara/amf_mjpeg_decoder
