### ISSUE TITLE
Video Encode API: HEVC Encoder is not yet included (Partially Answered)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#3]
I do not see any reference to H265 or HEVC in the code or an example on how to encode with it, only a decoding example. Is this still missing or did I just miss the one line that has it?

**Comment by nwgat** [comment]
the blog post [here](https://community.amd.com/community/gaming/blog/2016/08/16/high-quality-advanced-media-framework-streaming-and-recording-api-now-open-sourced) refers to it as well

**Comment by nwgat** [comment]
[`1.3.0.5 (19.07.2016) version`](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/Readme.txt)
 probably in the latest branch heh

**Comment by Xaymar** [comment]
/u/AMD_Robert answered this [on reddit](https://www.reddit.com/r/Amd/comments/4y10gr/today_we_released_a_new_version_of_the_amd_media/d6lkrzx), turns out it is not quite production ready yet. It'll most likely be in a future version.

**Comment by Tukan40** [comment]
stay tuned :)

**Comment by Xaymar** [comment]
I'd like to thank @Roph (In Issue #8) for sending me a copy of the AsVideoConv.exe, due to this I was able to find that HEVC is already supported. Simply use L"AMFEncoderHEVC" instead of L"AMFEncoderSVC" or L"AMFEncoderAVC" for initialization.

Using this knowledge, I can most likely find many more hidden parameters - some I have already discovered through tracing.

**Comment by Roph** [comment]
Well, over a month has passed and still nothing. Do you guys have a roadmap for supporting the advertised features such as HEVC or 2-pass encoding? Any ETA? :)

**Comment by Xaymar** [comment]
Implemented by commits:
- 1ee0166a35d2bb48d7c219ff491ea43f683c5d32
- dde744f39cf9162afd3779e932c0104cb65ea8c0
- 3852afaaf4b05925ee505dcc26a894ebe9dc15ce
