### ISSUE TITLE
OBS 0.16.2 H264 Encoder set to 60FPS, but file have less FPS

### ISSUE THREAD

**Issue by PNunesDev** [GPUOpen-LibrariesAndSDKs/AMF#30]
Hi xaymar not really sure if this is the place where I should report this, since OBS 0.16.2 have now your plugin built-in, but..
I had set the recording to 60FPS, and the game runs perfectly fine at 60FPS or above, altough, the video file ends up being 35FPS, or 39FPS or 48FPS, it's variable.
How can I solve this?

I left my obs log attached after a recording, I couldn't stop notice that obs failed to load some services too
https://gist.github.com/c4775e1b02e05cb044f31c138d2a1286

Cheers

**Comment by Xaymar** [comment]
No this is not the right place, this is for the AMF SDK. Please report it to the proper repository: https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/wiki/Troubleshooting

**Comment by Xaymar** [comment]
Can you close this issue report?
