### ISSUE TITLE
[Bug]: InitVulkan crashes

### ISSUE THREAD

**Issue by maxest** [GPUOpen-LibrariesAndSDKs/AMF#302]
**Setup (please complete the following information):**
 - OS: Windows 10
 - Driver Version: 30.0.15002.1004
 - GPU: RX 5700 XT
 - Which component has the issue: Vulkan interop

After call to InitVulkan, BUT with vulkan device pointer set, I get:
```
2022-03-25 16:09:09.567     32D4 [VulkanImportTable]   Error: ..\..\..\..\..\public\common\VulkanImportTable.cpp(404):Failed to aquire entrypoint vkGetPhysicalDeviceProperties2KHR
2022-03-25 16:09:09.567     32D4 [AMFDeviceVulkanImpl]   Error: ..\..\..\..\..\runtime\src\core\DeviceVulkanImpl.cpp(658):AMF_ERROR 1 : AMF_FAIL: CreateDeviceAndQueues() LoadInstanceFunctionsTableExt failed
2022-03-25 16:09:09.567     32D4 [AMFDeviceVulkanImpl]   Error: ..\..\..\..\..\runtime\src\core\DeviceVulkanImpl.cpp(444):AMF_ERROR 1 : AMF_FAIL: CreateDeviceAndFindQueues() failed
2022-03-25 16:09:09.567     32D4 [AMFContextImpl]   Error: ..\..\..\..\..\runtime\src\core\ContextImpl.cpp(885):AMF_ERROR 1 : AMF_FAIL: pDeviceVulkan->Init(pVulkanDevice)
```

In CapabilityManager.cpp, before this line:
`g_AMFFactory.GetDebug()->AssertsEnable(false);`
I added this code:
```
{
	amf::AMFContextPtr pContext;

	if (g_AMFFactory.GetFactory()->CreateContext(&pContext) != AMF_OK)
	{
		std::wcerr << L"Failed to instatiate Capability Manager.\n";
		return -1;
	}

	DeviceVulkan   deviceVulkan;

	{
		amf::AMFContext1Ptr pContext1(pContext);
		if (pContext1 != nullptr)
		{
			if (deviceVulkan.Init(0, pContext) == AMF_OK)
			{
				(pContext1->InitVulkan(deviceVulkan.GetDevice()) == AMF_OK);
			}			
		}
	}
}
```

Now, I hacked code around in DeviceVulkan.cpp. If I add this instance extension:
`VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME`
the problem goes away.

HOWEVER, when I decided to turn on Vulkan validation layer, that is to add layer
`VK_LAYER_KHRONOS_validation`
to ppEnabledLayerNames of instanceCreateInfo, call to InitVulkan crashes:
![image](https://user-images.githubusercontent.com/37375338/160149129-c84645be-8585-4e7b-a343-dc5f0b1de185.png)

I would expect InitVulkan to work with validation layer turned on.

**Comment by MikhailAMD** [comment]
You are right. VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME already added to DeviceVulkan.cpp in the latest update.
AMF is not compatible with Vulkan debug layers because it is using private VK extensions unknown to debug layers. We understand the inconvenience and looking it.

**Comment by maxest** [comment]
Got it.
Also, I stumbled upon another problem. When I called context's GetVulkanDeviceExtensions AFTER vkCreateInstance, then vkCreateDevice would fail saying that extension
`VK_AMD_video_encode_queue_pvt`
could not be found. Surprisingly, when I removed this extension from the list of extensions returned by GetVulkanDeviceExtensions, everything worked without any problems.

I don't think GetVulkanDeviceExtensions so implicitly assumes that vkCreateInstance has not yet been called. It should return an error in that case.

**Comment by MikhailAMD** [comment]
Without this extension AMF would fall back to older encoder. This currently works but you will loose many features. The app should call GetVulkanDeviceExtensions before anything related to Vulkan.

**Comment by maxest** [comment]
We use Vulkan interop only in our decoding app, where the decoded data goes straight into a Vulkan image that we're displaying. On the encoding side/app, our input data is on cpu, so we use CreateSurfaceFromHostNative, no Vulkan interop whatsoever. So I guess we would see no difference having `VK_AMD_video_encode_queue_pvt` extension or not?

**Comment by MikhailAMD** [comment]
I guess, yes, but in general, we cannot guarantee backwards compatibility beyond AMF API. The list of extensions had been changed and can be changed in the future.
