### ISSUE TITLE
[Question]:how do we compile this on linux

### ISSUE THREAD

**Issue by RyzenDew** [GPUOpen-LibrariesAndSDKs/AMF#304]
So I want to know how do we compile this on linux the instructions are not clear and a friend wants to included amf with obs on nobara os a fedora spin meant for creators and gamers. 

Please be kind it would be super useful to the community to know thanks.

**Comment by rhutsAMD** [comment]
I have updated the Wiki to include Linux and Windows build instructions. Please take a look here:
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki
