### ISSUE TITLE
[Question]: AMFDisplayCapture supported device list

### ISSUE THREAD

**Issue by dreifachstein** [GPUOpen-LibrariesAndSDKs/AMF#308]
The AMFDisplayCapture component does not seem to work on legacy GPUs where the component can be created but fails on initiaization: 

> 2022-04-08 12:03:34.702     5538 [AMFScreenCaptureEngineImplDX11]   Error: ..\..\..\..\..\runtime\src\components\ScreenCapture\DX11\ScreenCaptureEngineDX11.cpp(100):Assertion failed:GetExtInterface(AmdDxExtScreenCaptureID) failed
> 2022-04-08 12:03:34.702     5538 [AMFScreenCaptureImpl]   Error: ..\..\..\..\..\runtime\src\components\ScreenCapture\ScreenCaptureImpl.cpp(154):AMF_ERROR 1 : AMF_FAIL: InitDisplayCapture() failed

**Comment by MikhailAMD** [comment]
Which GPU and which drivee version?

**Comment by dreifachstein** [comment]
- 7870K APU
- Radeon R5 420 (Oland)
Both running legacy driver 21.5.2

**Comment by MikhailAMD** [comment]
This driver doesn't support Direct Capture. Internal SW version in Radeon Settings should be 21.40.xx.xx or later.
