### ISSUE TITLE
[Bug]: Video artifacts when decoding certain H.264 via ffmpeg dxva/d3d11va

### ISSUE THREAD

**Issue by nyanmisaka** [GPUOpen-LibrariesAndSDKs/AMF#309]
**Describe the bug**
ffmpeg d3d11va/dxva decoder produce corrupted frames on AMD GPU but works fine on Intel and Nvidia GPU, [resulting video artifacts in LAVFilters](https://github.com/Nevcairiel/LAVFilters/issues/486) that used in MPC-HC video player too.

**To Reproduce**
1. Download the video sample from https://bit.ly/37rwrno
2. Run `ffmpeg.exe -hwaccel d3d11va -hwaccel_output_format nv12 -i "WALL-E-024.mkv" -y corrupted1.yuv`
3. Run `ffmpeg.exe -hwaccel dxva2 -hwaccel_output_format nv12 -i "WALL-E-024.mkv" -y corrupted2.yuv`
4. Run `ffmpeg.exe -i "WALL-E-024.mkv" -y fine.yuv`
5. Both d3d11va and dxva decoder produce corrupted data but software decoder works fine.

**Setup (please complete the following information):**
 - OS: Windows 10
 - Driver Version: 22.4.1
 - GPU: Radeon Graphics on 5700G APU, RX Vega 64
 - Which component has the issue: Decoder

**Expected behavior**
No artifacts and corrupted frames.

**Screenshots**
![1](https://user-images.githubusercontent.com/14953024/162609761-96dd4851-c43b-48b2-a4ad-e90e6fa03160.png)

**Additional context**
```
General
Unique ID                      : 146628897135855929091513478022359267749 (0x6E4FB2C86B1C314FA8AC85A924DDB9A5)
Complete name                  : WALL-E-024.mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 97.0 MiB
Duration                       : 28 s 737 ms
Overall bit rate mode          : Variable
Overall bit rate               : 28.3 Mb/s
Movie name                     : WALL-E
Encoded date                   : UTC 2021-11-29 14:31:42
Writing application            : mkvmerge v63.0.0 ('Everything') 64-bit
Writing library                : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.1
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 4 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 28 s 737 ms
Bit rate mode                  : Variable
Bit rate                       : 28.3 Mb/s
Maximum bit rate               : 30.5 Mb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.569
Stream size                    : 97.0 MiB (100%)
Language                       : English
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709


```

**Comment by MikhailAMD** [comment]
The clip is non-standard. The first frame is not IDR and there are other errors. While some decoders can hide some errors, this is not guaranteed:. here is screenshot from analyzer:
![image](https://user-images.githubusercontent.com/15144639/162754006-fae22eca-e10b-46fa-a20e-7c72446b35d1.png)

**Comment by nyanmisaka** [comment]
I see. But actually Films&TV player can decode it correctly on AMD.

**Comment by MikhailAMD** [comment]
ffmpeg and Films&TV have different parsers for elementary stream, while DXVA or D3D11VA (HW decoder) are the same. I tried the clip with AMF sample PlaybackHW - first few frames show blocky corruption -but no green. Then the playing is OK. This is expected with such reference errors in the stream. Note, that AMF decoder has own elementary stream parser.

**Comment by nyanmisaka** [comment]
Thanks! Any chance to add a workaround at driver level to handle this corner case? Since the clip play fine without any blocky or greeny on Intel and Nvidia DXVA/D3D11VA when using the same elementary stream parser in ffmpeg.

**Comment by MikhailAMD** [comment]
I am not sure it is a driver issue. Films&TVs just skip first two corrupted frames. You should check the first two frames on IN and NV platforms. 
In any case, working to get-arounds for bad clips would be low priority.

**Comment by mitzsch** [comment]
So I guess this one is an FFmpeg windows issue then? (hw decoding on linux with an amd gpu is fine with the provided sample)
