### ISSUE TITLE
Support for fully fledged Variable Bitrate (Target & Peak Bitrate)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#31]
Right now I do not see a way to do this, but it would be nice to have for services like YouTube, Beam and Hitbox which support Variable Bitrate (if it doesn't go too low). Technically all that is needed is Filler Data support for Variable Bitrate and everything would be okay.

**Comment by MikhailAMD** [comment]
Well, adding filler data converts VBR into CBR. The result will be nearly identical. I consulted with codec experts. They recommend to try VBR with peaks and try larger VBV buffer to preserve quality. With normal buffering in the player (about 16 frames) there is very low risk that VBR would cause a glitch during playback of scenes with a lot of changes.

**Comment by Xaymar** [comment]
It's not a glitch I'm talking about, but most of these services will end the stream if they detect a bitrate too low - which VBR can have since it only uses Peak Bitrate and not Target Bitrate. Adding Filler Data here would not make it CBR, since CBR has only a Target Bitrate, while VBR has a Peak and Target Bitrate and Filler Data should only be added until it reaches the Target Bitrate. But I understand if this is not wanted, as right now this is a software encoding only feature.

**Comment by MikhailAMD** [comment]
You are right in the sense that it is possible to have peaks outside of target bit rate and filler data for low areas. Though not standard, we may consider this for the future if there is enough of use case weights.

**Comment by Xaymar** [comment]
As most sites now support some form of VBR as long as the connection doesn't drop, I don't think this feature is necessary anymore. I believe the only site causing problems is beam now, which largely uses their own protocol anyway.
