### ISSUE TITLE
[Question]: <Why is AMF_ENCODER_NOT_PRESENT returned?>

### ISSUE THREAD

**Issue by yhmun** [GPUOpen-LibrariesAndSDKs/AMF#317]
I wonder why I got an error code with AMF_ENCODER_NOT_PRESENT when initializing the H.264 encoder failed on a heavy workload running on GPU (S7150X ). What factors cause this:
- OS version
- GPU model
- Catalyst version
- or Something else?

**Comment by MikhailAMD** [comment]
Everything factor you mentioned does matter. This GPU has H264 encoder. Are you running apps in VM or GPU bare-metal setup? Which driver version? Which OS, Which app?

**Comment by yhmun** [comment]
It works fine with no workload. It fails with heavy workloads randomly (like multiple remote desktop sessions running open-GL apps that consume nearly 95% or higher GPU usage)
- CreateComponent(AMFVideoEncoderVCE_AVC): OK
- Encoder->GetCaps(): OK
- Encoder->SetProperty(): OK
- Encoder->Init(AMF_SURFACE_BGRA, 1920, 1080): Fails when GPU runs the heavy workload

-- System Detail ----
OS: Microsoft Windows Server 2019 Version 10.0  (Build 17763)
CPU: Genuine Intel Intel(R) Xeon(R) CPU E5-1607 v3 @ 3.10GHz
GPU model: AMD FirePro S7150
Driver version: 26.20.11024.1 (2019-06-11)
App: a sort of Remote Desktop

**Comment by MikhailAMD** [comment]
My guess is, that HW encoder is out of sessions (16 is current max). Each remote desktop session may use at least one encoder session. But try to update the driver to a newer version.

**Comment by nathankidd** [comment]
> My guess is, that HW encoder is out of sessions (16 is current max). Each remote desktop session may use at least one encoder session. 

In this case encode is happening in the system session (service app).   Are you saying for the entire system there is a 16 encode session max, but each desktop session should be guaranteed at least one encode session?

Is there somewhere to read more about encoder session limitations as related to desktop sessions?

**Comment by MikhailAMD** [comment]
In older GPUs like yours this is total system limit. You can get it from encoder CAPs property:  AMF_VIDEO_ENCODER_CAP_NUM_OF_STREAMS. Newer systems don't have such limitation. There is no guarantee here. First come, first served. And it is not limited or unique to desktop session. What counts is number of encode sessions created on the system by any application.

**Comment by yhmun** [comment]
Thanks!!
