### ISSUE TITLE
[Request]: <2 pass encoding hevc, and avc>

### ISSUE THREAD

**Issue by LuisB79** [GPUOpen-LibrariesAndSDKs/AMF#318]
Allow for 2 pass encoding using hw acceleration

**Comment by rhutsAMD** [comment]
1. `AMF_VIDEO_ENCODER_PREENCODE_ENABLE` / `AMF_VIDEO_ENCODER_HEVC_PREENCODE_ENABLE`
Enables or disables rate control pre-analysis, disabled by default.
When it is enabled, the encoder will lookahead for 1 frame and encode it with ¼ resolution at first. The second pass will use the result from the first encoding pass and will optimize the **rate control** settings in the second pass encoding.


2. `AMF_VIDEO_ENCODER_HIGH_MOTION_QUALITY_BOOST_ENABLE` / `AMF_VIDEO_ENCODER_HEVC_HIGH_MOTION_QUALITY_BOOST_ENABLE`
Enables high motion quality boost mode. It pre-analyzes the motion of the video and uses the information for better encoding.
When it is enabled, the encoder will lookahead for 1 frame and encode it with ¼ resolution at first. The second pass will use the result from the first encoding pass and will optimize the **motion search** in the second pass encoding.

Both options can be enabled simultaneously. The total overhead from both features being enabled simultaneously is less than the sum of each feature enabled individually.

**Comment by cs9kc** [comment]
> 2\. Enables high motion quality boost mode. It pre-analyzes the motion of the video and uses the information for better encoding.

Hi @rhutsAMD!  In the documentation for the PreAnalysis module, it is listed that VBAQ and PREENCODE are disabled when the PA module is enabled. 

Given that High Quality Motion Boost appears to work in a similar way to PREENCODE, does enabling the PA module also disable High Quality Motion Boost, too?

Thanks!

**Comment by MikhailAMD** [comment]
PA (AMF_VIDEO_ENCODER_PRE_ANALYSIS_ENABLE) feature enables pre-analyze of the input video and allows user to enable some PA features listed in table 1. It also allows user to enables some other feature such as: 
AMF_VIDEO_ENCODER_ADAPTIVE_MINIGOP
Or AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD = QVBR, HQVBR or HQCBR.

PA will add extra latency so it is recommended to enable only under these rate control methods: AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD = VBR or QVBR, HQVBR or HQCBR.
PA can work with pre-encode assisted rate control (AMF_VIDEO_ENCODER_PREENCODE_ENABLE) and extended 2 pass motion search (AMF_VIDEO_ENCODER_HIGH_MOTION_QUALITY_BOOST_ENABLE). Thanks for pointing out this issue and we will update our documents in the near future.

**Comment by cs9kc** [comment]
Excellent!  Thank you for the information!

> Or AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD = QVBR, HQVBR or HQCBR.

I don't even see these rate control methods in the code, yet.  I would love to know more about them in the upcoming documentation, too (including which int that each lives in, for both AVC and HEVC, if possible).  <3

**Comment by LuisB79** [comment]
Closing this out of relevance.
