### ISSUE TITLE
[Request]: <Hw accelerated Cpu encoding>

### ISSUE THREAD

**Issue by LuisB79** [GPUOpen-LibrariesAndSDKs/AMF#319]
Allow for hw encoding to do a first pass and pass the data struct to another cpu encoder, x265, aomenc, etc.

**Comment by rhutsAMD** [comment]
This feature is not currently supported and unfortunately we cannot discuss possible future features in this forum.

**Comment by LuisB79** [comment]
> This feature is not currently supported and unfortunately we cannot discuss possible future features in this forum.

where can possible future features be discussed?

**Comment by LuisB79** [comment]
closing this, as requests aren't being taken
