### ISSUE TITLE
Video Encode API: B-Frames broken on VCE 2 GPUs

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#32]
Reported by quite a few users, it seems that setting B-Pictures to anything but 0 causes severe flickering artifacts or even makes the output outright unwatchable. It only affects VCE 2 cards, VCE 3 cards have no issues like this at all.

Examples:
- 1st Example: https://www.youtube.com/watch?v=bOvXzNpiobg (first part before the black screen)
- 2nd Example: [B-Pictures at 3](https://www.twitch.tv/everyth1ngtv/v/93029772), [B-Pictures at 0](https://www.twitch.tv/everyth1ngtv/v/93030078), [Log File](https://obsproject.com/forum/attachments/2016-10-04-17-23-29-txt.19845/)

**Comment by MikhailAMD** [comment]
Could you please ask to share the actual recorded file that demonstrates the problem and information about player used to view? Not much I can do with streams from youtube or twitch.

**Comment by Xaymar** [comment]
Files:

* 2nd Example: [Video](http://www.mediafire.com/file/1lrrrsbg00jld8h/AMD+VCE+2.0+B+Frames+Issue+10+11+16.mp4) [Log](http://www.mediafire.com/file/cjjjp1d6fd86wkq/2016-10-11_16-05-13.txt)

I've watched this with MPC-HC, Windows Media Player and VLC and both show this, so I don't think this is a player issue.

**Comment by MikhailAMD** [comment]
Reproduced and internal ticket issued.

**Comment by MikhailAMD** [comment]
The fix should be in the release hot fix driver: 16.11.1
http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-Edition-16.11.1-Release-Notes.aspx

**Comment by Xaymar** [comment]
Seen no quality complaints lately with B-Pictures, so I'll close this now.
