### ISSUE TITLE
[Question]: Using the new OBS Studio w/AMF encoder, for the first few seconds, encoder overloads & framerate tanks w/PreAnalysis, but ok after that

### ISSUE THREAD

**Issue by cs9kc** [GPUOpen-LibrariesAndSDKs/AMF#323]
Hello all.  While using OBS Studio's new AMD AMF encoder that one can directly send settings to, I have run across an issue with PreAnalysis.  The build of OBS Studio with the new AMD AMF encoder can be found here: https://github.com/obsproject/obs-studio/pull/6508

When EnablePreAnalysis (or HEVCEnablePreAnalysis) are set to true, OBS Studio gives an Encoder Overloaded message during the first 2-3 seconds of any recording, using both with H264 and H265/HEVC.  Likewise, during that overloaded period, the encoded video's framerate drops to 1-5fps for the first few seconds.  I have tried many combinations of rate control and other settings, but so long as PreAnalysis is enabled, the encoder overloads and framerate runs at 1-5fps for the first few seconds.  The encoder usage in task manager does spike up to near 100% during the encoder overload in OBS Studio.

Strangely, after the initial overload, the video encodes as expected, nice and smoothly.

Below is the most recent of the few H264 setting groups that I tried with the new encoder, while trying to narrow down what may be causing the overload
> RateControlMethod=1 Profile=100 ProfileLevel=42 QualityPreset=2 IDRPeriod=120 TargetBitrate=7000000 PeakBitrate=7200000 VBVBufferSize=14000000 InitialVBVBufferFullness=64 MaxNumRefFrames=4 FillerDataEnable=true HalfPixel=true QuarterPixel=true MaxOfLTRFrames=0 EnforceHRD=true DeBlockingFilter=true HighMotionQualityBoostEnable=false EnablePreAnalysis=true RateControlSkipFrameEnable=true AdaptiveMiniGOP=true MaxConsecutiveBPictures=3 BPicturesPattern=3 BReferenceEnable=true PASceneChangeDetectionEnable=false

I haven't marked this as a bug since I don't know if it is an issue with OBS Studio's new encoder setup, or whether it is due to a combination of settings that I am not setting properly.

Windows 11 Pro, Reference RX 6900 XT LC, WHQL 22.5.2 drivers

*Edit:  I'll add the context that I do realize that the PA module and use of B-frames do mean that the first small bit of a video file is going to be unplayable since there's reference frames and other analysis being done to the video stream as it is being processed, I just want to make sure I'm not doing anything wrong, since that "start-up" eats basically the first two GOP's (using 2-second gop w/cbr), and results in an "encoder overload".

Thank you for your time!

**Comment by cs9kc** [comment]
I poorly worded this issue submission.  I will re-submit with more-clear intent, information, and questions, at a later time.

**Comment by azamet90** [comment]
i have the same gpu and encoding lag problems on streaming with preanalysis also, did you managed to fix that problem?
