### ISSUE TITLE
Actually increase the Runtime version with each driver build.

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#33]
Currently AMFQueryVersion will always return 1.3.0.5, which makes it impossible to tell what driver a user is actually on - there are about 12 drivers that contains 1.3.0.5, so how would I tell them apart without querying another interface?

AMF already has a define called AMF_VERSION_BUILD_NUM, it would be nice if it was increased for every driver build in the future.

**Comment by MikhailAMD** [comment]
The version represents API changes, not the build number. I understand that you want to code against driver but.... As some analogy: you don't code against driver version for WIn32 or DirectX APIs though drivers may have bugs.
The version allows AMF potentially block forward compatibility (doesn't happen now) and ensure backward compatibility.

**Comment by MikhailAMD** [comment]
You can get version number of the DLL using Win32 version API. Check DLL properties, Details tab: "Product version" field changes with every build. 
GetFileVersionInfo(), VerQueryValue() etc.

**Comment by Xaymar** [comment]
Done, thanks for the help!
