### ISSUE TITLE
[Question]: DLL libamfrt64.so.1 failed to open

### ISSUE THREAD

**Issue by 21pages** [GPUOpen-LibrariesAndSDKs/AMF#335]
ffmpeg `avcodec_open2` failed
```
[h264_amf @ 0x7fb3e8001180] DLL libamfrt64.so.1 failed to open
avcodec_open2: Unknown error occurred
```
but I can't find `libamfrt64.so.1`, a teammate install new amd driver, but cause the display screen to be black.
system: ubuntu22.04, not virtual machine

How can I install `libamfrt64.so.1`?

If I use AMD to decode, can I use vaapi or vdpau? Is there any other way？

**Comment by MikhailAMD** [comment]
Several topics:
1. Follow installation instructions for AMD Pro/Workstation driver: https://amdgpu-install.readthedocs.io/en/latest/ 
2. AMF installation command line: amdgpu-install --usecase=workstation,amf -y --vulkan=pro --opencl=rocr,legacy
3. AMF decoder is not integrated into ffmpeg. You should use VAAPI

**Comment by jjasoncool** [comment]
If my system doesn't support amdgpu-install
How to solve this issue?

**Comment by jjasoncool** [comment]
I am try to bring `amf-amdgpu-pro-1.4.36-2125445.el9.x86_64.rpm`'s libamfrt64.so.1 into my fedora.

But it's have more problems.

Can you give me some pointers so I can transplant it myself?

In addition, I used 7900XTX to study for a day and there seems to be no progress

Thanks to AMD for its contribution to the open source community

I just think it's a pity because I have difficulty using ffmpeg

**Comment by MikhailAMD** [comment]
You also need libencenc64.so and matching VCN FW and probably some common staff. It is all in separate packages. check archLinux as they seem figured out which packages are needed.

**Comment by jjasoncool** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/392

**Comment by jjasoncool** [comment]
> You also need libencenc64.so and matching VCN FW and probably some common staff. It is all in separate packages. check archLinux as they seem figured out which packages are needed.

May I ask where `libencenc64.so` is?
I can't find in amf-amdgpu-pro-1.4.36-2125445.el9.x86_64.rpm
