### ISSUE TITLE
Missing 'defined' in preprocessor check

### ISSUE THREAD

**Issue by BtbN** [GPUOpen-LibrariesAndSDKs/AMF#339]
The following line appears to be missing the 'defined', causing a compile time warning, and potentially some issue when actually using clang on non-linux.

https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/9c7189ebb0a78e7e9287547b7898995abf268af8/amf/public/include/core/Platform.h#L75

**Comment by rhutsAMD** [comment]
Thanks for noticing this! It has been fixed and will be available in an upcoming release.

**Comment by rhutsAMD** [comment]
Yes, it has been corrected to `defined(__ANDROID__)`.

**Comment by rhutsAMD** [comment]
The fix is now available in the latest release [v1.4.26](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v1.4.26)
