### ISSUE TITLE
Video Encode API: How to query MaxOfReferenceFrames?

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#34]
The documentation says that some parameters are only available when MaxOfReferenceFrames is greater than 1. There is no such parameter in VCECaps though, so how do I query this?

The closest I found is:

* AMF_VIDEO_ENCODER_CAP_MIN_REFERENCE_FRAMES
* AMF_VIDEO_ENCODER_CAP_MAX_REFERENCE_FRAMES

For my card, it returns 1 - 16. For a VCE 1 card it also returns 1 - 16 but AMF_VIDEO_ENCODER_CAP_BFRAMES is 0. Is this a driver bug?

**Comment by MikhailAMD** [comment]
Reference frames and B-frames are kind of unrelated. Imaging there are no B-frames. And stream is:
IPPPPPPPPPPPPPPPPPI . I-frames don't have references. But P-frames may use from 1 to N number of reference frames before them. The same is true for B-frames. VCE1 doesn't have B-frames but P-frames still refer to other frames.

**Comment by Xaymar** [comment]
So the only things I should be looking at is AMF_VIDEO_ENCODER_CAP_BFRAMES and make sure that NumOfLTR is 0 when B-Pictures should be used. The documentation states this at the moment, which might not be correct here:

```
BPicturesDeltaQP, ReferenceBPicturesDeltaQP, IntraRefreshNumMBsPerSlot, BPicturesPattern and BReferenceEnable parameters are available only when:

* MaxOfReferenceFrames is greater than 1
* NumOfLTR is 0 (LTR is not used)
```

**Comment by MikhailAMD** [comment]
Yes, in short, B- frames are possible if  max number of ref frames are > 1 and LTRs are not used.

**Comment by Xaymar** [comment]
Alright. Thanks.
