### ISSUE TITLE
[Bug]: RX 6700 doesn't support P010 input

### ISSUE THREAD

**Issue by arancino1** [GPUOpen-LibrariesAndSDKs/AMF#341]
while enumerating the input capabilities with GetNumOfFormats() there's no support for P010 being shown.

AMF_VIDEO_ENCODER_HEVC_PROFILE_MAIN_10 seems to be supported Win10 System with a RX 6700. Contrary to a old RX 570 which shows P010 as supported on this system with a RX6700 it's apparently not. Why is that?
 
Win10, RX 6700, SDK v1.4.24, current driver: 30.0.21023.1015

P010 should be supported on all cards capable of 10bit HEVc encoding. Which input format should be used for 10bit HEVC encoding if there's no P010?

**Comment by rhutsAMD** [comment]
This issue has been fixed and confirmed working on recent Radeon™ Software Adrenalin driver release version 23.3.1 (22.40.37.01).
