### ISSUE TITLE
[Question]: Is there any alternative to polling QueryOutput() on the encoder?

### ISSUE THREAD

**Issue by SebastianSchumm** [GPUOpen-LibrariesAndSDKs/AMF#343]
Dear AMF-Team,

I am currently experimenting with video encoding performance using AMF.
Our use case is low latency streaming, so we configured the encoder accordingly to have 1 frame input leading to 1 package output.
According to all samples, documentation and discussions here, we need to poll QueryOutput() on the encoder to get the output.
To not busy loop the CPU, the samples use amf_sleep(1) plus amf_increase_timer_precision().
To reduce the latency, we would like to fetch the result as early as possible. In my measurements, a busy loop without sleep is about 10% faster than the sleep version. So, we would like to get rid of this extra ms.
Is there any way to wait for the exact end of the encoding, make QueryOutput blocking, receive an event or similar?

Sebastian

**Comment by MikhailAMD** [comment]
Hi, yes there is a simple way. Set AMF_VIDEO_ENCODER_QUERY_TIMEOUT property for H264 to something like 50. it is in milliseconds. There is a similar property for HEVC. It will force QueryOutput to block the call and wait till an output frame is ready or till timeout value. You can keep your polling code for safety reasons but with such approach it will almost never happen.

**Comment by SebastianSchumm** [comment]
Hi Mikhail,
thanks a lot for the quick help! Now that I know what to search for, I found AMF_VIDEO_ENCODER_HEVC_QUERY_TIMEOUT being set in the EncoderLatency sample as well. Doing this perfectly works as desired.

Sebastian

**Comment by guygodin** [comment]
> Hi, yes there is a simple way. Set AMF_VIDEO_ENCODER_QUERY_TIMEOUT property for H264 to something like 50. it is in milliseconds. There is a similar property for HEVC. It will force QueryOutput to block the call and wait till an output frame is ready or till timeout value. You can keep your polling code for safety reasons but with such approach it will almost never happen.

Would it be possible to add such a property for the video converter as well since we need to call QueryOutput on the converter as well (when doing RGBA -> H.264/HEVC)? Thanks!
