### ISSUE TITLE
[Question]:  About AMFDisplayCapture on Ubuntu 22.04

### ISSUE THREAD

**Issue by gang929** [GPUOpen-LibrariesAndSDKs/AMF#345]
When using AMFDisplayCapture to capture screen,  The code 
```
    res = g_AMFFactory.GetFactory()->CreateComponent(m_pContext, AMFDisplayCapture, &m_pDisplayCapture);
    CHECK_AMF_ERROR_RETURN(res, "AMFCreateComponent AMFDisplayCapture failed");
    ....
    res = m_pDisplayCapture->Init(amf::AMF_SURFACE_UNKNOWN, 0, 0);
    CHECK_AMF_ERROR_RETURN(res, "Failed to make AMFDisplayCapture");
```
report error 
```
0122-07-18 16:28:41 4870A640 [AMFScreenCaptureImpl]   Error: ../../../../../runtime/src/components/ScreenCapture/ScreenCaptureImpl.cpp(249):Assertion failed:Failed to create capture engine type 0
```
OS: Ubuntu 22.04.1  5.15.0-46
Display Adapter: AMD RX 470
Amd Driver: amdgpu-install_22.20.50200-1_all.deb

Is the Device RX470 not supported or other reason?

**Comment by MikhailAMD** [comment]
It looks like you did not initialize Vulkan and AMFContext with Vulkan. For simple cases use AMFContext1::InitVulkan(NULL).

**Comment by gang929** [comment]
Thanks, It's right.
The demo is copy from example DVR, It's run with windows, not init vulkan.   I miss it.

**Comment by gang929** [comment]
Hello @MikhailAMD
When add the vulkan Init,  AMFDisplayCapture is created and Init successed, But, 
```
res = m_pDisplayCapture->QueryOutput(&data);
```
The data is always NULL and res is AMF_REPEAT

What about it, missed something?

**Comment by MikhailAMD** [comment]
Few things to check:
1. Anything in the log?
2. What capture mode do you use? "AMF_DISPLAYCAPTURE_MODE_WAIT_FOR_PRESENT" mode doesn't work yet in Linux. Please use AMF_DISPLAYCAPTURE_MODE_KEEP_FRAMERATE.

**Comment by gang929** [comment]
The  capture mode is AMF_DISPLAYCAPTURE_MODE_WAIT_FOR_PRESENT, `m_pDisplayCapture->Init` return OK, and no warning or error log.
But replace  "AMF_DISPLAYCAPTURE_MODE_WAIT_FOR_PRESENT"  by " AMF_DISPLAYCAPTURE_MODE_KEEP_FRAMERATE", the Init will fail.
Init Code
```
    res = g_AMFFactory.GetFactory()->CreateComponent(m_pContext, AMFDisplayCapture, &m_pDisplayCapture);
    CHECK_AMF_ERROR_RETURN(res, "AMFCreateComponent AMFDisplayCapture failed");
    res = m_pDisplayCapture->SetProperty(AMF_DISPLAYCAPTURE_MONITOR_INDEX, m_monitorID);
    CHECK_AMF_ERROR_RETURN(res, "Failed to set monitor ID");
    res = m_pDisplayCapture->SetProperty(AMF_DISPLAYCAPTURE_CURRENT_TIME_INTERFACE, m_pCurrentTime);
    CHECK_AMF_ERROR_RETURN(res, "Failed to set current time interface");
    res = m_pDisplayCapture->SetProperty(AMF_DISPLAYCAPTURE_FRAMERATE, AMFConstructRate(30, 1));
    CHECK_AMF_ERROR_RETURN(res, "Failed to set frame rate");
    res = m_pDisplayCapture->SetProperty(AMF_DISPLAYCAPTURE_MODE, AMF_DISPLAYCAPTURE_MODE_KEEP_FRAMERATE);
    CHECK_AMF_ERROR_RETURN(res, "Failed to set CAPTURE_MODE");
    res = m_pDisplayCapture->Init(amf::AMF_SURFACE_UNKNOWN, 0, 0);
```
log
```
0122-08-07 22:03:30 FFC8E640 [AMFScreenCaptureEngineImplDRM]   Error: ../../../../../runtime/src/components/ScreenCapture/drm/ScreenCaptureEngineDRM.cpp(339):Assertion failed:Cannot find sutable plane for Crtc ID55
0122-08-07 22:03:30 FFC8E640 [AMFScreenCaptureEngineImplDRM]   Error: ../../../../../runtime/src/components/ScreenCapture/drm/ScreenCaptureEngineDRM.cpp(245):AMF_ERROR 1 : AMF_FAIL: ReloadTextures() failed
0122-08-07 22:03:30 FFC8E640 [AMFScreenCaptureImpl]   Error: ../../../../../runtime/src/components/ScreenCapture/ScreenCaptureImpl.cpp(289):AMF_ERROR 1 : AMF_FAIL: InitDisplayCapture() failed
```

**Comment by MikhailAMD** [comment]
1. Do you run process as root/sudo?
2. Do you have physical display attached or some kind of virtual display/remote access?

**Comment by gang929** [comment]
1. Use sudo to run app
2. The pc has a monitor AOC 19'', that is connect to HDMI-A-1

**Comment by MikhailAMD** [comment]
So does it work?

**Comment by gang929** [comment]
Thanks! Yes, it worked.
At first, it ran with root. After the os several restarts, I forgot to switch to root
