### ISSUE TITLE
[Question]: is there a motion estimation only mode?

### ISSUE THREAD

**Issue by mbucchia** [GPUOpen-LibrariesAndSDKs/AMF#347]
Hello,

Is there a mode to compute motion vectors from 2 input images?

I've not found anything in the doc. The closest looked like the PreAnalysis "activity map" but it doesn't actually looks like motion vectors (the output only has one component).

Thank you.

**Comment by rhutsAMD** [comment]
Motion vector output from AMF is not available to the public at this point. There are some thirdparty tools that can compute motion vectors between images or extract the motion vectors from encoded videos.

**Comment by mbucchia** [comment]
Thank you for the information.
