### ISSUE TITLE
[Question]: Requesting more information about "AMF_PA_LOOKAHEAD_BUFFER_DEPTH"

### ISSUE THREAD

**Issue by cs9kc** [GPUOpen-LibrariesAndSDKs/AMF#349]
Hello.  In researching the many features that the PreAnalysis Component provides, I can't seem to find much information about AMF_PA_LOOKAHEAD_BUFFER_DEPTH.  

Could you all provide some context as to:
- How this feature works
- What values are being set, and what range(s) is/are possible
- A TL;DR: on how it might affect encode quality
- Features that it may be incompatible with, if any

Thank you!

**Comment by rhutsAMD** [comment]
Please see responses inline:

- How this feature works

	__*The lookahead buffer depth determines how many previous frames must be processed in PA before the current frame’s type is decided and is sent to the encoder.*__

- What values are being set, and what range(s) is/are possible

	__*The maximum lookahead buffer depth is internally defined as 41. This creates a range of [0, 41] inclusive for the `AMF_PA_LOOKAHEAD_BUFFER_DEPTH`, where 0 would decide the frame type and send frames that are processed by PA to the encoder immediately.*__

- A TL;DR: on how it might affect encode quality

	__*The longer the lookahead depth, the better the encoding quality could be expected - possibly at the cost of encoding latency.*__
		__*For scene analysis, When AMF_PA_SCENE_CHANGE_DETECTION_ENABLE is enabled, lookahead depth will determine the scene analysis version, ` SA2 > SA1 > SA0 ` .*__
		__*[0, 10] -> SA0 (0 future frame version) *__
		__*[11, 20] -> SA1 (1 future frame version) *__
		__*[20, 41] -> SA2  (2 future frame version) *__

- Features that it may be incompatible with, if any

	__*The following are some recommendations when the lookahead buffer depth property is used in combination with other features:*__
	- __*For TAQ, a longer lookahead depth improves the quality. It is recommended to set lookahead depth to ` >= 20`.*__
	- __*When AMF_PA_HIGH_MOTION_QUALITY_BOOST_MODE is enabled, lookahead depth should be ` >= 1`.*__

**Comment by cs9kc** [comment]
@rhutsAMD Thank you so much for your quick reply!  This is very informative!  

A few more questions:

- When the PreAnalysis Component is invoked, what is the default lookahead depth (assuming one leaves all other PreAnalysis Component settings at their defaults; assuming one does not invoke any other PA parameters manually)?
- Do the number of available surfaces need to be increased as the lookahead buffer is increased?

Regarding the last question, forgive me if my understanding of the encoder is flawed/incomplete.  In a different issue ticket regarding B-frames, it turns out that giving more surfaces to the encoder solved the issue (3 was previously set, 10 is the value in OBS Studio 28.0.1 (current version as of this post).  I noticed that the frames dropped at the beginning of the encode decreased dramatically as well when the # of surfaces was increased to 10; even more-dramatically decreased in an experimental OBS Studio version with 20 surfaces.  

I say all of that in case the last question is related to the available surfaces.

Thank you for your time!

**Comment by cs9kc** [comment]
> The default value for `AMF_PA_LOOKAHEAD_BUFFER_DEPTH` is 0

I... knew this.  Sorry about that!  

And understood!  Thank you so much for the information <3
