### ISSUE TITLE
Video Encode API: AMF_VIDEO_ENCODER_B_REFERENCE_ENABLE is incorrectly logged

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#35]
When AMF_VIDEO_ENCODER_B_REFERENCE_ENABLE is set to true, the log file will show the following:

```
12:40:43.297: [VCEEncoderTrace]     Info:     encBPicPattern: 3
12:40:43.298: [VCEEncoderTrace]     Info:     disableBRefere: 1
```

Needless to say, that is wrong since BReference is enabled.

**Comment by MikhailAMD** [comment]
What is the nature of concern?
There are two different features: 
 - enable B-frames in the stream (AMF_VIDEO_ENCODER_B_REFERENCE_ENABLE)
- use/not use B-frames as reference frames for other frames (AMF_VIDEO_ENCODER_B_REFERENCE_ENABLE)

**Comment by Xaymar** [comment]
Merely debugging and logging. While it still uses the correct one, the log file will say disable instead of enable - which can confuse users and people trying to figure out what went wrong and where.

**Comment by MikhailAMD** [comment]
Again the features are independent. The case you log is the valid one.

**Comment by Xaymar** [comment]
Alright, got it.
