### ISSUE TITLE
[Question]: Requesting more information about "AMF_PA_HIGH_MOTION_QUALITY_BOOST_MODE"

### ISSUE THREAD

**Issue by cs9kc** [GPUOpen-LibrariesAndSDKs/AMF#350]
Hello.  In researching the many features that the PreAnalysis Component provides, I can't seem to find much information about the recently-added feature AMF_PA_HIGH_MOTION_QUALITY_BOOST_MODE.

Could you all provide some context as to:
- How this feature works compared to the standard "HIGH_MOTION_QUALITY_BOOST_ENABLE" that is available in the base encoder options for both H264 and HEVC?
- Is this feature best used without HIGH_MOTION_QUALITY_BOOST_ENABLE, or can/should they be used together?
- A TL;DR: on how it might affect encode quality
- Other features that it may be incompatible with, if any

Thank you!

**Comment by rhutsAMD** [comment]
Please see responses inline:

- How this feature works compared to the standard "HIGH_MOTION_QUALITY_BOOST_ENABLE" that is available in the base encoder options for both H264 and HEVC?

	__*The PA version uses shaders to do hierarchical motion search and generates motion vector hints to the encoder. The encoder versions use the HW encoder to search motion vectors with a reduced size at first, then these motion vectors are used as hints for the second round of formal encoding.*__

- Is this feature best used without HIGH_MOTION_QUALITY_BOOST_ENABLE, or can/should they be used together?

	You can only use one of the following at a time.
	`AMF_PA_HIGH_MOTION_QUALITY_BOOST_MODE`
	`AMF_VIDEO_ENCODER_HIGH_MOTION_QUALITY_BOOST_ENABLE` 
	`AMF_VIDEO_ENCODER_HEVC_HIGH_MOTION_QUALITY_BOOST_ENABLE`

- A TL;DR: on how it might affect encode quality

	__*A high motion quality boost mode can be enabled when encoding high motion videos to improve the quality. This is helpful especially when the motion is outside of the HW's motion search range.*__

- Other features that it may be incompatible with, if any

	__*High motion quality boost modes are not intercompatible with each other and cannot be enabled simultaneously.*__

**Comment by cs9kc** [comment]
Thank you so much for your explanation!  This helps tremendously with formulating some setting combinations that might be more-ideal for Twitch-bitrate (~6Mbit) CBR streaming with H264 using the latest OBS Studio with the updated AMF encoder implementation!

And just to confirm, AMF_PA_HIGH_MOTION_QUALITY_BOOST_MODE is still for AVC1 encoding only, and is not compatible with HEVC encoding?

Thanks again!

**Comment by rhutsAMD** [comment]
At this moment, `AMF_PA_HIGH_MOTION_QUALITY_BOOST_MODE` and `AMF_PA_LOOKAHEAD_BUFFER_DEPTH` are only supported for AVC encoding. Please stay tuned.

**Comment by cs9kc** [comment]
Thank you so much! <3
