### ISSUE TITLE
[Request]: Add HIP interop support for AMF Compute

### ISSUE THREAD

**Issue by TheNewSound** [GPUOpen-LibrariesAndSDKs/AMF#353]
**Is your feature request related to a problem? Please describe.**
I would like to have better performing AMF Compute kernels with greater flexibility provided by the HIP runtime. To achieve efficient realtime machine learning on video feeds, eliminating CPU-GPU roundtrip.

**Describe the solution you'd like**
Adding HIP interop with AMF, so HIP kernels can be scheduled before/after encoding/decoding. Especially a way to maintain  shared memory contents across the processing of frames would be useful for temporal analysis. An intermediate solution to this could be to decode & process 5 frames per HIP kernel launch. 

**Describe alternatives you've considered**
none

**Additional context**
Is adding HIP interop support something the AMF team can consider?

**Comment by LuisB79** [comment]
the amf team is as flexible as glass, i doubt they'll fully read your post.

**Comment by MikhailAMD** [comment]
AMF team does read every post but not comment on plans, upcoming releases or possible features.

**Comment by LuisB79** [comment]
As glass.
