### ISSUE TITLE
[Question]: Max bitrate for RX 6000-series limited to 100000 (100Mbps)?

### ISSUE THREAD

**Issue by Espionage724** [GPUOpen-LibrariesAndSDKs/AMF#357]
With Oculus on a RX 6600 XT, regardless of what bitrate is set in Oculus, it stays at 100Mbps. Oculus logs hint at the limit coming from AMF:

```
23/09 10:41:18.908 {INFO}    [xrstreaming] ---- AMD AMFVideoEncoderVCE_AVC Capabilities ----
 HW acceleration available
        MaxBitrate = 100000000
        MaxReferenceFrames = 16
        MaxTemporalLayers = 4
        NumOfStreams = 16
        MinReferenceFrames = 1
        MaxProfile = 100
        MaxLevel = 52
        BFrames = 1
        FixedSliceMode = Fail with error [11]
        NumOfHwInstances = 1
        ColorConversion = 0
```

A user on Guru3D forums reports that [VCEEnc](https://github.com/rigaya/VCEEnc) when told to encode at 200Mbps, gets limited to 100Mbps: https://forums.guru3d.com/threads/amd-software-adrenalin-edition-22-10-1-driver-download-and-discussion.444840/page-5#post-6058076

This notably affects how PCVR looks through a Quest 2 headset. Is there a bug somewhere? I don't know if this affects any other software or GPUs.

**Comment by Espionage724** [comment]
It looks like Oculus can go above 100 Mbps for both AVC and HEVC; this change was either from driver 22.9.1 -> 22.10.1 or an update on Oculus's end. [The peak bitrate is still reported to be 100 Mbps in Oculus logs](https://forums.guru3d.com/threads/amd-amf-and-gpu-encoding-issues-and-discussion-notably-for-vr.443275/#post-6059170), but manually setting a higher bitrate works.

I'm not sure about other software, but I suppose this is resolved for Oculus in my case.

**Comment by Anoobizzz** [comment]
Same issue i guess
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/364
