### ISSUE TITLE
[Bug]: AMF failed to initialize on the default Vulkan device: 1 on Ubuntu 22.04

### ISSUE THREAD

**Issue by rishubn** [GPUOpen-LibrariesAndSDKs/AMF#358]
**Describe the bug**
I'm trying to use FFMPEG with an amf encoder but get this error:
```
[h264_amf @ 0x56511bc2d200] AMF failed to initialize on the default Vulkan device: 1
[h264_amf @ 0x56511bc2d200] AMF initialisation is not supported.
```

**To Reproduce**
I installed the amdgpu_install script and ran:
`amdgpu_install --usecase=amf --vulkan=pro`

**Setup (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Driver Version [e.g. 22.2.1]
 - GPU: Ryzen 9 4900H

I know 22.04 isn't yet supported but I think this is related to an icd issue, but don't know how to solve it

**Comment by MikhailAMD** [comment]
Looks like an issue with Vulkan driver or driver in general.
Try the driver install CMD:  
amdgpu-install -y  --usecase=workstation,amf
or 
amdgpu-install -y  --usecase=graphics,amf

It should install Vulkan Pro driver as dependency.
And I assume this is bare-metal setup, not VM.

**Comment by rishubn** [comment]
Thanks for the quick reply!

Yes this is a bare metal setup; more specifically ubuntu server headless

Both install commands didn't do anything it seems:
```
$  amdgpu-install -y --usecase=graphics,amf
Hit:1 http://at.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://at.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://at.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://at.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://repo.radeon.com/amdgpu/22.20/ubuntu focal InRelease                 
Hit:6 https://repo.radeon.com/rocm/apt/5.2 ubuntu InRelease                           
Hit:7 https://repo.jellyfin.org/ubuntu jammy InRelease                                
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
linux-headers-5.15.0-50-generic is already the newest version (5.15.0-50.56).
linux-modules-extra-5.15.0-50-generic is already the newest version (5.15.0-50.56).
amf-amdgpu-pro is already the newest version (1.4.26-1438746~20.04).
amdgpu-dkms is already the newest version (1:5.16.9.22.20.50200-1438746~20.04).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-amdgpu-video-amdgpu : Depends: xorg-video-abi-24 but it is not installable
E: Unable to correct problems, you have held broken packages.
janitor@minicloud:~$  amdgpu-install -y --usecase=workstation,amf
Hit:1 http://at.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://at.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://at.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://at.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://repo.jellyfin.org/ubuntu jammy InRelease                 
Hit:6 https://repo.radeon.com/amdgpu/22.20/ubuntu focal InRelease     
Hit:7 https://repo.radeon.com/rocm/apt/5.2 ubuntu InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
linux-headers-5.15.0-50-generic is already the newest version (5.15.0-50.56).
linux-modules-extra-5.15.0-50-generic is already the newest version (5.15.0-50.56).
amf-amdgpu-pro is already the newest version (1.4.26-1438746~20.04).
amdgpu-dkms is already the newest version (1:5.16.9.22.20.50200-1438746~20.04).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-amdgpu-video-amdgpu : Depends: xorg-video-abi-24 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by rishubn** [comment]
Seems like the driver is loaded though:
```
janitor@minicloud:~$ lspci -k | grep -EA3 'VGA|3D|Display' 
06:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev f0)
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Renoir
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

**Comment by rishubn** [comment]
Sorry for the spam, vulkaninfo indicates a problem:
```
~$ vulkaninfo
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:649:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
```

**Comment by MikhailAMD** [comment]
OK, this confirms that this is not an AMF issue.

**Comment by rishubn** [comment]
> OK, this confirms that this is not an AMF issue.

I tried running `sudo vulkaninfo` and got what I assume is expected output. I can paste the full vulkaninfo if needed:
```
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file amd_icd32.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file amd_icd32.json
'DISPLAY' environment variable not set... skipping surface info
error: XDG_RUNTIME_DIR not set in the environment.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.204
....
```

**Comment by rishubn** [comment]
Will close this, you're right, it is still a vulkan issue

**Comment by 21pages** [comment]
> The following packages have unmet dependencies:
 xserver-xorg-amdgpu-video-amdgpu : Depends: xorg-video-abi-24 but it is not installable
E: Unable to correct problems, you have held broken packages.

How did you fix it?

**Comment by Mizuno-Mashiro** [comment]
@rishubn Have you solved the issue? I am having the same issue for hours and couldn't find a fix to it... I am using the Radeon 780M. These are some error messages:

> [h264_amf @ 0x5584aa279680] AMF failed to initialise on the given Vulkan device: 1.
[vost#0:0/h264_amf @ 0x5584aa278500] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[vf#0:0 @ 0x5584aa48a800] Error sending frames to consumers: Function not implemented
[vf#0:0 @ 0x5584aa48a800] Task finished with error code: -38 (Function not implemented)
[vf#0:0 @ 0x5584aa48a800] Terminating thread with return code -38 (Function not implemented)
[vost#0:0/h264_amf @ 0x5584aa278500] Could not open encoder before EOF
[vost#0:0/h264_amf @ 0x5584aa278500] Task finished with error code: -22 (Invalid argument)
[vost#0:0/h264_amf @ 0x5584aa278500] Terminating thread with return code -22 (Invalid argument)
[out#0/mp4 @ 0x5584aa0aea40] Nothing was written into output file, because at least one of its streams received no packets.

**Comment by rishubn** [comment]
> @rishubn Have you solved the issue? I am having the same issue for hours and couldn't find a fix to it... I am using the Radeon 780M. These are some error messages:
> 
> > [h264_amf @ 0x5584aa279680] AMF failed to initialise on the given Vulkan device: 1.
> > [vost#0:0/h264_amf @ 0x5584aa278500] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
> > [vf#0:0 @ 0x5584aa48a800] Error sending frames to consumers: Function not implemented
> > [vf#0:0 @ 0x5584aa48a800] Task finished with error code: -38 (Function not implemented)
> > [vf#0:0 @ 0x5584aa48a800] Terminating thread with return code -38 (Function not implemented)
> > [vost#0:0/h264_amf @ 0x5584aa278500] Could not open encoder before EOF
> > [vost#0:0/h264_amf @ 0x5584aa278500] Task finished with error code: -22 (Invalid argument)
> > [vost#0:0/h264_amf @ 0x5584aa278500] Terminating thread with return code -22 (Invalid argument)
> > [out#0/mp4 @ 0x5584aa0aea40] Nothing was written into output file, because at least one of its streams received no packets.

Unfortunately, I was never able to get it quite working and ultimately my solution was to switch to Intel
