### ISSUE TITLE
 AV1 Encoder

### ISSUE THREAD

**Issue by shiyue-code** [GPUOpen-LibrariesAndSDKs/AMF#359]
**I don't find  AV1 Encoder in AMF **
Will AV1 Encode be supported in the future?

**Comment by draconb** [comment]
Looking foward to it with RDNA 3

**Comment by rhutsAMD** [comment]
Closing this issue since AV1 encoding support was added with [AMF v.1.4.28](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/tree/v1.4.28) 😃
