### ISSUE TITLE
Video Encode API: Expose additional Properties

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#36]
To split the "expose some properties" from my GitHub, here is the ones I'd like to be able to control without having to rely on reverse engineering to understand how they work:

### CABACEnable
CABAC is a more efficient way of entropy coding and on average allows up to 5% extra data to be stored for most use cases. x264 software encoding has this enabled by default. Use cases would be streaming or recording to surveillance disks which are massively slower than consumer grade disks.  
There is currently a bug with CABAC encoding which makes the stream unseekable, so CABAC coded files need to be played back from the start. I'd recommend fixing this on the driver side before exposing the parameter officially.

### Aspect Ratio
While only something that is needed for special encoding (like with Adobe Media Encoder and similar), it would be nice if this is officially available.

### NominalRange
Full Range encoding for recording in true color. Helps with games such as Thief, Killing Floor, The Forest (in caves), Space Engineers (when there is no sun) and other games where most of the visible stuff is near the dark end of colors (<20) or when there are really bright spots (>230).
Supported already by some cards in Driver 16.11.1 and up.

I will add more to this request once I find them and figure out if they are useful or not.

**Comment by MikhailAMD** [comment]
Will appear in the next major driver release (not in hot fixes)

**Comment by Xaymar** [comment]
CABACEnable works perfectly fine with latest (16.11.2) drivers. Well done!

**Comment by Xaymar** [comment]
I noticed that CABACEnable is an enumeration, is it going to be renamed in the future? It now has the values 0 (Default?), 1 (CABAC) and 2 (CALVC).

Also a question for another parameter that I noticed, what is EnableVBAQ? My best guess at what it is was "Variable Bitrate Average Quality", but I couldn't see a difference with it on or off yet.

**Comment by Xaymar** [comment]
I noticed a typo in the EnableVBAQ thing with SVC encoding. If this ever becomes a public parameter, it might be good to fix that one.

```
23:23:47.475: [AMF Encoder]  [TL0.QL0.EanbleVBAQ] TL0.QL0 Eanble VBAQ (Type: Boolean, Index 64)
23:23:47.476: [AMF Encoder]  [TL1.QL0.EanbleVBAQ] TL1.QL0 Eanble VBAQ (Type: Boolean, Index 65)
23:23:47.477: [AMF Encoder]  [TL2.QL0.EanbleVBAQ] TL2.QL0 Eanble VBAQ (Type: Boolean, Index 66)
23:23:47.477: [AMF Encoder]  [TL3.QL0.EanbleVBAQ] TL3.QL0 Eanble VBAQ (Type: Boolean, Index 67)
```

**Comment by Xaymar** [comment]
AMF 1.4 now exposes the following new parameters:

- Aspect Ratio (HEVC, VCE)
- VBAQ (HEVC, VCE)
- Full Range (VCE only, HEVC still uses L"NominalRange")
- CABACEnable (VCE only)
- Reference Frames (HEVC, VCE)
- PreAnalysis (HEVC boolean, VCE enum-ish?)

I think that covers everything I requested.
