### ISSUE TITLE
Bug: CQP on HEVC behaves very poorly when VBAQ is enabled

### ISSUE THREAD

**Issue by flaeri** [GPUOpen-LibrariesAndSDKs/AMF#362]
**Describe the bug**
Visual output of HEVC CQP when using VBAQ is very poor. Disabling VBAQ returns things to normal/expected output.

```
TranscodeHW.exe -INPUT input.mp4 -OUTPUT output.mp4 -HevcUsage TRANSCODING -HevcQualityPreset speed -HevcRateControlMethod CQP -Hevcqp_i 10 -HevcQP_p 10 -CODEC HEVC -HevcEnableVBAQ true
```

**To Reproduce**
1. Use the AMD HW H.265 (HEVC) encoder
2. Pick CQP rate control
3. Pick CQ Level: 10
4. Encode and inspect footage with VBAQ on/off

**Setup (please complete the following information):**
 - OS: Win 11 22H2
 - Driver Version: 31.0.12019.9007
 - GPU: AMD R5 4500U APU
 - Which component has the issue: Encoder

Also tested on latest drivers `22.10.2`

**Debug Log (please upload or paste):**
https://gist.githubusercontent.com/flaeri/23338903669bcb7b9a1c517b3d49a51d/raw/4345788f484394d2391ee27a6f0cdb2498f2a7cb/gistfile1.txt

**Expected behavior**
When recording via AMF HEVC, using the CQP rate control at a low value (QP 10) I expect to get nice and clean looking footage.

**Screenshots**
![image](https://user-images.githubusercontent.com/50419942/203320300-8bd67170-08c1-4f8f-a138-5a47655503b9.png)

**Additional context**
The image above was with identical settings, the only difference being VBAQ on/off.

It is more distinct at lower resolutions, like 720p (see image), but happens on higher resolutions as well.

This happens in AMD's transcode HW, as well as in OBS studio. More context:
https://github.com/obsproject/obs-studio/issues/7827

**Comment by MikhailAMD** [comment]
Hi, VBAQ is bitrate control feature and is not designed to work with CQP. We will update documentation.

**Comment by flaeri** [comment]
I don't disagree, and its just nice to have a conclusion. I assume you would you say the same is true for H264 as well @MikhailAMD ?

**Comment by MikhailAMD** [comment]
Yes, true for H264 as well. All clarifications are always welcome.

**Comment by flaeri** [comment]
Much appreciated! I'm happy to close this issue, unless you want to keep it as a reminder for the docs.

**Comment by MikhailAMD** [comment]
You can close, codec folks will update doc.
