### ISSUE TITLE
Does amf support hevc encoding of yuv444

### ISSUE THREAD

**Issue by 375583810a** [GPUOpen-LibrariesAndSDKs/AMF#363]
Is there any documentation or examples?

**Comment by 375583810a** [comment]
like  nvenc api:
  uint32_t                            chromaFormatIDC;            /**< [in]: Specifies the chroma format. Should be set to 1 for yuv420 input, 3 for yuv444 input.

**Comment by nyanmisaka** [comment]
AFAIK all currently known AMD GPU hardware only supports 4:2:0 subsampling.

**Comment by MikhailAMD** [comment]
Sorry, but we cannot comment on future hardware features. At this point 4:4:4 is not supported.

**Comment by 375583810a** [comment]
thank you guys
