### ISSUE TITLE
VP9 Encoding support in Polaris?

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#37]
[This Page](https://en.wikipedia.org/wiki/VP9#Hardware_encoding.2Fdecoding_support) states that Polaris supports VP9 encoding. When will we have an interface to use this type of encoding? Will it be even longer than the wait for HEVC?

Edit: Does Polaris actually support encoding VP9 or just decoding?

**Comment by MikhailAMD** [comment]
Polaris does not support VP9 encoding.

**Comment by Xaymar** [comment]
I will put that as a comment on the wikipedia page so it gets fixed. Thanks for the comment.
