### ISSUE TITLE
[DOCS] Missing some lines?

### ISSUE THREAD

**Issue by Johl7** [GPUOpen-LibrariesAndSDKs/AMF#370]
In the AMF_Video_Encode_API.pdf docs there seems to be some lines regarding VBAQ that are not there, VBAQ info is bellow EnforceHRD instead.

![2023-02-08 (1)](https://user-images.githubusercontent.com/83582881/217533847-368b17d4-c625-434e-828e-65e550929666.png)

**Comment by rhutsAMD** [comment]
Thanks for catching this! It has been fixed in 624f8ba34bc5fd5c242cbb0e182378055495c2e1.
