### ISSUE TITLE
[Bug]: H264 encoder overloads when PAHMQB is enabled, and PALookaheadBufferDepth is >0

### ISSUE THREAD

**Issue by cs9kc** [GPUOpen-LibrariesAndSDKs/AMF#372]
**Describe the bug**
Now that PALookAheadBufferDepth (from https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/352) has been fixed in the latest releases of AMF/Radeon GPU drivers, I decided to give it a try with other encoder options.

**To Reproduce**
In OBS studio v29.0.2, on an RX 6900 XT LC using driver 23.2.1, enable the following parameters for H264 encoding, to include "PAHighMotionQualityBoostMode=true", and then set "PALookAheadBufferDepth" to any number greater than 0:

EnablePreAnalysis=true PASceneChangeDetectionEnable=false PAHighMotionQualityBoostMode=true PALookAheadBufferDepth=11

The encoder and currently running capture source application/game all lag VERY hard despite not being at 100% duty cycle in task manager.  Interestingly, if you stop the encode, it will eventually finish, though the output is a stuttery disaster as one might expect.  This occurred with and without B-frames. 

**Setup (please complete the following information):**
    - OS: Windows 10 22H2
    - Driver Version: 23.2.1
    - GPU: RX 6900 XT LC
    - Which component has the issue: H264 Encoder

**Debug Log (please upload or paste):**
[2023-02-27 19-23-21.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/10845668/2023-02-27.19-23-21.txt)

**Expected behavior**

**Screenshots**
Other OBS Studio settings: ![image](https://user-images.githubusercontent.com/64284066/221728866-615cff3d-f0f6-49a0-8594-3ce6ed64c1e8.png)

**Additional context**
Thanks!

**Comment by rhutsAMD** [comment]
PAHMQB and PALookAheadBufferDepth are not computationally free and will cost some computational resources or cause an increase in latency. Users should choose them according to their device performance and application context. Depending on how many other applications you have running, which are also requesting resources from the GPU, this may affect the settings you can enable while ensuring real-time encoding as well.

OBS is usually used in a real-time screen recording or live streaming scenario. The priority of real-time is higher than that of quality. We suggest to monitor the OBS statistics such as the number of skipped frames when tuning these more advanced features.

The statistics window can be opened in OBS with View > Stats. While tweaking advanced feature settings, observe the skipped frames count and keep or revert each setting accordingly.


![image](https://user-images.githubusercontent.com/71274498/235213558-8f198a24-5312-48c7-a3cb-92aa98cd1ca0.png)

![image](https://user-images.githubusercontent.com/71274498/235213603-bdee9900-ba83-4c3f-b58f-65bd3868c9af.png)

Encoding B-frames is also resource intensive. More information on the PAHMQB and PALookAheadBufferDepth properties can be found in the [AMF_Video_PreAnalysis_API](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_PreAnalysis_API.md#22-properties) doc.

**Comment by cs9kc** [comment]
Thank you for the detailed information!
