### ISSUE TITLE
[Question]: Several related questions regarding AMF H264 B-frames, PALookAheadBufferDepth, AdaptiveMiniGOP, and B-Frames as reference

### ISSUE THREAD

**Issue by cs9kc** [GPUOpen-LibrariesAndSDKs/AMF#373]
I wanted to run these issues that myself and other users have noticed when using B-frames with PALookAheadBufferDepth, as well other issues that several users have noticed regarding AdaptiveMiniGOP.  For all of the entries below, the testing myself and others have done have not thrown any errors when using the latest stable version of OBS Studio, and most of these issues have been tested to persist as far as 23.2.1.
 
 
 
If you determine that any of these could possibly be reportable bugs, just say the word and I'll gather more data and make a proper bug submission.
 
 
 
_**First Question:**_ B-frames. PALookAheadBufferDepth, and encoder overload

One user has found a pattern with B-frames and PALookAheadBufferDepth, that may have been mentioned before, but I want to ask for clarification just in case.  My question is: Is the following pattern expected behaviour of the AMF H264 encoder?

The pattern goes like this, using the encoding settings below:
- With one B-frame, PALookAheadBufferDepth can be set to 41 with no problems
- With two B-frames, it can only be set as high as 21; any higher will cause encoder overload
- With three B-frames, it can only be set as high as 11; any higher will cause encoder overload

> HighMotionQualityBoostEnable=true EnablePreAnalysis=true RateControlPreanalysisEnable=true PAHighMotionQualityBoostMode=0 PATemporalAQMode=2 PAFrameSadEnable=true AdaptiveMiniGOP=false PALookAheadBufferDepth=41 PACAQStrength=2

_**Second Question:**_ B-frames and AdaptiveMiniGOP

The good news: AdaptiveMiniGOP appears to work as expected, adjusting the number of B-frames properly between 0 and the maximum number of B-frames that the user sets.

The bad news: AdaptiveMiniGOP seems to actually hurt image quality, instead of helping it.  This is observed regardless of whether PA and its many options are used, and regardless of whether B-frames as reference frames is used.  The effect is more severe as the maximum number of B-frames is increased, with 3 B-frames being the worst.

I've done some reading and I can't figure out why this may be.  It feels like AdaptiveMiniGOP is either disabling other settings that would help image quality, or having AdaptiveMiniGOP enabled at all is affecting the encoder in such a way as to not be outwardly visible to us through settings or debug output, but the video output is noticeably worse when this setting is enabled.

The image quality decrease presents itself as a minor overall loss in quality, with occasional and quite jarring moments where a few frames in a row will appear _very_ blocky, but then image quality will quickly improve as presumably the P-frames or the next I-frame clean things up.

**Third Question**  This question is about B-frames as reference (For simplicity's sake, B-frames is set to 3, and AdaptiveMiniGOP is disabled)

Myself and others have noticed very little difference, if any at all, when enabling B-frames as reference frames.  I understand that it really *shouldn't* make a large difference, but output with this setting enabled and disabled is almost identical.  Using the trial of Elecard StreamEye, we do see a change to the # and position of the frames that each frame on its own uses as a reference.  Alas, as I am no expert, I don't know if the output quality is as it should be, nor can I tell if the feature is truly working properly or not.

Typical settings for the GUI elements of OBS Studio.  Assume that all pictures settings are the same between all tests above, except for max number of B-frames, and the text-entry field.

![image](https://user-images.githubusercontent.com/64284066/222035774-3667eed9-ac71-42b0-8a0c-e364de664174.png)

**Comment by rhutsAMD** [comment]
We are investigating the performance in the context of your first question. Could you please confirm your system configuration including which CPU, GPU, and driver version you are using? Is it the same setup from #352 with a RX 6900 XT LC using the 23.2.1 driver?

Regarding your second question, the benefit of Adaptive MiniGOP is content dependent. We have seen quality gains for majority of clips in our testing and there are a few cases that it causes loss. If you can share your test clip, we are happy to look into this specific case.

As for the third question, the benefit of B-frames as reference frames is also content dependent.

**Comment by cs9kc** [comment]
> We are investigating the performance in the context of your first question. Could you please confirm your system configuration including which CPU, GPU, and driver version you are using? Is it the same setup from #352 with a RX 6900 XT LC using the 23.2.1 driver?

Yes, it was the same system and GPU using 23.2.1 at the time.  I currently have an RX 7900 XTX in the same system for right this moment, and I can try to repro on that GPU tonight too.

I'll try to get a clip where AdaptiveMiniGOP gets more-pixelated with it enabled than without (all other settings remain the same).  

As for question 2 and 3: I understand, thank you.  I'll try different game types and experiment for myself to try and better work out which gaming use-cases those settings make sense for. <3

**Comment by cs9kc** [comment]
Quick update:
> The pattern goes like this, using the encoding settings below:
>     * With one B-frame, PALookAheadBufferDepth can be set to 41 with no problems
>     * With two B-frames, it can only be set as high as 21; any higher will cause encoder overload
>     * With three B-frames, it can only be set as high as 11; any higher will cause encoder overload

Using the settings from First Question, on 23.3.1 drivers, it did repro on the RX 7900 XTX, however:
- PALookAheadBufferDepth only overloaded the encoder when B-frames were set to 3
- The encoder did not overload with 0, 1, nor 2 B-frames

Also, quick update on the other user that can repro First Question:
> XFX 6900 XT MERC 319 and I was using 23.2.1. **But the issue persists with all the subsequent driver versions also.**

**Comment by Johl7** [comment]
Did a few tests in here, can repro, i would say 1bframe is the safest maximum when using PALookAheadBufferDepth, it might not overload right on the get go, but i get sutters ingame and the encoder overloads at times(gpu not maxed). With a non PA setup and HMQB, id say the safe is 1 bframe plus the quality preset to Balanced.

**Comment by rhutsAMD** [comment]
This was tested on the following setup and the overloading issue was not reproduced on the latest public driver. Are you still seeing this issue with the latest driver?

**Driver:** 23.12.1
**OBS:** 30.0.0.0
**GPU:** RX 7900 XTX
**Resolution:** 1080p@30 and 1080p@60
**Encoder settings:** RC = CBR, Bitrate = 7500 Kbps, KeyFrame Interval = 2s, Preset = Quality, Profile = High, Max B-Frames = 3
**AMF/FFmpeg Options:** `HighMotionQualityBoostEnable=true EnablePreAnalysis=true RateControlPreanalysisEnable=true PAHighMotionQualityBoostMode=0 PATemporalAQMode=2 PAFrameSadEnable=true AdaptiveMiniGOP=false PALookAheadBufferDepth=41 PACAQStrength=2`

**Comment by Johl7** [comment]
> This was tested on the following setup and the overloading issue was not reproduced on the latest public driver. Are you still seeing this issue with the latest driver?
> 
> **Driver:** 23.12.1 **OBS:** 30.0.0.0 **GPU:** RX 7900 XTX **Resolution:** 1080p@30 and 1080p@60 **Encoder settings:** RC = CBR, Bitrate = 7500 Kbps, KeyFrame Interval = 2s, Preset = Quality, Profile = High, Max B-Frames = 3 **AMF/FFmpeg Options:** `HighMotionQualityBoostEnable=true EnablePreAnalysis=true RateControlPreanalysisEnable=true PAHighMotionQualityBoostMode=0 PATemporalAQMode=2 PAFrameSadEnable=true AdaptiveMiniGOP=false PALookAheadBufferDepth=41 PACAQStrength=2`

Sorry for the out of place question(kinda), but does PACAQStrength also dictates PATemporalAQMode strenght? cause from what i understood of the docs it seems to imply to work only with PAQ. Thanks!

**Comment by cs9kc** [comment]
> **AMF/FFmpeg Options:** `HighMotionQualityBoostEnable=true EnablePreAnalysis=true RateControlPreanalysisEnable=true PAHighMotionQualityBoostMode=0 PATemporalAQMode=2 PAFrameSadEnable=true AdaptiveMiniGOP=false PALookAheadBufferDepth=41 PACAQStrength=2`

This looks good on my XTX with identical settings!  I even checked AdaptiveMiniGOP and the output was acceptable; no overloads nor stuttering (using a media file as the source, 1080p60). 

Thank you all for your hard work.  Forgive me for taking so long to check up on this bug; I admit that I forgot it was still in here.  We can consider this ticket closed. 

Until the next time I break something: Thanks! <3

**Comment by rhutsAMD** [comment]
> > This was tested on the following setup and the overloading issue was not reproduced on the latest public driver. Are you still seeing this issue with the latest driver?
> > **Driver:** 23.12.1 **OBS:** 30.0.0.0 **GPU:** RX 7900 XTX **Resolution:** 1080p@30 and 1080p@60 **Encoder settings:** RC = CBR, Bitrate = 7500 Kbps, KeyFrame Interval = 2s, Preset = Quality, Profile = High, Max B-Frames = 3 **AMF/FFmpeg Options:** `HighMotionQualityBoostEnable=true EnablePreAnalysis=true RateControlPreanalysisEnable=true PAHighMotionQualityBoostMode=0 PATemporalAQMode=2 PAFrameSadEnable=true AdaptiveMiniGOP=false PALookAheadBufferDepth=41 PACAQStrength=2`
> 
> Sorry for the out of place question(kinda), but does PACAQStrength also dictates PATemporalAQMode strenght? cause from what i understood of the docs it seems to imply to work only with PAQ. Thanks!
> 
> In regards to the overloading issue, i can confirm repro on my setup, using the latest driver avaiable, gpu is a rx 6650 xt. Without any 3D aplications running it wont overload, but as soon as a game is opened and running, it will overload(gpu not maxed, vram to spare). With a somewhat alike config in OBS, i know of someone who wont get overloads, but his gpu is a rx 6900 xt, does the higher end models have a more robust encoder?

`AMF_PA_CAQ_STRENGTH` does not affect `AMF_PA_TAQ_MODE` strength. `AMF_PA_CAQ_STRENGTH` controls the CAQ strength only when `AMF_PA_PAQ_MODE` is set to `AMF_PA_PAQ_MODE_CAQ`. It has no effect on `AMF_PA_TAQ_MODE`.

Linking #439 regarding your second point for anyone reading this in the future.

**Comment by DimkaTsv** [comment]
> PACAQStrength also dictates PATemporalAQMode strenght? cause from what i understood of the docs it seems to imply to work only with PAQ. Thanks!

To simplify Rhuts. Enabling TAQ will override CAQ setup. So only TAQ intensity will matter. 
Also TAQ=2 is most heavy hitting parameter from basically anything i know of. 7800XT, 7900XT and XTX have significantly faster encoder, so they probably can get away with that. But RDNA2 cards will hit overloads on real-time encode tasks. [It will be fine for transcoding though]. 
To add onto despite noticeably reducing bitrate, TAQ=2 will slightly hurt quality compared to  TAQ=1.
