### ISSUE TITLE
[Question]: Quick question regarding AV1 encoding, reference frames, and related encoder options

### ISSUE THREAD

**Issue by cs9kc** [GPUOpen-LibrariesAndSDKs/AMF#374]
Hello.  In recent weeks, while trying to wrap my head around AV1 encoding and how it works vs previous encoder incarnations, a question has come up with me that I can't seem to answer with available documentation:

Does the AMD AMF AV1 encoder support some of the more advanced inter-prediction features, such as extended reference frames?  More specifically, does it support any of the bi-directional reference frames: backward-reference and/or alt-reference frames (What effectively amounts to a B-frame from earlier encoders, but for AV1)?

If so, what rate control method(s) or setting combinations will invoke using such frames, and are there any features (normal or PreAnalysis) that can't work with said combination of settings?

Thanks!

**Comment by rhutsAMD** [comment]
Currently, the AMD AMF AV1 encoder supports P-frames but does not support B-frames. Support for B-frames is available in the AMD AMF H264 encoder.

**Comment by cs9kc** [comment]
Thanks!
