### ISSUE TITLE
[Question]: How to fill yuv buf to surface which memory type is DX9?

### ISSUE THREAD

**Issue by 21pages** [GPUOpen-LibrariesAndSDKs/AMF#375]
It works when memory type is DX11/Host/OpenCL, 

When memoryType = `DX11`/`OpenCL`, I use `amf::AMFCompute::CopyPlaneFromHost` to copy yuv data to surface,
When memoryType = `DX9`/`HOST`, I use code above to copy yuv data to suface, `HOST` works, but `DX9` got segmentation fault, because `GetNative` return `IDirect3DSurface9`, not buffer.
```
size_t planeCount = surface->GetPlanesCount();
for (uint8_t i = 0; i < planeCount; i++) 
{
	amf::AMFPlanePtr plane  = surface->GetPlaneAt(i);
	int32_t          width  = plane->GetWidth();
	int32_t          height = plane->GetHeight();
	int32_t          hpitch = plane->GetHPitch();
	void* plane_nat = plane->GetNative();
	for (int32_t py = 0; py < height; py++) {
		printf("py:%d\n", py);
		int32_t plane_off = py * hpitch;
		int32_t frame_off = py * frame->linesize[i];
		std::memcpy(static_cast<void*>(static_cast<uint8_t*>(plane_nat) + plane_off),
					static_cast<void*>(frame->data[i] + frame_off), frame->linesize[i]);
	}
}
```
`AMF_RESULT amf::AMFContext::GetCompute` says: `Access to AMFCompute interface - AMF_MEMORY_OPENCL, AMF_MEMORY_COMPUTE_FOR_DX9, AMF_MEMORY_COMPUTE_FOR_DX11 are currently supported`

So how to fill yuv buf (not in file) to DX9 ?

**Comment by 21pages** [comment]
>AMF_RESULT amf::AMFContext::GetCompute says: Access to AMFCompute interface - AMF_MEMORY_OPENCL, AMF_MEMORY_COMPUTE_FOR_DX9, AMF_MEMORY_COMPUTE_FOR_DX11 are currently supported
```
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/4bfa819fc3d6aa4714ad28f8dab46d0fa95177ad/amf/public/samples/CPPSamples/SimpleEncoder/SimpleEncoder.cpp#L699

https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/4bfa819fc3d6aa4714ad28f8dab46d0fa95177ad/amf/public/samples/CPPSamples/SimpleDecoder/SimpleDecoder.cpp#L231

Samples use `AMF_MEMORY_VULKAN`, `AMF_MEMORY_DX12`, and when I use `AMF_MEMORY_DX11`, it was OK. It's different from what's stated in the document.

**Comment by rhutsAMD** [comment]
Regarding the documentation. The doc has been updated internally and the change will be visible in an upcoming release.

| Parameter        | Description                                                                                                                                                                                                                 |
| :--------------- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| memType [in]     | <p>Memory type. Can be one of the following:</p><p>`AMF_MEMORY_OPENCL` – for OpenCL</p><p>`AMF_MEMORY_VULKAN` for AMF Compute on Vulkan</p><p>`AMF_MEMORY_COMPUTE_FOR_DX9` – for AMF Compute on DirectX9</p><p>`AMF_MEMORY_COMPUTE_FOR_DX11` – for AMF Compute on DirectX11</p><p>`AMF_MEMORY_COMPUTE_FOR_DX12` – for AMF Compute on DirectX12</p> |

Regarding filling the YUV buffer, you cannot copy to `DX9` memory directly from `Host`. Instead, you have two options:
 
1.	You may start with a surface allocated in `Host` memory before filling it with data and convert to `DX9` at the end.
2.	Convert the `DX9` surface to `OpenCL` through interop ( `surface->Convert(AMF_MEMORY_OPENCL)` ), then do the copy using AMFCompute, and finally convert back to `DX9`.

**Comment by 21pages** [comment]
> Convert the DX9 surface to OpenCL through interop ( surface->Convert(AMF_MEMORY_OPENCL) ), then do the copy using AMFCompute, and finally convert back to DX9.

This method works!  But a warning occurs when calling `m_AMFFactory.GetFactory()->CreateComponent(m_AMFContext, m_codec.c_str(), &m_AMFEncoder);` 
The warning is `[AMFEncoderCoreBaseImpl] Warning: Failed to QueryThroughput()!`.

BTW, `m_AMFContext->GetCompute(amf::AMF_MEMORY_DX11, &m_AMFCompute)` works ok.

https://github.com/21pages/native_codec/blob/main/amf/src/encode.cpp

**Comment by MikhailAMD** [comment]
You can ignore the warning.
