### ISSUE TITLE
[Bug]: Unable to locate package amf-amdgpu-pro

### ISSUE THREAD

**Issue by 21pages** [GPUOpen-LibrariesAndSDKs/AMF#378]
**Describe the bug**

**To Reproduce**
1. `amdgpu-install --uninstall && sudo apt-get purge amdgpu-install`
2. `sudo apt-get update && sudo apt-get dist-upgrade`
3. install driver [https://www.amd.com/en/support/linux-drivers](https://www.amd.com/en/support/linux-drivers), `sudo apt install ./amdgpu-install_5.4.50403-1_all.deb`
4. `sudo amdgpu-install -y --usecase=graphics,amf --opencl=rocr`

**Setup (please complete the following information):**
 - OS:  Ubuntu Linux 22.10 x86_64
 - Driver Version : 22.40.3
 - GPU : R7 5800H

**Debug Log (please upload or paste):**
```
➜  /tmp sudo amdgpu-install -y --usecase=graphics,amf --opencl=rocr
Hit:1 http://cn.archive.ubuntu.com/ubuntu kinetic InRelease                    
Get:2 http://security.ubuntu.com/ubuntu kinetic-security InRelease [109 kB]    
Hit:3 https://repo.radeon.com/amdgpu/5.4/ubuntu jammy InRelease                
Get:4 http://cn.archive.ubuntu.com/ubuntu kinetic-updates InRelease [118 kB]   
Hit:5 https://repo.radeon.com/rocm/apt/5.4 jammy InRelease                     
Get:6 http://cn.archive.ubuntu.com/ubuntu kinetic-backports InRelease [99.9 kB]
Fetched 326 kB in 3s (119 kB/s)     
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package amf-amdgpu-pro

```

**Expected behavior**
install AMF usecase

**Comment by jc-bao** [comment]
I think I have found a workaround by adding the flag `--accept-eula`

```shell
sudo amdgpu-install -y --usecase=workstation,amf --opencl=rocr  --vulkan=pro --accept-eula
```

**Comment by Mystro256** [comment]
> I think I have found a workaround by adding the flag `--accept-eula`
> 
> ```shell
> sudo amdgpu-install -y --usecase=workstation,amf --opencl=rocr  --vulkan=pro --accept-eula
> ```

Normally it should prompt you for an acceptance dialog. Are you running non-interactively? If so it skips the EULA acceptance and will fail to install any amdgpu-pro components, including amf. The  --accept-eula allows non-interactive EULA acceptance.

**Comment by mcr-ksh** [comment]
Can confirm this still happens with `amdgpu-install 6.0.60000-1697589.22.04`:

```
E: Unable to locate package amdgpu-pro
E: Unable to locate package amf-amdgpu-pro
E: Unable to locate package vulkan-amdgpu-pro
```

**Comment by 21pages** [comment]
> I think I have found a workaround by adding the flag `--accept-eula`
> 
> ```shell
> sudo amdgpu-install -y --usecase=workstation,amf --opencl=rocr  --vulkan=pro --accept-eula
> ```

Error occurred during installation. After installation, amf is available, but after restarting, I cannot enter the gui.

**Comment by Winnus** [comment]
> I think I have found a workaround by adding the flag `--accept-eula`
> 
> ```shell
> sudo amdgpu-install -y --usecase=workstation,amf --opencl=rocr  --vulkan=pro --accept-eula
> ```

` --accept-eula` solved it thanks!

**Comment by neoedmund** [comment]
for using amf, I installed fresh Ubuntu 22.04,  but
```
sudo amdgpu-install -y --usecase=graphics,amf   --accept-eula
Hit:1 https://repo.radeon.com/amdgpu/6.1/ubuntu jammy InRelease
Hit:2 https://repo.radeon.com/rocm/apt/6.1 jammy InRelease                     
Hit:3 http://jp.archive.ubuntu.com/ubuntu jammy InRelease                      
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://jp.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://jp.archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Hit:1 https://repo.radeon.com/amdgpu/6.1/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 https://repo.radeon.com/rocm/apt/6.1 jammy InRelease
Hit:4 http://jp.archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://jp.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://jp.archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package amf-amdgpu-pro
Hit:1 https://repo.radeon.com/amdgpu/6.1/ubuntu jammy InRelease
Hit:2 https://repo.radeon.com/rocm/apt/6.1 jammy InRelease                     
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:4 http://jp.archive.ubuntu.com/ubuntu jammy InRelease                    
Hit:5 http://jp.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://jp.archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Hit:1 https://repo.radeon.com/amdgpu/6.1/ubuntu jammy InRelease
Hit:2 https://repo.radeon.com/rocm/apt/6.1 jammy InRelease                     
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:4 http://jp.archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://jp.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://jp.archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
```
so `amf-amdgpu-pro` should in `https://repo.radeon.com/amdgpu/6.1/ubuntu jammy` or ` https://repo.radeon.com/rocm/apt/6.1 jammy` , right?
but there is not such package in the repo ,
so I think `--accept-eula` will not do any magic.

And I wonder why amf cannot be more easily installed like other software for general Linux distro,
even not work in the *supported* distro?

**Comment by rhutsAMD** [comment]
@neoedmund Could you please try to delete the `/var/lib/dkms/amdgpu/` folder, then reboot and reinstall the driver?

**Comment by neoedmund** [comment]
> @neoedmund Could you please try to delete the `/var/lib/dkms/amdgpu/` folder, then reboot and reinstall the driver?

There is no such directory, I rebooted, but no lucky. 

uname `Linux 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC x86_64 GNU/Linux `

**Comment by wszgrcy** [comment]
> Can confirm this still happens with `amdgpu-install 6.0.60000-1697589.22.04`:
> 
> ```
> E: Unable to locate package amdgpu-pro
> E: Unable to locate package amf-amdgpu-pro
> E: Unable to locate package vulkan-amdgpu-pro
> ```

I find amd-install >5.7.3 remove `[proprietary/](https://repo.radeon.com/amdgpu/5.7.3/ubuntu/pool/proprietary/)`
That is to say, versions 6.0 and above do not support AMF

**Comment by wszgrcy** [comment]
6.1.3 add package https://repo.radeon.com/amdgpu/6.1.3/ubuntu/pool/proprietary/

**Comment by Mystro256** [comment]
Please don't use ROCm releases to install AMF.
AMF is a part of the radeon software for linux releases, which are based on ROCm releases. It's best to see the Radeon Software for Linux as a superset of the ROCm stack.

The latest release is 24.10, which was based on the 6.1.3 rocm release:
https://www.amd.com/en/resources/support-articles/release-notes/RN-AMDGPU-UNIFIED-LINUX-24-10-3.html
