### ISSUE TITLE
Question: Easier way to tell AMF which device to use for encoding and OpenCL?

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#38]
As I now have a system with multiple GPUs and an internal GPU, I wanted to add this feature to my encoder plugin. However, I couldn't yet figure out how to do this properly.

### 1\. For InitDX9, InitDX11 and InitOpenGL**
Do I have to create a proper DirectX/OpenGL context for the encoder to use or is there a simpler way to do this?

### 2\. For InitOpenCL
I saw that there is a class called AMFComputeFactory which can be used to gather AMFComputeDevices. However I saw no way to read out the device id as a human readable name.
Do I have to create a custom openCL context for this as well?

Any help is greatly appreciated.

**Comment by MikhailAMD** [comment]
Hi,
AMF does not provide a replacement for DX9, DX11 or OpenCL device handling. For the proper adapter enumeration and device creation application is encouraged to use these APIs. There is a sample VCEEncoderD3D that shows how to do it. Check DeviceDX9.h/cpp, DeviceDX11.h/cpp and DeviceOpenCL.h/cpp. I don't think you need OpenGL.
Once you have a DX device you can initialize AMF and check capabilities. I think the VCE AMF plug-in is already doing so. In any case, CapabilityManager sample will help. 
If the app intends to use OpenCL and choose to create own OCL device and context it is important to pass the correct DX9 or/and DX11 devices created earlier for interop between APIs to work. AMF encoder works only via DX9 or via DX11. DeviceOpenCL.cpp has the code. Though, you can rely on AMF to do OpenCL initialization and then get OpenCL device and context and query additional properties if needed. 
AMFComputeFactory provides OpenCL device enumeration and creation but not connected to any DX. It is used primary for AMD True Audio Next SDK.

**Comment by Xaymar** [comment]
Alright thank you. I will take a look at the VCEEncoderD3D example and see what I can do myself.
