### ISSUE TITLE
[Question]: PreAnalysis Component support in ffmpeg

### ISSUE THREAD

**Issue by cs9kc** [GPUOpen-LibrariesAndSDKs/AMF#385]
Hello!  I was reminded today to go look through the recently updated ffmpeg code, and I confirmed that I could not see that AMD had added support for the PreAnalysis Component in ffmpeg with the latest update.

To the best of my knowledge, ffmpeg has never been able to invoke the PreAnalysis Component leading up to this point.  

- If the PreAnalysis Component is accessible with the latest update, could you tell us how to use it?
- If the PreAnalysis Component is not part of ffmpeg, it would be a nice addition to the AMF ffmpeg encoder package! 

Thank you!

**Comment by MikhailAMD** [comment]
We will introduce FFmpeg patch soon.

**Comment by cs9kc** [comment]
Excellent, thank you!  <3

Closing this ticket.
