### ISSUE TITLE
[Bug]: Cannot include VulkanAMF.h when using C

### ISSUE THREAD

**Issue by FreezyLemon** [GPUOpen-LibrariesAndSDKs/AMF#388]
**Describe the bug**
There is a `bool` field in the `AMFVulkanSync` struct. `bool` is not a built-in type in C, so this generates a compile-time error. This can be worked around with `typedef amf_bool bool;`, but that's not a good solution. The field should be a `amf_bool` instead.

**To Reproduce**
1. Create `main.c` (just this one line is needed):
```c
#include <AMF/core/VulkanAMF.h>
```
2. `gcc main.c`:
```c
In file included from main.c:1:
/usr/include/AMF/core/VulkanAMF.h:58:9: error: unknown type name ‘bool’
   58 |         bool                bSubmitted;         // if true - wait for hSemaphore. re-submit hSemaphore if not synced by other ways and set to true
      |         ^~~~
```

**Setup:**
 - OS: Linux
 - Header version 1.4.29
 - GCC 12

**Comment by rhutsAMD** [comment]
Thanks for catching this, it has been fixed in commit daee84bf3cde928dc1cd0b502c1b6a50cbff2495
