### ISSUE TITLE
Variable Bitrate (Peak Constrained) ignores given constraints.

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#39]
Seems to be a regression from an earlier driver (accidentally changed the wrong code?), VBR seems to completely ignore any constraints. Min/Max QP, VBV Buffer Size, Target/Peak Bitrate all have no effect on what it is going to use for the actual bitrate and usually it hovers at around a fixed 20mbit/s.

Edit: Bitrate drops below 20mbit/s when Target Bitrate is set to exactly 0. Still does not follow any other constraints.

## Constraints being ignored completely:
* Min QP (unless 0)
* Target Bitrate
* Peak Bitrate
* VBV Buffer

### System Information
* Windows 10 64-Bit (Anniversary Update, automatic Updates enabled)
* CPU: Intel 4690
* Mainboard: GIGABYTE H97-D3H
* GPU: RASUS Radeon R9 285 Strix OC DirectCU II
* Driver: 16.10.3

### 2016-11-03 (Wrong Target Bitrate)
* Log: http://cdn.xaymar.com/private/2016/11/2016-11-03_14-19-53.txt
* Video 1: http://cdn.xaymar.com/private/2016/11/2016-11-03%2014-18-17.mkv
* Video 2: http://cdn.xaymar.com/private/2016/11/2016-11-03%2014-18-57.mkv
* Video 3: http://cdn.xaymar.com/private/2016/11/2016-11-03%2014-19-22.mkv

### 2016-11-03 (Corrected Target Bitrate)
* Log: http://cdn.xaymar.com/private/2016/11/2016-11-03_15-07-56.txt
* Video 1: http://cdn.xaymar.com/private/2016/11/2016-11-03%2015-02-50.mp4
* Video 2: http://cdn.xaymar.com/private/2016/11/2016-11-03%2015-06-39.mp4

### 2016-11-03 (Applied fixes by Mikhail)
* https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/39#issuecomment-258203275

**Comment by Xaymar** [comment]
When setting Target Bitrate to 0 and only using Peak Bitrate, the achieved bitrate drops to 3200kbit/s. Still unsure how to control the actual bitrate, it seems to ignore me completely.

**Comment by MikhailAMD** [comment]
There was no changes in the driver in this area. 
From what I see in the log is that peak bitrate is less then target bitrate (9000000 vs 20000000). It doesn't have a lot of sense. AMF will not correct this and codec team told that HW behaviour would be unpredicted.

**Comment by Xaymar** [comment]
So the name of the rate control method AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_PEAK_CONSTRAINED_VBR is wrong here?

**Comment by Xaymar** [comment]
Another thing that I forgot in the last response, I did not set Target Bitrate to 20mbit/s. I set Target Bitrate to 0, since it is called PEAK_CONSTRAINED_VBR and should be using Peak Bitrate instead.

**Comment by MikhailAMD** [comment]
Not sure but it was not intended to work.
This method uses two parameters target bitrate (kind of average bitrate) and hard limitation for peaks. Obviously peak limitation should be higher then average.

**Comment by Xaymar** [comment]
I will do some additional tests and report back

**Comment by Xaymar** [comment]
Further testing with "correct" Bitrates (3500000 for Target, 9000000 for Peak) revealed that it doesn't work at all - which reflects what users have been reporting with Plays.TV for a while too. Average bitrate is again close to 20mbit/s instead of the given 9mbit/s.

### 2016-11-03
* Log: http://cdn.xaymar.com/private/2016/11/2016-11-03_15-07-56.txt
* Video 1: http://cdn.xaymar.com/private/2016/11/2016-11-03%2015-02-50.mp4
* Video 2: http://cdn.xaymar.com/private/2016/11/2016-11-03%2015-06-39.mp4

**Comment by MikhailAMD** [comment]
I looked briefly into the plug-in code. Please confirm if I am right or not: the plug-in sets bitrate parameters before calling encoder->Init(), correct?
If so it is wrong. There parameters are overwritten but applying "usage" parameter inside Init() method. All dynamic parameters including bitrate should be set after Init() call.

**Comment by Xaymar** [comment]
That is a very strange way of handling that. Would I have to instantly ReInit the encoder to apply them? Some of the properties can only be applied before calling Init() too, otherwise they return AMF_ALREADY_INITIALIZED.

I will update the code to match your change now and see if that helps.

**Comment by MikhailAMD** [comment]
You should not use Reinit() for dynamic properties. You can set them at any time and they will be applied before next frame is submitted. The header file clearly separated dynamic and static properties. Statics should be set before Init() or after with Reinit() call, dynamic should be set after Init(). Check AMF samples they all written this way.

**Comment by Xaymar** [comment]
> You should not use Reinit() for dynamic properties. You can set them at any time and they will be applied before next frame is submitted.

If this actually works, that would be great. Early tests (on driver 16.9.2 and 16.10.1) however did not automatically apply dynamic properties and instead applied them only when ReInit was called. If 16.10.2/.3 fixed this, that would be a neat fix. (That was the reason for even implementing the ReInit behaviour.)

> The header file clearly separated dynamic and static properties. Statics should be set before Init() or after with Reinit() call, dynamic should be set after Init().

Then I have a question: What actually are the dynamic parameters? The documentation only lists "Profile", "ProfileLevel" and "MaxOfLTRFrames" as Static Parameters, but "BPicturesDeltaQP" and "ReferenceBPicturesDeltaQP" are also static parameters that need to be set before Init() and can't ever be changed afterwards (not even with ReInit(), it will just not change them).

I have also applied the suggested changes now, but have had no different results to before. Total average bitrate is still a lot higher than the given target bitrate.

* Log: http://cdn.xaymar.com/private/2016/11/2016-11-03_15-56-11.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-03_15-56-11.txt

Is there a better way to tell where things fail? The debug output from AMF is rather sparse and doesn't really tell me why things aren't working the way they should.

**Comment by MikhailAMD** [comment]
check the VideoEncoderVCE.h: all properties below this comment are dynamic.
// Dynamic properties - can be set at any time
In documentation the "static" word is in the parameter table making group of them but it should be more visible, agree. 
There only few static parameters, when in question  follow header file.

**Comment by MikhailAMD** [comment]
From the log: you should not call Reinit() after updating rate control and other dynamic parameters.

**Comment by MikhailAMD** [comment]
Regardless of reinit: log seem right. Where is the file?

**Comment by Xaymar** [comment]
My bad, i uploaded the log twice. I have removed any trace of ReInit from my code, however there is still a ReInit call in the log file that is not mine. Here are the up to date files:

* Log: http://cdn.xaymar.com/private/2016/11/2016-11-03_16-20-44.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-03%2016-15-35.mp4

**Comment by Xaymar** [comment]
I have noticed another thing, CABACEnable is now always 1. I can assume that 16.10.3 fixed any issues with it?

**Comment by MikhailAMD** [comment]
Internal reInit() will be triggered if you set a static property after Init() call. See in the log that QualityPreset property is set after Init().
For rate control Please:
- enable HDR
- disable filler data
Not rate control related:
- enable CABAC
- Disable B-frames
- Profile Level should be higher then 4 
Please share the results.
Thanks,

**Comment by Xaymar** [comment]
I have a feeling that something went wrong with the changes I did, now it says original size 64x64. MediaInfo output for recorded Video:

```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 5 s 717 ms
Bit rate                                 : 1 460 kb/s
Width                                    : 1 920 pixels
Original width                           : 64 pixels
Height                                   : 1 080 pixels
Original height                          : 64 pixels
Display aspect ratio                     : 16:9
Original display aspect ratio            : 1.000
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.012
Stream size                              : 1 019 KiB (92%)
Color range                              : Limited
```

* Log: http://cdn.xaymar.com/private/2016/11/2016-11-03%2017-24-50.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-03%2017-26-18.mp4

**Comment by Xaymar** [comment]
Okay, I modified some of the code to not override static settings in update(), hopefully should have removed the ReInit() call now.

Average bitrate is now at about 12mb/s, about what Peak Bitrate + Target Bitrate would be.

* Log: http://cdn.xaymar.com/private/2016/11/2016-11-03%2017-49-44.txt
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-03%2017-50-22.mp4

Changes applied:

* Static Properties shouldn't be set after Init() anymore.
* HRD is enabled (HDR not, I don't have a HDR surface to submit yet or in the near future)
* Filler Data is Disabled
* CABAC is Enabled, even though I have no control over it since 16.10.3
* B-Pictures and Reference are both 0
* Profile Level set to 52 (no idea why that was on 40)

**Comment by Xaymar** [comment]
Same solution as in #18: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/18#issuecomment-259203547
