### ISSUE TITLE
[Bug]: crashed when call amf::AMFContext1Ptr(context)->InitVulkan(NULL) on linux

### ISSUE THREAD

**Issue by Oblivic** [GPUOpen-LibrariesAndSDKs/AMF#390]
Segmentation fault

libvulkan.so.1!vkGetDeviceQueue
libamfrt64.so.1!amf::AMFDeviceVulkanImpl::CreateDeviceAndFindQueues(bool, int) 
libamfrt64.so.1!amf::AMFDeviceVulkanImpl::Init(void*)
libamfrt64.so.1!AMFContextImpl::InitVulkan(void*) 
simpleEncode(const wchar_t * pCodec, const wchar_t * pFileNameOut) (/home/user/sample/AMF/amf/public/samples/CPPSamples/SimpleEncoder/SimpleEncoder.cpp:158)
main() (/home/user/sample/AMF/amf/public/samples/CPPSamples/SimpleEncoder/SimpleEncoder.cpp:124)

 - OS:  Ubuntu Linux 20.04.6
 - Driver Version [e.g. 22.2.1]
 - GPU: RX 470

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

GLX version: 1.4
    Vendor: AMD (0x1002)
    Device: AMD Radeon (TM) RX 470 Graphics (polaris10, LLVM 15.0.3, DRM 3.48, 5.15.0-69-generic) (0x67df)
    Version: 22.3.0
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2

**Comment by rhutsAMD** [comment]
You are running an older driver from early last year. Could you please try updating to the latest available public driver?
https://www.amd.com/en/support

If you have made any changes to the SimpleEncoder sample app, could you please provide a copy of the changes you have made?

**Comment by Oblivic** [comment]
I updated the vulkan version and everything looks fine now
