### ISSUE TITLE
H265: No documentation of AMF_VIDEO_ENCODER_HEVC_OUTPUT_DATA_TYPE_IDR

### ISSUE THREAD

**Issue by Vixea** [GPUOpen-LibrariesAndSDKs/AMF#393]
AMF documentation didn't seem to be updated after this issue was closed #86

**Comment by rhutsAMD** [comment]
Thanks for noticing that. It has now been fixed in commit bd5db31d3d8ea1fae7002dd903898599bdb7d97a.
