### ISSUE TITLE
AMF_INPUT_FULL: m_pConverter->SubmitInput Failed

### ISSUE THREAD

**Issue by 21pages** [GPUOpen-LibrariesAndSDKs/AMF#394]
Encoding ID3DTexture2D with AMF_SURFACE_BGRA format, H264/H265 got 2 problems.

For H264:
After coding for a while, an error occurs.
```
2023-05-29 21:41:26.099     77C8 [AMFEncoder]   Error: src/encode.cpp(108):AMF_ERROR 25 : AMF_INPUT_FULL: SubmitInput() failed

2023-05-29 21:41:27.100     77C8 [AMFEncoderCoreH264]   Error: ..\..\..\..\..\runtime\src\components\EncoderCore\EncoderCoreH264Impl.cpp(1357):AMF_ERROR 25 : AMF_INPUT_FULL: m_pConverter->SubmitInput Failed
```

For H265:
After encoding for a period of time, the length of each encoded frame is 40, and the picture is still

code : https://github.com/21pages/native_codec/blob/0c77d269aa82ef9eacf8ed03731758a2395a144c/amf/src/encode.cpp#L108

**Comment by MikhailAMD** [comment]
- Which GPU do you use?
- Which driver version (try the latest)
- Can you enable more AMF logging and provide the log?
- In the link to the code above a single frame is encoded for the test. Does this exact code fail, or you have some loop with input?
- In the current code you allocate AMFSurface, get ID3D11Texture2D from there, wrap it again into AMFSurface and submit to encoder. In this piece of code it is OK. But in the real code do you ensure that ID3D11Texture2D is not reused before encoding is done? - can be done by callback.

**Comment by 21pages** [comment]
* GPU: AMD Ryzen 7 5800H with Radeon Graphics 
* Driver version: 30.0.14052.4003, with `EnumAdapters1` I can get two AMD adapters with different adatper guid, but I can ensure capture and encoding use the same adapter.
* I'll provide more logs later.
* I capture the screen, get ID3DTexture2D, send it to encode
* Yes, the capture and encoding use the same ID3DTexture2D pointer, but it's sync operation and in the same thread.

**Comment by MikhailAMD** [comment]
While waiting for logs: AMF DVR sample does the same. Can you try it and compare with your app?

**Comment by 21pages** [comment]
OK

**Comment by 21pages** [comment]
Running DVR about 20 minutes, it's ok, I'm busy with somthing and I'll dig into it soon.

**Comment by 21pages** [comment]
[amf_hevc_bad_len_is_38.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/11645659/amf_hevc_bad_len_is_38.txt)

[amf_hevc_good.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/11645660/amf_hevc_good.txt)

**Comment by MikhailAMD** [comment]
The logs don't show any abnormalities except output is 38 bytes. In general, it means that the content of input frame doesn't change. The failing log starts with frame #8797. Did anything happen before that? Better to share full logs, even large.
If you could reproduce the problem with DVR sample, we would have a chance to debug it here.

**Comment by 21pages** [comment]
I'll test DVR for a long time.

**Comment by 21pages** [comment]
@MikhailAMD  I got time for this, and create a vs project for convenience. https://github.com/21pages/native_codec/tree/main/vs/AMFTest

Still encoded picture can be reduced by this vs project , and the length of the frame after encoding is about 40. 

By saving the texture of the screenshot into the bmp (every 1000 frames into the texture_bmp folder), it can be ruled out that the screenshot is not same texture, so It is judged that there is a problem on the encoding side, and I don't know why.

![1687592990735](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/14891774/aa91bb2b-5d61-49c9-a2c0-c2eb43965613)

Follow the steps below to build the environment (rust is not required).

1. `git clone git@github.com:21pages/native_codec.git`
2.  open `vs/AMFTest/AMFTest.sln` with visual studio
3.  Change the code in `main.cpp` to be consistent with your computer.
     change luid by downloading and running https://github.com/21pages/test/releases/download/test/native_codec_available.exe
    ```
    int64_t luid = 64474;
    DataFormat dataFormat = H265;
    int width = 2880;
    int height = 1800;
    ```
4.  run vs project, you will got a error `SDL2 not found`, copy `externals/SDL/lib/x64/SDL2.dll` to `vs/AMFTest/x64/Debug` and rerun.

If there is any problem, please let me know, I will be here as soon as possible.

If successful, and there is no recurrence in ten minutes, please turn off and run again, and it can be reproduced after running a few more times.

If reproduced, please see ` vs\AMFTest\texture_bmp`, there is many bmp with timestamp, you can see that  the texture picture is always changing, although there is a problem with the direction of the bmp.

**Comment by 21pages** [comment]
Still reproduced after change
![1687824660429](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/14891774/86c7d567-5383-4bd1-88d4-e373ab7b6dfa)

**Comment by MikhailAMD** [comment]
OK, ignore the Duplicate. Yesterday I was able to repro with unreleased internal driver. 
Now I am running the test on the APU similar to yours (Ryzen 7 5800) with the latest public driver and so far cannot repro. I tried several runs during an hour. Your driver is slightly older.  Can you try the latest driver? https://www.amd.com/en/support/apu/amd-ryzen-pro-processors/amd-ryzen-7-pro-5000-series-mobile-processors/amd-ryzen-7-0
BTW: I modified the app so it can accept null LUID and get in this case the first GPU adapter. Also I added getting width and height from DXGI duplication initialization from IDXGIOutput. It was done for ease of use on any machine.

**Comment by 21pages** [comment]
Thanks for your tests, I can't reproduce either without any code change.
There is some change on my computer:
1. > I can get two AMD adapters with different adatper guid, but I can ensure capture and encoding use the same adapter.

Only One luid now.

2. I uninstall the parsec display driver.

I haven't updated the drivers yet, let me close the issue first, and I'll do more tests to try to reproduce it.
I will reopen this issue once I reproduce it again.
