### ISSUE TITLE
[Bug]: Using preanalysis "lookahead" feature with AMF hw decoder and AMFHQScaler (as well as other vpp filters) causes black and green flicker in resulting video. 

### ISSUE THREAD

**Issue by DimkaTsv** [GPUOpen-LibrariesAndSDKs/AMF#402]
**Describtion the bug**
When upscaling is being used on source video with "lookahead" buffer enabled (to any value), resulting video will have occasional black of green flickering transcoded. 

**To Reproduce**
1. To see it more easily, use VCEEncC as command line application for AMF. 
2. Use HW decoder (as i use VCEEncC, so it is equal to **--avhw**). Software decoder doesn't produce such problem. 
3. Use any --vpp filter, or to reproduce it more easily, just set --output-res ????x???? to be upscaled. For me it is 1920x1080 source, output res 3840x2160 (4k)
4. Use **--pa lookahead=41** (max), but value can be other than 41 
5. Transcode video source. (i used HEVC Adrenaline screen capture of game as source)
6. Watch resulting video (i use MPC-HC, D3D11 HW acceleration)
7. Occasionally single frames will be either flickering black or green. Happens in darker videos more often, it seems. 

**Setup:**
 - OS: [Windows 11, build 22621.1928]
 - Driver Version [23.7.1]
 - GPU [RX 6750 XT]
 - Which component has the issue [e.g. Encoder, Decoder]: Encoder, i suppose. But probably it is combination of both decoder and encoder. 

**Debug Log (please upload or paste):**
FFprobe output of source video:
```
ffprobe version 2023-05-31-git-baa9fccf8d-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 12.100 / 58. 12.100
  libavcodec     60. 16.100 / 60. 16.100
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[hevc @ 00000231789ed7c0] VPS 0 does not exist
[hevc @ 00000231789ed7c0] SPS 0 does not exist.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\-----\Videos\Radeon ReLive\Returnal™\Returnal™_2023.07.09-16.05.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.27.100
  Duration: 00:01:11.38, start: 0.000000, bitrate: 50340 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, bt709/reserved/bt709), 1920x1080 [SAR 1:1 DAR 16:9], 50017 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 315 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[hevc @ 0000023178a9d000] VPS 0 does not exist
[hevc @ 0000023178a9d000] SPS 0 does not exist.

```
AVHW source decoding - in resulting video a lot of flickering happens:
[vceenc_log_avhw.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/11995681/vceenc_log_avhw.txt)

AVSW source decoding - resulting video has no issues:
[vceenc_log_avsw.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/11995682/vceenc_log_avsw.txt)

**Expected behavior**
Transcoding should result in video without such flickering.

**Screenshots**
Normal frames of video:
![image](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/9446187/2028b239-6e67-4f13-864f-054356475cc7)

Bad frame - black flicker: 
![image](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/9446187/7c3fd83e-af79-410c-beb0-69a7a57b24e4)

Bad frame - green flicker:
![image](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/9446187/516ddee1-1232-481e-ba02-1f6cccef887f)

**Additional context**
```
[hevc @ 0000023178a9d000] VPS 0 does not exist
[hevc @ 0000023178a9d000] SPS 0 does not exist.
```
These errors of source are happening on every screen capture with Adrenaline software... No idea if it is bug or such behaviour is OK, so just noting.

Used VCEEncC command (through drag and drop on top of .bat file with it):
For --avhw (**--avhw** itself can be excluded, VCEEncC defaults to it)
```
%~dp0\VCEEncC64.exe -i %1 -o "%~n1_test%~x1" --avhw --output-res 3840x2160 --codec hevc --profile main --tier high --level 6.2 --preset slow --ref 4 --ltr 2 --vbr 7500 --max-bitrate 10000 --qp-max 35 --pa sc=high,ss=high,activity-type=yuv,lookahead=41,taq=1 --audio-copy --chapter-copy  --log "vceenc_log_avhw.txt" --log-level debug
pause
```
For --avsw
```
%~dp0\VCEEncC64.exe -i %1 -o "%~n1_test%~x1" --avsw --output-res 3840x2160 --codec hevc --profile main --tier high --level 6.2 --preset slow --ref 4 --ltr 2 --vbr 7500 --max-bitrate 10000 --qp-max 35 --pa sc=high,ss=high,activity-type=yuv,lookahead=41,taq=1 --audio-copy --chapter-copy  --log "vceenc_log_avsw.txt" --log-level debug
pause
```

**Comment by rhutsAMD** [comment]
The issue has been fixed internally and will be available in a future driver release. We will notify you once the driver containing the fix is publicly available.

**Comment by DimkaTsv** [comment]
Looks like i cannot reproduce issue for several driver versions, so i assume fix is out now
Thank you for fixing the issue!
