### ISSUE TITLE
Video Encode API: Crash inside 'atiumd6a.dll' inside QueryOutput/SubmitInput call (AVC/H.264)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#41]
Reported by two users, for some reason the encoding crashes inside the Driver on QueryOutput or SubmitInput.

1. Report: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/143
2. Report: https://obsproject.com/forum/threads/obs-crashing-when-streaming-recording-using-amf-plugin.57619/#post-252017, https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/144
3. Report: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/145

### 1. Report
* Log: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/587270/2016-11-12.15-23-26.txt
* Crash Log: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/587274/Crash.2016-11-12.15-35-46.txt
* Video: https://drive.google.com/open?id=0B1y2xDp8Jscna29UNG1GZGdZeHM
* Dump: https://drive.google.com/open?id=0B1y2xDp8JscnQ1pMbE5pdzE2cjQ (look at Thread ID 13388)

### 2. Report
* Log, Crash Log, System Specs, Dump: https://www.dropbox.com/s/1sm9uv7sz4a7vr8/r4b.7z?dl=0 (Thread Id: 2284)

**Comment by Xaymar** [comment]
Both dumps show the same behaviour, SubmitInput stalled for some time and caused the plugin submission queue to fill up. Shortly after it was full, QueryOutput crashed.

**Comment by MikhailAMD** [comment]
The dumps are very informative.
Could you please ask users to provide hardware device ID for **both crashes** from Radeon Settings? (System->Hardware tab->Device ID)

**Comment by razorlikes** [comment]
I am one of the users. My device ID is 67B1.

**Comment by MikhailAMD** [comment]
thanks, which log was yours?

**Comment by razorlikes** [comment]
The first one.

**Comment by MikhailAMD** [comment]
OK, I found the second ID in the log. The bug reported here is seem fixed recently (description and all signs do match) but not published yet. I will see how fast we could push it into the public driver.
Thanks for the reporting.

**Comment by Xaymar** [comment]
Great to hear, I'll notify the users affected once I know it's fixed in the public driver.

**Comment by r4bc** [comment]
Just spotted this - I'm the 2nd user. Let me know if you need anything else from me. Many thanks!

**Comment by Xaymar** [comment]
Still happening with 16.11.4, hoping for a fix soon.

**Comment by MikhailAMD** [comment]
This should be fixed in today ReLive release

**Comment by Xaymar** [comment]
Waiting for user confirmation that it is indeed fixed.

**Comment by Xaymar** [comment]
User confirmation that it is fixed has arrived.
