### ISSUE TITLE
[Bug]: RX Vega H.264 encoder fails when operating High Motion Quality Boost

### ISSUE THREAD

**Issue by Masa-tam** [GPUOpen-LibrariesAndSDKs/AMF#412]
**Describe the bug**

https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Encode_API.md
From reading the manual, there does not seem to be a limitation, but it is an error.

**To Reproduce**
1. Apply the following patches
```
diff --git a/amf/public/samples/CPPSamples/common/MiscHelpers.cpp b/amf/public/samples/CPPSamples/common/MiscHelpers.cpp
index cfc923e..4203ecb 100644
--- a/amf/public/samples/CPPSamples/common/MiscHelpers.cpp
+++ b/amf/public/samples/CPPSamples/common/MiscHelpers.cpp
@@ -108,7 +108,10 @@ AMF_RESULT SetEncoderDefaultsAVC(amf::AMFComponent* pEncoder, amf_int64 bitRate,
     res = pEncoder->SetProperty(AMF_VIDEO_ENCODER_USAGE, AMF_VIDEO_ENCODER_USAGE_TRANSCODING);
     AMF_RETURN_IF_FAILED(res, L"SetProperty(AMF_VIDEO_ENCODER_USAGE, AMF_VIDEO_ENCODER_USAGE_TRANSCODING) failed");
 
-    if (bMaximumSpeed)
+	res = pEncoder->SetProperty(AMF_VIDEO_ENCODER_HIGH_MOTION_QUALITY_BOOST_ENABLE, true);
+	AMF_RETURN_IF_FAILED(res, L"SetProperty(AMF_VIDEO_ENCODER_HIGH_MOTION_QUALITY_BOOST_ENABLE, true) failed");
+	
+	if (bMaximumSpeed)
     {
         res = pEncoder->SetProperty(AMF_VIDEO_ENCODER_B_PIC_PATTERN, 0);
         // do not check error for AMF_VIDEO_ENCODER_B_PIC_PATTERN - can be not supported - check Capability Manager sample
```
2. Build amf/public/samples/CPPSamples_vs2019.sln
3. Run `SimpleEncoder.exe`

**Setup (please complete the following information):**
 - OS: Windows 11 22H2
 - Driver Version 23.8.2
 - GPU RX Vega
 - Which component has the issue [e.g. Encoder, Decoder]

**Debug Log (please upload or paste):**
```
2023-09-06 15:38:07.785      BB8 [VCEEncoderTrace] Warning: SetProperty HighMotionQualityBoostEnable not found
2023-09-06 15:38:07.785      BB8 [MiscHelpers]   Error: D:\src\AMF\amf\public\samples\CPPSamples\common\MiscHelpers.cpp(112):AMF_ERROR 4 : AMF_INVALID_ARG: SetProperty(AMF_VIDEO_ENCODER_HIGH_MOTION_QUALITY_BOOST_ENABLE, true) failed
```

**Expected behavior**
If it is not supported, please describe how it is determined.

**Comment by rhutsAMD** [comment]
`HIGH_MOTION_QUALITY_BOOST` is supported by Radeon RX 5000 Series or newer GPUs as well as Ryzen 2000 U/H series or newer APUs.

The return code indicates if the feature is supported or not. In this case, the returned `AMF_INVALID_ARG` shows that enabling the feature is not valid in the current configuration.

`GetPropertyInfo()` or `ValidateProperty()` from `AMFPropertyStorageEx` can also be used to check if the property is available in the HW.

**Comment by Masa-tam** [comment]
Thank you for taking the time to support with me.
I would like to follow your advice and check the properties during the initialization phase.
