### ISSUE TITLE
[Question]: AMFTrace lifetime clarification

### ISSUE THREAD

**Issue by aconverse** [GPUOpen-LibrariesAndSDKs/AMF#415]
The docs say "The object which implements the AMFTrace interface is not reference counted. Do not delete the object obtained from AMFFactory::GetTrace."

https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/2f326350e849894a929296854f5290e66197c97c/amf/doc/AMF_API_Reference.md#225-amftrace

Fair enough. But what is the lifetime an AMFTrace object is valid? Is it valid for the lifetime of the AMFFactory? Is it a singleton created when the first factory is initialized (and good forever)? Something completely different?

**Comment by rhutsAMD** [comment]
The AMFTrace object is static and alive from as soon as the DLL / SO is loaded until it is unloaded.
