### ISSUE TITLE
HEVC Main 10 support in Radeon RX 6800 XT

### ISSUE THREAD

**Issue by Shhiva5** [GPUOpen-LibrariesAndSDKs/AMF#418]
AMF version : 1.4.30
AMD GPU Hardware : Radeon RX 6800 XT

API Reference: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/a118570647cfa579af8875c3955a314c3ddd7058/amf/doc/AMF_API_Reference.pdf
HEVC API Reference: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/a118570647cfa579af8875c3955a314c3ddd7058/amf/doc/AMF_Video_Encode_HEVC_API.pdf 

When initialization the encoder for P010, we are getting AMF_INVALID_FORMAT. MemoryType is AMF_MEMORY_DX11. Essentially, we are unable to get HEVC Main 10 encoding support. 
Could anyone please suggest how to encode 10-bit yuv (HEVC Main 10) in AMD Radeon RX 6800 XT hardware using HEVC encoder?

**Comment by rhutsAMD** [comment]
Using 10-bit HEVC encoding requires setting the `AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH` property. Have you made sure to set this property before encoder initialization?
              
Here is an example of how it is set in [MiscHelpers.cpp#L164](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/public/samples/CPPSamples/common/MiscHelpers.cpp#L164)

```cpp
res = pEncoder->SetProperty(AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH, AMF_COLOR_BIT_DEPTH_10);
AMF_RETURN_IF_FAILED(res, L"SetProperty(AMF_VIDEO_ENCODER_HEVC_COLOR_BIT_DEPTH, AMF_COLOR_BIT_DEPTH_10) failed");
```

**Comment by Shhiva5** [comment]
Thank you rhutsAMD.
