### ISSUE TITLE
[Filled Legal Court Complain & 10000000 USD Dollars Compensations against AMD]:

### ISSUE THREAD

**Issue by amdvce** [GPUOpen-LibrariesAndSDKs/AMF#422]
Due of AMD policy, a legal court complain have successfully been filled and present to the respective 2 (two) continents. US and EU.
The main reason is the absolute joke of amd hardware compared with counter-parts such as nvda and intc.
Mostly the quality of video processing, crippled and intentionally reduced per-functions and extreme négligence to it's buyers.
Those above and further more will be something to remember in amd own history, as to not ever again mock it's users/buyers/customers with petty excuses.

Also a complain for github has been filled with compensations too.

**Comment by wbsdty331** [comment]
Please calm down, Github issues is a technical discussion for AMF, not youtube comments area.

**Comment by rhutsAMD** [comment]
Discussion is not related to AMF, closing.
