### ISSUE TITLE
Interop between AMF and different backends covered by SYCL

### ISSUE THREAD

**Issue by romka0017** [GPUOpen-LibrariesAndSDKs/AMF#426]
Hi, AMF team.
We want to build pipeline with cross platform backend video filters and AMD AMF encoding. For fast result we need to use interop.
In VCEEncoderD3D we have example:
 AMF_STD_CALL Convert(AMF_MEMORY_TYPE type) = 0; // optimal interop if possible. Copy through host memory if needed
 AMF_STD_CALL Interop(AMF_MEMORY_TYPE type) = 0; // only optimal interop if possible. No copy through host memory for GPU objects

Could you please describe, which approach do you use inside?

**Comment by MikhailAMD** [comment]
It depends on underling API. For DX & Vulkan we would use shared handles, For DX9, DX11, OGL->OCL, public OCL interop API. It could be some private API if something is missing in the public API. 
What is your case?

**Comment by romka0017** [comment]
We want to use SYCL + HIP backend and AMF encoding.

**Comment by MikhailAMD** [comment]
At this point AMF interop doesn't support these APIs. But AMF interop is mostly based on shared handles (SH) on Windows or file descriptors (FD) on Linux. This is for textures/images and for fences/semaphores. If your app can acquire SH or FD from these APIs and open them in DX or Vulkan, you can submit such textures / images into AMF. You should also take care of synchronization.

**Comment by romka0017** [comment]
And as workaround. Can we create AMF surface and get pointer to raw data?
For example: Allocate AMF  surface -> Fill surface -> Get pointer to data -> apply our SYCL(on HIP) filter -> Encode based on AMF

**Comment by MikhailAMD** [comment]
Sure, access to raw data : surface->GetPlaneAt(planeIndex)->GetNative(). The return depends on surface memory type, some examples:
HOST->raw memory pointer separate for each plane
DX11->ID3D11Texture2D* - common for all NV12/P010/RGBA formats, separate textures for 420P
DX12->ID3D12Resource* - common for all NV12/P010/RGBA fromats, separate textures for 420P
Vulkan->AMFVulkanView* to each plane, see AMFVulkanSurface    *pSurface member to access VkImage
