### ISSUE TITLE
[Request]: Add "monitor off" to Display Capture API

### ISSUE THREAD

**Issue by peacepenguin** [GPUOpen-LibrariesAndSDKs/AMF#428]
**Is your feature request related to a problem? Please describe.**

Amd Link is being retired. We need a way to implement the AMD Link feature "Monitor off" in AMF to be able to recreate that feature in other game streaming apps.

**Describe the solution you'd like**
After selecting a display for Display Capture, we need to be able to signal that the monitor should turn off at the start of the streaming session.

**Describe alternatives you've considered**
AMD Link has this feature. But is unknown how it is implemented. If amd link is killed off as planned, we will have no way to stream with the monitor off.

**Additional context**

**Comment by peacepenguin** [comment]
Closed as complete, fantastic! Is there any documentation on it, or can you point me to the commit that enables this so I can try it out?

**Comment by MikhailAMD** [comment]
I think Roman forgot to add a link: there is ADLX SDK for display management which includes blanking: https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/blob/main/SDK/Include/IDisplaySettings.h
If it is not what you are looking for, please contact ADLX team.
