### ISSUE TITLE
Video Encode API: Crash in CreateComponent with AMD Hybrid/Switchable GPU systems

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#43]
Initialliy reported here (https://obsproject.com/forum/threads/fresh-install-results-in-crash.57277/), it seems that AMF successfully initializes but then fails later on in CreateComponent with an unhandled null pointer exception.

# Data
* Dump: http://www.mediafire.com/file/jbyamki015mylkp/obs32.rar (Thread Id: 3396)
* Device Id: 6660 (Vendor Id: 1002, SubSystem: 3818, SubSystem Vendor: 17AA, Revision: 83) (R5 M330)
* Driver Version: 16.11.2 (Radeon Settings Version: 2016.1103.2042.35350)

**Comment by MikhailAMD** [comment]
The dump in the rar file doesn't match the text file in the report on obsproject.com forum. Dump doesn't have AMF on the stack of the main thread while the text file does . 
1. I would need a dump file with AMF on the stack to prevent the crash.
2. To make it working VCE plug-in should enumerate DX devices and find the correct AMD one. By default AMF creates the first available DX device ( first adapter) which  happens to be Intel and cannot use it.

**Comment by Xaymar** [comment]
1. AMF is on the Call Stack in the Main Thread, [just doubleclick on the entry to go back to it](http://cdn.xaymar.com/private/2016/11/devenv_2016-11-16_19-08-40.png). OBS's crash handler caught it to ensure a safe-ish shutdown of OBS.
2. Shouldn't the expected behaviour be to return AMF_NO_DEVICE or AMF_NOT_SUPPORTED (no device that supports this type of encoding)?

I've asked the user to also provide a log and crash log for the crash now.

**Comment by Xaymar** [comment]
* Log: [2016-11-15 17-35-08.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/595554/2016-11-15.17-35-08.txt)
* Crash Log: [Crash 2016-11-15 17-35-17.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/595555/Crash.2016-11-15.17-35-17.txt)

**Comment by MikhailAMD** [comment]
Yes, I can see the stack if I get VS2015, Originally I tried VS2013. The crash happens in undocumented use of HEVC encoder. I cannot debug or comment on this. Does it happen with AVC? Also please ensure that you are using AMD DX device. AMF can get wrong default one. All device selection should be done by the client code.

**Comment by Xaymar** [comment]
Oh it happens in HEVC, that explains a lot.

**Comment by Xaymar** [comment]
I've removed HEVC testing from the plugin for now, waiting for the user to confirm that it no longer crashes.

**Comment by Xaymar** [comment]
No longer crashes.
