### ISSUE TITLE
[Bug]: <LTR components not working with OBSs current vers.(30.0.2)>

### ISSUE THREAD

**Issue by Johl7** [GPUOpen-LibrariesAndSDKs/AMF#435]
Describe the bug
Encoder error when starting an output in OBS(apparently the encoder tries to fallback to the older encoder version, wichs not supported anymore)

To Reproduce
1. Set the following properties 'LTRMode, MaxOfLTRFrames and/or PALongTermReferenceEnable'
2. Initialize the Encoder

Setup:
 - OS: Windows 11
 - Driver Version 23.12.1
 - RX 6650 XT
 - Encoder on OBS

Debug Log (please upload or paste):
12:45:37.801: [texture-amf-h264] amf_avc_create_texencode: AMFComponent::Init failed: AMF_FAIL
12:12:59.211: [fallback-amf-h264] amf_avc_create_fallback: AMFComponent::Init failed: AMF_FAIL

Expected behavior
No error when starting the encoder

**Comment by MikhailAMD** [comment]
The first encoder is the one which submits D3D11 textures. The fallback is the one that submits frames in system memory. From AMF perspective this is the same encoder and both are supported.  

- What is the exact string for parameters? 
- Does it work if you don't set the properties above?
- Can you provide the full log?
- Can you provide DxDiag log?
- Can you run AMF sample CapabilityManager?

**Comment by Johl7** [comment]
About the non texture based encoder, it was deprecated in OBS awhile ago.

- Log: [2024-01-02 14-09-46.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/13812302/2024-01-02.14-09-46.txt)

- Yep, without the said LTR parameters it works propper

- Params in use: HighMotionQualityBoostEnable=true EnableVBAQ=0 RateControlPreanalysisEnable=0 BReferenceEnable=false LTRMode=0 MaxOfLTRFrames=2 EnablePreAnalysis=true PASceneChangeDetectionEnable=false PALongTermReferenceEnable=true PATemporalAQMode=2 PALookAheadBufferDepth=20
Any value higher than 1 for MaxOfLTRFrame will result in a start error, same for PALongTermReferenceEnable, if set to true, the encoder will always get an error on startup.

The other things that were asked i dunno how to help with.

**Comment by MikhailAMD** [comment]
The problem is in B- frames. OBS AMF implementation forces MaxConsecutiveBPictures to 3 if b-frames supported. But this contradicts with LTR frames. The work-around is to add MaxConsecutiveBPictures=0
I will discuss this internally and see if AMF or OBS need to be fixed

**Comment by Johl7** [comment]
Ohh, how weird... i thought that by setting it to 0 in the OBS UI, or setting BReferenceEnable to false would completely disable it. Ur right, setting MaxConsecutiveBPictures to 0 through the AMF Options space did the trick!

Thanks for the help Mikhail.
