### ISSUE TITLE
using new optical flow technology (fluid motion frames ) for effecient bitrate 

### ISSUE THREAD

**Issue by bisher13** [GPUOpen-LibrariesAndSDKs/AMF#436]
is there Anyplan or possibility to use AFMF technology for amf encoder for increasing video rates without losing a lot of quality

**Comment by MikhailAMD** [comment]
Added new FRC component is in the essence AFMF. https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/public/include/components/FRC.h
You can try :)

**Comment by bisher13** [comment]
i saw it now lol thx for the mention.
