### ISSUE TITLE
Query on CreateSurfaceFromDX11Native

### ISSUE THREAD

**Issue by saurabh-ittiam** [GPUOpen-LibrariesAndSDKs/AMF#438]
AMF version : 1.4.30
AMD GPU Hardware : Radeon RX 6800 XT
Encoder : HEVC

Trying to use `CreateSurfaceFromDX11Native` and it returns `AMF_NOT_SUPPORTED`. For the same DX11 surface, if I get the `D3D11_MAPPED_SUBRESOURCE` and use the host pointer in `CreateSurfaceFromHostNative`, the surface gets created successfully. What could be the reason for this?

Please suggest what information I can provide to help me solve this.

**Comment by MikhailAMD** [comment]
What is your full D3D11_TEXTURE2D_DESC?

**Comment by saurabh-ittiam** [comment]
@MikhailAMD 

```
D3D11_TEXTURE2D_DESC desc;
desc.Height = height;
desc.Width = width;
desc.SampleDesc.Count = 1;
desc.SampleDesc.Quality = 0;
desc.MipLevels = 1;
desc.ArraySize = 1;
desc.Usage = D3D11_USAGE_DYNAMIC;
desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
desc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
desc.MiscFlags = 0;
desc.Format = DXGI_FORMAT_NV12;

```

**Comment by MikhailAMD** [comment]
The only reason why this function can return AMF_NOT_SUPPORTED is if ID3D11Device used in the texture creation is different from the one provided to AMFContext::InitDX11. The device object needs to be shared. If you called AMFContext::InitDX11(nullptr), AMF will create own device object.

**Comment by saurabh-ittiam** [comment]
Thanks @MikhailAMD 

You are right. I was calling `AMFContext::InitDX11(nullptr)`. Once I passed right `ID3D11Device`, `CreateSurfaceFromDX11Native` returns `AMF_OK`.
