### ISSUE TITLE
Frame Skipping causes only I-Frames to be encoded (VCE3.4, RX 4xx, AVC)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#44]
This took a while to track down, mostly because it is so insanely rare to reproduce - in my 14 tests, it happened 3 times and it seems heavily dependent on instantaneous GPU load. Since it was so incredibly difficult to reproduce, I don't yet have a log or dump file with AMF trace active.

I used actual game footage to produce this issue, since my attempts with pre-rendered footage didn't seem to cause it at all. It's possible that this only happens in very extreme GPU usage situations. I will continue trying to reproduce it more accurately.

### 2016-11-21
* Portable Test Setup: http://cdn.xaymar.com/private/2016/11/2016-11-21_Issue44_PortableRepro.7z (Also contains log files of earlier tests)
* Example Video Files: http://cdn.xaymar.com/private/2016/11/2016-11-21_Issue44_ExampleVideos.7z

Test setup needs to have the Game Capture pointed real world use case footage like games or benchmarks (Ashes of the Singularity for example).

**Comment by MikhailAMD** [comment]
Problem reproduced, internal ticket created.

**Comment by Xaymar** [comment]
Can no longer reproduce on my end. Considering this fixed unless I'm told otherwise.

**Comment by Xaymar** [comment]
Unable to reproduce with 16.12.2 or 17.1.1.
