### ISSUE TITLE
[Question]: Is RDNA 3 able to encode YUV444 or similar (full chroma resolution) format?

### ISSUE THREAD

**Issue by mdias** [GPUOpen-LibrariesAndSDKs/AMF#441]
I have a 7900 XTX GPU that I'm trying to encode video at full chroma resolution with and can't seem to do it.
I've tried tweaking the SimpleEncoder app and when I call `encoder->Init(formatOut, widthIn, heightIn);` with a 4:4:4 surface format I get a `AMF_INVALID_FORMAT` return result. Trying with HEVC codec.

I'm unsure if I'm just missing some property setting, if it's a current driver limitation or if it's a hardware limitation.

This highly impacts VR gaming that uses video streaming with certain game scenes looking very blurry if colors are - for example - mostly red.

**Comment by rhutsAMD** [comment]
At this point, 4:4:4 encoding is not supported by the hardware.

**Comment by mdias** [comment]
That's bad news. But thank you for the super quick reply 👍
