### ISSUE TITLE
[Request]: Change Bitrate Cap in Adrenaline

### ISSUE THREAD

**Issue by MattyFresh68** [GPUOpen-LibrariesAndSDKs/AMF#443]
**Is your feature request related to a problem? Please describe.**
With the recently added support for 120fps recording/clips, I find it results in slightly soft footage at times due to limited bitrate. Using HEVC at 3440x1440/120fps, I get slightly better results using OBS + cqp + cq level of 17 with HEVC. 

**Describe the solution you'd like**
Increasing the bitrate to something like 125 or 150 Mb/s seems like it would alleviate this softness and I would probably utilize adrenaline for recording more often.

**Describe alternatives you've considered**
Without providing additional rate controls in adrenaline(which I'm ok with in order to keep simplicity), not sure there is really an alternative. 

**Additional context**
I appreciate the continued work and efforts on both the software and encoder performance. Happy you all beat nvidia to the >60fps recording

**Comment by DimkaTsv** [comment]
ReLive developers are separate team from AMF developers. 
So, as feature request it won't work. 

But i guess it can be thought of as: "Can someone pass that simple request to ReLive development team"?

**Comment by MattyFresh68** [comment]
> ReLive developers are separate team from AMF developers. So, as feature request it won't work.
> 
> But i guess it can be thought of as: "Can someone pass that simple request to ReLive development team"?

This is good to know. Thank you. Was suggested to maybe ask here from a friend in the obs discord server after I posted screenshot of sending amd Twitter a DM. Wasn't sure where else I could ask for this feature. Maybe rhuts has some colleagues/contacts to forward my request to 😉

**Comment by MikhailAMD** [comment]
> > ReLive developers are separate team from AMF developers. So, as feature request it won't work.
> > But i guess it can be thought of as: "Can someone pass that simple request to ReLive development team"?
> 
> This is good to know. Thank you. Was suggested to maybe ask here from a friend in the obs discord server after I posted screenshot of sending amd Twitter a DM. Wasn't sure where else I could ask for this feature. Maybe rhuts has some colleagues/contacts to forward my request to 😉

This is in general true, but I've passed this request to ReLive team, in the end ReLive is AMF-based. :)

**Comment by MattyFresh68** [comment]
> > > ReLive developers are separate team from AMF developers. So, as feature request it won't work.
> > > But i guess it can be thought of as: "Can someone pass that simple request to ReLive development team"?
> > 
> > 
> > This is good to know. Thank you. Was suggested to maybe ask here from a friend in the obs discord server after I posted screenshot of sending amd Twitter a DM. Wasn't sure where else I could ask for this feature. Maybe rhuts has some colleagues/contacts to forward my request to 😉
> 
> This is in general true, but I've passed this request to ReLive team, in the end ReLive is AMF-based. :)

You are THE BEST. Thank you!
