### ISSUE TITLE
Driver Crash while streaming and watching stream on 16.11.4 (AVC)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#45]
Was trying to test streaming when all of a sudden everything stopped and the screens flickered black. Happened as soon as the Twitch stream loaded in, so something collided there.

Encoding was done using the R9 285 instead of the RX 480, since the R9 285 is slightly more powerful with AVC encoding.

## System
- MB: Gigabyte H97-D3H-CF
- CPU: Intel i5-4690
- RAM: 16GB DDR3 1333Mhz
- GPU: AMD RX 480 8GB + AMD R9 285
- DSK: 256GB M.2 SSD + 1TB+1TB RAID0
- OS: Windows 10 64-Bit

### 2016-11-21
- Log: https://gist.github.com/1569bb38c176fe1d73e2e579ab4b3a0f (see the end of it, there was more than one recording/streaming attempt to reproduce another issue)
- Dump: http://cdn.xaymar.com/private/2016/11/obs64.7z
- Video: http://cdn.xaymar.com/private/2016/11/2016-11-21%2022-42-28.mkv
### 2016-11-21 22-55
* Log: https://gist.github.com/ea314ca1e16f55099999d68a2d21e0c5
* Dump: http://cdn.xaymar.com/private/2016/11/2016-11-21-22-55_obs64.7z
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-21%2022-54-14.mkv

**Comment by Xaymar** [comment]
Instantly reproduced this again afterwards, happens as soon as the stream loads in chrome. Same GPU used with DX11 and no OpenCL.

* Log: https://gist.github.com/ea314ca1e16f55099999d68a2d21e0c5
* Dump: http://cdn.xaymar.com/private/2016/11/2016-11-21-22-55_obs64.7z
* Video: http://cdn.xaymar.com/private/2016/11/2016-11-21%2022-54-14.mkv

**Comment by Xaymar** [comment]
Seems to be due to use of CABACEnable, the entire system visible hitches when the encoder is initialized with CABACEnable set to anything but 0.

**Comment by Xaymar** [comment]
Common things:
- Encoding Bitrate drops fast
- Display driver resets
- Decoded stream looks fucked up from the start, like a gif with the frames set to copy the previous frames in transparent areas or a game with no color buffer clearing

It can be instantly reproduced when CABACEnable is set to 2 (CALV), 1 in 10 chance to reproduce with 1 (CABAC) and 1 in 50 change to reproduce with 0 (Default?).

**Comment by MikhailAMD** [comment]
Could you please provide exact steps (as 1, 2 , 3) to reproduce the display driver crash: I guess you recorded in OBS + plug-in with all default settings + CABAC to 2 and start playing Twitch video in Chrome. I need the steps to speed things up, I will not have access to HW for 2-3 days and will have to ask someone in the office to repro.

**Comment by Xaymar** [comment]
1. Install OBS Studio 0.16.6 on a Windows 10 (Anniversary Update) System with an AMD GPU (GCN1/2/3/4) and Driver 16.11.4.
2. Initial Setup: [Video Tab](http://cdn.xaymar.com/private/2016/11/2016-11-22_00-04-19.png), [Output Tab](http://cdn.xaymar.com/private/2016/11/obs64_2016-11-22_00-05-12.png)
3. Change "Device" to the installed AMD card.
4. Set up streaming to a service like Twitch, open your twitch page in a hardware accelerated browser (Chrome, Firefox).
5. Set up the scene to be streamed with one Game Capture, I had mine pointed at Steep (Open Beta).
6. Stream and play. It happens randomly, but usually either instantly when the stream loads in the browser or after 3-4 minutes of a really weirdly decoded stream. GPU temps usually also shoot up quickly when this happens.

As usual, a portable repro install exists: http://cdn.xaymar.com/private/2016/11/AMFIssue45_PortableRepro.7z .  It has the profile and scene set up, just needs a twitch streaming key and the correct device to be selected.

**Comment by MikhailAMD** [comment]
This is what I need, thanks.

**Comment by Xaymar** [comment]
While updating the plugin code I noticed that I had switched CABAC and CALVC around, so that setting it to CABAC actually made it set to 2 (CALV) and using CALVC actually made it set to 1 (CABAC). I was however able to reproduce it again with CABACEnable set to anything but 0, so this likely only affected the plugin itself.

**Comment by MikhailAMD** [comment]
The issue was reproduced and internal ticket was opened. Thanks.

**Comment by MikhailAMD** [comment]
The issue seem fixed in ReLive driver 16.12.1. Let me know if you see it again.

**Comment by Xaymar** [comment]
So far not been able to reproduce it again. Looks like it was fixed then. Many thanks!
