### ISSUE TITLE
AMF SDK 1.3 / surface conversion issue ( DX9 -> OpenGL) / FirePro W7100

### ISSUE THREAD

**Issue by hbonnaillie-gpsw** [GPUOpen-LibrariesAndSDKs/AMF#47]
Hi,

I'm facing issue while trying to decode a simple 1080p h264 elementary stream using AMF SDK 1.3 running on AMD Firepro W7100 and the last AMD radeon.

I modified the "PlaybackHW" AMF sample in the following manner:
- In the "PlaybackHW", the decoder is initialized to generate BGRA instead of NV12.
- In the "PlaybackPipeline.cpp", I disabled the video converter (m_pConverter is no more instantiated and not connection to the decode pipeline).
- In the "VideoPresenterOpenGL.cpp", I replaced the call
    -- pSurface->Convert(amf::AMF_MEMORY_OPENGL) by 
   ++pSurface->Interop(amf::AMF_MEMORY_OPENGL) and check the error code.

When I run the application using VideoPresenter OpenGL, The interop function call returns error 10 (AMF_NOT_SUPPORTED).

When I keep the call to convert, the surface is correctly converted to opengl but it is done using CPU and by the way it takes a long time (about 28 msec).

I don't see the reason, interopt shall be working on such hardware.

Regards
HB

**Comment by MikhailAMD** [comment]
Hi,
It will not work this way: The Convert(), Interop() and Duplicate() methods work with limitations of underlying technologies (DX9, DX11, OpenCL, OpenGL). 
For your case you would need that decoder produced OpenGL textures as an output but there is no such API to tell him to do so. This API does exist in Converter (AMF_VIDEO_CONVERTER_MEMORY_TYPE). Keep in mind that the hardware decoder always decodes into NV12 so when you ask the decoder to produce BGRA output you implicitly force the decoder to create the same AMF Converter as the sample does but application doesn't have full control over the converter component.
Converter behaviour: Decoder always output in DX9 or DX11. There is no direct Interop from DX to OpenGL - the one you assume. Instead the Converter does the trick: Converter input is the DX9 surface or DX11 texture, it is interoped into OpenCL. The Converter output is allocated as DX9, DX11 or OpenGL via AMF_VIDEO_CONVERTER_MEMORY_TYPE property and then interoped also in OpenCL. Then the converter does the job from OpenCL to OpenCL. Then the converter un-interops the output back to the allocated type.
Regards,
Mikhail

**Comment by MikhailAMD** [comment]
Does more info required or I can close this?

**Comment by MikhailAMD** [comment]
Closing for now
