### ISSUE TITLE
Encoding from D3D RGBA/BGRA surfaces (encoder fails to init)

### ISSUE THREAD

**Issue by MichaelLudeo** [GPUOpen-LibrariesAndSDKs/AMF#470]
Hi. I am new to AMF.
I need to create h264 encoding app from D3D11 textures which are coming in from a game engine.
I am using the latest version of the SDK, Windows 11, Radeon RX 7600.
I set up my app based on the D3D example in the SDK.
When I call: 

`mAmfEncoder->Init(amf::AMF_SURFACE_BGRA, mWidth, mHeight);`

where mWidth = 1280,mHeigh = 720;

It returns with the error:

>  5178 [AMFEncoderCoreImpl]   Error: ..\..\..\..\..\runtime\src\components\EncoderCore\EncoderCoreImpl.cpp(1209):Assertion failed:InitializePA() - format (BGRA) != AMF_SURFACE_NV12
> 5178 [AMFEncoderCoreH264]   Error: ..\..\..\..\..\runtime\src\components\EncoderCore\EncoderCoreH264Impl.cpp(857):AMF_ERROR 4 : AMF_INVALID_ARG: Failed to initialize PA properly
> 5178 [AMFEncoderCoreH264]   Error: ..\..\..\..\..\runtime\src\components\EncoderCore\EncoderCoreH264Impl.cpp(1018):AMF_ERROR 4 : AMF_INVALID_ARG: InitInternal(): Failed to create Encoder!
>  5178 [AMFEncoderCoreH264]   Error: ..\..\..\..\..\runtime\src\components\EncoderCore\EncoderCoreH264Impl.cpp(456):AMF_ERROR 4 : AMF_INVALID_ARG: _Init() - Failed

I am trying to figure out why the encoder expects NV12. I found a param `AMF_PA_ENGINE_TYPE` which is supposed to set memory type to work with. Maybe I need to use it? I also haven't find any docs explaining this one. Additionally, I was reading AMF encoder implementation in Unreal Engine 4.27 ,and I see they do similar setup to mine, where D3D11 textures are mapped to the input surface and they also use AMF_SURFACE_BGRA as input format. Will appreciate any help as probably I am missing something.

**Comment by MichaelLudeo** [comment]
So I found that `AMF_VIDEO_ENCODER_USAGE_HIGH_QUALITY`  causes that error. If I change to:
`AMF_VIDEO_ENCODER_USAGE_LOW_LATENCY `or `AMF_VIDEO_ENCODER_USAGE_LOW_LATENCY_HIGH_QUALITY` that error doesn't happen. Can someone explain why I can't use HIGH QUALITY preset with BGRA surfaces?

**Comment by rhutsAMD** [comment]
The H264 encoder configuration parameters table in the H264 API doc [here](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Encode_API.md#table-a-1-encoder-configuration-parameters) shows that `AMF_VIDEO_ENCODER_PRE_ANALYSIS_ENABLE` is set when usage is `AMF_VIDEO_ENCODER_USAGE_HIGH_QUALITY`. PreAnalysis is supported on the NV12 format.

If you want to use the high quality defaults usage setting, you may disable PreAnalysis by explicitly setting `AMF_VIDEO_ENCODER_PRE_ANALYSIS_ENABLE` to false, or you may convert your input BGRA surfaces to NV12 to work with PreAnalysis.

**Comment by MichaelLudeo** [comment]
Thanks for the clarification. The issue is solved.
