### ISSUE TITLE
[Question]: How to set 'low latency mode' for decoder?

### ISSUE THREAD

**Issue by MemeTao** [GPUOpen-LibrariesAndSDKs/AMF#478]
I found the amf decoder buffered 3-4 images before first image output:

input:      p1, p2, p3, p4, p5, p6, p7, p8
output:   nil,  nil, nil, p1, p2, p3, p4, p5

always exists 3 frames delay.

here is my codes:
```c++
// every 16.667ms
void doDecode(image) {
  pending_packets_.push_back(image);
  auto image = pending_packets_.front();
  auto res = amf_decoder_->SubmitInput(image);
  if (res == AMF_INPUT_FULL || res == AMF_DECODER_NO_FREE_SURFACES) {
    LOG_INFO("Input full, pending this image, queue size: %" PRIu64 "",
             pending_packets_.size());
    const size_t kMaxQueueLength = 4096;
    if (pending_packets_.size() > kMaxQueueLength) {
      LOG_ERROR("Amf input queue overflow, return false");
      return false;
    }
  } else {
    pending_packets_.pop_front();
  }
  amf::AMFDataPtr new_packet;
  do {
    auto res = amf_decoder_->QueryOutput(&new_packet);
    if (new_packet) {
      decoded_packets_.push_back(new_packet);
    }
    if (res != AMF_REPEAT && res != AMF_OK) {
      LOG_ERROR("call amf::QueryOutput failed, res:%d", res);
      return false;
    }
  } while (!!new_packet);
  if (decoded_packets_.empty()) {
    return true;
  }
  auto pkt = decoded_packets_.front();
  decoded_packets_.pop_front();
}
```
is there a parameters to eliminate the internal queue length?

input: p1, p2, p3, p4,----------p5, p6, p7, p8
output: nil, nil, nil, (p1,p2,p3), p4, p5, p6, p7

get all of images after p4 submit.

**Comment by MikhailAMD** [comment]
Decoder  delays output because of possible reorder of frames. By default, it defines how long to delay based on characteristics of input stream. There is a parameter with three modes to control reorder behavior: AMF_VIDEO_DECODER_REORDER_MODE - see description of each mode in the header.
