### ISSUE TITLE
[Bug]: CapabilityManager fails to create vulkan device "vkCreateDevice() failed, Error=-7" with RADV

### ISSUE THREAD

**Issue by OktaOEDC** [GPUOpen-LibrariesAndSDKs/AMF#479]
**Describe the bug**
I read the latest release notes for AMF (1.4.33) and wanted to try it out with Mesa's RADV driver, but I am getting an error when running the sample "CapabilityManager" (see log down below)

**To Reproduce**
1. Install version 6.0.60002-1 of the amdgpu install script from https://www.amd.com/en/support/linux-drivers
2. Install AMF only `sudo amdgpu-install -y --usecase=amf --accept-eula`
3. Clone the AMF repo 
4. Follow steps 2.1 and 2.2 of this wiki page -> (https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/Build-FFmpeg-with-AMF-Support#2-build-ffmpeg-with-amf-for-linux) . I originally wanted to build FFmpeg with AMF support but it gave me a similar error when using the 'h264_amf' codec while trying to re-encode a video`[h264_amf @ 0x5607a4bd8580] AMF failed to initialise on the given Vulkan device: 1.` hence I tried using the samples
5. Modify file "amf/public/make/common_defs.mak" of the AMF repo and remove line 164 "-Werror \", otherwise it will not build the samples and return an error
6. Build the samples by following the instructions of this wiki article (https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/Build%20Linux)
7. Run Capability Manager

**Setup (please complete the following information):**
 - OS: Ubuntu 22.04.4
 - Driver Version: Mesa 23.2.1-1ubuntu3.1~22.04.2
 - GPU: AMD RX560

**Debug Log (please upload or paste):**
```
AMF version (header):                                                            210000
AMF version (runtime):                                                           210000
0124-04-11 12:27:45 D8A3C740 [DeviceVulkan]   Error: ../../../../public/samples/CPPSamples/common/DeviceVulkan.cpp(404):Assertion failed:CreateDeviceAndQueues() vkCreateDevice() failed, Error=-7
0124-04-11 12:27:45 D8A3C740 [DeviceVulkan]   Error: ../../../../public/samples/CPPSamples/common/DeviceVulkan.cpp(98):AMF_ERROR 1 : AMF_FAIL: CreateDeviceAndFindQueues() failed

Querying CPU capabilities...
        Vendor: GenuineIntel
        Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
        Supported Instruction Sets:
                SSE capabilities:
                        SSE
                        SSE2
                        SSE3
                        SSSE3
                        SSE4.1
                        SSE4.2
                AVX capabilities:
                        AVX
                        AVX2

```

**Expected behavior**
No errors when running

Please let me know what other information I can provide to solve this issue.

**Comment by MikhailAMD** [comment]
New AMD drivers and AMF support GPUs starting from RX 5xxx. Your GPU RX560 is not supported. Sorry.

**Comment by OktaOEDC** [comment]
Understood, thanks for the info
