### ISSUE TITLE
Artifacting with h264(Bframes + HMQB)

### ISSUE THREAD

**Issue by Johl7** [GPUOpen-LibrariesAndSDKs/AMF#485]
Video encoding is artifacting when using both bframes and HMQB in conjunction

In OBS
1. Set both bframes(any value) and HMQB to on
2. Initialize the Encoder
3. Output will have some visible bluish artifacting at times

**Setup
 - OS: W11
 - Driver Version 24.5.1
 - GPU RX 6650 XT
 - Encoder issue

**Expected behavior**
No artifacting occurs

**Screenshots**
![Screenshot 2024-06-16 092619](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/83582881/a3f2ed52-0db2-4e87-98ef-929deaf7c142)

**Comment by lextra2** [comment]
Why did you close this? Did you solve the issue?

**Comment by Johl7** [comment]
> Why did you close this? Did you solve the issue?

Ohh, its because i was mistaken, that bluish is from the game.. lol. Some glitches can occur, but only when paired with some params, like PA, theres some other(or a combo o em) but about those, iam not sure wich o em causes it.

**Comment by lextra2** [comment]
> > Why did you close this? Did you solve the issue?
> 
> Ohh, its because i was mistaken, that bluish is from the game.. lol. Some glitches can occur, but only when paired with some params, like PA, theres some other(or a combo o em) but about those, iam not sure wich o em causes it.

Ok. Thanks for clarifying.
