### ISSUE TITLE
[Question]: Question about HQVBR bitrate management

### ISSUE THREAD

**Issue by DimkaTsv** [GPUOpen-LibrariesAndSDKs/AMF#489]
Sorry for probably silly question, but how HQVBR works in particular (and HQCBR as well, which is even more weird as it is technically CBR, but with preanalysis?)? Are there optimal settings? (like max bitrate proportion to average bitrate limitation) 

I understand that it is more conservatively expends available bitrate to create buffer for future transitions. But is it intended for it to completely not follow set average bitrate?

Question arose after i tried to transcode animated movie. I wanted to use around 8000 kbps bitrate, and VBR 8000 worked for this, but with HQVBR it didn't work as i would've expected. At HQVBR 8000/32000 result had 5804 kbps. During next experiments i got 7604 kbps when using HQVBR 12000/48000 and 8564 kbps at HQVBR 15000/60000. (for context, result was about 8250 kbps when i used VBR 8000). Issue here is that despite HQVBR better balancing allowing better compensation for worst case transitions, it can be (at least currently) much harder to figure out actual bitrate that video will encode at. 

So i decided to ask if this is intended behaviour or not, because increasing set bitrate still clearly works and you get output with higher bitrate as well, but said increase is not linear.

**Comment by rhutsAMD** [comment]
Could you please clarify what you mean by “At HQVBR 8000/32000 result had 5804 kbps.” Does this mean you set the target bitrate to 8000 and peak bitrate to 32000?

**Comment by DimkaTsv** [comment]
>Could you please clarify what you mean by “At HQVBR 8000/32000 result had 5804 kbps.” Does this mean you set the target bitrate to 8000 and peak bitrate to 32000?

Yes, pretty much exactly what i meant. Peak bitrate was set to 4x target (if i do remember correctly for VBR 3-4x difference is recommended, isn't it?). 

Here are examples:
1.1 Command (HQVBR 5000/20000): `C:\Users\-----\Videos\Processing>C:\Users\-----\Desktop\Utilites\VCE_Encoder\VCEEncC_x64\\VCEEncC64.exe -i C:\Users\-----\Videos\Processing\Test_fragmented.mkv -o "Test_fragmented_processed.mkv" --codec HEVC --profile main --tier high --level 6.2 --preset slow --vbrhq 5000 --max-bitrate 20000 --output-res 3840x-2 --vpp-resize amf_fsr --pa lookahead=41,sc=high,ss=high,activity-type=y,taq=2,ltr=true --audio-copy --chapter-copy --sub-copy --log vceencc_log.txt --log-level info`

1.2 Output: 
```
------------------------------------------------------------------------------------------
Test_fragmented_processed.mkv
------------------------------------------------------------------------------------------
Pre-analysis will be enabled for VBR-HQ mode.
VCEEnc (x64) 8.23 (r1710) by rigaya, Jul 18 2024 12:57:57 (VC 1940/Win)
OS:            Windows 11 x64 (22631) [UTF-8]
CPU:           AMD Ryzen 7 5800X3D 8-Core Processor [4.48GHz] (8C/16T)
GPU:           AMD Radeon RX 7800 XT [32.0.11029.1008]
AMF:           Runtime 1.4.34 / SDK 1.4.34
Input Info:    avvce: H.264/AVC, 1920x1080, 24000/1001 fps
VPP            HQscaler: 1920x1080 -> 3840x2160, fsr, sharpness 0.5
Output:        H.265/HEVC  main @ Level 6.2 (high tier)
               3840x2160p 0:0 23.976fps (24000/1001fps)
               avwriter: hevc, eac3, eac3, truehd, truehd, subtitle#1,
                subtitle#2, subtitle#3, subtitle#4, subtitle#5 => matroska
Quality:       slow
VBR-HQ:           5000 kbps
Max bitrate:   20000 kbps
QP:            Min: 0:0, Max: 51:51
VBV Bufsize:   5000 kb
Bframes:       0 frames
Pre Analysis:  sc high, ss high, activity y
               lookahead 41, caq medium, paq none, taq 2, motion-qual none, ltr on
Ref frames:    2 frames
LTR frames:    4 frames
Motion Est:    Q-pel
Slices:        1
GOP Len:       240 frames
Others:        skipframe:on deblock
Terminating internal PA thread s, 2865 kb/s, remain 0:00:00, GPU 9%, VE 66%, est out size 204.2MB

encoded 14399 frames, 22.01 fps, 2868.61 kbps, 205.37 MB
encode time 0:10:54, CPU: 0.1%, GPU: 9.7%, VE: 61.5%
frame type IDR    60
frame type I      60,  avgQP  26.33,  total size    8.78 MB
frame type P   14339,  avgQP  25.97,  total size  196.59 MB
```
2.1 Command (HQVBR 8000/32000): `C:\Users\-----\Videos\Processing>C:\Users\-----\Desktop\Utilites\VCE_Encoder\VCEEncC_x64\\VCEEncC64.exe -i C:\Users\-----\Videos\Processing\Test_fragmented.mkv -o "Test_fragmented_processed.mkv" --codec HEVC --profile main --tier high --level 6.2 --preset slow --vbrhq 8000 --max-bitrate 32000 --output-res 3840x-2 --vpp-resize amf_fsr --pa lookahead=41,sc=high,ss=high,activity-type=y,taq=2,ltr=true --audio-copy --chapter-copy --sub-copy --log vceencc_log.txt --log-level info`

2.2 Output:
```
------------------------------------------------------------------------------------------
Test_fragmented_processed.mkv
------------------------------------------------------------------------------------------
Pre-analysis will be enabled for VBR-HQ mode.
VCEEnc (x64) 8.23 (r1710) by rigaya, Jul 18 2024 12:57:57 (VC 1940/Win)
OS:            Windows 11 x64 (22631) [UTF-8]
CPU:           AMD Ryzen 7 5800X3D 8-Core Processor [4.48GHz] (8C/16T)
GPU:           AMD Radeon RX 7800 XT [32.0.11029.1008]
AMF:           Runtime 1.4.34 / SDK 1.4.34
Input Info:    avvce: H.264/AVC, 1920x1080, 24000/1001 fps
VPP            HQscaler: 1920x1080 -> 3840x2160, fsr, sharpness 0.5
Output:        H.265/HEVC  main @ Level 6.2 (high tier)
               3840x2160p 0:0 23.976fps (24000/1001fps)
               avwriter: hevc, eac3, eac3, truehd, truehd, subtitle#1,
                subtitle#2, subtitle#3, subtitle#4, subtitle#5 => matroska
Quality:       slow
VBR-HQ:           8000 kbps
Max bitrate:   32000 kbps
QP:            Min: 0:0, Max: 51:51
VBV Bufsize:   8000 kb
Bframes:       0 frames
Pre Analysis:  sc high, ss high, activity y
               lookahead 41, caq medium, paq none, taq 2, motion-qual none, ltr on
Ref frames:    2 frames
LTR frames:    4 frames
Motion Est:    Q-pel
Slices:        1
GOP Len:       240 frames
Others:        skipframe:on deblock
Terminating internal PA thread s, 4861 kb/s, remain 0:00:00, GPU 9%, VE 62%, est out size 346.4MB

encoded 14399 frames, 21.94 fps, 4864.08 kbps, 348.23 MB
encode time 0:10:56, CPU: 0.1%, GPU: 9.7%, VE: 62.7%
frame type IDR    60
frame type I      60,  avgQP  24.20,  total size   12.15 MB
frame type P   14339,  avgQP  24.00,  total size  336.08 MB
```

**Comment by DimkaTsv** [comment]
Oh, just found even more interesting example! There can also be almost 0 difference between 7500 and 10000 kbps in target bitrate. At this point i really don't think it is how it is supposed to work... 

HQVBR 7500/22500: `--codec HEVC --profile main --tier high --level 6.2 --preset slow --vbrhq 7500 --max-bitrate 22500 --pa lookahead=41,sc=high,ss=high,activity-type=y,taq=2,ltr=true --audio-copy --chapter-copy --sub-copy`

Result: 
```
------------------------------------------------------------------------------------------
Test_fragmented_processed.mkv
------------------------------------------------------------------------------------------
Pre-analysis will be enabled for VBR-HQ mode.
VCEEnc (x64) 8.23 (r1710) by rigaya, Jul 18 2024 12:57:57 (VC 1940/Win)
OS:            Windows 11 x64 (22631) [UTF-8]
CPU:           AMD Ryzen 7 5800X3D 8-Core Processor [4.46GHz] (8C/16T)
GPU:           AMD Radeon RX 7800 XT [32.0.11029.1008]
AMF:           Runtime 1.4.34 / SDK 1.4.34
Input Info:    avvce: H.264/AVC, 1920x1080, 24000/1001 fps
Output:        H.265/HEVC  main @ Level 6.2 (high tier)
               1920x1080p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc, eac3, eac3, truehd, truehd, subtitle#1,
                subtitle#2, subtitle#3, subtitle#4, subtitle#5 => matroska
Quality:       slow
VBR-HQ:           7500 kbps
Max bitrate:   22500 kbps
QP:            Min: 0:0, Max: 51:51
VBV Bufsize:   7500 kb
Bframes:       0 frames
Pre Analysis:  sc high, ss high, activity y
               lookahead 41, caq medium, paq none, taq 2, motion-qual none, ltr on
Ref frames:    2 frames
LTR frames:    4 frames
Motion Est:    Q-pel
Slices:        1
GOP Len:       240 frames
Others:        skipframe:on deblock
Terminating internal PA thread s, 2250 kb/s, remain 0:00:00, GPU 12%, VE 73%, est out size 160.3MB

encoded 14399 frames, 75.17 fps, 2246.96 kbps, 160.86 MB
encode time 0:03:11, CPU: 0.2%, GPU: 12.5%, VE: 79.4%
frame type IDR    60
frame type I      60,  avgQP  20.53,  total size    7.06 MB
frame type P   14339,  avgQP  20.60,  total size  153.81 MB
```

HQVBR 10000/30000: `--codec HEVC --profile main --tier high --level 6.2 --preset slow --vbrhq 10000 --max-bitrate 30000 --pa lookahead=41,sc=high,ss=high,activity-type=y,taq=2,ltr=true --audio-copy --chapter-copy --sub-copy`

Result: 
```
------------------------------------------------------------------------------------------
Test_fragmented_processed.mkv
------------------------------------------------------------------------------------------
Pre-analysis will be enabled for VBR-HQ mode.
VCEEnc (x64) 8.23 (r1710) by rigaya, Jul 18 2024 12:57:57 (VC 1940/Win)
OS:            Windows 11 x64 (22631) [UTF-8]
CPU:           AMD Ryzen 7 5800X3D 8-Core Processor [4.45GHz] (8C/16T)
GPU:           AMD Radeon RX 7800 XT [32.0.11029.1008]
AMF:           Runtime 1.4.34 / SDK 1.4.34
Input Info:    avvce: H.264/AVC, 1920x1080, 24000/1001 fps
Output:        H.265/HEVC  main @ Level 6.2 (high tier)
               1920x1080p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc, eac3, eac3, truehd, truehd, subtitle#1,
                subtitle#2, subtitle#3, subtitle#4, subtitle#5 => matroska
Quality:       slow
VBR-HQ:           10000 kbps
Max bitrate:   30000 kbps
QP:            Min: 0:0, Max: 51:51
VBV Bufsize:   10000 kb
Bframes:       0 frames
Pre Analysis:  sc high, ss high, activity y
               lookahead 41, caq medium, paq none, taq 2, motion-qual none, ltr on
Ref frames:    2 frames
LTR frames:    4 frames
Motion Est:    Q-pel
Slices:        1
GOP Len:       240 frames
Others:        skipframe:on deblock
Terminating internal PA thread s, 2255 kb/s, remain 0:00:00, GPU 11%, VE 69%, est out size 160.3MB

encoded 14399 frames, 73.35 fps, 2256.00 kbps, 161.51 MB
encode time 0:03:16, CPU: 0.2%, GPU: 12.1%, VE: 77.9%
frame type IDR    60
frame type I      60,  avgQP  20.48,  total size    7.09 MB
frame type P   14339,  avgQP  20.58,  total size  154.42 MB
```

**Comment by rhutsAMD** [comment]
Based on the provided description, the encoder’s behaviour is expected.

The purpose of HQVBR/HQCBR is mainly to guarantee the perceptual quality of the encoded video. It will not spend extra bits on scenes that do not bring in perceptual benefits. It will also try to retain minimum video quality without excessive coding artifacts.

Therefore, in the case of very simple scenes such as animation in your case, there is a chance that it will not generate the bitrate as high as you have set. On the other hand, if the scene is extremely complicated, it would likely overshoot the bitrate when the target is set too low.

**Comment by DimkaTsv** [comment]
Oh, i see. 
It's not that i didn't expect that it has internal limiters on max and min quality, just before all videos i used it on were more complex so encoder followed target pretty tightly (sometimes even better than VBR). To be fair, i guessed about their existence, but nothing besides that.

And still... Based on what you said and with exact sample mentioned above, it should not be expected result, that if i try to set target to HQVBR 2500/7500, then encoder won't even try to approach same bitrate that it reached before... For some reason... Instead becomes even more conservative. 

Command (HQVBR 2500/7500): ` --codec HEVC --profile main --tier high --level 6.2 --preset slow --vbrhq 2500 --max-bitrate 7500 --pa lookahead=41,sc=high,ss=high,activity-type=y,taq=2,ltr=true --audio-copy --chapter-copy --sub-copy`

Result:
```
Terminating internal PA thread s, 1492 kb/s, remain 0:00:00, GPU 7%, VE 82%, est out size 106.3MB

encoded 14399 frames, 79.98 fps, 1492.72 kbps, 106.87 MB
encode time 0:03:00, CPU: 0.2%, GPU: 7.4%, VE: 100.0%
frame type IDR    60
frame type I      60,  avgQP  23.20,  total size    4.97 MB
frame type P   14339,  avgQP  22.95,  total size  101.89 MB
```
.

If anything, even when setting target to HQVBR 5000/15000 it still doesn't reach strict bitrate limit based on quality expectations. 

Command (HQVBR 5000/15000):  `--codec HEVC --profile main --tier high --level 6.2 --preset slow --vbrhq 5000 --max-bitrate 15000 --pa lookahead=41,sc=high,ss=high,activity-type=y,taq=2,ltr=true --audio-copy --chapter-copy --sub-copy`

Result:
```
Terminating internal PA thread s, 2155 kb/s, remain 0:00:00, GPU 7%, VE 83%, est out size 153.2MB

encoded 14399 frames, 77.28 fps, 2156.14 kbps, 154.36 MB
encode time 0:03:06, CPU: 0.2%, GPU: 7.0%, VE: 82.2%
frame type IDR    60
frame type I      60,  avgQP  20.82,  total size    6.78 MB
frame type P   14339,  avgQP  20.82,  total size  147.58 MB
```


If it is proper behavior, then is there any way to predict what resulting bitrate i might expect compared to what i set if video is not as demanding? Because it's not like this quality threshold is always static (aka hard limited), but instead somehow scales based on what set bitrate i use. And non-linearly at that! Otherwise bitrate would've not dropped from 2256 kbps to 2156 to 1492 kbps when i reduce target from 7500 to 5000 to 2500. Because it should fit under limits in all cases.

**Comment by rhutsAMD** [comment]
If you would like to have more control over bitrate accuracy, please consider using `PCVBR`. This rate control method technically should not reduce bitrate accuracy at extremely low/high bitrates, or when scene is extremely simple/complex, as does `HQVBR`.

**Comment by DimkaTsv** [comment]
I see. So, if i understood correctly, as `HQVBR `has algorithm based on constraining and limiters, it was not intended to be used on non-demanding videos.

So, in case when i hit case when result is overly constrained and i want strict bitrate, i should just use `VBR` (if i understand correctly by looking on documentation `VBR` is what you called `PCVBR`). It will inflict penalty on some peak to peak quality variation in edge cases, but will allow me to achieve higher quality in general in cases when HQVBR is constraining bitrate too much.

Or, as other option, i can use HQVBR with some very high bitrate limit so it would hit bitrate limit due to quality threshold instead of landing target bitrate onto constriction range. This way it will make video with highest bitrate expected instead of just overly constricting it. 

Understood. Thanks for answering. 
Resolved.

**Comment by DimkaTsv** [comment]
Oh, wait... I just thought of another question. This one should be quick, though. 
Is there any tangible difference between HQVBR and HQCBR? Or are they basically same thing? 

It is just that based on quick test i did they produced 1:1 results... I cannot even guess how CBR could actually work with such adaptive algorithm... Oh, and on different source (non-demanding one) outputs were different for some reason. Technically it may be due to VBV buffer size being automatically set to different values, but still.

**Comment by rhutsAMD** [comment]
Glad to help :)

Usually, when we talk about VBR in the AMD encoder domain, we are referring to PCVBR. Most of the time, you can consider them identical.

[GPUOpen-LibrariesAndSDKs/AMF/wiki/Rate Control Methods#peak-constraint-variable-bitrate-pcvbr](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/Rate%20Control%20Methods#peak-constraint-variable-bitrate-pcvbr)

When comparing HQVBR and PCVBR, HQVBR allows the bitrate to vary more significantly based on content. Therefore, HQVBR is suitable for scenarios where there is high tolerance for bitrate variation and a high demand for quality.

VBR has precise rate control and low tolerance for bitrate variation, aiming to provide the best possible video quality within the bitrate constraints. Therefore, PCVBR is suitable for scenarios where there is low tolerance for bitrate variation.

HQ-VBR and HQ-CBR aim to maintain constant perceptual quality. HQ-VBR uses a larger buffer than HQ-CBR, allowing for greater frame size variance. As a result, HQ-VBR typically provides better quality than HQ-CBR.
