### ISSUE TITLE
[Question]: How do avoid generate keyframe when dynamic change encoder frame rate?

### ISSUE THREAD

**Issue by MemeTao** [GPUOpen-LibrariesAndSDKs/AMF#494]
I want to decrease| increase frame rate dynamically, But every time i call 'SetProperty(FrameRate)' will generate key frame automatically.
Is there any method can avoid this like nvenc?

**Comment by MikhailAMD** [comment]
Which codec?

**Comment by MemeTao** [comment]
> Which codec?

AMFVideoEncoderHW_HEVC.

Platform: AMD Radeon RX 7700 XT.
OS: Windows 11

**Comment by MemeTao** [comment]
> Which codec?
AMFVideoEncoderHW_HEVC.

Platform: AMD Radeon RX 7700 XT.
OS: Windows 11

Is there any api to avoid generate key frame when dynamic change frame rate (set_property(FRAMERATE, fps))?@MikhailAMD

**Comment by MemeTao** [comment]
> Currently every change in framerate property causes insertion of IDR frame. This is done to have ability to insert SPS with VUI header with timing information containing the new framerate. If you want to change framerate just to manage bitrate control, you can use bitrate instead. The effect would be the same.

Thanks. You are right. I just want to control the bitrate. I will try the method you said.
