### ISSUE TITLE
[Question]: Is RateControlPreanalysisEnable for AVC still an integer value? Documentation

### ISSUE THREAD

**Issue by lextra2** [GPUOpen-LibrariesAndSDKs/AMF#497]
See
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/a6fca4a3bb5585bd0bca4d1a531c40e39f5f572b/amf/public/include/components/VideoEncoderVCE.h#L200

But for HEVC & AV1 its a bool:
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/a6fca4a3bb5585bd0bca4d1a531c40e39f5f572b/amf/public/include/components/VideoEncoderHEVC.h#L186

Is this still the case or is this an oversight?

**Comment by MikhailAMD** [comment]
It was an oversight in H264 and supposed to be bool. But it is too late to change for backward compatibility reasons.

**Comment by lextra2** [comment]
Thank you for clarifying!
