### ISSUE TITLE
[Question]: ffmpeg Why only amf h264 encoder without decoder?

### ISSUE THREAD

**Issue by xengine-qyt** [GPUOpen-LibrariesAndSDKs/AMF#504]
https://www.gyan.dev/ffmpeg/builds/   full build

avcodec_find_encoder_by_name("h264_amf");   it's ok

avcodec_find_decoder_by_name("h264_amf");   return NULL..

cpu(gpu): ryzen 7840hs   win 11x64
How to use amd decode?

**Comment by MikhailAMD** [comment]
You need patches with AMF decoder, AMF HW context and AMF scaler/color converter. Two versions where already submitted but needed more work. A new set of patches will be submitted soon. Once the patches are approved by community, they will be merged into FFmpeg master.

**Comment by xengine-qyt** [comment]
> You need patches with AMF decoder, AMF HW context and AMF scaler/color converter. Two versions where already submitted but needed more work. A new set of patches will be submitted soon. Once the patches are approved by community, they will be merged into FFmpeg master.

o ...ok.i don't know how to patche amf decoder ,I'd better wait for the patch to be merged into ffmpeg
