### ISSUE TITLE
[Question]: Is HighMotionQualityBoostEnable=true required for PAHighMotionQualityBoostMode=1

### ISSUE THREAD

**Issue by lextra2** [GPUOpen-LibrariesAndSDKs/AMF#507]
1. Do I have to explicitly set `HighMotionQualityBoostEnable=true` if I want to use `PAHighMotionQualityBoostMode=1` ?

2. Or does just `PAHighMotionQualityBoostMode=1` also imply and set `HighMotionQualityBoostEnable=true` ?

**Comment by Johl7** [comment]
1. Nope
2. Nope, they are supposed  to be 2 different parameters, so u either set one or the other. The docs states that PAHMQB overrides HMQB when both are enabled(and PA is on, ofc).

**Comment by lextra2** [comment]
>The docs states that PAHMQB overrides HMQB when both are enabled

Mind linking me those docs?
Neither
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Encode_HEVC_API.md
nor
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_PreAnalysis_API.md
had info on that

**Comment by Johl7** [comment]
> > The docs states that PAHMQB overrides HMQB when both are enabled
> 
> Would you mind linking me those docs? None of these two: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Encode_HEVC_API.md
> 
> https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_PreAnalysis_API.md
> 
> say anything about that

https://github.com/GPUOpen-LibrariesAndSDKs/AMF/wiki/AMF-Encoder-Settings-and-Tuning-in-FFmpeg

**Comment by lextra2** [comment]
Thanks for the link. It does imply that they are indeed seperate functions.
