### ISSUE TITLE
About 4k 60hz encoding,HDR/stereo capture support,H264 ME mode..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/AMF#51]
Hi,
three questions:
1) last week release of Relive game capture tool slides, mention that no current AMD GPU support capturing games at 4k 60hz only 4k 30fps maximum on Fiji and Polaris.. is that due to limitation of HW or AMF framework or the Relive tool by itself? i.e. AMF supports 4k 60fps encoding (either HEVC or H264) on current Polaris HW? if not hope upcoming Vega GPU supports that use case..
2) also from Nvidia recieved mail "DesignWorks December 2016 Release" saying new codec sdk and
Nvidia capture sdk releases:
***Codec SDK** supports already 10bit color with HEVC codec and mentions "H264 ME only mode" seems used for Oculus spacewarp but nice to expose also for developers wanting to use it..
***Capture sdk** "Version 6.0 focuses on NVFBC improvements including, improved capture times, stereo support, and 10-bit ARGB and HDR support for Pascal based GPUs. Available early 2017"
so question is easy, how about all this features in AMF: 
can explitily mention for every A),B),C) what is current status: existing support, planned/upcoming support, no ETA support..
A)HDR encoding support (i.e. 10 bit color depth) and also support for Relive tool.
Please route request to Relive devs of once this supported allow uploading as "Youtube HDR" videos..
B)Stereo encoding support
C)H264 ME only?

Thanks..

**Comment by MikhailAMD** [comment]
1. It is HW limitation. Cannot comment on upcoming HW.
2. 
A) Cannot comment of future HW
B) Could you please be more clear: there are many ways to encode stereoscopic video with current codecs. Are you asking about MVC extension?
C) ME mode was provided for Oculus by AMF via LiquidVR SDK for Async Space Warp (ASW). Stay tuned for LiquidVR SDL update on this. Public AMF support is not ready. It will help if you state your needs (use cases and application type).
Capture SDK: I hear you.

**Comment by Xaymar** [comment]
To 1: To my knowledge and testing, only [R9 285](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware-VCE3.0#r9-285) and [R9 380](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware-VCE3.0#r9-380) currently support 4K60. Any other card can only to 30 or 48 fps.

**Comment by MikhailAMD** [comment]
Yes these Tonga and Tonga Pro are unique and can support 4K@60.

**Comment by oscarbg** [comment]
Hi Mikhail and Xaymar,
thanks for super fast and informative response..
Ok so current gen GPUs doesn't support encoding 4k@60 HEVC and Tonga supported 4k@60 h.264.. now I understand why I vaguely thought seeing 4k@60 encode in some GPU launch slides some years ago..

A) Also like you answer to A) so seems also 10bit color encodes aren't posible today but hints maybe coming eventually, of course..
You may know there is at least one game "Shadow Warrior 2" that seems to support HDR on AMD GPUs..
so as soon as GPUs support 10 bit encodes may make sense to add HDR game capture support to your Relive tool.. 
With yesterday Radeon Instinct press launch now Vega GPU is semi-public news.. so will now reask you about Vega GPU real soon now maybe after CES you can answer if Vega supports 4k@60 h264 and hevc and 10 bit color depth encodes..

B) Regarding B) was only copying NV anouncement which cited stereo support.. but thinking more about it here are my two cents:
*About MVC ext: Well Intel Media SDK supports it for sure, NV not so sure, and stereo gaming supports days aren't hot like past years but anyway current hot games continue supporting it (notably Square Enix games like Rise of Tomb Raider, and think either Hitman and/or Deus Ex MD).. so yes at least now you Relive tolos is public if some AMD GPUs support MVC encode makes sense to future Relive versions supporting stereo game capture in this games and capturing efficiently via MVC ext. achieving 50% more encoding.. 
also in case stereo gaming is not important enough to justify the effort also with the big bang in VR gaming also makes sense to Relive tool to support capturing VR games (SteamVR/Oculus) and also here capturing the framebuffer and treating left horizontal half of it as left eye and other half as right eye and using MVC may well give improved compression, as similar to stereo render there is lot of correlation (altough eyes are distorted of course) as compressiong the framebuffer as monoscopic..
So yes MVC maybe interesting for capturing stereo games (not dead yet!) and VR games..

C) Thanks for info pointing to new Liquid VR SDK.. was waiting for it but for new multires shading.. maybe a good release..
May use case is for experimenting implementing a idea: Implement spacewarp like technique but for normal games to gain 2x FPS.. this is similar to how multires shading (initially VR optimization) has been used to improve FPS on non VR game (Shadow Warrior 2) so yes want to play with "ME only mode"

Briefly A) and B) would be useful for Relive tool to support HDR (10bit)captures of HDR games and also add support to capture stereo/VR games more efficiently via MVC
For C) as said ME only mode could be useful tool to improve frames in current games on 4k monitors on not so powerful GPUs adding temporally interpolated frames..

Make sense all my wishes?

thanks..

**Comment by MikhailAMD** [comment]
Hi,
A) Display and D3D HDR output of the game and HDR support (10 bit) in encoder are two different things. I have not authority to comment on unreleased product :). This forum is for AMF support. As soon as Vega is released to the public, we release AMF support for Vega and we measure the actual performance we can discuss it here.  AMF SimpleEncoder sample have pretty accurate performance measurement of the encoder.
B) Thank you for your thoughts. I will use them in discussion on future development of AMF, ReLive, Encoder HW etc.
C) The same here. I will use your requests in discussions.
All of this make perfect sense and I am with you on this.

**Comment by Xaymar** [comment]
Question to your response to A: There are defines for P010 and Float surface formats. Do these end up being actual HDR in HEVC or will it convert these back to whatever the encoder is configured to do?

**Comment by wingback18** [comment]
hi ,
im late to this thread , i have a vega56 card , when i try to record gameplay or my desktop using re:live with HDR enable the videos come out with washed out colors while recording with HDR and distorted colors and over saturated on standard 

i want to ask if with the rx vega 56 card hdr recoding is supported on relive

**Comment by MikhailAMD** [comment]
This forum is for AMF integration. You can ask questions about relive on general AMD forums. Though, I forwarded your post to a relive developer.

**Comment by wingback18** [comment]
thank you, 
i been there and they send me here lol
ill wait for an answer then

**Comment by MikhailAMD** [comment]
I got this link from relive developer. Please send me info who sent you here. I will try to straighten this up.

**Comment by Benman2785** [comment]
i "send" you here (https://community.amd.com/thread/232287) - because i wonder if AMF supports HDR; which i dont know - but you may can ask the developer for that :p 

@MikhailAMD 
can you confirm that h264 uses only 8bit - and therefore no HDR? - so we can say that AMF/VCE etc and therefore OBS Studio and ReLive cant stream in HDR
while i think that h265 uses 10bit - so both should be able to record locally in HDR

**Comment by MikhailAMD** [comment]
At this point H264 and HEVC encoders support 8 bit only 4:2:0, no HDR.

**Comment by wingback18** [comment]
thank you.

**Comment by MikhailAMD** [comment]
Navi supports 10 bit encoding in NEVC (P010 input).
