### ISSUE TITLE
[Question]: How to disable AUD?

### ISSUE THREAD

**Issue by MemeTao** [GPUOpen-LibrariesAndSDKs/AMF#510]
codec: Both 264 and 265
How to reproduction: SimpleEncoder
GPU: AMD Radeon RX 6950 XT
Windows: win11

I found that AUD exists in every P frame.  

I set AMF_VIDEO_ENCODER_INSERT_AUD to false, but it doesn't work.

![image](https://github.com/user-attachments/assets/2b06788f-a8f7-4874-bf8e-2c8411601dc5)

![image](https://github.com/user-attachments/assets/d5b6c71a-d392-4145-b751-9fdbe3ff780d)

**Comment by MikhailAMD** [comment]
AMF_VIDEO_ENCODER_INSERT_AUD property is "per-submission" and has to be set on input surface, not on the encoder..
