### ISSUE TITLE
[Question]: QP_I not works on h264

### ISSUE THREAD

**Issue by MemeTao** [GPUOpen-LibrariesAndSDKs/AMF#512]
**Question 1:  How to set qp_i for h264?**

I set QP_I to 22, but the QP value of output frame not equal to 22:
![image](https://github.com/user-attachments/assets/75d56897-ac51-4bdf-a8fe-7ae0b0b77a40)
here is my code:
```c++
set_avc_property(amf_encoder_, QP_I, 22);
amf_encoder_->Init();   // rc = AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_CBR;
```
and i get qp value:
```c++
  uint64_t average_qp = 0;
  pkt->GetProperty(AMF_VIDEO_ENCODER_STATISTIC_AVERAGE_QP, &average_qp);
```
Windows 11 && AMD Radeon RX 6950 XT.

**Question 2: There are min_qp_i and max_qp_i in hevc, but not h264**

**Comment by lextra2** [comment]
>rc = AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_CBR

Have you tried using
`AMF_VIDEO_ENCODER_RATE_CONTROL_METHOD_CONSTANT_QP`

**Comment by MikhailAMD** [comment]
Yes, fixed QP is for CQP rate control method.
h264 only have AMF_VIDEO_ENCODER_MIN_QP and AMF_VIDEO_ENCODER_MAX_QP, no separation by frame type.

**Comment by MemeTao** [comment]
Thanks for replay.
