### ISSUE TITLE
[Bug]: H264 Encoder - B-frame encoded packets are wrongly reported as IDR (OutputDataType == 0)

### ISSUE THREAD

**Issue by actus-reus** [GPUOpen-LibrariesAndSDKs/AMF#515]
**Describe the bug**
B-frame encoded packets are wrongly reported as IDR (OutputDataType == 0 instead of 3). 

**To Reproduce**
1. Setup AMF encoder to
        a. H264 (AMFVideoEncoderVCE_AVC)
        b. Usage = Transcoding
        c. BPicturesPattern = 1

2. Submit inputs to encoder
3. Query output of encoder and log AMFBuffer properties

**Setup (please complete the following information):**
 - OS: Windows 10 
 - Driver Version: 32.0.12019.1028
 - GPU: RX 7600 
 - Which component has the issue:  Encoder

**Debug Log (please upload or paste):**
Encoder properties:

Property 'AdaptiveMiniGOP': false
Property 'AspectRatio': 1,1
Property 'BPicturesPattern': 1
Property 'BReferenceEnable': true
Property 'CABACEnable': 0
Property 'CodecId': 5
Property 'ColorBitDepth': 8
Property 'DeBlockingFilter': true
Property 'EnableEncoderSmartAccessVideo': false
Property 'EnableGOPAlignment': true
Property 'EnablePreAnalysis': false
Property 'EnableSecondaryReference': false
Property 'EnableVBAQ': false
Property 'EncodeLatency': 0
Property 'EncoderGPU': -1
Property 'EncoderInstance': 0
Property 'EncoderMFLowLatency': false
Property 'EndOfSequence': false
Property 'EndOfStream': false
Property 'EngineType': 0
Property 'ExtraData': 0
Property 'ForceLTRReferenceBitfield': 0
Property 'ForcePictureType': 0
Property 'FrameSize': 1280,720
Property 'FullRangeColor': false
Property 'GOPSize': 60
Property 'GOPType': 0
Property 'HalfPixel': true
Property 'HeaderInsertionMode': 2
Property 'HeaderInsertionSpacing': 15
Property 'HighMotionQualityBoostEnable': false
Property 'IDRPeriod': 15
Property 'InColorPrimaries': 0
Property 'InColorProfile': -1
Property 'InColorTransferChar': 0
Property 'InHDRMetadata': 0
Property 'InitialVBVBufferFullness': 64
Property 'InputQueueSize': 16
Property 'InsertAUD': true
Property 'InsertPPS': false
Property 'InsertSPS': false
Property 'InstanceID': -1
Property 'IntraPeriod': 15
Property 'IntraRefreshMBsNumberPerSlot': 0
Property 'IntraRefreshMode': 0
Property 'IntraRefreshNumOfStripes': 1
Property 'IsUVE': true
Property 'LTRMode': 0
Property 'LowLatencyInternal': false
Property 'MarkCurrentWithLTRIndex': -1
Property 'MaxConsecutiveBPictures': 1
Property 'MaxMBPerSec': 1944000
Property 'MaxNumOfTemporalLayers': 1
Property 'MaxNumRefFrames': 4
Property 'MaxOfLTRFrames': 0
Property 'NumOfTemporalEnhancmentLayers': 1
Property 'OutColorPrimaries': 1
Property 'OutColorProfile': -1
...

Here is, in order, the sequence of encoded packet properties retrieved from encoder:

Property 'MarkedLTRIndex': 4294967295
Property 'OutputBufferType': 0
Property 'OutputDataType': 0  [CORRECT - IDR]
Property 'OutputTemporalLayer': 0
Property 'PresentationTimeStamp': 0
Property 'ReferencedLTRIndexBitfield': 0

Property 'MarkedLTRIndex': 4294967295
Property 'OutputBufferType': 0
Property 'OutputDataType': 2  [CORRECT - P-frame]
Property 'OutputTemporalLayer': 0
Property 'PTS_PKEY': 400000
 Property 'PresentationTimeStamp': 400000
Property 'ReferencedLTRIndexBitfield': 0

Property 'MarkedLTRIndex': 4294967295
Property 'OutputBufferType': 0
Property 'OutputDataType': 0   **[INCORRECT - should be reported as a B-frame]**
 Property 'OutputTemporalLayer': 0
Property 'PTS_PKEY': 200000
Property 'PresentationTimeStamp': 200000
Property 'ReferencedLTRIndexBitfield': 0

Property 'OutputBufferType': 0
Property 'OutputDataType': 2   [CORRECT - P-frame]
Property 'OutputTemporalLayer': 0
Property 'PTS_PKEY': 800000
Property 'PresentationTimeStamp': 800000
Property 'ReferencedLTRIndexBitfield': 0

Property 'MarkedLTRIndex': 4294967295
Property 'OutputBufferType': 0    **[INCORRECT - should be reported as a B-frame]**
Property 'OutputDataType': 0
Property 'OutputTemporalLayer': 0
Property 'PTS_PKEY': 600000
Property 'PresentationTimeStamp': 600000
Property 'ReferencedLTRIndexBitfield': 0

**Expected behavior**

B-frame encoded AMFBuffer should be tagged with the correct OutputDataType property of AMF_VIDEO_ENCODER_OUTPUT_DATA_TYPE_B (3)

**Screenshots**
![image](https://github.com/user-attachments/assets/71c8aee1-bcfc-4bce-9b34-b0f928d83d7f)

B-frames are present in the encoded stream. 

**Additional context**
N/A

**Comment by MikhailAMD** [comment]
Yes, this is known issue, already fixed, will come with driver update.

**Comment by actus-reus** [comment]
Excellent. Thanks.

**Comment by Johl7** [comment]
Is there any documentation on those new parameters yet? i couldn't find any

**Comment by Johl7** [comment]
> There are no new parameters in this issue. The output buffer was incorrectly marked in case of B-frames. It should be AMF_VIDEO_ENCODER_OUTPUT_DATA_TYPE_B. The output types are described here: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Encode_API.md

Ohh, ok... i got curious cause this parameter 'EnableSecondaryReference' being set in OBS would not error out when using the latest gpu driver, while with older ones, it would.

**Comment by MikhailAMD** [comment]
You are asking about a non-public parameter. They they are experimental, incomplete or debug parameters. Everything that is ready for use we put in public header files.

**Comment by actus-reus** [comment]
I confirm version 32.0.12033.1030 fixes the issue. Thank you.
