### ISSUE TITLE
Color Shifting with ReLive

### ISSUE THREAD

**Issue by LeninLime** [GPUOpen-LibrariesAndSDKs/AMF#52]
I currently own a RX 460 and have been using it record game play with the help of OBS Studio and the AMF H.264 encoder.  All had been going well with that.  With the release of ReLive and it supporting HEVC, I was quick to test it out.  But something started to become obvious to me quickly was the weird color shift that was happening in my recording that I never experience with OBS.  I tried the AVC and HEVC encoder in ReLive with the same results. 

I go into much greater detail in the link below.  I go by the username "KarMa" on videohelp's website.    

http://forum.videohelp.com/threads/380081-AMD-Polaris-%28Radeon-RX-4xx%29-H265-Encoding-Samples?p=2470495&viewfull=1#post2470495

**Comment by MikhailAMD** [comment]
I let the developer know.


Mikhail
On Fri, Dec 16, 2016 at 8:56am, LeninLime <notifications@github.com<mailto:notifications@github.com>> wrote:


I currently own a RX 460 and have been using it record game play with the help of OBS Studio and the AMF H.264 encoder. All had been going well with that. With the release of ReLive and it supporting HEVC, I was quick to test it out. But something started to become obvious to me quickly was the weird color shift that was happening in my recording that I never experience with OBS. I tried the AVC and HEVC encoder in ReLive with the same results.

I go into much greater detail in the link below. I go by the username "KarMa" on videohelp's website.

http://forum.videohelp.com/threads/380081-AMD-Polaris-%28Radeon-RX-4xx%29-H265-Encoding-Samples?p=2470495&viewfull=1#post2470495

-

**Comment by Xaymar** [comment]
The AMF plugin has the same issue if it fails to create a converter component, so this is most likely what happened.

**Comment by SuslikV** [comment]
Also it is important to keep adjusted all the equipment (sometimes, it is hard to understand where color error is - on converting or on displaying). Useful color test charts: https://obsproject.com/forum/resources/obs-studio-color-space-color-format-color-range-settings-guide-test-charts.442/  (currently OBS Studio uses 8-bit output, BT.601, BT.709; PC, TV range). Please, test you playback software/hardware too.

**Comment by LeninLime** [comment]
Don't want to leave this issue hanging as I've seen some convincing evidence (in the videohelp thread) that ReLive is recording with rec709 color in my 1080p tests.  Which is the correct thing to do.  The issues arises when trying to display it properly with GUI Avisynth programs along with VLC or MPC-HC.  Also found out that if I upload a rec709 video to youtube, the 1080p and 720p versions will display correctly while the 480p and below will display the rec709 as rec601.  So this is a bit of a problem for everyone.    

Anyway seems like the problem was on my end and I'm fine with this issue being closed.

**Comment by MikhailAMD** [comment]
We incline to the similar conclusion but since many people are on vacation including me the public responce is delayed.


Mikhail
