### ISSUE TITLE
[Question]: does rdna 2 HEVC support b frames?

### ISSUE THREAD

**Issue by MattyFresh68** [GPUOpen-LibrariesAndSDKs/AMF#521]
I'm not the greatest at looking at the docs/api infos. Had a friend look into it and it doesn't seem HEVC supports b frames, but figured I'd check with the pros! TIA

**Comment by MikhailAMD** [comment]
Currently AMD GPUs don't have B-frames for HEVC.

**Comment by MattyFresh68** [comment]
Thank you for the confirmation!
