### ISSUE TITLE
HEVC: Latency Constrained VBR not supported?

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#57]
See title. The header defines Latency Constrained VBR as a valid part of the enum, but when actually querying the HEVC propery set, the only allowed values are "Quality (0), PEAKVBR (2), CBR(3)".

Is this intended?

**Comment by MikhailAMD** [comment]
Will add to AMF runtime in the next driver update, thanks

**Comment by Xaymar** [comment]
17.3.1: VBR_LAT (Latency Constrained VBR) is a selectable Option.

Closing as fixed.
