### ISSUE TITLE
install

### ISSUE THREAD

**Issue by monte91** [GPUOpen-LibrariesAndSDKs/AMF#59]
newb question, but can i install this s an exe or where does it go?

**Comment by pcnorden** [comment]
What exactly do you want to have as an .exe?
Almost everything here is a library that you use in visual studio or alike. There are some samples, but you need to: 
1. download the AMD APP SDK [(You can find it here)](http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/).
2. Install visual studio (2013 not 2017 nor 2015)
3. Clone this repo
4. Use visual studio to open the file at "Amf/amf/public/samples/CPPSamples_vs2013.sln" (relative path, not absolute (make sure you unzip it)).
5. Try to compile whatever project you want.

Some warning though, I'm on linux, so I haven't used VS for about 4 months. This is all from my memory, and what I could understand from this repo and the GPUOpen-website. If you have some struggles, let me know and maybe I can help you

**Comment by MikhailAMD** [comment]
Thanks pcnorden. One note to add: all sample projects can be converted to VS2015 and they will work.  I did not try VS2017 yet.

**Comment by monte91** [comment]
oh ok i thought it was ore of a codec pack, thx yall.

**Comment by ajmalrasi** [comment]
why not visual studio 2017 community edition?

**Comment by MikhailAMD** [comment]
working on it.
