### ISSUE TITLE
HEVC: Pre-Pass encoding causes Bluescreen and other side effects for AVC & HEVC

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#62]
Settings HevcRateControlPreAnalysisEnable to true currently causes a bluescreen with rather heavy side effects. Side effects include (but are not limited to):

- CreateComponent returning AMF_ENCODER_NOT_PRESENT for AVC, SVC and HEVC
- Screen flickering as if something was writing directly to the screen buffer while it is being read
- SubmitInput returns AMF_INPUT_FULL while QueryOutput returns AMF_FAIL
- Absolutely nothing happens, including no encoding. It will just sit there forever doing nothing.

### Repro Steps
1. Run VCEEncoderD3D.exe using the following command line

`VCEEncoderD3D.exe -CODEC HEVC -WIDTH 256 -HEIGHT 256 -FRAMES 500 -RENDER DX11 -ADAPTERID 0 -HevcQualityPreset Speed -HevcUsage TRANSCODING -HevcProfile Main -HevcProfileLevel 62 -HevcTier Main -HevcRateControlMethod CBR -HevcRateControlPreAnalysisEnable true -HevcRateControlSkipFrameEnable false -HevcMinQP_I 18 -HevcMaxQP_I 51 -HevcMinQP_P 18 -HevcMaxQP_P 51 -HevcTargetBitrate 3500000 -HevcPeakBitrate 3500000 -HevcQP_I 22 -HevcQP_P 22 -HevcDeBlockingFilter true -HevcFillerDataEnable false -HevcVBVBufferSize 3500000 -HevcInitialVBVBufferFullness 64 -HevcHalfPixel false -HevcQuarterPixel false -HevcMaxNumRefFrames 16 -HevcEnableVBAQ true -HevcGOPSize 60 -HevcGOPSPerIDR 1 -HevcInputQueueSize 32`

2. If the mouse cursor switches to the loading symbol, you probably are going to get a bluescreen.
3. Bluescreen - hope to god that everything is like you left it.
4. Experience side effects in AVC and HEVC encoding after recovering from the bluescreen. Effects vary between CreateComponent return AMF_ENCODER_NOT_PRESENT for AVC/SVC, QueryOutput failing while SubmitInput returns AMF_INPUT_FULL even though nothing was submitted ever and odd screen flickering in the case that AVC or HEVC actually works again.

**Comment by Xaymar** [comment]
In other news, I now have a RX 480 that is incapable of encoding AVC or HEVC!

**Comment by MikhailAMD** [comment]
Are you running 7.1.1 driver?

**Comment by Xaymar** [comment]
17.1.1-jan16. amfrt*.dll version string is:

- 32-bit: 1;4;0;0;1.2;201701131128
- 64-bit: 1;4;0;0;1.2;201701131129

**Comment by MikhailAMD** [comment]
Thanks. Internal ticket was issued.

**Comment by MikhailAMD** [comment]
The BSOD is caused by HW limitation. We will put software checking in the driver. For now frame size cannot be less then 1024x512.

**Comment by MikhailAMD** [comment]
This bug should be fixed in the latest driver release 17.3.1
http://support.amd.com/en-us/download/desktop?os=Windows+10+-+64#

**Comment by Xaymar** [comment]
Confirming as fixed in 17.3.1. Great work!
