### ISSUE TITLE
H265: VUI Header is missing (In Progress)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#63]
Title explains everything, the property is completely ignored and i don't think it's the only one.

`VCEEncoderD3D.exe -OUTPUT h264lossless.h264 -RENDER DX11 -ADAPTERID 0 -FRAMES 240 -WIDTH 1280 -HEIGHT 720 -CODEC AVC -usage transcoding -profile high -profilelevel 52 -qualitypreset quality -framerate 60,1 -ratecontrolmethod cqp -qpi 0 -qpp 0 -qpb 0 -bpicturespattern 0 -idrperiod 30 -fillerdataenable false -fullrangecolor true -maxnumrefframes 16`

Outputs a 60 fps AVC file with near lossless quality (as lossless as NV12 and H264 can get).

`VCEEncoderD3D.exe -OUTPUT h265lossless.h265 -RENDER DX11 -ADAPTERID 0 -FRAMES 240 -WIDTH 1280 -HEIGHT 720 -CODEC HEVC -hevcusage transcoding -hevcprofile main -hevcprofilelevel 62 -hevctier main -hevcqualitypreset speed -hevcframerate 60,1 -hevcratecontrolmethod cqp -hevcqp_i 0 -hevcqp_p 0 -hevcgopsize 30 -hevcgopsperidr 1 -hevcfillerdataenable false -hevcmaxnumrefframes 1 -hevcminqp_i 0 -hevcminqp_p 0 -hevcmaxqp_i 51 -hevcmaxqp_p 51 -hevcenforcehrd true`

Outputs a 25 fps HEVC file with [ridiculous flickering issues](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/61).

In both cases, the Submit/Query total time is low enough so that the encoder can actually output 60 fps, so what gives?

**Comment by MikhailAMD** [comment]
How did you measure fps for the elementary stream this sample produces? the stream doesn't have HEVC VUI header with fps.

**Comment by Xaymar** [comment]
I think that explains the problem then. Without the header any editing software or players just use whatever other information is available. MPC-HC, VLC and ffmpeg all seem to think it's 25.03 fps, so something has to have set that or is that the new default fps for HEVC content?

I measured the FPS by taking what MediaInfo, ffprobe, MPC-HC, VLC and ffmpeg all show. MPC-HC even shows decode latency (<2ms) and dropped frames (0) so it's not a decoding problem.

**Comment by MikhailAMD** [comment]
I've opened an internal ticket requesting to add VUI header into SPS header. VUI should have frame rate information that is used by players and muxers. Currently if a muxer like ffmpeg gets frame rate from calling application or command line the produced file will have the correct frame rate.

**Comment by boxerab** [comment]
@Xaymar , AMD should hire you as QA !

**Comment by Xaymar** [comment]
@boxerab I've tried applying as an intern in Munich (Germany), but I couldn't figure out how to get past the "This job cannot be viewed at this time. It has either been deleted or is no longer available for application." error that shows for every position.

**Comment by boxerab** [comment]
They seem to be hiring a lot of people at the moment, particularly here in Toronto.  Keep trying! @MikhailAMD  should be able to give you a good reference :)

**Comment by boxerab** [comment]
Your attention to detail and persistence are very clear in all of the issues you've opened.

**Comment by SuslikV** [comment]
Is this HEVC able to produce variable frame rate?

**Comment by MikhailAMD** [comment]
Variable frame rate is produced by container by setting timestamps on frames, not by encoder. The frame rate set to encoder is used only for bit distribution in bitrate control. The speed of playback and the time when a frame is presented is outside of encoder realm.

**Comment by Xaymar** [comment]
Is there any news on this @MikhailAMD?

Software and web services recently started supporting HEVC content and the missing VUI headers also means that anything but 609 Partial is not supported by AMF. It will simply be decoded wrong leading to completely wrong colors.

**Comment by MikhailAMD** [comment]
Frame rate and aspect ratio info should be added to VUI header in 17.7.2 driver.

**Comment by Xaymar** [comment]
VUI header does not contain frame rate, aspect ratio. It does however seem to contain the color space and range now. Still defaults to 25.00 FPS and 1:1 Aspect Ratio unless the container provides different values. I've tried all repro tools I have for this issue and they all have the same result.

**Comment by MikhailAMD** [comment]
Tested by modifying SimpleEncoder sample with driver v17.8.1: timeing info (frame rate) is now available in VUI header

**Comment by MikhailAMD** [comment]
There is also a fix for timing value in 17.9.2 driver
