### ISSUE TITLE
HEVC: HevcAspectRatio seems to be not working

### ISSUE THREAD

**Issue by rigaya** [GPUOpen-LibrariesAndSDKs/AMF#64]
I was trying to set aspect ratio to the stream, which does not seem to work with HEVC encoding. (I'm using RX460 with Radeon Software 17.1.1)

When I try
VCEEncoderD3D.exe -output test.264 -WIDTH 1440 -HEIGHT 1080 -FRAMES 500 -usage transcoding -AspectRatio 4,3

The output of ffprobe is like below, I can get H.264 stream with aspect ratio applied.
Stream #0:0: Video: h264 (Main), yuv420p(tv, progressive), 1440x1080 [SAR 4:3 DAR 16:9], 30 fps, 30 tbr, 1200k tbn, 60 tbc

However, when I try
VCEEncoderD3D.exe -output test.hevc -WIDTH 1440 -HEIGHT 1080 -FRAMES 500 -CODEC HEVC -HevcUsage transcoding -HevcAspectRatio 4,3

I get HEVC stream, but the output of ffprobe is like below, aspect ratio not applied.
Stream #0:0: Video: hevc (Main), yuv420p(tv), 1440x1080, 25 fps, 25 tbr, 1200k tbn, 25 tbc

I also checked with MediaInfo, but it was the same. How can I make "HevcAspectRatio" working?

**Comment by MikhailAMD** [comment]
Aspect ratio is stored in the optional VUI header inside SPS NAL unit in AVC and HEVC, AVC encoder produces VUI header while HEVC is not. I already put a request to add VUI to HEVC.

**Comment by MikhailAMD** [comment]
Frame rate and aspect ratio info should be added to VUI header in 17.7.2 driver.

**Comment by MikhailAMD** [comment]
Tested by modifying SimpleEncoder sample with driver v17.8.1: aspect ratio is now available in VUI header
