### ISSUE TITLE
Short mouse freezes while recording

### ISSUE THREAD

**Issue by EliteHunter** [GPUOpen-LibrariesAndSDKs/AMF#65]
I'm having 1-2 second mouse freezes when i'm recording. This is what is repeating millions of times in my log file;

`06:19:07.602: [AMF Encoder] [06:19:07.574][AMFDeviceDX11Impl]    Error: ..\..\..\..\..\runtime\src\core\DeviceDX11Impl.cpp(162):COM failed, HR = 80070057:CreateNativeSurface - CreateTexture2D failed
06:19:07.602: [AMF Encoder] [06:19:07.574][AMFDeviceDX11Impl]    Error: ..\..\..\..\..\runtime\src\core\DeviceDX11Impl.cpp(200):AMF_ERROR 18 : AMF_DIRECTX_FAILED: CreateNativeSurface(format, width, height, true, (void**)&pSurface)
06:19:07.602: [AMF Encoder] [06:19:07.574][AMFSurfaceImpl]    Error: ..\..\..\..\..\runtime\src\core\SurfaceImpl.cpp(292):AMF_ERROR 18 : AMF_DIRECTX_FAILED: AllocPlanes()- CreateSurface`

I even had a log file that was 1.7GB.

I'm using;
OS: Windows 7 x64
CPU: AMD 9590
GPU: AMD 7950
Encoder: H264 Encoder (AMD Advanced Media Framework)
Renderer: Direct3D 11, OpenGL
Color Format: NV12
Mouse: Logitech G900 (Tried with both using a cable and wireless)

I saw the mention of Windows 7 not being able to encode DX11 properly so i tried OpenGL too but the same problem existed. I'm not sure what the mouse freeze is caused by, might be the error output rate that freezes a specific I/O? Not likely since everything else works fine and i haven't seen my CPU go above %60.

**Comment by MikhailAMD** [comment]
Mouse freeze probably means that video driver is restarted. After that DX is not able to allocated textures. I need to understand your full initialization set. 
Win7 has limitations: the encoder can run on DX9 only. If you want to use DX11 or OpenGL as an input you would need to employ interops: There are two ways to do so:
1. Use AMF color space converter. You need to convert from RGB/BGRA to NV12 anyway. To make interop working you have to force the converter to use OpenCL. Call InitDX9(), InitDX11() InitOpenCL() -in this order. The point is OpenCL must be initialized after DX. Then tell the converter to use AMF_VIDEO_CONVERTER_MEMORY_TYPE = AMF_MEMORY_DX11 and AMF_VIDEO_CONVERTER_COMPUTE_DEVICE = AMF_MEMORY_OPENCL. You also have to be ensure that RGB/BGRA textures are allocated with shared handle. BTW: AMF always allocates them this way. But back buffers from DX11 swap chain cannot be allocated with shared handle.
2. Allocate BGRA input texture with shared handle (RGBA will not work). Call surface->Convert(AMF_MEMORY_DX9). This will use interop between DX11 and DX9. use AMF converter without OpenCL programmed for DX9.
