### ISSUE TITLE
Is there an equivalent to this issue tracker for AMD ReLive product issues (driver, screen recorder/capture, profiles, feature support?)

### ISSUE THREAD

**Issue by rdeleonp** [GPUOpen-LibrariesAndSDKs/AMF#67]
As per $SUBJECT, I've seen amazing interaction between AMF's team and the community thru this issue tracker, great results all around, so I was wondering if such a thing exists for AMD Radeon ReLive issues.

Thanks for your time.

**Comment by MikhailAMD** [comment]
Please use this forum: https://community.amd.com/community/support-forums/drivers-software

**Comment by rdeleonp** [comment]
Thanks for the reply.

I'll try it out and hopefully the experience will be similar to the one in this issue tracker.

Cheers.
