### ISSUE TITLE
HEVC: Filler Data causes incorrect output

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#69]
Similar to #60, but this one doesn't crash and instead causes the output to be corrupted/wrong. Possibly the same fix as #60 requires.

**Comment by Xaymar** [comment]
Seems like this is actually a HW decoder issue when it skips frames? If you watch the HEVC stream live as it is being encoded (with no way to skip frames because you don't know if you can), these artifacts do not happen.

**Comment by MikhailAMD** [comment]
Could you please share command line parameters for TranscodeHW and input and output streams?

**Comment by Xaymar** [comment]
I've used lossless Overwatch footage (~22gb in size), so uploading the input may not be as feasible as just recording a quick match in overwatch and using that as input. As for the output, I can upload that on monday when I get my DSL line (cable network was sold off to the highest bidder, leaving me with no internet for ~1 months). VLC, MPC-HC and similar should all immediately show the problem when watching the output.

An example of how it looks:
![http://cdn.xaymar.com/private/2017/02/10/16/2017-02-10_16-40-44.png](http://cdn.xaymar.com/private/2017/02/10/16/2017-02-10_16-40-44.png)

Command line:

* 64-Bit\TranscodeHW.exe -CODEC HEVC -RENDER DX11 -ENGINE DX11 -ADAPTERID 0 -HevcUsage TRANSCODING -HevcQualityPreset Quality -HevcProfile Main -HevcProfileLevel 62 -HevcTier High -HevcRateControlMethod CBR -HevcRateControlSkipFrameEnable FALSE -HevcMinQP_I 18 -HevcMaxQP_I 51 -HevcMinQP_P 18 -HevcMaxQP_P 51 -HevcTargetBitrate 2500000 -HevcPeakBitrate 2500000 -HevcDeBlockingFilter FALSE -HevcFillerDataEnable FALSE -HevcVBVBufferSize 2500000 -HevcInitialVBVBufferFullness 64 -HevcHalfPixel TRUE -HevcQuarterPixel TRUE -HevcEnableVBAQ TRUE -HevcEnableVBAQ TRUE -HevcGOPSPerIDR 2 -HevcGOPSize 30 -HevcRateControlPreAnalysisEnable FALSE -INPUT "A:\Videos\Recording\2016-10-29 20-44-23.mkv" -OUTPUT "A:\Videos\Recording\2016-10-29 20-44-23.DISABLED.h265"
* 64-Bit\TranscodeHW.exe -CODEC HEVC -RENDER DX11 -ENGINE DX11 -ADAPTERID 0 -HevcUsage TRANSCODING -HevcQualityPreset Quality -HevcProfile Main -HevcProfileLevel 62 -HevcTier High -HevcRateControlMethod CBR -HevcRateControlSkipFrameEnable FALSE -HevcMinQP_I 18 -HevcMaxQP_I 51 -HevcMinQP_P 18 -HevcMaxQP_P 51 -HevcTargetBitrate 2500000 -HevcPeakBitrate 2500000 -HevcDeBlockingFilter FALSE -HevcFillerDataEnable FALSE -HevcVBVBufferSize 2500000 -HevcInitialVBVBufferFullness 64 -HevcHalfPixel TRUE -HevcQuarterPixel TRUE -HevcEnableVBAQ TRUE -HevcEnableVBAQ TRUE -HevcGOPSPerIDR 2 -HevcGOPSize 30 -HevcRateControlPreAnalysisEnable TRUE -INPUT "A:\Videos\Recording\2016-10-29 20-44-23.mkv" -OUTPUT "A:\Videos\Recording\2016-10-29 20-44-23.ENABLED.h265"

**Comment by Xaymar** [comment]
Right so disregard anything I said before now. This is the same issue as #60 but with a different result. When Filler Data is turned off, the footage returns to normal. This effect is most likely due to to the fact that my plugin sets dynamic parameters before and after the Init call.

**Comment by Xaymar** [comment]
I will close this until I have further data suggesting the opposite.
