### ISSUE TITLE
Video Encode API: Documentation Error on Page 11

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#7]
On Page 11 it says

`IDRPeriod, 0 ... 1000, Sets IDR period. IDRPeriod= 0 turns IDR off`

It should actually say 1000*FrameRateDen (like before in Media SDK) and 0 doesn't turn IDR off, it creates exactly one IDR frame (at the beginning).

**Comment by Tukan40** [comment]
IDR period parameter is in frames - not related to frame rate.

**Comment by Xaymar** [comment]
Okay, so it was documented wrong in the old SDK. Closing this.
