### ISSUE TITLE
HEVC: Full Input Queue causes crash in atiumd6a.dll on next SubmitInput/QueryOutput call

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#70]
One of the more rare ones, only discovered this by using really noisy footage, like white noise at a 1:1 scale. Nothing critical, since I haven't managed to reproduce this at all with normal footage yet.

Edit: Settings used:

* 1920x1080, 60 FPS, NV12 709 Partial-ish? (HEVC is always full range?)
* Constant Bitrate, 1000kbit/s, Pre-Analysis, VBAQ, Enforce HRD, No Filler Data, No Frame Skipping
* GOP Size 60, GOPS per IDR 2 (2 second interval)

The noise in question: ![noise](https://cloud.githubusercontent.com/assets/437395/22830852/53a3a4fc-efa8-11e6-9fbf-ed2e0e06f289.gif). It's important that this isn't scaled, so it needs to be repeated on x&y axis until it fills the frame.

**Comment by MikhailAMD** [comment]
This bug should be fixed in the latest driver release 17.3.1
http://support.amd.com/en-us/download/desktop?os=Windows+10+-+64#

**Comment by Xaymar** [comment]
Confirming this as completely fixed, the encoder even keeps up with encoding now. Great work!
