### ISSUE TITLE
What does 'EnableVBAQ' do?

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#72]
I couldn't find an explanation for this anywhere (I might have overlooked it if it exists), so I'm asking here now. From what I understand of it, it somehow improves quality - but has no impact on speed at all. I don't know what it stands for (my current guess is Variable Bitrate Average Quality) or if I should even expose this to end-users.

My Tests:

- AVC CQP: No effect
- AVC VBR, 2000 - 9000 kbit, VBV 9000 kbit: VBAQ on slightly reduced peak bitrate
- AVC CBR, 3500 kbit, VBV 3500 kbit: Slightly increased peak bitrate
- HEVC CQP: Turns everything into green blocks similar to the CABAC/CAVLC problem in AVC pre-16.12.1
- HEVC VBR, 2000 - 9000 kbit, VBV 9000 kbit: No impact?
- HEVC CBR, 3500 kbit, VBV 3500 kbit: No Impact?

**Comment by MikhailAMD** [comment]
VBAQ stands for “Variance Based Adaptive Quantization”.
The basic idea of VBAQ:
Human visual system is typically less sensitive to artifacts in highly textured area. In VBAQ mode, we use pixel variance to indicate the complexity of spatial texture. This allows us to allocate more bits to smoother areas. Enabling such feature leads to improvements in subjective visual quality with some content.

**Comment by Xaymar** [comment]
Thank you, I've changed the description in the plugin to match this.
