### ISSUE TITLE
H265: Enforce HRD breaks HEVC bitstream

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#73]
This bug is a strange one as it has a different behaviour depending on other options. I previously reported this as #69, even though that report is incorrect. The visual effect is always identical, the output will look as if the bitrate was at the lowest possible. From there there are two options:

1. If Filler Data is enabled the effect immediately appears and the bitrate goes through the roof (as if it was using CQP with all values at 18) but the visual quality is drastically below normal. This is probably a write out-of-bounds or read out-of-bounds issue, similar to another bug I reported with AVC.
2. If Filler Data isn't enabled the effect appeards after roughly 25 seconds and lasts for about 1 minute and 10 seconds. It then stops for a short while and reappears.

I seem to be unable to reproduce this issue with the TranscodeHW sample, so is it because of how my plugin initializes the encoder? I currently do the following:

- Creation of Factory, Context, Encoder and Convert as described in #68 
- Set up static properties
- Set up dynamic properties
- Init
- Set up dynamic properties (again)

**Comment by Xaymar** [comment]
Example files for each problem:

1. http://cdn.xaymar.com/private/2017/02/15/03/2017-02-12_23-41-44.mkv
2. http://cdn.xaymar.com/private/2017/02/15/02/2017-02-13_00-01-11.mkv

**Comment by Xaymar** [comment]
17.2.1 seems to have fixed this.

**Comment by Xaymar** [comment]
Still not fixed by 17.4.1

**Comment by MikhailAMD** [comment]
Checked HRD parameter with the latest driver v 17.8.2 - according to Vega analyzer the stream is compliant with specs. If problem persists please try to provide complete combination of parameters by modifying SimpleEncoder sample.

**Comment by Xaymar** [comment]
See #80 for what and why this happens. It has very similar symptoms caused by the same set of parameters.

**Comment by Xaymar** [comment]
Has #80 been fixed? IIRC it was the cause for both this and the behavior seen in #80.

**Comment by Xaymar** [comment]
What is the status on this issue? I have not seen this being declared as fixed in any driver patch notes.

**Comment by Xaymar** [comment]
Can no longer reproduce this on the RX 480s. Will re-open if it reappears.
