### ISSUE TITLE
AVC/HEVC: Support for other Timestamps than amf_pts (Feature Request)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#74]
As it stands right now, AMF only ever expects timestamps to be in amf_pts (100 ns IIRC). This makes integration into other formats rather difficult. This causes issues when the container and internal timestamps use different bases.

For example OBS uses a frame based index for the container and doesn't modify the bitstream content:

* If I use the frame index for SetPts the output becomes unseekable in any player.
* If I use fixed amf_pts increments for SetPts multiplied by the frame index, I get a seekable file that slowly desyncs and becomes harder to seek over time.
* If I use variable amf_pts increments for SetPts multiplied by the frame index, I get a seekable file that doesn't desync as much, but still takes longer to seek than it should.

It would be great if AMF started supporting other timebases than 100ns. This way programmers wouldn't have to worry about eventually running out of numbers to represent the frame or running into inaccuracies in integer (fixed timestep) or floating point processing (variable timestep).

The ideal solution is if AMF started using the framerate given to it and use that as a timebase, as it would fix issues with non-integer timebases.

**Comment by MikhailAMD** [comment]
AMF Encoder will generate timestamps and duration only if it was not set on input surface. If you set one it will copy the pts and duration from input surface to output buffer with one caveat: if you enable B-frames and output is reordered the output pts will be resorted to guarantee monotonously increased output. In addition one can attach a private property to the input surface and get it back from the output buffer. There properties are not resorted.

**Comment by Xaymar** [comment]
I am aware of the custom properties however this is not a request for that. Simply put, the way the VUI header is being generated right now results in broken output. I would either have to modify it in software after encoding (ffmpeg remuxing with header rewrite) or get actual control over what is being written to them.

The current ways that I have control over are:

1. Don't set Pts or Duration: results in me being unable to provide decode timestamps to the muxer/obs in their proper format. The muxed file will thus be corrupt in any player or be played back in the wrong order since muxers usually do the reordering on their end. No player supports this to date and ffmpeg remuxing usually doesn't work.
2. Set Pts (and Duration): If it is in frame increments (1 per frame) I get a playable muxed file with proper container timestamps, but the seeking and playback position is locked to perfect keyframes and will cause a quick "catch-up" moment for all players where the video is incredibly fast but audio is normal. If it is in part-second increments (1/FrameRate seconds converted to amf_pts) the output is playable, correctly muxed, playback position is correct but seeking is broken.  After several seconds seeking becomes next to impossible with players freezing or locking up.

Neither of these options are good and the only way to fix this problem is by using ffmpeg to remux so that both the container and the content use the same timestamps.

Ideally we would get control over the VUI fields that actually control this, so that programmers can define the proper vui_time_scale and vui_num_units_in_tick. With control over these the output timestamp is much more accurate than anything that could be produced in amf_pts increments.

Examples:

- 60/1 FPS (60.00 FPS): vui_time_scale is 60, vui_num_units_in_tick 1
- 60000/1001 FPS (59.94 FPS): vui_time_scale is 6000, vui_num_units_in_tick is 1001
- etc

**Comment by MikhailAMD** [comment]
What I am trying to say is that the calling application controls PTS, not the encoder component. And how VUI header is related to PTS? The only connection is that AMF will write frame rate into it. One can use 60000/1001 as a frame rate parameter for the encoder, it will be written to VUI and one can calculate exact PTS for the desired rate.

**Comment by Xaymar** [comment]
[This file](http://cdn.xaymar.com/private/2017/02/14/19/2017-02-14_19-41-32.mkv) should help show the issue. As you can see, it becomes unseekable after several seconds, with each second requiring more and more time to play.

This is with SetPts and SetDuration called with a dynamic timestamp increment based on the result of "FPSDen/FPSNum * FrameNum * AMF_SECOND". The only way that file becomes mostly seekable is by using ffmpeg and rewriting the timestamps to match the video content, causing audio desynchronization.

**Comment by MikhailAMD** [comment]
Again, pts /duration is controlled by the app. The formula you provided will generate PTS on AMF scale: 100th of nanoseconds. But FFmpeg requires a different scale, it is not fixed and depend on container (muxer) type. AMF TranscodeHW sample does conversion of timestamps from AMF to FFmpeg scale. 
FileMuxerFFMPEGImpl.cpp AMFFileMuxerFFMPEGImpl::WriteData()
Application can generate PTS on any scale it prefers, AMF Encoder should return what the app generated without change.

**Comment by Xaymar** [comment]
Nevermind, I found a way to fix it. I just need to make the Duration properly represent the nanosecond difference that happens with framerates that can't be represented ideally using integers.
