### ISSUE TITLE
Sample Tools: Init fails when -WIDTH is greater than 1920 (AVC)

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#75]
This seems to only happen with the sample tools provided in the SDK. The following calls will always result in a AMF_ENCODER_NOT_PRESENT on my system.

Example command line:

* VCEEncoderD3D.exe -RENDER DX11 -ADAPTERID 0 -FRAMES 300 -CODEC AVC -Usage TRANSCODING -Profile High -ProfileLevel 52 -Framerate 60,1 -RateControlMethod CBR -RateControlPreAnalysisEnable DISABLED -RateControlSkipFrameEnable false -MinQP 18 -MaxQP 51 -TargetBitrate 3500000 -PeakBitrate 3500000 -QP_I 22 -QP_P 22 -QP_B 22 -DeBlockingFilter true -FillerDataEnable false -VBVBufferSize 3500000 -InitialVBVBufferFullness 64 -HalfPixel true -QuarterPixel true -MaxNumRefFrames 16 -EnableVBAQ false -FullRangeColor false -BPicturesPattern 0 -WIDTH 2048 -HEIGHT 2048 -OUTPUT ../ResultsH264/H264_2048x2048_Speed.h264 -QualityPreset Speed
* VCEEncoderD3D.exe -RENDER DX11 -ADAPTERID 0 -FRAMES 300 -CODEC AVC -Usage TRANSCODING -Profile High -ProfileLevel 52 -Framerate 60,1 -RateControlMethod CBR -RateControlPreAnalysisEnable DISABLED -RateControlSkipFrameEnable false -MinQP 18 -MaxQP 51 -TargetBitrate 3500000 -PeakBitrate 3500000 -QP_I 22 -QP_P 22 -QP_B 22 -DeBlockingFilter true -FillerDataEnable false -VBVBufferSize 3500000 -InitialVBVBufferFullness 64 -HalfPixel true -QuarterPixel true -MaxNumRefFrames 16 -EnableVBAQ false -FullRangeColor false -BPicturesPattern 0 -WIDTH 2560 -HEIGHT 1440 -OUTPUT ../ResultsH264/H264_2048x2048_Speed.h264 -QualityPreset Speed
* VCEEncoderD3D.exe -RENDER DX11 -ADAPTERID 0 -FRAMES 300 -CODEC AVC -Usage TRANSCODING -Profile High -ProfileLevel 52 -Framerate 60,1 -RateControlMethod CBR -RateControlPreAnalysisEnable DISABLED -RateControlSkipFrameEnable false -MinQP 18 -MaxQP 51 -TargetBitrate 3500000 -PeakBitrate 3500000 -QP_I 22 -QP_P 22 -QP_B 22 -DeBlockingFilter true -FillerDataEnable false -VBVBufferSize 3500000 -InitialVBVBufferFullness 64 -HalfPixel true -QuarterPixel true -MaxNumRefFrames 16 -EnableVBAQ false -FullRangeColor false -BPicturesPattern 0 -WIDTH 3840 -HEIGHT 2160 -OUTPUT ../ResultsH264/H264_2048x2048_Speed.h264 -QualityPreset Speed

HEVC doesn't seem to be affected by this.

**Comment by MikhailAMD** [comment]
The failure is the correct reaction on the provided set of parameters. Here is the formula that calculates max number of reference frames from here: https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC
**capacity = min(floor(MaxDpbMbs / (PicWidthInMbs * FrameHeightInMbs)), 16)** 
for level 5.2 MaxDpbMbs = 184,320
PicWidthInMbs = 2048 /16 = 128
FrameHeightInMbs = = 2048 /16 = 128
so **capacity =11**
If you change -MaxNumRefFrames to **11** the command line works. 
AMF cannot provide this information before Init() call with width and height as parameters.

**Comment by Xaymar** [comment]
Oh i didn't even notice that I still had that one enabled. My bad, sorry. Thanks for that.
