### ISSUE TITLE
No B-Pattern config for HEVC?

### ISSUE THREAD

**Issue by ivellioscolin** [GPUOpen-LibrariesAndSDKs/AMF#78]
Unlike AVC, seems no HEVC property to config B-Pattern, like AMF_VIDEO_ENCODER_B_PIC_PATTERN, AMF_VIDEO_ENCODER_QP_B, etc. AMF_VIDEO_ENCODER_HEVC_FORCE_PICTURE_TYPE can only set I or P.
Any comment?

**Comment by MikhailAMD** [comment]
Currently B-Frames for HEVC encoder are unsupported.

**Comment by ivellioscolin** [comment]
Got it. Any rough schedule when B-Frames will be supported in future release?

**Comment by MikhailAMD** [comment]
I cannot comment on these types of questions :(

**Comment by ivellioscolin** [comment]
As a former AMD employee, it's fully understandable, personally. :)
