### ISSUE TITLE
H265: Filler Data requires Peak Bitrate to be set for CBR

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#80]
With Constant Bitrate set for Rate Control Method, Filler Data still requires Peak Bitrate to be set when using the HEVC encoder. This is somewhat of a regression compared to the AVC encoder, but nothing hard to fix.

Would be nice to see this being consistent in its behaviour across all codecs.

### Instead of:
1. Set Target Bitrate
2. Set Filler Data to Enabled

### You do:
1. Set Target Bitrate
2. Set Peak Bitrate to Target Bitrate
3. Set Filler Data to Enabled

**Comment by Xaymar** [comment]
This also applies to #73.

**Comment by MikhailAMD** [comment]
Is this still an issue?

**Comment by Xaymar** [comment]
To my knowledge yes. This has never been addressed and testers reported that a build with the workaround applied produces outright broken files.

**Comment by MikhailAMD** [comment]
Reproduced and ticket logged. Current way-around as Xaymar mentioned is to set Peak bitrate. After the fix Peak value will be ignored.

**Comment by Xaymar** [comment]
What is the status on this?

**Comment by Xaymar** [comment]
What is the status on this issue? @MikhailAMD

**Comment by MikhailAMD** [comment]
This one is fixed in driver software version 17.40

**Comment by Xaymar** [comment]
Can no longer reproduce this on the RX 480s. Will re-open if it reappears.
