### ISSUE TITLE
h264 - GOP & IDR

### ISSUE THREAD

**Issue by Benman2785** [GPUOpen-LibrariesAndSDKs/AMF#81]
Hi,

Xaymar told me u uses GOP = FPS and IDR = 2x FPS for h264 to simplify it -> but for 90% of scenes that doesnt produce a decent quality -> these values are usually used for slow-movement scenes (like Hearthstone) but arent good for Shooters

can you once try: GOP = 1/2 FPS (maybe also = IDR) // IDR of 1/5 -1/2 FPS is also quiet improveing quality - maybe by cost of "worser" compression, but the reference time of 2x fps of now is pretty useless for nearly all games - so the impact on compression wouldnt be that much, because only a range of 10-20 frames refer to each other

---
when i have slept enough i will write more about it ;)

**Comment by Xaymar** [comment]
> Xaymar told me u uses GOP = FPS

To clear this up further, GOP is either FPS or at the IDR Period, depending on which is smaller. ffprobe can be used to figure out which.

> IDR = 2x FPS for h264

I did not say this. I said that the plugin sets it to Keyframe Interval * Framerate rounded to the nearest integer, so your example of "2x FPS" is only when you set Keyframe Interval to 2.

Also you have to understand that GOP is only really used to determine the decoding picture group (and in AMDs encoder to determine the average bitrate). Changing the GOP will not get you overall better quality, as the quality problem with AMDs encoder is in varying places (one ever references one frame for data, no macroblock dropping, ...).

**Comment by Benman2785** [comment]
well GOP alone is more important when considering quality of compression - but when set properly it can help not make the image worse -> and the current way of handling gop makes it worse

720p3500kbps; http://benmanshafen.de/pics/OBS/Xaymar/Xaymar-1.9.9.11-settings.jpg
![xaymar-1 9 9 11-settings](https://cloud.githubusercontent.com/assets/21282980/24982660/d9a1ce8e-1fe2-11e7-9236-2f435663b13c.jpg)
TESTVIDEO: http://benmanshafen.de/pics/OBS/Xaymar/30fps_idr-10_org.flv <- "save as"
shows that we need the ability to set fixed i-frames -> this will improve quality for streaming

but then we still need a better fitting GOP (like 1/2 FPS) - so we can have a better i,p,b frame mix -> we have to be able to set it specific for most scenes: for fast scenes with many changes per frame (most Shooters) and slow scenes with less changes (so it has more reference)
better frametype mix for good compression with best image-quality -> like nearly all shooters need: ipbbbpbbbipbbbb or ipbbbbipbbbbipb - but now it has something like: ipbbbbpbbbbpbbbpbbbbpbbbbpbbbb -> so for low bitrates there is no other way to look shitty -> but the compression is better -> yet my two GOP examples (those with 15 Frames) would still look decent while have a streamable compression

**Comment by MikhailAMD** [comment]
Form AMF H.64 Encoder API perspective we provide three independent parameters relevant to this discussion:
1.	AMF_VIDEO_ENCODER_FRAMERATE – used for rate control only and does not interfere with I / IDR frames.
2.	AMF_VIDEO_ENCODER_IDR_PERIOD – period at which IDR frame appears – please note that AMF does not provide a separate GOP period – IDR period is identical to GOP period.
3.	AMF_VIDEO_ENCODER_FORCE_PICTURE_TYPE – can be set onto input frame and forces the next frame to be of the provided type – can be I or IDR - one time command.
All these parameters do not correlate and should provide enough flexibility for the app.
Please note that if you make IDR too frequent  you will leave less bit budget for the rest of the frames.

**Comment by Benman2785** [comment]
for 2.

IDR = GOP is nice for local recording - but pretty much useless for streaming -> can u add changeable GOP size for a new release?

- as i said - we have to play around with minQP and maxQP to find the sweetspot for compression and imagequality for "lower bitrates for streaming" -> if check the video i provided u will see MAJOR improvement over to normal quality of given bitrate -> due to current AMF puts not enough i-frames and to many frames try to refer to each other after frame has changed -> result in blurry blocks instead of nice quality ;)

**Comment by MikhailAMD** [comment]
You should be able pretty much achieve this by setting IDR period bigger and force individual I-frames from the app making your own GOP period.

**Comment by Xaymar** [comment]
I've already made a feature enhancement ticket for the AMF encoder plugin: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/220 . This will be released with 2.1.0, which relies on 2.0.0. I hope that #66 will be working before 2.0.0 hits the public or I'll be flooded with "why doesn't this work?!" bug reports.

**Comment by MikhailAMD** [comment]
What is your timeframe?

**Comment by Xaymar** [comment]
For 2.0.0 the timeframe is 15.05.2017 (15th May 2017) or the next major OBS update, depending on which happens earlier. Since Microsoft is now rolling out the Windows 10 Creators Update, a major OBS update might be happening sooner than the date I planned to release on.

**Comment by MikhailAMD** [comment]
I see, Let's hope that #66 will be in time. I am pushing.

**Comment by Benman2785** [comment]
OBS needs to fix GameCapture -> so there will be an big update soon

**Comment by MikhailAMD** [comment]
Any update?

**Comment by MikhailAMD** [comment]
Implemented in OBS AMF encoder plugin v.2.1.x
