### ISSUE TITLE
AMFVideoConverter crop error ?

### ISSUE THREAD

**Issue by logitechlike** [GPUOpen-LibrariesAndSDKs/AMF#82]
Test Device Radeon RX470,  Driver Version 22.19.157.3.
Windows os type is 64bit System Windows 10 Build 10586.

My code do decode then converter

init:
	res = m_pDecoder->Init(m_FormatOut, m_widthIn, m_heightIn);
			m_amfCropX = pParams->display_area.left;
			m_amfCropY = pParams->display_area.top;
			m_amfCropWidth = pParams->display_area.right - pParams->display_area.left;
			m_amfCropHeight = pParams->display_area.bottom - pParams->display_area.top;
			AMFRect m_rectClient = { m_amfCropX, m_amfCropY, m_amfCropWidth, m_amfCropHeight };
			res = m_pConverter->SetProperty(AMF_VIDEO_CONVERTER_OUTPUT_RECT, m_rectClient);
		}
		res = m_pConverter->SetProperty(AMF_VIDEO_CONVERTER_OUTPUT_SIZE, AMFConstructSize(m_amfCropWidth, m_amfCropHeight));

run:
after  get data from decode by m_pDecoder->QueryOutput(&data);

set crop use 
amf::AMFSurfacePtr surfaceIn(data);
 surfaceIn->SetCrop( m_amfCropX, m_amfCropY, m_amfCropWidth, m_amfCropHeight);

before Submit into AMFVideoConverter

m_pConverter->SubmitInput(surfaceIn);

after converter i turn surface to yuv

work good with m_widthIn = 1920, m_heightIn = 1080
m_amfCropX = 960, m_amfCropY = 540, m_amfCropWidth = 960, m_amfCropHeight = 540;

work good with m_widthIn = 1920, m_heightIn = 1080
m_amfCropX = 32, m_amfCropY = 32, m_amfCropWidth = 1888, m_amfCropHeight = 1048;

and other params
so, is this a bug or i use api wrong ?
if not a bug is there a example to show how to crop ? Thanks

Original post : https://community.amd.com/thread/215229

**Comment by MikhailAMD** [comment]
With your code crop offsets (left, top) are used  as an offset in the output surface but this was not your intention. 
You don't have to set crop to OUTPUT_RECT. When you set crop on input surface (surfaceIn->SetCrop()) the converter will use the provided rectangle as a source. and will write to full size OUTPUT_SIZE.

**Comment by logitechlike** [comment]
@MikhailAMD

**Comment by logitechlike** [comment]
@MikhailAMD 
Thanks.  
so , I removed set AMF_VIDEO_CONVERTER_OUTPUT_RECT, 
and continue surfaceIn->SetCrop( m_amfCropX, m_amfCropY, m_amfCropWidth, m_amfCropHeight);
in each surface input into converter,
m_pConverter->QueryOutput()  surface have crop info , 
I use the crop info copy surface to YUV , work OK now .

But There is a new question,  
How should I set info with work flow like TranscodeHW demo.
decode -> converter (crop) -> encode 

before the encode SubmitInput I can see the surface have crop info
but the encode out frame not right.

should I use CopySurfaceRegion to copy the convertered (croped) surface to dstX = 0,  dstY =0
Will this slow the whole process ? 

Why Converter not return surface moved to   (left, top)->(0, 0)  ?
It seems intel vpp, and cuda do so. Or, there is something I do wrong?  Thanks.

**Comment by MikhailAMD** [comment]
CopySurfaceRegion will be unnecessary. The idea is that Converter does the crop and passes the ready surface to the encoder. There is possibility that you passes wrong frame size to the encoder during initialization. Here is the pseudo-code:
Decoder: output->Size1 (may have  crop if frame size is not aligned to 16 )
App: applies crop-> Size2 ( Size1 + Crop)
Converter: input ->  Size2 (Size1 + Crop)
Converter: crop + scale if needed
Converter: output->Size3 (no crop, if no scale Size3 = Size2)
Encoder: input->Size3 (no crop) (needs to initialize the encoder with Size3 in mind)

**Comment by logitechlike** [comment]
@MikhailAMD 

Test 1 work flow: ( 1920 x 1080 -> 1920 x 800,  crop top / bottom 140)
1.  Decoder: Init(AMF_SURFACE_NV12, 1920, 1080);
2.  Converter: 
SetProperty(AMF_VIDEO_CONVERTER_OUTPUT_SIZE, AMFConstructSize(1920, 800));
Init(amf::AMF_SURFACE_NV12, 1920, 800);
3. Decode out surface SetCrop(0, 140, 1920, 800);
then Converter SubmitInput() this surface only with set crop info;
4. Converter: output surface , 
GetPlane(amf::AMF_PLANE_Y)->GetOffsetX();     0
GetPlane(amf::AMF_PLANE_Y)->GetOffsetY();     140   ???(why not 0)
GetPlane(amf::AMF_PLANE_Y)->GetWidth();       1920
GetPlane(amf::AMF_PLANE_Y)->GetHeight();      800

Test 2 work flow: ( 1920 x 1080 -> 1920 x 800(crop top / bottom 140) -> 960 x 400(resize))
1.  Decoder: Init(AMF_SURFACE_NV12, 1920, 1080);
2.  Converter: 
SetProperty(AMF_VIDEO_CONVERTER_OUTPUT_SIZE, AMFConstructSize(960, 400));
Init(amf::AMF_SURFACE_NV12, 1920, 800);
3. Decode out surface SetCrop(0, 140, 1920, 800);
then Converter SubmitInput() this surface only with set crop info;
4. Converter: output surface , 
GetPlane(amf::AMF_PLANE_Y)->GetOffsetX();     0
GetPlane(amf::AMF_PLANE_Y)->GetOffsetY();     0   ???(why)
GetPlane(amf::AMF_PLANE_Y)->GetWidth();       960
GetPlane(amf::AMF_PLANE_Y)->GetHeight();      400

I think Test 1 (only  crop),  Converter out is wrong,

**Comment by logitechlike** [comment]
Continue test, like TranscodeHW TranscodePipeline.

Decoder -> Converter -> Encoder

Test 3 work flow: ( 1920 x 1080 -> 1920 x 800, crop top / bottom 140)

1. Decoder: Init(AMF_SURFACE_NV12, 1920, 1080);
2. Converter:
    SetProperty(AMF_VIDEO_CONVERTER_OUTPUT_SIZE, AMFConstructSize(1920, 800));
    Init(amf::AMF_SURFACE_NV12, 1920, 800);
3. Encoder: Init(amf::AMF_SURFACE_NV12, 1920, 800);
4. Decode out surface SetCrop(0, 140, 1920, 800);
      then Converter SubmitInput() this surface only with set crop info;
5.  Converter: output surface ,  SubmitInput Encoder without change 
GetPlane(amf::AMF_PLANE_Y)->GetOffsetX(); 0
GetPlane(amf::AMF_PLANE_Y)->GetOffsetY(); 140 (??? why not 0)
GetPlane(amf::AMF_PLANE_Y)->GetWidth(); 1920
GetPlane(amf::AMF_PLANE_Y)->GetHeight(); 800
6. Encoder: output  
    pic crop postion wrong

Test 4 work flow: ( 1920 x 1080 -> 1920 x 800(crop top / bottom 140) -> 960 x 400(resize))

1. Decoder: Init(AMF_SURFACE_NV12, 1920, 1080);
2. Converter:
     SetProperty(AMF_VIDEO_CONVERTER_OUTPUT_SIZE, AMFConstructSize(960, 400));
    Init(amf::AMF_SURFACE_NV12, 1920, 800);
3. Encoder: Init(amf::AMF_SURFACE_NV12, 960, 400);
4.  Decode out surface SetCrop(0, 140, 1920, 800);
then Converter SubmitInput() this surface only with set crop info;
5. Converter: output surface , SubmitInput Encoder without change 
GetPlane(amf::AMF_PLANE_Y)->GetOffsetX(); 0
GetPlane(amf::AMF_PLANE_Y)->GetOffsetY(); 0 
GetPlane(amf::AMF_PLANE_Y)->GetWidth(); 960
GetPlane(amf::AMF_PLANE_Y)->GetHeight(); 400
6. Encoder: output  pic good

**Comment by MikhailAMD** [comment]
Got it. When there no color conversion and no scale the converter passes input surface through. In the end of the day it is a converter. I will consider to add such crop functionality. Meanwhile you can allocate surface of needed size using amf and call indeed CopySurfaceRegion

**Comment by MikhailAMD** [comment]
Can we close this issue?

**Comment by logitechlike** [comment]
@MikhailAMD 
Close. We can crop.
