### ISSUE TITLE
pls make VCE load readable

### ISSUE THREAD

**Issue by Benman2785** [GPUOpen-LibrariesAndSDKs/AMF#83]
hi, please make the load of VCE readable for MSI Afterburner or HWMonitor
this could help me to find the correct QP for each scenario - and it shows if there is still headroom left

ps for NVenc it is possible

**Comment by Xaymar** [comment]
It's already readable as encoding latency, the more load the higher the latency of the encode.

**Comment by chummy02** [comment]
I think he want to take something for end user check the load like this one, Video Engine Load: http://i.imgur.com/Ai2M3RL.png

**Comment by MikhailAMD** [comment]
I understand the need but this is not the SDK issue. In general, AMD GPUs as all others produce proper ETL logging that can be used in real-time tools. Try GPUVIEW  to capture ETLs and review them in GPUVIEW.EXE or in MSFT's "Media eXperience Analyzer" with the same ETL files. You will see VCE activity separated from the rest, though with these tools it is not real-time. So unless something is missing deep in the driver this is an application issue. I will send a note to the appropriate guy, but please open an issue on AMD website to raise awareness.
