### ISSUE TITLE
H265: No way to tell apart I-Frames and IDR-Frames?

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#86]
I don't think is intended, as programs need to know when they can safely cut off an encoder without possibly corrupting the entire file. As you are able to set the picture type for individual frames to Skip, IDR, I or P there should be a similar list for Output data type. So this: 

```
enum AMF_VIDEO_ENCODER_HEVC_OUTPUT_DATA_TYPE_ENUM
{
    AMF_VIDEO_ENCODER_HEVC_OUTPUT_DATA_TYPE_I,
    AMF_VIDEO_ENCODER_HEVC_OUTPUT_DATA_TYPE_P
};
```

should instead be:
```
enum AMF_VIDEO_ENCODER_HEVC_OUTPUT_DATA_TYPE_ENUM
{
    AMF_VIDEO_ENCODER_HEVC_OUTPUT_DATA_TYPE_IDR,
    AMF_VIDEO_ENCODER_HEVC_OUTPUT_DATA_TYPE_I,
    AMF_VIDEO_ENCODER_HEVC_OUTPUT_DATA_TYPE_P
};
```

An alternative would be to add a property to the output frame that can be read from to know if the frame is a keyframe.

**Comment by MikhailAMD** [comment]
I already submitted a ticket about this issue :)

**Comment by MikhailAMD** [comment]
Should be fixed in 17.7.2 driver.

**Comment by Xaymar** [comment]
Confirming fixed.

**Comment by Xaymar** [comment]
Seeking in HEVC files works now, people will very likely enjoy this change.
