### ISSUE TITLE
Quality Preset 'Quality' is misconfigured

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#87]
After thorough testing with many different source videos, I've come to the conclusion that the Quality Presets in AMF are mislabeled. See the following table for why I've come to this conclusion:

[![image](https://cloud.githubusercontent.com/assets/437395/25778187/32861a9c-32f7-11e7-8862-dca59abac238.png)](http://cdn.xaymar.com/private/2017/05/07/07/2017-05-07_07-31-29.png)

* "Speed" provides a middle-ground in terms of quality while also being the fastest option.
* "Balanced" provides the best quality while being the middle-ground in terms of speed/throughput.
* "Quality" provides the worst quality combined with the worst speed/throughput.

Is there a reason for this?

**Comment by MikhailAMD** [comment]
The quality presets have to be tested with Peak VBR.

**Comment by Xaymar** [comment]
I will re-run the test with Peak VBR then, however I don't think that will actually do anything. CQP has similar issues with Quality Presets and individual QP sets completely mess everything up (QP 23 is better than QP 5 for example). Hopefully it will be done by tomorrow morning.

**Comment by Xaymar** [comment]
Further tests with @MikhailAMD have resulted in the following:
- All resolutions up to 1280x720 have Quality as the best one.
- Resolutions above that have Balanced as the best one.
- At 3840x2160 the Speed preset sits dangerously close to the Balanced preset which leads me to believe that all presets are not properly configured.

### 3840x2160 30fps
![image](https://cloud.githubusercontent.com/assets/437395/25863135/ecc71880-34ea-11e7-803c-6930e13e0231.png)

### 1920x1080 30fps
![image](https://cloud.githubusercontent.com/assets/437395/25863141/efb1d1ca-34ea-11e7-91b8-cbdefa87e375.png)

### 1280x720 30fps
![image](https://cloud.githubusercontent.com/assets/437395/25863146/f25b2fc0-34ea-11e7-9778-05a5e1b68abe.png)

### 853x480 30fps
![image](https://cloud.githubusercontent.com/assets/437395/25863149/f53fece4-34ea-11e7-8567-271330b078b0.png)

**Comment by Oldgam3r** [comment]
Fail , AMD - brotherhood of waiting :) . Always waiting for something , wait for support , wait for patches , wait for bios , wait for ... with time will be better :) . Honestly after new Volta from Nvidia i sell my RX 480 and bye bye AMD. Was hope to change my i7 for ryzen but intel soon will be put on mainstream 6 core and bye bye ryzen. Tell u Xaymar , throw away this amd crap and focus on other better things. U hard and good work is pointless . with amd always will be something wrong.

**Comment by MikhailAMD** [comment]
We played with this clip (720p), the latest build of FFmpeg and the AMF TranscodeHW sample from 1.4.2. We found that SSIM metric is not consistent with AMF profile options. But when we tried PSNR metric in the same setup we got pretty consistent and expected results. We spot-checked CBR and Peak VBR. Codec team confirmed that they use PSNR as the metric. For details see attached numbers and a BAT file that run the tests.
Please note that if bitrate is too low for the selected resolution the results may be not consistent and may depend on content.

[result.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/990812/result.txt)
[transcode-psnr.bat.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/990815/transcode-psnr.bat.txt)

**Comment by Xaymar** [comment]
You were playing 720p the exact resolution **where it actually worked**. As you can see above, it's when you go above 720p when it breaks. Please redo the test with the actually broken resolutions.

**Comment by MikhailAMD** [comment]
try PSNR instead of SSIM

**Comment by Xaymar** [comment]
Top to bottom: Quality, Balanced, Speed

```
[Parsed_psnr_1 @ 0000000002cd53a0] PSNR y:29.186164 u:40.614823 v:42.224261 average:30.816967 min:27.152989 max:inf
[Parsed_psnr_1 @ 000000000072c260] PSNR y:29.206098 u:40.645968 v:42.260132 average:30.837288 min:27.216103 max:inf
[Parsed_psnr_1 @ 00000000026aade0] PSNR y:29.205861 u:40.647620 v:42.263357 average:30.837126 min:27.218447 max:inf
```

I'm sorry, but I'm getting the exact same result I was getting with SSIM here. Balanced is better than Speed (on average) and Speed is better than Quality (with all measurements).

**Comment by MikhailAMD** [comment]
Y PSNR is 29 - very low. Something is wrong. Check my table.

**Comment by Xaymar** [comment]
Reran the tests at 1080p instead of 2160p:

```
[Parsed_psnr_1 @ 000000000333d220] PSNR y:33.490118 u:43.538568 v:45.158017 average:35.073395 min:29.684413 max:inf
[Parsed_psnr_1 @ 0000000002fcb820] PSNR y:33.678208 u:43.709331 v:45.326830 average:35.260758 min:29.770945 max:91.044995
[Parsed_psnr_1 @ 000000000270c6a0] PSNR y:33.640766 u:43.701827 v:45.312446 average:35.224404 min:29.767551 max:90.937090
```

If i go any lower we reach the point (720p) where Quality works again.

**Comment by Xaymar** [comment]
Since this is only true when limiting the bitrate too much, I think I can close this.
