### ISSUE TITLE
H265: Unexpected crash after approx 1h25m45s recording

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#88]
Crash Log: [Crash 2017-05-13 16-48-51.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/998731/Crash.2017-05-13.16-48-51.txt)

OBS Log file: [2017-05-13 15-20-50.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/998729/2017-05-13.15-20-50.zip) (Begins at line 1820)

I was playing ARMA 3 during this, which seems to have a 100% reproduction rate for this bug.

**Comment by MikhailAMD** [comment]
will investigate. If possible next time could you please produce crash dump?

**Comment by Xaymar** [comment]
Have not been able to reproduce so far. I did get into an odd situation with HEVC encoded content that had absolutely no I or IDR frames even though IDR Period was set to 2 and GOP Size was set to 75. Unsure if these are caused by the same thing, hoping to have better luck on the Monday ARMA 3 run.
