### ISSUE TITLE
AVC: SubmitInput to QueryOutput time drastically increases after 12 frames

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#90]
For an unknown reason encoding becomes slower after submitting exactly 12 frames. This is clearly visible when looking at the actual timing information and the extra time can be anywhere from 4 ms to 175 ms, resulting in output that stutters and the dreaded OBS 'Encoding overloaded!' message. This is probably a regression from an earlier driver and was only discovered through the much more strict main encoding loop the plugin now has.

Is there any reason for this behavior? And how could i solve it without adding extra encoding latency?

Log File: [2017-05-14 13-37-50.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/999295/2017-05-14.13-37-50.txt)

**Comment by MikhailAMD** [comment]
1. Is it a regression?
2. The description looks like encoder tasks are piling up ( submitting more before previous are done). This will increase latency. The current code in the plug-in measures not encoding duration but encoding latency:
pf_main = (pf_query - pf_submit); - this is latency if encoding HW queue is not empty.
3. Please check if you use "speed" profile.
4. Record very short ETL using GPUVIEW logging - the starting 5 seconds and share with me.

**Comment by Xaymar** [comment]
> Is it a regression?

It definitely looks like one. 

> The description looks like encoder tasks are piling up ( submitting more before previous are done).

That is actually impossible as the plugin only submits up to B-Frame count frames before considering waiting for output. This means that with 0 B-Frames it will only ever work on one frame at a time.

> The current code in the plug-in measures not encoding duration but encoding latency:

It measures the time from one submit to the actual output, so yes, latency and in case of single-frame modes also duration.

> Record very short ETL using GPUVIEW logging - the starting 5 seconds and share with me.

This 7zip file contains both 1.4.3.11 and 2.1.2 measurements on Speed preset at CBR 3500kbit: http://cdn.xaymar.com/private/2017/05/14/22/Issue-90.7z

**Comment by Xaymar** [comment]
Summary of the Skype Discussion: Copy to GPU, Convert, Submit and Query should ideally be done in parallel.

Plugin 2.1.3 and later now include a working patch for this behaviour and no longer show Encoding overloaded! in completely fine situations.
