### ISSUE TITLE
32-Bit AMF logging callback crash

### ISSUE THREAD

**Issue by Xaymar** [GPUOpen-LibrariesAndSDKs/AMF#91]
As discussed over Skype, there is currently a crash due to improper calling convention in the latest driver (17.5.1). The crash happens due to the message parameter pointing to invalid memory.

**Comment by MikhailAMD** [comment]
Yes, will be fixed.

**Comment by Xaymar** [comment]
Is this fixed in 17.6.1?

**Comment by MikhailAMD** [comment]
No, I will let you know.

**Comment by MikhailAMD** [comment]
Should be fixed in 17.7.2 driver.

**Comment by Xaymar** [comment]
Fixed in 17.7.2
