### ISSUE TITLE
Encoding Performance of RX580?

### ISSUE THREAD

**Issue by aaronblake** [GPUOpen-LibrariesAndSDKs/AMF#93]
I tried to find the the encoding performance of RX580 with AMF. But it is a fairly new card and I find nothing about it. Can you share the encoding performance of RX580 with 1920x1080 and 3840x2160 resolution? Also, how is the encoding performance of Radeon Pro WX7100 comparing to encoding performance of RX580?

**Comment by MikhailAMD** [comment]
The encoder performance on all these cards should be very similar. We don't have official numbers because there are a lot of parameters involved as well as depend on application's rate of encode job submission power management may affect timing. If you want to measure the speed you can use SimpleEncoder sample - it gives pretty accurate values. You can change parameters to your needs.

**Comment by aaronblake** [comment]
Will video content affect encoding performance? For example, comparing the result of encoding a video that changes each pixel color every frame and the other video that remains same color every frame.

**Comment by MikhailAMD** [comment]
Very little. Most operations are fixed function so content doesn't affect performance.

**Comment by MikhailAMD** [comment]
Were are we here?

**Comment by Roph** [comment]
The 580 is a re-released 480, its VCE performance is identical.

You can find benchmarks of various cards and VCE versions on this github wiki: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki

Just click the VCE versions on the right. The 580's VCE is 4th generation, which that wiki for some reason refers to as 3.4.

**Comment by Xaymar** [comment]
> Just click the VCE versions on the right. The 580's VCE is 4th generation, which that wiki for some reason refers to as 3.4.

That's because AMD refers to it as VCE 3.4. VCE 4.0 is apparently available in Vega and later cards. See wikipedia for this: https://en.wikipedia.org/wiki/Video_Coding_Engine
