### ISSUE TITLE
AMF sample simpleEncoder fails with DX11 memory, when i tried to get BGRA to h264 conversion.

### ISSUE THREAD

**Issue by MohammadTaha39** [GPUOpen-LibrariesAndSDKs/AMF#94]
When i tried to run AMF sample **simpleEncoder** with **AMF_MEMORY_DX11** then  **AMFCreateComponent** function returns error  **AMF_ENCODER_NOT_PRESENT**.

Does AMD's AMF sample simpleEncoder supports BGRA to h264 conversion? If yes then how should i get it work. Am i missing something. 

If anyone knows, kindly help me in doing this.

**Comment by MikhailAMD** [comment]
Which OS are you running?
Did you replace call InitDX9 with InitDX11?
Did you pass BGRA to component->In it?
Yes you can encode BGRA surfaces(textures) using built-in color converter or convert it separately using AMF color converter component. See SimpleConverter sample.
I will update SimpleEncoder sample to cover DX11 case.

**Comment by MohammadTaha39** [comment]
I am using Windows 10.
I didn't replace InitDX9 with InitDX11, i am running original sample.
I got error at AMFCreateComponent after context->InitDX11(NULL) called.

**Comment by MikhailAMD** [comment]
Which GPU do you have?
Does original DX9 code work?
By any chance do you have a second non AMD GPU enabled? (Embedded Intel or Nvidia board?)

**Comment by MikhailAMD** [comment]
And which driver so you run?

**Comment by MohammadTaha39** [comment]
GPU i am using is AMD Radeon(TM) R4 Graphics.
Yes original DX9 code works fine.
No i don't have any second GPU. 
Driver version is 13.302.1904.0

**Comment by MohammadTaha39** [comment]
Can you tell me where this SimpleConverter sample can be found. As this sample is not in my amf samples.
If there any link where SimpleConverter sample can be found. If yes, then kindly share that link with me.

**Comment by MikhailAMD** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/tree/master/amf/public/samples/CPPSamples/SimpleConverter

Where did you get the driver version? It is either extremely old or wrong. You should check Radeon Settings->System->Software->Driver Packaging Version.
In any case AMF requires certain driver version or newer:
https://github.com/GPUOpen-LibrariesAndSDKs/AMF
Regarding GPU:
Please send me: Radeon Settings->System->Hardware->Device ID.

**Comment by MohammadTaha39** [comment]
![amddisplayinfo](https://user-images.githubusercontent.com/16932811/27000460-4affc19c-4dd0-11e7-8cbe-db8bd84b5284.PNG)

Kindly see the pic above pasted to know the details of information of my system.

**Comment by Xaymar** [comment]
The driver you have seems to be part of a All-In-One install from the system manufacturer, those usually never get updated. Install the official ones from AMD: http://www.amd.com/Pages/PageNotFoundError.aspx?requestUrl=http://www.amd.com/en-us/download/

**Comment by MikhailAMD** [comment]
The driver is very old and is not supported by AMF. Please use the latest one from AMD website.

**Comment by MohammadTaha39** [comment]
I have installed **AMD Auto Detect** and Install drivers from [](http://support.amd.com/en-us/download).
But it always says partially installed drivers, I checked error log, it only gets **Failed at AMD Display Driver: Final Status: Fail.**

Then i installed AMD driver from Dell official site as my laptop is Dell Inspiron 15 3000 series , it also detect automatically my system information and take me to this link : [](http://www.dell.com/support/home/us/en/19/Drivers/DriversDetails?driverId=9YNPW&fileId=3490809880&osCode=WB64A&productCode=inspiron-15-3541-laptop&languageCode=en&categoryId=VI)
From above link i have downloaded Video_Driver_AMD and installed it. It installed successfully but when i checked driver version no updation is there.

So i tried AMD Auto Detect and Install drivers from [](http://support.amd.com/en-us/download) again. And this time it says: Components are already installed. As you can see in the pic below:
![capture_amd](https://user-images.githubusercontent.com/16932811/27033730-47b172c8-4f98-11e7-90bb-a78c6df90f49.PNG)

Is there any other way to update driver or i am doing something wrong, or on my Laptop it cannot update anymore then this version.

**Comment by Xaymar** [comment]
Here's 17.6.1, wipe the old AMD driver before you install the new ones (with DDU): http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-17.6.1-Release-Notes.aspx

**Comment by MohammadTaha39** [comment]
Hi Xaymar 
In Link provided by you **Radeon Mobility Product Family Compatibility** ​ is not  showing for AMD Radeon(TM) R4 Graphics

**Comment by SuslikV** [comment]
http://support.amd.com/en-us/download/apu?os=Windows+10+-+32
http://support.amd.com/en-us/download/apu?os=Windows+10+-+64
If nothing of this works - then forget about this encoder for this pc.

**Comment by MikhailAMD** [comment]
Please go to this page: http://support.amd.com/en-us/download and select:
 - APU
- Mobile API
- A-Series APU w/Radeon R4 Graphics
- Windows 10 64
It should bring you here: http://support.amd.com/en-us/download/apu?os=Windows%2010%20-%2064  
If you select "Supported Products" tab it should bring you here: http://support.amd.com/en-us/download/apu?os=Windows%2010%20-%2064
There is mentioning of R4 in APU section.
To try clean install you may want to try uninstall all AMD drivers using this utility: http://support.amd.com/en-us/kb-articles/Pages/AMD-Clean-Uninstall-Utility.aspx

**Comment by MikhailAMD** [comment]
Can we close this issue?
