### ISSUE TITLE
How to know at run time that AMF sample supports Hardware acceleration.

### ISSUE THREAD

**Issue by MohammadTaha39** [GPUOpen-LibrariesAndSDKs/AMF#95]
Can anyone know how to know that AMF sample either encode or decode supports Hardware acceleration on particular system. Is there any function by which i can get weather it supports Hardware acceleration or not, If yes then how can i get weather PC supports hardware or not.

**Comment by MikhailAMD** [comment]
Check CapabilityManager sample in AMF. There is a set of interfaces designed for precisely this.

**Comment by MohammadTaha39** [comment]
Thanks, i got it.
