### ISSUE TITLE
Vega GPU encode/decode features info..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/AMF#96]
Hi,
today Vega Frontiers Edition is public so can AMD speak about impromevents to video encode/decode vs Polaris GPUs?
I see:
"Multi-stream hardware H.265 HD encode/decode for power-efficient and quick video encoding and playback"
All below I ask for HW acceleration of course:
supports 4k@ 60fps HEVC video encode? also 4k60 H264 encode? supports 10bit HEVC encoding?
what about VP9 decode? is now native.. not hybrid? supports VP9 profile 2 (HDR) for YouTube HDR support?

**Comment by Roph** [comment]
Was going to make a similar post, hoping @MikhailAMD will post (brag? :D) about vega's VCE details. 

Has B-frame support made a return? Any overall quality improvements for H264/5 over polaris VCE?

**Comment by M4RK22** [comment]
http://pro.radeon.com/en-us/product/radeon-vega-frontier-edition/ seems to be supporting h265 only 4k60

**Comment by MikhailAMD** [comment]
At this point this link is the only public information available. Details will follow. Stay tuned.

**Comment by boxerab** [comment]
What does this mean ?

HEVC acceleration is subject to inclusion/installation of compatible HEVC players. GD-81

**Comment by MikhailAMD** [comment]
Not sure I understand the question.

**Comment by Xaymar** [comment]
> What does this mean ?
> 
> > HEVC acceleration is subject to inclusion/installation of compatible HEVC players. GD-81

This means that players need to use either Media Foundation or have AMF support to use HW accelerated playback.

**Comment by boxerab** [comment]
Thanks. OBS seems to be at the cutting edge of support for AMD encode/decode. Do you happen to know how OBS compares to gstreamer support for AMD encode/decode ? I use gstreamer a lot, and have been developing plugins there.

**Comment by boxerab** [comment]
@MikhailAMD this line is footnote mentioned in link provided by @M4RK22

**Comment by Xaymar** [comment]
> Thanks. OBS seems to be at the cutting edge of support for AMD encode/decode. Do you happen to know how OBS compares to gstreamer support for AMD encode/decode ? I use gstreamer a lot, and have been developing plugins there.

OBS and gstreamer have different focus. OBS is a streaming/recording tool and gstreamer seems to be a multimedia framework.

**Comment by boxerab** [comment]
OK, thanks.

**Comment by Xaymar** [comment]
From what little information has actually reached me from a Vega FE owner, the card supposedly have a new multimedia IP. If this is VCE 4.0 or not remains to be seen when the consumer oriented cards appear.

**Comment by Roph** [comment]
RX Vega now unveiled, care to spill the beans @MikhailAMD? :)

**Comment by oscarbg** [comment]
8K video decode (h264&h265)? vp9 HW decode? vp9 10 bit for YouTube HDR? and Playready 3 support for Netflix 4k?

**Comment by oscarbg** [comment]
someone has dxvachecker of even a Vega FE with 17.20 and 17.30 drivers?

**Comment by MikhailAMD** [comment]
AMD published a white paper which has details for multimedia HW blocks:
http://radeon.com/_downloads/vega-whitepaper-11.6.17.pdf

**Comment by Roph** [comment]
So a nice speed bump. Are there any quality improvements or new features? Have B-frames made a return? 10-bit encoding?

**Comment by MikhailAMD** [comment]
No B-frames and 10-bit encoding in this HW.

**Comment by NikosDi** [comment]
So, once again, no VP9 fixed function decoding.

VEGA uses hybrid decoding like Polaris according to that PDF.

"Vega can also decode the VP9 format at resolutions up to 3840x2160 using a hybrid approach where the video and shader engines collaborate to offload work from the CPU."

**Comment by Roph** [comment]
I'm assuming he can't say, but I hope they're busy on AV1 support for Navi. AMD is an AOMedia member after all :)

**Comment by NikosDi** [comment]
I don't think he needs to say anything special or top secret.

The PDF posted says everything, I think.

**Comment by Cru-N-cher** [comment]
[quote]So, once again, no VP9 fixed function decoding.

VEGA uses hybrid decoding like Polaris according to that PDF.

"Vega can also decode the VP9 format at resolutions up to 3840x2160 using a hybrid approach where the video and shader engines collaborate to offload work from the CPU."[/quote]

Nvidia does necessarily nothing else it scales with the GPU line the GP107 and GP102 are the most advanced and as we know the GP102 the most expensive.

For AVG joe and AVG Gamer only practical commercially sound use case scenarios make sense.

and if you weight overall architectural balance VEGA at least sounds very balanced :)

But yeah they are much to few qualified reviewers to really tap into how compute plays a role supporting video decoding encoding on a low level one thing for sure AMD isn't beating Intel yet neither does Nvidia ;)

**Comment by MikhailAMD** [comment]
Closed as stale issue
