### ISSUE TITLE
Encoding in 60fps stutters on r9 290 

### ISSUE THREAD

**Issue by amfthrowaway** [GPUOpen-LibrariesAndSDKs/AMF#97]
Hey,

So I tried the AMF encoding with the help of simple encoding sample code. I noticed that when I'm encoding in 60fps with both quality and speed preset, there's a noticeable stutter around every 1 second in games that use the same gpu that is doing the encoding. Otherwise the fps is pretty stable, but there's that stutter that happens.

How come the gpu starts to lag even if it's the video coding engine that is doing the encoding? I was under the impression that the dedicated encoding chip does all the work, so that the other rendering work won't be affected by the encoding process. So is this a bug in the amf library which causes this noticeable stutter, or is the chip designed in a way that it affects the gpu's workload aswell?

I also tried the intel's quick sync feature(which is also a dedicated chip for encoding) with same settings, and in my testings it only affected the performance a very little bit. This seems like a very promising technology for example for game streaming, but as of now a x264 software renderer or intel's quicksync is a far more better option for fast encoding. It's a shame really, because using the encoding chip that's located in the cpu requires a memory transfer from gpu to cpu, which adds its own overhead.

**Comment by Xaymar** [comment]
What application did you use that interfaces with AMF? AMD ReLive, Open Broadcaster Software Studio or a different software?

**Comment by amfthrowaway** [comment]
I looked at the SimpleEncoding sample and pretty much copied that code to a test project. I modified the code a bit so instead of feeding frames to the encoder any time it's possible, the frames are submitted every 16ms for smooth 60fps encoding. As far as I know, the code currently doesn't transfer any data between main memory and video memory, as the rendered frames are already in video memory.

**Comment by Xaymar** [comment]
Do you get the same issue if you just use the SimpleEncoder example? I have not observed any AMF related stuttering, except in two cases:

1. The card does not get enough power from the PSU, resulting in system halts.
2. You have Intel drivers installed that replace or override the AMD OpenCL, DirectX, OpenGL and Vulkan runtime. This is a rather common one I had to debug for the AMF integration into OBS Studio.

If neither of these apply, I am unsure of what is causing it for you. Mikhail will likely know more then.

**Comment by amfthrowaway** [comment]
Yes, I had the same problem initially when I just copied the code. I just tried to make it use a bit less resources to see if that would have helped the issue.

Yeah, neither of those points apply. I'm sure the PSU is powerful enough and the right drivers are loaded for games and the amf.

If the encoding chip should work entirely independently without a major interference of the gpu, I can't think of any other reason than a bug in the driver or the amf library.

**Comment by amfthrowaway** [comment]
Alright, so a few observations I made:

When I disabled one monitor of my dual full hd 60 hz monitor setup, the stuttering almost disappeared. The other monitor didn't actively display anything moving(just an empty desktop) when I tried testing the encoding with both monitors active. The primary monitor was the only one where the game was displayed. Also, when I fed frames to the encoder in full speed(not in 16ms periods), the stuttering became more visible in both dual and single monitor setup.

The gpu is hooked into a pci 2.0 bus I think, so is it possible that the speed of that bus isn't enough for simultaneously encoding and displaying 2 full hd 60 fps video data? I don't think that would explain why it stutters every 1 second, though. I also did try to dispose the encoded data as soon as it became available, so that it wouldn't traverse from the video memory to main memory, but that didn't have any effect to the stuttering effect.

**Comment by MikhailAMD** [comment]
- What resolution do you encode?
- how GPU intensive is the game?
- SimpleEncoder sample is DX9. Where do you get frames and do you submit them as DX9?
- Who does color conversion and how?

**Comment by amfthrowaway** [comment]
- In full hd

- I tested with gta V and with an old game that uses pixel buffer objects to draw the scenery to video ram with the cpu. The old game that does manually the drawing plays at about 700 fps, and I think the stuttering is very similar both in gta V and on that old game. Now that I tested on gta V again, the encoding process completely stops when I switch to that game and won't turn on again after switching back to desktop. The second monitor won't update either when the gta V is on fullscreen, but works normally again after switching back to desktop. I wonder if the encoder freeze is related to that.

- I just completely copied the SimpleEncoder sample code and used that. The encoding itself processes frames at 60 fps, but if there's a game on fullscreen while the encoding process is happening, the game will stutter.

- I think there's no color conversion because the sample code uses nv12 surface.

**Comment by amfthrowaway** [comment]
Alright, the encoder freezing was caused by something that was left in my code, unrelated to the sample. Now that I could test gta V aswell, it seems that the stuttering effect is a little bit more unnoticeable in that game. The game also runs with a lot less fps, so is it possible that the stuttering is related to the game's fps?

**Comment by MikhailAMD** [comment]
Could you please provide more details: 
- where do you get the frames?
- Do you use GPU for color conversion to NV12?
- Do you use DX9 or DX11?
I am aiming to the fact that while VCE encoder is completely independent from GPU load, the color conversion and possible transfers between system and video memory are not independent from GPU load and may interfere with game especially if game gets all GPU. This also included DWM that handles monitors. 
Anther thing: as I understand you have also Intel GPU on the system. If so please try to disable it via BIOS.

**Comment by amfthrowaway** [comment]
- It's just the sample SimpleEncoder([https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/public/samples/CPPSamples/SimpleEncoder/SimpleEncoder.cpp](SimpleEncoder.cpp)) code that I simply copypasted to my own project. The only difference between that and my code is that I use std::thread instead of the AMF thread and I restrict the submission of the frames to 60 frames per second. The SimpleEncoder seems to render the frames via the IDirect3DDevice that is obtained from the AMFContext. It just does ColorFill twice in the drawing function. I submit those frames to the encoder.
- No I don't. The SimpleEncoder renders the frames in NV12 already.
- DX9.

The SimpleEncoder sample only seems to transfer the frame back to main memory after it's encoded.

Yeah, I have also intel GPU that powers my third monitor. I can try disabling it via the BIOS to see if it makes any difference.

**Comment by MikhailAMD** [comment]
OK, ColorFill is done on GPU and will share it with the game. You can record short  (5 sec) GPUVIEW log that includes the hitch, zip it and share with me.
There is interaction between Intel GPU and AMD GPU to provide united desktop. This may require transfers through PCIe. So you slow PCI speed may be a factor.

**Comment by amfthrowaway** [comment]
Alright. There wasn't a setting to disable intel gpu from the bios, but I disabled it via the device manager in Windows. Disabling the intel gpu didn't have any effect.

I'll try to record a log where I'm encoding and playing the game.

**Comment by amfthrowaway** [comment]
Is it possible to send this file via email? I'd rather not share it here because I'm not quite sure if it contains private or identifiable data.

**Comment by MikhailAMD** [comment]
The fill may be too big for Email. Can you do some dropbox?  mikhail"dot"mironov"ATT"amd"dot"com

**Comment by amfthrowaway** [comment]
Alright, I'll upload it there. I'll also provide some info about the file in the email.

**Comment by amfthrowaway** [comment]
Okay, I sent the file and provided some info along with it aswell.

**Comment by amfthrowaway** [comment]
Alright, so after some troubleshooting it seems that the hitches are caused by the csrss.exe interfering with gpu intensive applications. After looking at gpuview, the latency spikes in-game correlate with cdd.dll in csrss.exe submitting a lot of work to the context cpu queue. The effect is apparent when the encoder is running aswell. The hitches happen in 1 second periods.

The csrss.exe also interferes with the game when alt tabbing in to the game. It probably happens aswell when alt tabbing out of the game.

I'm on Windows 7, and apparently the interference is greater in versions older than Windows 10. I don't have Windows 10 at hand, so unfortunately I can't test this right now.

**Comment by amfthrowaway** [comment]
The same issue still persists in windows 10.

**Comment by MikhailAMD** [comment]
please provide GPUVIEW log.

**Comment by MikhailAMD** [comment]
any update?

**Comment by amfthrowaway** [comment]
I'm very sorry for forgetting this thread, but I've since updated my GPU and unfortunately cannot test it anymore.

**Comment by amfthrowaway** [comment]
The issue might be due to the fact that r9 290 doesn't yet have a discrete chip dedicated to encoding, because the encoding in 2nd GCN is shader based. 3rd GCN has a real discrete chip for VCE.
