### ISSUE TITLE
simpleDecoder sample memory performance issue

### ISSUE THREAD

**Issue by MohammadTaha39** [GPUOpen-LibrariesAndSDKs/AMF#98]
I am running simpleDecoder.exe from amf sample's. On Windows 8.1 it takes 26-28 Mb and on Windows 10 it takes 103-105 Mb.

Command line i used to used to Run simpleDecoder exe is : **simpleDecoder.exe <File.h264> DX9 true**

I am running **32-bit** simpleDecoder.exe.
I am using DX9 memory. **Why simpleDecoder  exe is taking more memory on Windows 10**?

**Details of my Windows 8.1 PC is:**
Procecessor : AMD A6-6310 APU with AMD Radeon R4 Graphics 1.80 GHz
RAM            : 4.00GB (3.43 GB usable)
System Type: 64-bit Operating System

**Details of my Windows 10 PC is:**
Procecessor : AMD A9-9410 Radeon R5, 5 COMPUTE CORES 2C+3G   2.90 GHz
RAM            : 4.00GB (3.88 GB usable)
System Type: 64-bit Operating System

**Comment by MikhailAMD** [comment]
Just checked on Win10 on a similar laptop, 1080 clip, Working Set:
Debug 32 bit 121 MB
Release 32 bit 72 MB
Debug 64 bit 122 MB
Release 64 bit 73 MB
On Desktop Release 64 bit 36 MB
Driver is more or less the same. But OS is different. You can try Windows Media Player and compare memory usage. From decoder and driver perspective it is the same.

**Comment by MohammadTaha39** [comment]
I checked on Win 10 with 1080 clip:

**Window Media Player** takes **8-9% GPU, 2-5% CPU, 102MB memory** and used following dll's of amd:
aticfx32.dll
atiu9pag.dll
atiumdag.dll
atiumdva.dll

**AMF simpleDecoder.exe 32-bit release** takes **13-15% GPU, 20-24 % CPU, 174MB memory** and used follwing dll's of amd:
amf-component-uvd-windesktop32.dll
amf-core-windesktop32.dl
aticfx32.dll
atiu9pag.dll
atiumdag.dll
atiumdva.dll

On **Windows 8.1** **AMF simpleDecoder.exe 32-bit release** takes **7-12% GPU, 14-24% CPU, 81 MB memory** and used follwing dll's of amd:
amf-component-uvd-windesktop32.dll
amf-core-windesktop32.dl
aticfx32.dll
atiu9pag.dll
atiumdag.dll
atiumdva.dll

I am using 1920x1080 h264 file for above run.
I am using amf sample of simpleDecoder. I don't know why simpleDecoder exe is taking so much of CPU and Memory. 
Can you guide me what i have to do, to reduce CPU and memory or is there any other better amd decode sample?

**Comment by MikhailAMD** [comment]
OK, several different issues:
1. CPU usage: WMP keeps frame rate while SimpleDecoder decodes ASAP.
2. Memory usage: from DLL names I deduce that you are using the old Media SDK 1.1. It was retired two yeas ago and everyone works on AMF SDK from this GitHub location. Could you please try it instead?
The numbers I gave are for the AMF SDK.
In general, I suspect differences in DX9 implementation of Windows since AMF and driver are the same.   
For completeness you may want to add WMP on Win8.1.

**Comment by MohammadTaha39** [comment]
I have downloaded latest amf from github. Now simpleDecoder.exe runs fine. Bus when is checked simpleEncoder.exe it gets failed on g_AMFFactory.GetFactory()->CreateComponent(context, AMFVideoEncoderVCE_AVC, &enocde). When i checked CapabilityManager.exe. it also says Encoder Codec AMFVideoEncoderVCE_AVC not supported, AMFVideoEncoderVCE_SVC not supported. 

But my previous amf sample 1.1 version was working with these codec.

**Comment by MikhailAMD** [comment]
Please ensure that you run the latest driver.

**Comment by MohammadTaha39** [comment]
Can you please elaborate what latest driver you are taking about?

**Comment by MikhailAMD** [comment]
Find and install the latest driver from here: http://support.amd.com/en-us/download

**Comment by MohammadTaha39** [comment]
I have two AMD laptops one is Windows 8.1 and other is Windows 10. And on Windows 10 after updating driver it works, but on Windows 8.1 the driver is already updated but Encoder Codec AMFVideoEncoderVCE_AVC not supported, 
I need to create executable of amd encoder and decoder which should work on all the AMD enable PC's and laptops.

**Comment by MikhailAMD** [comment]
Latest drivers do not support Win 8.1. The last one I see on download page is from Dec 2016. v 16.12.2. AMF should work with it though you will not see latest improvements and fixes.
Please check the driver version that was actually installed on your Win8.1 system in Radeon Settings app.

**Comment by MikhailAMD** [comment]
Any update?

**Comment by MikhailAMD** [comment]
Closed as stale issue
