### ISSUE TITLE
Modified simpleDecode to get h264 data from buffer instead of file, But memory leak occur

### ISSUE THREAD

**Issue by MohammadTaha39** [GPUOpen-LibrariesAndSDKs/AMF#99]
I have created my code which takes h264 data as buffer and i do decode it. But there is **memory leak** in my Decode Data function. I tried soo many times to solve it but not succeeded. Can any one help me finding my memory leak. My code is below:
``
//Decoder init function
init(int width, int height)
{
	m_log->info(_T("AMD Decoder Init"));
	m_bIsGotIDR = false;
	m_formatOut    = amf::AMF_SURFACE_NV12;
	m_memoryTypeOut = amf::AMF_MEMORY_DX9;
	AMF_RESULT res = AMF_OK;
	res = g_AMFFactory.Init();
	if (res != AMF_OK)
	{
		printf(""AMF Failed to initialize");
		printf("\nres : %d\n", res);
		return 1;
	}
	g_AMFFactory.GetTrace()->SetWriterLevel(AMF_TRACE_WRITER_DEBUG_OUTPUT, AMF_TRACE_TRACE);
	::amf_increase_timer_precision()
	// context
	res = g_AMFFactory.GetFactory()->CreateContext(&m_context);
	if (res != AMF_OK)
	{
		printf("FAIL: AMD Decoder AMFCreateContext error :[%d]", res);
		return false;
	}
	if (m_memoryTypeOut == amf::AMF_MEMORY_DX9)
	{
		res = m_context->InitDX9(NULL); // can be DX9 or DX9Ex device
	}
	if (m_memoryTypeOut == amf::AMF_MEMORY_DX11)
	{
		res = m_context->InitDX11(NULL); // can be DX11 device
	}
	// component: decoder
	res = g_AMFFactory.GetFactory()->CreateComponent(m_context, AMFVideoDecoderUVD_H264_AVC, &m_decoder);
	if (res != AMF_OK)
	{
		printf("FAIL: AMD Decoder AMFCreateComponent error :[%d]", res);
		return false;
	}
	res = m_decoder->SetProperty(AMF_TIMESTAMP_MODE, amf_int64(AMF_TS_DECODE)); // our sample H264 parser provides decode order timestamps - change this depend on demuxer

	res = m_context->AllocBuffer(amf::AMF_MEMORY_HOST, (width*height*2), &m_pictureBuffer);
	if (res != AMF_OK)
	{
		printf("FAIL: AMD Decode AllocBuffer, error :[%d]", res);
		return false;
	}
	printf("\nw x h : [%d x %d] m_formatOut : %d", width, height, m_formatOut);
	res = m_decoder->Init(m_formatOut, width, height);
	if (res != AMF_OK)
	{
		printf("FAIL: AMD Decoder m_decoder->Init error :[%d]", res);
		return false;
	}
	return true;
}

// Decode Data function
DecodeData(const UINT8* EncData, UINT32 EncLen, UINT8* DecData, UINT32 DecLen)
{		
//EncData: Encoded h264 data buffer 
//EncLen : Encoded h264 data size
//DecData : Decoded data buffer to be filled
//DecLen : Size of Decoded data buffer
	AMF_RESULT res = AMF_OK;	
amf::AMFBufferPtr pictureBuffer;
	res = m_context->AllocBuffer(amf::AMF_MEMORY_HOST, EncLen, &pictureBuffer);
	if (res != AMF_OK)
	{
		printf("FAIL: AMD Decode AllocBuffer, error :[%d]", res);
		return 0;
	}		
	amf_uint8 *mdata = (amf_uint8*) pictureBuffer->GetNative();
	memcpy(mdata, EncData, EncLen);
	pictureBuffer->SetDuration(416666);
	amf::AMFDataPtr  Ddata = pictureBuffer.Detach();		
	amf_pts start_time = amf_high_precision_clock();
	Ddata->SetProperty(START_TIME_PROPERTY, start_time);
	res = m_decoder->SubmitInput(Ddata);
	if (res != AMF_OK)
	{
		printf("FAIL: AMD Decode SubmitInput, error :[%d]", res);
		return -1;
	}	
	res = m_decoder->QueryOutput(&Ddata);	
	if (Ddata != NULL && res == AMF_OK)
	{
		WaitDecoder(amf::AMFSurfacePtr(Ddata)); // Waits till decoder finishes decode the surface. Need for accurate profiling only. Do not use in the product!!!	
		
		// this operation is slow nneed to remove it from stat
		res = Ddata->Convert(amf::AMF_MEMORY_HOST); // convert to system memory
		if (res != AMF_OK)
		{
			printf("FAIL: AMD Decode Data convert, error :[%d]", res);
		}	
		amf::AMFSurfacePtr surface(Ddata); // query for surface interface
		UINT8* temp = DecData;
		WritePlaneToBuf(surface->GetPlane(amf::AMF_PLANE_Y), temp); // get y-plane pixels// Copy Data into buffer.
		if	(m_bIsNV12)
		{
			WritePlaneToBuf(surface->GetPlane(amf::AMF_PLANE_UV), temp); // get uv-plane pixels
		}
		return DecLen;
	}
	else if (res == AMF_OK)
	{
		printf("FAIL: AMD Decode Query output Ddata is NULL...");
		Sleep(1);
		return 0;
	}
	printf("FAIL: AMD Decode Query output , error :[%d]", res);
	return -1;
}

**Comment by MikhailAMD** [comment]
I don't see anything obvious. The once thing I would change the code snippet:
----------------------------------------------
amf::AMFDataPtr  Ddata = pictureBuffer.Detach();
	
amf_pts start_time = amf_high_precision_clock();
Ddata->SetProperty(START_TIME_PROPERTY, start_time);

res = m_decoder->SubmitInput(Ddata);
if (res != AMF_OK)
{
	printf("FAIL: AMD Decode SubmitInput, error :[%d]", res);
	return -1;
}

res = m_decoder->QueryOutput(&Ddata);
----------------------------------------------
I would replace with:
----------------------------------------------
amf::AMFDataPtr  Ddata;
	
amf_pts start_time = amf_high_precision_clock();
Ddata->SetProperty(START_TIME_PROPERTY, start_time);

res = m_decoder->SubmitInput(pictureBuffer);
if (res != AMF_OK)
{
	printf("FAIL: AMD Decode SubmitInput, error :[%d]", res);
	return -1;
}

res = m_decoder->QueryOutput(&Ddata);
----------------------------------------------
Reuse of smart pointers can be tricky - depend on implementation and sometimes on compiler. You code relies that (&Data) will release previous content of data. And it should in AMF implementation but... 
Also I done see WritePlaneToBuf() implementation.
How big is a leak for let say 100 frames?

**Comment by MohammadTaha39** [comment]
Memory is constantly increasing on each call by 1.5 MB.
My WritePlaneToBuff() implementation is : 
 WritePlaneToBuf(amf::AMFPlane *plane, UINT8*& lbuff)
{
	// write NV12 surface removing offsets and alignments
	amf_uint8 *data     = reinterpret_cast<amf_uint8*>(plane->GetNative());
	amf_int32 offsetX   = plane->GetOffsetX();
	amf_int32 offsetY   = plane->GetOffsetY();
	amf_int32 pixelSize = plane->GetPixelSizeInBytes();
	amf_int32 height    = plane->GetHeight();
	amf_int32 width     = plane->GetWidth();
	amf_int32 pitchH    = plane->GetHPitch();
	
	//printf("\n Address : %u  Height : %d , Width : %d pixelSize : %d \n", lbuff, height, width, pixelSize);
	for( amf_int32 y = 0; y < height; y++)
	{
		amf_uint8 *line = data + (y + offsetY) * pitchH;

		memcpy((void*)(lbuff + offsetX * pixelSize), line + offsetX * pixelSize, width * pixelSize);
		lbuff += width * pixelSize;
	}
}

**Comment by MohammadTaha39** [comment]
Thank you, the memory leak is solved by doing as you suggested:
amf_pts start_time = amf_high_precision_clock();
Ddata->SetProperty(START_TIME_PROPERTY, start_time);

res = m_decoder->SubmitInput(pictureBuffer);
if (res != AMF_OK)
{
printf("FAIL: AMD Decode SubmitInput, error :[%d]", res);
return -1;
}

But the decoding FPS rate is 14 FPS on Windows 8.1 and 24 on Windows 10.
CPU as per my above code is  20 on Windows 8.1 and 40 on Windows 10.

**Comment by MohammadTaha39** [comment]
My decoding FPS as per above code is:
On Windows 8.1 16 FPS.
On Windows 10 24 FPS. 
Is there any thing by which my FPS gets increase?

**Comment by MikhailAMD** [comment]
If you use high precision timer function to profile your code you will find a reason for such speed. My bet is that the subpar performance is caused by conversion of uncompressed frames to host memory and dumping them to a file. It is pretty costly operation, especially on APUs. In general, the goal is to keep all processing in GPU. If you really need the uncompressed frames in host memory please try to initialize AMF to DX11. The transfer between GPU and host memory will be somewhat faster, though no miracles.

**Comment by MohammadTaha39** [comment]
Only AMF_MEMORY_HOST is returning success and other memory types return AMF_NOT_SUPPORTED. Suggest me how i can keep all processing in GPU.

**Comment by MikhailAMD** [comment]
By default the sample works in DX9. You can covert it into DX11. The decoder output is in DX.

**Comment by MohammadTaha39** [comment]
I have done DX11 init. With 1920x1080 file:
On windows 8.1 i am getting FPS 16 and CPU 20% - 25%.
On windows 10 i am getting FPS 24-28 and CPU 45% - 50%.
I don't understand why CPU is so high and why FPS is so low.

**Comment by MikhailAMD** [comment]
Try to comment Ddata->Convert(amf::AMF_MEMORY_HOST);
and WritePlaneToBuf()

**Comment by MohammadTaha39** [comment]
I did comment Ddata->Convert(amf::AMF_MEMORY_HOST); and WritePlaneToBuf() and then i got:
On Windows 8.1 CPU 25% and FPS 72
On Windows 10 CPU 40 % and FPS 75.

Most of the CPU and processing time is taken by Ddata->Convert(amf::AMF_MEMORY_HOST).  Is there any alternative to get Decoded data into buffer. Or what is the better way to get Decoded data into buffer with low CPU.

**Comment by MikhailAMD** [comment]
These are  the expected numbers. There are no alternatives. The whole point is to stay on GPU side. All attempts to transfer large data to CPU memory are slow. Why do you need this?

**Comment by MohammadTaha39** [comment]
I need this as i have to create a library which takes encoded h264 data from one module and decode it in BGRA and send to other module. 
I have different module for Encoding, Decoding and Rendering. But i am currently stuck on Decoding module as Decoding FPS is low and CPU is high.

**Comment by MikhailAMD** [comment]
While it is your design and your library when one deals with GPUs for fast performance it is important to keep everything on GPU side. One way to pass data between modules is to exchange pointers to DX objects (textures, etc.). Another way is to exchange shared handles. This would work even across processes. Though, it would require extra care on synchronization. Please also note that transfers to and from video memory are much faster on discreet GPUs.

**Comment by MohammadTaha39** [comment]
Initialisation process for Encoder and Decoder is mostly like the same in sample. 
Sample code of encoder uses  AMFCreateComponent(context, AMFVideoEncoderVCE_AVC, &encoder); second parameter as AMFVideoEncoderVCE_AVC.
While sample code of decoder uses AMFCreateComponent(context, AMFVideoDecoderUVD_H264_AVC, &decoder); second parameter as AMFVideoDecoderUVD_H264_AVC.

When we see run() function PollingThread class. We find that encoder do:
res = encoder->QueryOutput(&data); then  amf::AMFBufferPtr buffer(data); and the encoder data is available in buffer->GetNative() and size of encoded buffer is available in buffer->GetSize().

Decoder also does decoder->QueryOutput(&data);  but when i do  amf::AMFBufferPtr buffer(data); and tried to get decoded raw buffer from buffer->GetNative() or size from  buffer->GetSize() it crashed as AMFBufferPtr  buffer is not initialised.

Tell me why is it required to do decoder->QueryOutput(&data); then data->Convert(amf::AMF_MEMORY_HOST); then amf::AMFSurfacePtr surface(data); Then by using surface plane Y, UV i have to fill raw buffer.

**Comment by MikhailAMD** [comment]
Decoder produces frames :
- If DX9: NV12 surface
- if DX11: NV12 texture.
if you call AMFSurfacePtr(data)->GetPlaneAt(0)->GetNative() it will return (void*) pointer pointing to:
 - DX9:  IDirect3DSurface9*
- DX11: D3D11Texture2D*
You can use them as DX objects.
If you want to have the decoded frame in system (host) memory you have to convert it:
data->Convert(AMF_MEMORY_HOST);
After conversion the same call AMFSurfacePtr(data)->GetPlaneAt(0)->GetNative()  will return (void*) pointer to system memory.

**Comment by MohammadTaha39** [comment]
Thanks for timely reply. I got some how what i need with the help of all your reply.

**Comment by 21pages** [comment]
> While it is your design and your library when one deals with GPUs for fast performance it is important to keep everything on GPU side. One way to pass data between modules is to exchange pointers to DX objects (textures, etc.). Another way is to exchange shared handles. This would work even across processes. Though, it would require extra care on synchronization. Please also note that transfers to and from video memory are much faster on discreet GPUs.

I need to render the decoded data via GPU, is there any available example?

**Comment by rhutsAMD** [comment]
Yes, the PlaybackHW sample app provides examples of how to render the decoded data via GPU.

The `AMFVideoConverter` component can help to perform color space conversion and has SimpleConverter provided as a sample app.

The following presenters used by PlaybackHW are available as examples:

[VideoPresenterDX11](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/public/samples/CPPSamples/common/VideoPresenterDX11.cpp)
[VideoPresenterDX9](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/public/samples/CPPSamples/common/VideoPresenterDX9.cpp)
[VideoPresenterDX12](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/public/samples/CPPSamples/common/VideoPresenterDX12.cpp)
[VideoPresenterOpenGL](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/public/samples/CPPSamples/common/VideoPresenterOpenGL.cpp)
[VideoPresenterVulkan](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/public/samples/CPPSamples/common/VideoPresenterVulkan.cpp)
